### ISSUE TITLE
Update doctest examples

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1004]
The latest [version of yard-doctest](https://github.com/p0deje/yard-doctest/compare/v0.1.7...v0.1.8) has made it so several doctest examples now fail. The project [pinned the dependency to the previous release](https://github.com/GoogleCloudPlatform/google-cloud-ruby/commit/90ff2b1e0c273d8e5c3059b54f7617523a208072), but we should fix the examples and upgrade to the most recent release.

**Comment by quartzmo** [comment]
refs #226
