### ISSUE TITLE
Support generic Batch HTTP requests

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-ruby#1008]
We got feedback on this page that we don't have any code samples. https://cloud.google.com/bigquery/batch

The API clients support batch requests, https://developers.google.com/api-client-library/java/google-api-java-client/batch but I don't think the Cloud libraries do.

**Comment by bjwatson** [comment]
@quartzmo @blowmage I checked with @tswast, and we can wait on this until post-beta.

**Comment by blowmage** [comment]
kk

**Comment by quartzmo** [comment]
@bjwatson Thanks for looking into this!

**Comment by bjwatson** [comment]
No problem.

**Comment by tswast** [comment]
Closing this since batch is considered a legacy feature. It is not supported in new gRPC-native APIs.

**Comment by blowmage** [comment]
@tswast Is BigQuery adding gRPC support? We are currently calling the JSON REST API.
