### ISSUE TITLE
Validating the vision API 

### ISSUE THREAD

**Issue by mberrueta** [GoogleCloudPlatform/google-cloud-ruby#1014]
Hello, 
I have a question regarding the validation for the API
For the  translate API I'm able to set the API key by code, but for vision I always need the json file ? 
 
```
  translate = Google::Cloud::Translate.new key: Rails.application.secrets.google_cloud_api_key:
  translation = translate.translate 'Hello world!', to: 'es'
  translation.text
```
is there any way to do something similar? (seems clear) like 

```
    vision = Google::Cloud::Vision.new key: Rails.application.secrets.google_cloud_api_key, project: 'xxx'
```

**Comment by quartzmo** [comment]
Hi @mberrueta,

Good question, thanks for asking! Yes, you are correct. For all services except Google Translate API (which currently depends on an API key), the `google-cloud` libraries are intended to be used with [service account](https://cloud.google.com/docs/authentication#user_accounts_and_service_accounts) credentials, as explained in the [authentication guide](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-vision/guides/authentication) for `google-cloud-vision`. You can provide the JSON-format credentials as a file, or even just store the JSON contents in an environment variable (`VISION_KEYFILE_JSON` or the more general `GOOGLE_CLOUD_KEYFILE_JSON`).

We feel service accounts are the best way to authenticate for real-world use cases. From the [Official Cloud Vision API guides: Authenticating to a Cloud API Service](https://cloud.google.com/vision/docs/common/auth):

> The simplest authentication scheme is that of an API key; however, an API key does not allow you to authorize to the service, so it is only usable on public data or data you pass directly to the RPC API. By contrast, the service account is the most useful auth scheme since you can use it to access a Cloud API by configuring your code to send credentials for the service account to the service.

> When accessing a Google Cloud Platform API, we recommend that you set up an API key for testing purposes, and set up a service account for production usage.

However, if you have a use case for Cloud Vision and API keys that you feel we should consider, please let us know!

**Comment by mberrueta** [comment]
Hello @quartzmo, pretty clear, thanks so much for the response. 
It works perfect with the json.

**Comment by quartzmo** [comment]
@mberrueta You bet. Enjoy using it, Vision API is so much fun! And do not hesitate to let us know if you find anything we can improve.
