### ISSUE TITLE
Vision Api - best performance question

### ISSUE THREAD

**Issue by mberrueta** [GoogleCloudPlatform/google-cloud-ruby#1015]
Hello all

Wondering in performance, I have currently my images stored in S3 and to get the tagging, I will need to download from the API, and then send to vision ( there are no way to send a public link to vision if I didn't seek bad) 

It is (pretty sure it do) faster if instead of S3, I upload to GS and then send to vision with the gs path? 
In other words, vision api take the image from GS and my server never download, right? 

(sorry if this is not the best place for questions, in the future should I ask in other place?)

**Comment by quartzmo** [comment]
If you can upload your images to Google Storage instead of S3 in the first place, I believe that is the best approach, both for simplicity and performance. Please be sure to comment on this issue after you've tried it! We really appreciate hearing about real-world experiences.

**Comment by quartzmo** [comment]
Regarding performance in general, be sure to read the [official Cloud Vision API guides: Best Practices](https://cloud.google.com/vision/docs/best-practices), especially the section on file sizes.

**Comment by mberrueta** [comment]
Thanks @quartzmo , I will take this into account.

I'm seeking a way to upload directly from the client side (angular - without my API) to GS, and then call vision from my backend API. 

I will post here my thoughts / conclusions

**Comment by quartzmo** [comment]
@mberrueta You might ask the maintainers of [google-cloud-node](https://github.com/GoogleCloudPlatform/google-cloud-node) if they have any ideas about client-side uploads to Google Cloud Storage. I recall that some time ago there was a `google-cloud-node` issue for client-side support, but I don't think it was ever implemented. I do believe they have considered it at some point.

I'll close this issue, but please add your experiences to it for future reference.
