### ISSUE TITLE
Outdated version of gems being installed when using gem "google-cloud"

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1032]
What went wrong:
I was trying to include all the sub-gems in "google-cloud" and the gem versions (0.20.1 or 0.20.2) didn't match the latest version in the README (0.21.0). Reproduction steps are listed below. 

Steps to reproduce:
1. Create a Gemfile (with source)
2. add **gem 'google-cloud'** [example](https://gist.github.com/frankyn/1ecbb5443b1a4c7f0373775bad23e353)
3. bundle install  (prints) --> [output](https://gist.github.com/frankyn/a494f970afe14e98a4bdb495c799290e)
4. bundle update (didn't update) --> [output](https://gist.github.com/frankyn/05bedf41821e092ed58111a3ce190233)
5. bundle clean --force (prints) --> [output](https://gist.github.com/frankyn/049a7b0c71e2ed5aa06ab51b07ef5dae)
6. bundle update (updates correctly and prints) [output](https://gist.github.com/frankyn/44de515a6ca04b3b574f238236d2bc9f)

This will also occur when changing from a specific sub-gem "google-cloud-datastore" to "google-cloud".

**Comment by blowmage** [comment]
What version of ruby are you using? And what version of bundled do you have installed?

**Comment by frankyn** [comment]
Bundler version 1.13.4
Ruby: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Comment by hxiong388** [comment]
Do you previously have google-cloud 0.20 installed? In that case, your first call to bundle install could've just reused the existing v0.20 installation, instead of grabbing the latest 0.21 version.

**Comment by blowmage** [comment]
I haven't been able to reproduce this. But I suspect it is related to #1033.

**Comment by frankyn** [comment]
Thanks @blowmage, I'll watch that issue.

**Comment by blowmage** [comment]
@frankyn Can you try this again? We found a problem with data being served by the rubygems API and I suspect this was the cause of the behavior you experienced. But I was never able to properly reproduce the behavior, so I can't say for sure.

**Comment by quartzmo** [comment]
@frankyn We believe this is resolved. Can you test, and if it works now for you, close?

**Comment by frankyn** [comment]
Thank you!

I don't have a version issue anymore with this update. 

Feedback: When I use "gcloud" it will download all related gems to "gcloud" and "google-cloud". If I use "google-cloud" it will only include "google-cloud" gems.

**Comment by blowmage** [comment]
> **Feedback**: When I use "gcloud" it will download all related gems to "gcloud" and "google-cloud". If I use "google-cloud" it will only include "google-cloud" gems. 

That is correct. The old name of the library was `gcloud`, but the new name is `google-cloud`. So all `gcloud` does is alias the constant `Gcloud` to `Google::Cloud` to maintain backwards compatibility.

**Comment by blowmage** [comment]
> I don't have a version issue anymore with this update. 

Fantastic! I'll mark this as closed then. Thank you for opening the issue and making us aware of this.
