### ISSUE TITLE
Vision image from buffer

### ISSUE THREAD

**Issue by mberrueta** [GoogleCloudPlatform/google-cloud-ruby#1035]
Hello, there is possible in any way to send to vision a image that I don't have in my fs?

My use case is that I will send a image that is on internet (I have the url only) so could be great send url, or at least a buffer in memory to avoid write the file in a temp file in my file system.

**Comment by blowmage** [comment]
Hi @mberrueta, Vision will accept an IO-ish object for the image data. So, you could read in the image from a URL, store the data in something like StringIO, and pass that to Vision.

Here is some code that does just that. It uses `open-uri` to retrieve the contents of an image from a URL. The `image` object is an instance of StringIO. Then we pass that object to vision to get the text of the image:

```ruby
require "open-uri"
image = open "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"

require "google/cloud/vision"
vision = Google::Cloud::Vision.new
annotation = vision.annotate image, text: true
puts annotation.text #=> Google
```

Hope this helps! If it doesn't help, please ask a follow-up question. If it does, then please mark this issue closed. Thanks!

**Comment by mberrueta** [comment]
Awesome @blowmage it works nice!

thanks sooo much
