### ISSUE TITLE
Language sentiment example is ambiguous and does not return score or magnitude

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/google-cloud-ruby#1053]
I'm having trouble using the latest 0.22.0 version of google-cloud-language

I'm trying this sample, as shown in the docs: [Annotating documents](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.22.0/google/cloud/language#annotating-documents)

```ruby
require "google/cloud/language"

language  = Google::Cloud::Language.new
document  = language.document "Darth Vader is the best villain in Star Wars."
sentiment = document.sentiment # API call

puts "Score: #{sentiment.score}"
puts "Magnitude: #{sentiment.magnitude}"
```

If I try running this, I get 0.0 for both values:

```sh
$ bundle install
Using public_suffix 2.0.4
...
Using googleauth 0.5.1
Using grpc 1.0.1
Using googleapis-common-protos 1.3.4
Using google-gax 0.6.0
Using google-cloud-language 0.22.0
Bundle complete! 1 Gemfile dependency, 20 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

```sh
$ bundle exec ruby sentiment.rb 
Score: 0.0
Magnitude: 0.0
```

I also tried setting `GOOGLE_CLOUD_PROJECT` and `GOOGLE_APPLICATION_CREDENTIALS` incase either/both of those are required, but I still get 0.0 for both values.  I wonder if I'm missing a required piece of authentication?

**Comment by quartzmo** [comment]
@remi Thanks for reporting this. I have been getting the same result since yesterday. However, with a less ambiguous sentence, I get non-zero return values (and I expect you will too):

```sh
irb(main):002:0> document  = language.document "Darth Vader is the best villain in Star Wars."
=> #<Google::Cloud::Language::Document ("Darth Vader is t...", format: :text, language: "")>
irb(main):003:0> sentiment = document.sentiment
=> #<Google::Cloud::Language::Annotation::Sentiment:0x007fd9e3b1bb00 @score=0.0, @magnitude=0.0, ...>
irb(main):004:0> document  = language.document "I love pizza."
=> #<Google::Cloud::Language::Document ("I love pizza....", format: :text, language: "")>
irb(main):005:0> sentiment = document.sentiment
=> #<Google::Cloud::Language::Annotation::Sentiment:0x007fd9e4346a50 @score=0.800000011920929, @magnitude=0.800000011920929, ...>
```

I have been hoping that the service results will at some point once again return a value > 0.0 for our current example, but if it does not happen soon, perhaps we should change the example.

**Comment by remi** [comment]
Great!  Confirmed!  Same for me.

 - *"I love pizza.  Pizza makes me happy and pleased."* --> ~ 0.8, 1.7
 - *"I hate you.  I am so angry.  Horrible things!"* --> ~ -0.5, 1.7

Renaming the issue to better reflect that this is more a problem with the documentation being misleading (I thought it didn't work 😕 )

**Comment by quartzmo** [comment]
Thanks @remi. I was really hoping to use a more nuanced example. However, given the new sentence scoping of sentiment analysis, changing to a multi-sentence example is probably good, so I will also change to something unambiguous that produces a positive result.
