### ISSUE TITLE
Should we use Circle CI for Linux builds and to publish to RubyGems?

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1059]
Due to long wait times on Travis CI, I am proposing that we *add* [Circle CI](https://circleci.com/) to the project, in order to get quicker confirmation that a PR passes on Linux.

This is not a proposal to replace either Travis CI or AppVeyor, which I think will still be needed for OS X and Windows builds, respectively.

**Comment by blowmage** [comment]
If CircleCI supported both Linux and OS X on the same build then we could drop Travis-CI completely. But I don't see how to enable that on CircleCI.

**Comment by quartzmo** [comment]
We are now using CircleCI for publishing to RubyGems! Closing.
