### ISSUE TITLE
Audio language: does not accept :en symbol 

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1062]
### Context
http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-speech/master/google/cloud/speech/audio

I'm trying to use the Speech API Japanese recognition. I'm not sure what the symbol, but I'm guessing it's `:jp`. I tried the snippet with english (I understand it's set by default),  but it fails with an invalid argument for string field. 

### Snippet
```
require "google/cloud/speech"

speech = Google::Cloud::Speech.new

audio = speech.audio "path/to/audio.raw",
                     encoding: :raw, sample_rate: 16000,
                     language: :en
```
### Error
```
from /usr/local/lib/ruby/gems/2.3.0/gems/google-cloud-speech-0.21.0/lib/google/cloud/speech/project.rb:512:in `initialize': Invalid argument for string field. (TypeError)
from /usr/local/lib/ruby/gems/2.3.0/gems/google-cloud-speech-0.21.0/lib/google/cloud/speech/project.rb:512:in `new'
from /usr/local/lib/ruby/gems/2.3.0/gems/google-cloud-speech-0.21.0/lib/google/cloud/speech/project.rb:512:in `audio_config'
from /usr/local/lib/ruby/gems/2.3.0/gems/google-cloud-speech-0.21.0/lib/google/cloud/speech/project.rb:392:in `recognize_job'
from /usr/local/lib/ruby/gems/2.3.0/gems/google-cloud-speech-0.21.0/lib/google/cloud/speech/audio.rb:239:in `recognize_job'
```

### Ruby Version
`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]`

### Gem Versions
```
  * addressable (2.5.0)
  * bundler (1.13.6)
  * faraday (0.10.0)
  * google-cloud-core (0.21.0)
  * google-cloud-speech (0.21.0)
  * google-cloud-translate (0.22.1)
  * google-gax (0.6.0)
  * google-protobuf (3.0.2)
  * googleapis-common-protos (1.3.4)
  * googleauth (0.5.1)
  * grpc (1.0.1)
  * jwt (1.5.6)
  * little-plugger (1.1.4)
  * logging (2.1.0)
  * memoist (0.15.0)
  * multi_json (1.12.1)
  * multipart-post (2.0.0)
  * os (0.9.6)
  * public_suffix (2.0.4)
  * rly (0.2.3)
  * signet (0.7.3)
  * streamio-ffmpeg (3.0.1)
```

**Comment by blowmage** [comment]
Thanks for the report. Will get this fixed ASAP.

**Comment by frankyn** [comment]
Thanks! :+1:

**Comment by blowmage** [comment]
This is fixed in google-cloud-speech 0.21.1. PTAL.

**Comment by frankyn** [comment]
@blowmage It now accepts :en, but It doesn't complain if I provide an incorrect language code such as ":ddddd". I think that's too flexible without an error message to provide feedback. 

Thanks for your help!

**Comment by blowmage** [comment]
We think its best to now check language codes in the ruby client. Language codes are checked during the API calls, and history has shown that supported language codes will change over time. If the ruby client adds a check for the code then we will eventually be in the position where the ruby client errors on a code that the API supports, or vice-versa.

**Comment by frankyn** [comment]
I understand. It might be helpful how to have a note about this in the client library documentation. I get confused for languages such as Chinese which has four language codes. How should I write the symbol for each? Would this be a correct symbol: `:cmn_Hant_TW`?

**Comment by blowmage** [comment]
According to [Language Support](https://cloud.google.com/speech/docs/languages) it would be `"cmn-Hant-TW"`.

**Comment by blowmage** [comment]
Ruby doesn't make it easy to create symbols with dashes in them, so if you want to express that as a symbol you can either use `"cmn-Hant-TW".to_sym` or `:"cmn-Hant-TW"`.

**Comment by frankyn** [comment]
Thanks! That was my question. That's where my confusion came from. Seeing the documentation have :en instead of :"en-US", when we have language codes with en-*. I guess it's assumed when someone writes "en" they mean "en-US".
