### ISSUE TITLE
Speech Stream isn't understandable

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1068]
Context: https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.22.0/google/cloud/speech/project?method=stream-instance

I'm not sure what the correct sending rate is given a sample size of 44100Hz with 16bit rate. I was informed to send 88200 bytes per second, and I also tried brute forcing different values. The error message doesn't help and additional information in the error message would be helpful. Such as, how to better calibrate the transmission rate given a sample rate and encoding. I want to note that I used the data in ` audio.grpc.content` as the payload.

Any help would be appreciated! Thank you.

Error: 
`11:Audio data is being streamed too fast. Please stream audio data approximately at real time.`

Code:
```
require 'google/cloud/speech'

# Stream to speech and wait for transcription... 
speech = Google::Cloud::Speech.new

# Setup raw file to be sent in as an Asynchronous job maximum time is ~80mins
audio = speech.audio "prince.raw",
                      encoding: :raw, sample_rate: 44100,
                      language: :ja 

# Send stream job
stream = speech.stream encoding: :raw, sample_rate: 44100, language: 'ja'

# Result callback
stream.on_result do |results|
  result = results.first
  puts result.transcript
end

# Error callback
stream.on_error do |error|
  puts error
end

# Start callback
stream.on_speech_start do 
  puts "Started listening"
end

# Complete callback
stream.on_complete do
  puts "Finished"
end

bytes_sent = 0
chunk_size = 88200
bytes_total = audio.grpc.content.size # Content of my raw file (This may be wrong)..

# Send one chunk per second 
while bytes_sent < bytes_total do 
  stream.send audio.grpc.content[bytes_sent, (bytes_sent + chunk_size)]
  bytes_sent += chunk_size 
  sleep 1
end

# Finished sending
stream.complete!

# Stop stream
stream.stop
```

**Comment by hxiong388** [comment]
I got this working on a .flac file, which is at 44100Hz, and I sent 88200 bytes per second (44100Hz * 1 channel * 16 bits = 88200 bytes per sec ).

Have you varified your .raw file is recorded at 44100Hz? Cause normally .raw file comes at 16000Hz I think. In case your raw file is at 16000Hz sample rate, then the sample size should be 16000Hz * 1 channel * 16 bit = 32000 bytes per sec.

**Comment by frankyn** [comment]
Playing using `play` the following is printed:
```
File Size: 5.29M     Bit Rate: 706k
  Encoding: Signed PCM    
  Channels: 1 @ 16-bit   
Samplerate: 44100Hz      
Replaygain: off         
  Duration: 00:01:00.00  
```

**Comment by blowmage** [comment]
Are you sending the entire file at once? Or are you spacing the upload to it takes ~5 seconds?

**Comment by frankyn** [comment]
The spacing is ~1 second. I wasn't aware of the ~5 second spacing. I'll try that.

**Comment by frankyn** [comment]
I get an error of:
```
Started listening
3:Invalid 'audio_content': too long.
Stopped listening
```

The script is the same as posted except the sleep time was extended to ~5 seconds.

**Comment by blowmage** [comment]
Oh, sorry. The `play` output showed the audio was one minute long, so it should take ~one minute to upload. My mistake, I thought it said 5 seconds.

**Comment by frankyn** [comment]
No worries. Hmm, I'm not sure what I might be going wrong.

**Comment by hxiong388** [comment]
After lots of Googling on audio file encoding, sample rate, bit rate, etc, I came to realize your array slicing logic is the culprit: `stream.send audio.grpc.content[bytes_sent, (bytes_sent + chunk_size)]`

Ruby array slice is ary[start index, length], so your code is graduating sending more and more data with each iteration. Just change it to `stream.send audio.grpc.content[bytes_sent, chunk_size]` should be good.

**Comment by frankyn** [comment]
Whomp. That was it. I completely missed that. 

Thank you!

**Comment by hxiong388** [comment]
I think the current error message "Audio data is being streamed too fast" does explain the problem of too much content being pushed to speech service in short time, doesn't it?

**Comment by frankyn** [comment]
How fast is too fast and how slow is too slow? This is the information that's lost in that error message. This would limit the developer experience to more audio inclined developers.

**Comment by blowmage** [comment]
The point of streaming is to process the audio from a live source. Like dictating a message with your phone. If you have an existing file it should be much simpler to use one of the other mechanisms to process it.

Here is some code that will [stream until an utterance is found](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/973#issuecomment-253890956).

**Comment by frankyn** [comment]
I understand your point.  I was trying to use streaming to subtitle a non-english video. Using the Speech API I streamed the audio and then the delay between received transcriptions was used to line up audio and subtitles. The subtitle timing wasn't too bad. 

In this case an error message stating too fast or too slow would have been helpful.
