### ISSUE TITLE
Document Datastore low-level API (GAPIC code)

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1071]
Types such as [v1/datastore_api.rb](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-datastore/lib/google/cloud/datastore/v1/datastore_api.rb) are not currently published to the gh-pages documentation.

See GoogleCloudPlatform/gcloud-common#207 for detailed design and mockups.

- [x] Remove exclusions from `.yardopts`
- [ ] Add navigation to GAPIC/gRPC code

**Comment by swcloud** [comment]
Please also make sure the GAPIC/GRPC doc will surface on rubydoc.info website as well. I think once gapic code is included in the .yardopts, they should surface there, right? @quartzmo

**Comment by quartzmo** [comment]
@swcloud The `.yardopts` file has only been included in the gemspec since sometime after the latest release. The GAPIC/gRPC code is currently excluded in `.yardopts`, so these excludes will need to be removed before the next release in order to expose the code. Thanks for bringing this to our attention!

**Comment by quartzmo** [comment]
Here is the list of JSON doc files that will be in the gh-pages site once the exclusions are removed from `.yardopts`:

```sh
jsondoc/google.json
jsondoc/google/cloud.json
jsondoc/google/cloud/datastore.json
jsondoc/google/cloud/datastore/key.json
jsondoc/google/cloud/datastore/query.json
jsondoc/google/cloud/datastore/commit.json
jsondoc/google/cloud/datastore/cursor.json
jsondoc/google/cloud/datastore/entity.json
jsondoc/google/cloud/datastore/keyerror.json
jsondoc/google/cloud/datastore/propertyerror.json
jsondoc/google/cloud/datastore/transactionerror.json
jsondoc/google/cloud/datastore/dataset.json
jsondoc/google/cloud/datastore/dataset/queryresults.json
jsondoc/google/cloud/datastore/dataset/lookupresults.json
jsondoc/google/cloud/datastore/gqlquery.json
jsondoc/google/cloud/datastore/properties.json
jsondoc/google/cloud/datastore/transaction.json
jsondoc/google/datastore.json
jsondoc/google/datastore/v1.json
jsondoc/google/cloud/core.json
jsondoc/google/datastore/v1/datastore.json
jsondoc/google/datastore/v1/datastore/service.json
jsondoc/google/cloud/datastore/v1.json
jsondoc/google/cloud/datastore/v1/datastoreclient.json
jsondoc/google/protobuf.json
jsondoc/google/protobuf/doublevalue.json
jsondoc/google/protobuf/floatvalue.json
jsondoc/google/protobuf/int64value.json
jsondoc/google/protobuf/uint64value.json
jsondoc/google/protobuf/int32value.json
jsondoc/google/protobuf/uint32value.json
jsondoc/google/protobuf/boolvalue.json
jsondoc/google/protobuf/stringvalue.json
jsondoc/google/protobuf/bytesvalue.json
jsondoc/google/datastore/v1/entityresult/resulttype.json
jsondoc/google/datastore/v1/propertyorder/direction.json
jsondoc/google/datastore/v1/compositefilter/operator.json
jsondoc/google/datastore/v1/propertyfilter/operator.json
jsondoc/google/datastore/v1/queryresultbatch/moreresultstype.json
jsondoc/google/datastore/v1/commitrequest/mode.json
jsondoc/google/datastore/v1/readoptions/readconsistency.json
jsondoc/types.json
```

@swcloud Does this look correct?

**Comment by swcloud** [comment]
I don't quite understand how these json files are generated.

For example, what is jsondoc/google/datastore/v1/readoptions/readconsistency.json? I don't find any corresponding .rb file
