### ISSUE TITLE
Broken link and incorrect landing page in Speech Documentation

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1072]
Context:  http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.22.0/google/cloud/speech

Broken Links:
- https://www.rfc-editor.org/rfc/bcp/bcp47.txt
- Language Support goes here -> https://cloud.google.com/speech/docs/best-practices#language_support
    and it should go: https://cloud.google.com/speech/docs/languages

**Comment by quartzmo** [comment]
Thanks for finding these, @frankyn!

**Comment by frankyn** [comment]
You're welcome!

**Comment by quartzmo** [comment]
@frankyn The link to https://www.rfc-editor.org/rfc/bcp/bcp47.txt does not appear to me to be broken (it's just a big, unwieldy `.txt` document.) Can you suggest a better resource?

**Comment by blowmage** [comment]
The HTML page for bcp47 is here:

https://tools.ietf.org/html/bcp47

**Comment by quartzmo** [comment]
awesome, thanks @blowmage

**Comment by frankyn** [comment]
Sorry, I didn't pinpoint the specific page inside Speech documentation. I listed two pages where I have found it, but I think it might also exist elsewhere in the documentation. 

Specific pages:

- http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.22.0/google/cloud/speech/project 
- http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.22.0/google/cloud/speech/audio

**Comment by quartzmo** [comment]
@frankyn Now I see the problem with the bcp47 links: `[https://www.rfc-editor.org/rfc/bcp/bcp47.txt](BCP-47)`. The title and target are reversed. Fixing and changing to the html version now.

**Comment by frankyn** [comment]
@quartzmo thanks!
