### ISSUE TITLE
Document Logging low-level API (GAPIC code)

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1073]
Types such as [v2/logging_service_v2_api.rb](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_api.rb) are not currently published to the gh-pages documentation.

See GoogleCloudPlatform/gcloud-common#207 for detailed design and mockups.

- [ ] Remove exclusions from `.yardopts`
- [ ] Add navigation to GAPIC/gRPC code

**Comment by swcloud** [comment]
Please also make sure the GAPIC/GRPC doc will surface on rubydoc.info website as well. I think once gapic code is included in the .yardopts, they should surface there, right? @quartzmo

**Comment by quartzmo** [comment]
@swcloud If you have been wondering why GAPIC/gRPC code is visible in some of the `google-cloud` gems on rubydoc.info and not in others, it is because the `.yardopts` file has only been included in the gemspec since around 10/28/16. This is after the latest Datastore release, for example. Now that all gems include `.yardopts`, and the GAPIC/gRPC code is currently excluded in `.yardopts`, these excludes will need to be removed before the next release of any gem that needs to expose this code. Thanks for bringing this to our attention!

**Comment by quartzmo** [comment]
Here is the list of JSON doc files that will be in the gh-pages site once the exclusions are removed from `.yardopts`:

```sh
jsondoc/google.json
jsondoc/google/cloud.json
jsondoc/google/cloud/logging.json
jsondoc/google/cloud/logging/sink.json
jsondoc/google/cloud/logging/sink/list.json
jsondoc/google/cloud/logging/railtie.json
jsondoc/google/cloud/logging/entry.json
jsondoc/google/cloud/logging/entry/list.json
jsondoc/google/cloud/logging/entry/operation.json
jsondoc/google/cloud/logging/entry/httprequest.json
jsondoc/google/cloud/logging/logger.json
jsondoc/google/cloud/logging/metric.json
jsondoc/google/cloud/logging/metric/list.json
jsondoc/google/cloud/logging/project.json
jsondoc/google/cloud/logging/resource.json
jsondoc/google/cloud/logging/middleware.json
jsondoc/google/cloud/logging/asyncwriter.json
jsondoc/google/cloud/logging/resourcedescriptor.json
jsondoc/google/cloud/logging/resourcedescriptor/labeldescriptor.json
jsondoc/google/cloud/logging/resourcedescriptor/list.json
jsondoc/google/logging.json
jsondoc/google/logging/v2.json
jsondoc/google/logging/v2/loggingservicev2.json
jsondoc/google/logging/v2/loggingservicev2/service.json
jsondoc/google/logging/v2/configservicev2.json
jsondoc/google/logging/v2/configservicev2/service.json
jsondoc/google/logging/v2/metricsservicev2.json
jsondoc/google/logging/v2/metricsservicev2/service.json
jsondoc/google/protobuf.json
jsondoc/google/protobuf/any.json
jsondoc/google/protobuf/duration.json
jsondoc/google/protobuf/timestamp.json
jsondoc/google/cloud/logging/v2.json
jsondoc/google/cloud/logging/v2/configservicev2client.json
jsondoc/google/cloud/logging/v2/metricsservicev2client.json
jsondoc/google/cloud/logging/v2/loggingservicev2client.json
jsondoc/google/api.json
jsondoc/google/api/monitoredresourcedescriptor.json
jsondoc/google/api/monitoredresource.json
jsondoc/google/logging/type.json
jsondoc/google/logging/type/httprequest.json
jsondoc/google/logging/v2/logsink/versionformat.json
jsondoc/google/logging/v2/logmetric/apiversion.json
jsondoc/types.json
```

@swcloud Does this look correct?

**Comment by swcloud** [comment]
I'm not familiar with jsondoc tool. Can you provide some instructions?

From what I can see, most .rb files under 'lib/google' have a corresponding json file, but I don't seem to find json files for these files:

google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/log_entry.rb
google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging.rb
google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_config.rb
google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_metrics.rb

**Comment by quartzmo** [comment]
The inputs to the [jsondoc tool](https://github.com/GoogleCloudPlatform/google-cloud-ruby/tree/gcloud-jsondoc) are YARD objects. From the [YARD Readme](https://github.com/lsegal/yard):

> 4. Raw Data Output: YARD also outputs documented objects as raw data (the dumped Namespace) which can be reloaded to do generation at a later date, or even auditing on code. This means that any developer can use the raw data to perform output generation for any custom format, such as YAML, for instance.

While the jsondoc outputs should be mostly 1-to-1 with the inputs, the disconnect you are seeing is that the YARD objects are not 1-to-1 with the code files. These are top-level code objects: classes and modules, I believe.
