### ISSUE TITLE
Supplement Legacy SQL feature.

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1086]
PR #720 added the legacy SQL feature, but the implementation wasn't complete. We need the following:

- [ ] Documentation
- [ ] Test Coverage
- [ ] Requested naming

**Comment by blowmage** [comment]
Looking at this closer, I think I would rather see a different method argument than `use_legacy_sql`. Perhaps something like:

```ruby
require "google/cloud/bigquery"

bigquery = Google::Cloud::Bigquery.new

data = bigquery.query "SELECT name FROM my_table", mode: :legacy
data.each do |row|
  puts row["name"]
end
```

Than:

```ruby
require "google/cloud/bigquery"

bigquery = Google::Cloud::Bigquery.new

data = bigquery.query "SELECT name FROM my_table", use_legacy_sql: true
data.each do |row|
  puts row["name"]
end
```

Or, perhaps as an attribute on a Query object, like the one coming in the PR for #1070.

**Comment by quartzmo** [comment]
My 2c: I prefer `use_legacy_sql: true` so that people can more easily follow the thread from the service's API docs.
