### ISSUE TITLE
AppVeyor is running full acceptance tests on tag build

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1120]
Tag builds should not run acceptance tests, but AppVeyor is.

**Comment by danoscarmike** [comment]
Hi Mike, what's a tag build?  Can you provide more description?  P2?

**Comment by blowmage** [comment]
We have 3 services running CI: CircleCI (Linux), Travis-CI (Mac), and AppVeyor (Windows). CircleCI is the main service, and runs builds on master, all PRs, and whenever we add a git tag. A git tag is a labeled commit that identifies the commit as a release, and CircleCI performs the build on a tag and releases the gem if the build is successful.

Travis-CI and AppVeyor do not perform releases, and so we only want them to build new commits added to the master branch. But right now AppVeyor is also building commits with tags. This means AppVeyor is doing more work than we need it to, and taking resources away from other GoogleCloudPlatform projects.

**Comment by blowmage** [comment]
AppVeyor was updated to not run acceptance tests on tag builds.
