### ISSUE TITLE
CircleCI not running on new PRs

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1121]
Sometime this week CircleCI stopped running on new PRs. Investigate why.

**Comment by blowmage** [comment]
Related: https://discuss.circleci.com/t/pull-request-from-forked-repos-are-not-being-tested/8588

**Comment by quartzmo** [comment]
I'm wondering if the drastic (but low cost) move of deleting and re-enabling the Circle CI's integration with repo might work. We can certainly wait to see what happens with the issue you linked above.

**Comment by blowmage** [comment]
Tried that on Friday, it didn't change anything.

**Comment by blowmage** [comment]
An [update](https://discuss.circleci.com/t/pull-request-from-forked-repos-are-not-being-tested/8588/4?u=blowmage) from CircleCI support:

> Due to a couple users on GitHub attempting to use forked builds to mine cryptocurrency on OSS projects, we made changes to the settings controlling forked PR builds. No customer code was affected, but as a result we disabled forked PR builds.
> 
> To enable, please visit your project's settings on CircleCI and set `Build forked pull requests` to on.

The settings UI now has the new option and it has been enabled. If it works the next PR should have a build.

**Comment by blowmage** [comment]
![prs-menu](https://cloud.githubusercontent.com/assets/730/21157522/d7ac4fe2-c136-11e6-91a2-1857849f4239.jpg)

**Comment by blowmage** [comment]
New PRs are running builds again. Closing.
