### ISSUE TITLE
rubydoc.info site does not have GAPIC/GRPC entries on the left navigation panel

### ISSUE THREAD

**Issue by swcloud** [GoogleCloudPlatform/google-cloud-ruby#1128]
http://www.rubydoc.info/gems/google-cloud-logging

The low-level gapic/grpc documentation shows up on the 'index' page: http://www.rubydoc.info/gems/google-cloud-logging/index

but not on the left navigation panel.

**Comment by blowmage** [comment]
We believe the site is using some cached data on the navigation view on the left hand side. I am investigating how to rebuild the gems to get the correct navigation to show. Hope to have this fixed soon.

**Comment by blowmage** [comment]
Compare the following URLs:

* http://www.rubydoc.info/gems/google-cloud-logging/index
* http://www.rubydoc.info/gems/google-cloud-logging/0.23.0/index

They should both be the same, but they are not. The default is to show the most recent gem version in both the navigation and content panes, but the first URL is showing a different navigation pane than what is in the content pane.

**Comment by quartzmo** [comment]
The left nav is loaded in an `iframe`: http://www.rubydoc.info/list/gems/google-cloud-logging/class

I don't believe we can do much to fix this.

**Comment by blowmage** [comment]
Informed the maintainers and they have cleared the app's cache and things work correctly now. Thanks for the heads up!

http://www.rubydoc.info/gems/google-cloud-logging/index
