### ISSUE TITLE
Consistency issue in Environmental Variable GOOGLE_CLOUD_PROJECT

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1131]
### Context

App Engine Flex Beta 2 was recently released and currently supports [GCLOUD_PROJECT](https://cloud.google.com/appengine/docs/flexible/ruby/runtime) as the environment variable which contains the project id. The **google-cloud-ruby** gem promotes the use of [GOOGLE_CLOUD_PROJECT](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/master/guides/authentication), but also supports GCLOUD_PROJECT in [the background](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/63f398c206708d4d66124d40aceb0fa57d27d557/google-cloud-translate/lib/google/cloud/translate/api.rb#L85). GCLOUD_PROJECT is currently supported in the flex runtime  @JustinBeckwith.

### Issue/Question

This may lead to confusion between the documentation for the **google-cloud-ruby** gem and **cloud.google.com/ruby** documentation. 

**I vote** to change this gems documented use of GOOGLE_CLOUD_PROJECT for GCLOUD_PROJECT instead.

**Comment by quartzmo** [comment]
@frankyn We have discontinued using the name "gcloud" (or "GCLOUD") for this project, in order to avoid confusion with [the `gcloud` CLI in the SDK](https://cloud.google.com/sdk/gcloud/):

> What is gcloud?

> gcloud is a tool that provides the primary command-line interface to Google Cloud Platform. You can use this tool to perform many common platform tasks either from the command-line, or in scripts and other automations.

If it is at all possible, the best solution is to change any mention of `GCLOUD_PROJECT` to `GOOGLE_CLOUD_PROJECT`.

**Comment by frankyn** [comment]
@quartzmo, I think `GCLOUD_PROJECT` is the only supported environment variable in App Engine Flex Beta 2. 

@JustinBeckwith, can App Engine Flex Beta 2 add support for GOOGLE_CLOUD_PROJECT?

**Comment by JustinBeckwith** [comment]
Sure.  We'll have to keep support for GCLOUD_PROJECT (since we just added it) but this shouldn't be an issue.

**Comment by quartzmo** [comment]
Thanks @JustinBeckwith. To resolve this inconsistency, changing to `GOOGLE_CLOUD_PROJECT` is the right solution. (We will also keep support for `GCLOUD_PROJECT`.)

**Comment by frankyn** [comment]
Thanks @JustinBeckwith !
