### ISSUE TITLE
Still showing "gcloud" in the title of client lib landing page

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-ruby#1140]
We should update the title to `google-cloud-ruby`

![image](https://cloud.githubusercontent.com/assets/6609430/21210914/c7c43128-c233-11e6-9b2f-7d98859d92a4.png)

**Comment by quartzmo** [comment]
I believe this is a duplicate of #945, and that the fix must be in gcloud-common per GoogleCloudPlatform/gcloud-common#195.

**Comment by quartzmo** [comment]
@omaray I'll see if I can produce a fix tomorrow for GoogleCloudPlatform/gcloud-common#195.
