### ISSUE TITLE
Broken links to Protobuf types

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1146]
Because YARD (our docs library) generates output that is scoped to Ruby classes and modules, Protobuf types that are exposed as **Ruby constants** are not currently published. So links in the gh-pages site to types like `Google::Datastore::V1::BeginTransactionResponse` (defined as a constant in lib/google/datastore/v1/datastore_pb.rb) are broken.

**Comment by quartzmo** [comment]
@swcloud I am wondering how we might be able to generate JSON docs from these types that are defined as constants.

**Comment by swcloud** [comment]
Google::Datastore::V1::BeginTransactionResponse is defined as a class below:

https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/datastore.rb#L82

**Comment by quartzmo** [comment]
@swcloud Thank you. I have located the types in the YARD output, the problem is in the jsondoc generation.

**Comment by quartzmo** [comment]
Actually, the problem seems to be that YARD overwrites the output from the class definitions in `lib/google/cloud/datastore/v1/doc/google/datastore/v1/datastore.rb` with empty output from the constant definitions of the same name in `lib/google/datastore/v1/datastore_pb.rb`, so the class definition docs are lost. I think just adding an exclusion to `.yardopts` may fix this issue.

**Comment by blowmage** [comment]
This is because implementation-wise, those are constants. They get their implementation by calling a method, and YARD is doing the right thing. Perhaps if the doc files were loaded _after_ the implementation files?

**Comment by quartzmo** [comment]
@blowmage Perhaps. It might be easiest (and cleanest) to just to exclude the constants in cases like this in which hand-written docs are provided on classes with the same name.

But, this does raise another issue, which is that it appears that our current jsondoc generation does NOT document constants. The gcloud-common [`service.schema`](https://github.com/GoogleCloudPlatform/gcloud-common/tree/master/site/schemas/service.schema.json) only supports `methods` as far as I can see.

**Comment by blowmage** [comment]
IMO it would be better to document them as modules and classes and not constants. My point is that YARD is doing the right thing, and it's the weird implementation that is causing this.

**Comment by blowmage** [comment]
If the GAPIC documentation files are loaded by YARD first, instead of the actual implementation files, then the YARD output would use them. To test this, change the `.yardopts` to the following:

```yaml
--no-private
--title=Google Cloud Datastore
--markup markdown

./lib/google/cloud/datastore/v1/doc/**/*.rb
./lib/**/*.rb
-
README.md
```

I'm of the opinion that the GAPIC documentation files should not be in `lib`. I think it would be better if the load directives read like this:

```yaml
./gapic/**/*.rb
./lib/**/*.rb
```

But that is tangental to this issue.

**Comment by quartzmo** [comment]
Thanks @blowmage, your options list above also works, I'll go with it.

**Comment by quartzmo** [comment]
The constants do produce a lot of YARD warnings like this one, however:

```sh
[warn]: in YARD::Handlers::Ruby::ConstantHandler: Undocumentable constant for existing class Google::Datastore::V1::EntityResult
[warn]: 	in file 'lib/google/datastore/v1/query_pb.rb':112:

	112: EntityResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.datastore.v1.EntityResult").msgclass
```

**Comment by blowmage** [comment]
Yeah, that's the price we pay for having multiple definitions.
