### ISSUE TITLE
Why not store encryption_key in Google::Cloud::Storage::File Class

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1149]
**[Context]**
When I attempt to download an encrypted file from Cloud Storage, I must use the encryption_key twice. Once to create the File object and another to download the file to my local disk. 

```
file = bucket.file storage_file_path, encryption_key: encryption_key
file.download local_file_path, encryption_key: encryption_key
```

**[Question]**
Do we have a reason for not storing the encryption_key in the File object while it's being used? 

Thank you.

**Comment by blowmage** [comment]
We considered this when first implementing encryption keys, but found it added too much complexity. There are several methods that can take encryption key. Storing the key on a file object doesn't indicate which methods that key should be used for, so we would still need an opt-in (or opt-out) mechanism on those methods.

**Comment by frankyn** [comment]
Follow-up Question: Opt-in / Opt-out which would allow the encryption to be stored in the file object and still be passed in explicitly if the user wants to?

**Comment by blowmage** [comment]
In the end we decided using encryption keys was sensitive enough that users should be explicit about using them, which is why we implemented the API we have.

**Comment by frankyn** [comment]
Understood. Thank you!

**Comment by quartzmo** [comment]
@frankyn If good, can we close?
