### ISSUE TITLE
Provide a simple interface for error reporting

### ISSUE THREAD

**Issue by dlackty** [GoogleCloudPlatform/google-cloud-ruby#1160]
These are some common error reporting services' API to send exception:

```ruby
Rollbar.error(e)
Airbrake.notify(e)
Honeybadger.notify(e)
Exceptional.handle(e)
Raygun.track_exception(e)
Raven.capture_exception(e)
Bugsnag.notify(e)
Appsignal.send_exception(e)
Opbeat.capture_exception(e)
```

Currently the only way to use  Stackdriver Error Reporting is to insert a rack middleware.

**Comment by hxiong388** [comment]
Hi @dlackty. Thanks for raising this question. The [google-cloud-error_reporting](https://rubygems.org/gems/google-cloud-error_reporting) gem currently doesn't have a User API yet, but it does come with a lower level system API, [Stackdriver Error Reporting API Client](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-error_reporting/v0.21.2/google/cloud/errorreporting/v1beta1/reporterrorsserviceapi), which is what the middleware and railtie built on top of.

Here's an example how to use the lower level API client directly:
```ruby
gem "google-cloud-error_reporting"
require "google/cloud/error_reporting/v1beta1"

error_reporting = Google::Cloud::ErrorReporting::V1beta1::ReportErrorsServiceApi.new
full_project_id = Google::Cloud::ErrorReporting::V1beta1::ReportErrorsServiceApi.project_path "<project id>"

begin
   fail "error"
rescue => e
  error_message = "#{e.backtrace.first}: #{e.message} (#{e.class})\n\t#{e.backtrace.drop(1).join("\n\t")}"
  # See https://cloud.google.com/error-reporting/reference/rest/v1beta1/projects.events/report on full ReportedErrorEvent structure
  error_event = {
    message: error_message,
    service_context: {
      service: "<service name>",
      version: "<service version>"
    } 
  }
  error_event_grpc = Google::Devtools::Clouderrorreporting::V1beta1::ReportedErrorEvent.decode_json error_event.to_json
  error_reporting.report_error_event full_project_id, error_event_grpc
end
```
/cc @omaray @swcloud

**Comment by quartzmo** [comment]
@hxiong388 Should this issue stay open? Do you plan to add a simple error method at some point?

**Comment by hxiong388** [comment]
@quartzmo. Per previous discussion with @omaray, we don't have immediate plan to add the simple interface for Error Reporting. We can backlog this feature request or close it for now.

**Comment by quartzmo** [comment]
Thanks @hxiong388.

@dlackty I think this is a great suggestion, but I'm closing this issue for now. While @hxiong388's example above using the lower-level client is not a one-liner, hopefully it helps.

**Comment by hxiong388** [comment]
To clarify  a little bit, I believe the current plan is to use Stackdriver Error Reporting as a test bed for the GAPIC client only delivering approach. So we don't have any plans to add a hand written simple interface for Error Reporting. But maybe down the road, the generate GAPIC client will be able to provide similar interface.
