### ISSUE TITLE
Change name Translate to Translation in code

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1166]
This issue is a follow-up to PR #1165 (issues #1112, #1135). 

### Summary

The scope is to update the following:

- [ ] Any code object names, such as the module name `Translate` or factory methods named `translate` to `Translation` (preserving case)
- [ ] Any sample code, including variables named `translate` to `Translation` (preserving case) Note: I feel it is best to wait change examples at the same time as the code, in order to stay in sync with cloud.google.com samples, and thus reduce churn for GoogleCloudPlatform/ruby-docs-samples#136
- [ ] The package and gem name from `google-cloud-translate` to `google-cloud-translation`

#### Code object names and sample code

Change nouns in code objects to the new name of the service. Leave the verb method `Project#translate` unchanged.

Now:

```ruby
require "google/cloud/translate"

translate = Google::Cloud::Translate.new
# The statement above is equivalent to:
# translate = Google::Cloud.translate

translation = translate.translate "Hello world!", to: "la"

puts translation #=> Salve mundi!

translation.text #=> "Salve mundi!"
```

Proposed:

```ruby
require "google/cloud/translation"

translation = Google::Cloud::Translation.new
# The statement above is equivalent to:
# translation = Google::Cloud.translation

result = translation.translate "Hello world!", to: "la"

result.text #=> "Salve mundi!"
```

As a result of changing the module name to `Translation`, gh-pages docs paths will also change from [`/google/cloud/translate/`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-translate/master/google/cloud/translate) to `/google/cloud/translation/`.

#### Package and gem name

The repo package directory [`google-cloud-translate`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/tree/master/google-cloud-translate) will change to `google-cloud-translation`.

The gem name  [`google-cloud-translate`](https://rubygems.org/gems/google-cloud-translate) will change to `google-cloud-translation`.

As a result of changing the package name to `google-cloud-translation`, gh-pages docs paths will also change from [`#/docs/google-cloud-translate/`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-translate/master/google/cloud/translate) to `#/docs/google-cloud-translation/`. 

Please let me know if I've missed anything, I'll be happy to add it to this description.

**Comment by blowmage** [comment]
Placing on hold until we hear this change is ready to be made.

**Comment by danoscarmike** [comment]
@omaray can you confirm the path here?  Can we "wont fix" this one?

**Comment by blowmage** [comment]
@danoscarmike We were told this change was coming, but had been delayed for a bit. That's why we added the `on hold` label.

**Comment by landrito** [comment]
cc @omaray @tcoffee-google Can you provide insight here?

**Comment by quartzmo** [comment]
Closing for now, this can be reopened if needed.
