### ISSUE TITLE
AppVeyor Builds Stopped

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1169]
The builds have stopped on AppVeyor. Some projects have builds queued up from 9 days ago.

**Comment by blowmage** [comment]
@omaray @jgeewax It doesn't look like we have a [paid account](https://ci.appveyor.com/billing) for AppVeyor. Log on with your GitHub credentials and choose the `GoogleCloudPlatform` account.

**Comment by quartzmo** [comment]
Looks to me like these are moving again. @blowmage Can we close this?

**Comment by blowmage** [comment]
Yep, this was fixed when I was on vacation. Closing.
