### ISSUE TITLE
Storage POST objects with the xml-api using an html multipart form

### ISSUE THREAD

**Issue by calavera** [GoogleCloudPlatform/google-cloud-ruby#1177]
Hi! 👋 

I'd like to upload objects to a storage bucket using signed post forms, like described in this guide:

https://cloud.google.com/storage/docs/xml-api/post-object

I thought everything I needed was already present in the [File::Signer class](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage/file.rb#L728-L813), but I'm having a hard time generating signatures like described in the guide's example.

My idea was to add a method that would return an object with the URL to send the form to and a hash of fields to set in the input fields. I was thinking on allowing the api clients to pass a policy document that would be signed in the same fashion that the example shows, but I cannot make it work:

```python
from base64 import b64encode
from M2Crypto import EVP
def Sign(pem_key, message):
    assert pem_key
    key = EVP.load_key_string(pem_key)
    key.reset_context(md='sha256')
    key.sign_init()
    key.sign_update(str(message))
    return key.sign_final()

SecretKey = open('key.pem', 'r').read()
Policy = b64encode(open('policy.txt', 'r').read())
Signature = b64encode(Sign(SecretKey, Policy))
print Policy
print
print Signature
```

I'd really appreciate some advice.

**Comment by blowmage** [comment]
Hi @calavera, File::Signer is private and should not be used. I would use [Bucket#signed_url](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.23.0/google/cloud/storage/bucket?method=signed_url-instance) to create the URL and then POST the file to it.

**Comment by calavera** [comment]
I tried that, but that doesn't work, I get this error:

```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidAuthentication</Code><Message>The provided authentication header is invalid.</Message><Details>Cannot use Query String params with form POST.</Details></Error>
```

It's because the signed url is something like `https://storage.googleapi.com/BUCKET/KEY?QUERY_WITH_ALL_THE_DATA` but in order to send a file using a mutipart form I need each query attribute independently to send it in the form, like the example in the docs:

```
<form action="http://travel-maps.storage.googleapis.com" method="post" enctype="multipart/form-data">
<input type="text" name="key" value="">
<input type="hidden" name="bucket" value="travel-maps">
<input type="hidden" name="Content-Type" value="image/jpeg">
<input type="hidden" name="GoogleAccessId" value="1234567890123@developer.gserviceaccount.com">
<input type="hidden" name="acl" value="bucket-owner-read">
<input type="hidden" name="success_action_redirect" value="http://www.example.com/success_notification.html">
<input type="hidden" name="policy" value="eyJleHBpcmF0aW9uIjogIjIwMTAtMDYtMTZUMTE6MTE6MTFaIiwNCiAiY29uZGl0aW9ucyI6IFsNCiAgWyJzdGFydHMtd2l0aCIsICJrZXkiLCAiIiBdLA0KICB7ImFjbCI6ICJidWNrZXQtb3duZXItcmVhZCIgfSwNCiAgeyJidWNrZXQiOiAidHJhdmVsLW1hcHMifSwNCiAgeyJzdWNjZXNzX2FjdGlvbl9yZWRpcmVjdCI6ICJodHRwOi8vd3d3LmV4YW1wbGUuY29tL3N1Y2Nlc3Nfbm90aWZpY2F0aW9uLmh0bWwiIH0sDQogIFsiZXEiLCAiQ29udGVudC1UeXBlIiwgImltYWdlL2pwZWciIF0sDQogIFsiY29udGVudC1sZW5ndGgtcmFuZ2UiLCAwLCAxMDAwMDAwXQ0KICBdDQp9">
<input type="hidden" name="signature" value="BSAMPLEaASAMPLE6SAMPLE+SAMPPLEqSAMPLEPSAMPLE+SAMPLEgSAMPLEzCPlgWREeF7oPGowkeKk7J4WApzkzxERdOQmAdrvshKSzUHg8Jqp1lw9tbiJfE2ExdOOIoJVmGLoDeAGnfzCd4fTsWcLbal9sFpqXsQI8IQi1493mw=">

<input name="file" type="file">
<input type="submit" value="Upload">
</form>
```

**Comment by blowmage** [comment]
Oh, do you mean using a [POST Object](https://cloud.google.com/storage/docs/xml-api/post-object)?

**Comment by calavera** [comment]
yes, that's what I meant. I didn't find support for it in this library and I wanted to add it, but I might have been looking at the wrong place.

**Comment by calavera** [comment]
I'd like to migrate user generated uploads from S3 to google cloud storage and not having this is a show stopper, since the migration would be much much harder if we had to support two different upload mechanisms. POST Object makes it drop-in replacement, since that's what we use currently with S3.

**Comment by calavera** [comment]
I took a first stab at implementing this in my fork, but I'm not sure if it's the best way to expose this:

https://github.com/calavera/google-cloud-ruby/commit/c356808fd5ce0a253d375fa4f43144f1488f4895

I can open a pull request if it looks correct-ish and we can iterate on it. It still needs documentation and more tests.
