### ISSUE TITLE
Generate content automatically for the table shown on the 'Data Types' page.

### ISSUE THREAD

**Issue by swcloud** [GoogleCloudPlatform/google-cloud-ruby#1180]
Right now, the content is manually added to the generated dummy ruby classes. We need to either generate the content for the table or add Angular app logic to extract the data from the ruby classes in order to display the table.

**Comment by quartzmo** [comment]
I agree.

**Comment by quartzmo** [comment]
My thinking is that until other platforms using the Angular site app have the same problem, it will be better to implement this in the `gcloud-jsondoc` build tool. I think the best approach will be a flag in `toc.json` that will currently only be processed by the build tool, but which could be handled by the Angular app at a later date with no change needed in the configuration. For example, a `generateTocDescription` flag as shown near the bottom of this `toc.json` fragment:

```js
        {
          "title": "V1",
          "type": "google/cloud/datastore/v1",
          "patterns": ["\/datastore\/v1"],
          "nav": [
            {
              "title": "DatastoreClient",
              "type": "google/cloud/datastore/v1/datastoreclient"
            },
            {
              "title": "Data Types",
              "type": "google/datastore/v1",
              "generateTocDescription": true
            }
          ]
        }
```

When true, the description would be appended with a generated table linking to all children in the namespace in the `type` attribute.

**Comment by blowmage** [comment]
We could build a YARD plugin to generate this, instead of putting it in gcloud-jsondoc.

**Comment by quartzmo** [comment]
I'd rather keep all these hacks in one place ;)

**Comment by blowmage** [comment]
I am not in favor of having `gcloud-jsondoc` implement this, since the documentation won't be added to the ruby files and be available to services like rubydoc.info that generate documentation from the files distributed in the gems. Would it be possible to have GAPIC generate the "Data Types" documentation?

**Comment by quartzmo** [comment]
@blowmage I don't think access in rubydoc.info is a problem (see the left nav for [Google/Datastore/V1/AllocateIdsRequest](http://www.rubydoc.info/gems/google-cloud-datastore/Google/Datastore/V1/AllocateIdsRequest), for example.) The need for this table is purely in the gh-pages site, because of the lack of a complete "index" listing in the left nav, or am I mistaken?

**Comment by blowmage** [comment]
Right now the gh-pages site needs a namespace (module or class) to navigate to , so my assumption here is that this documentation will be added to a module or class. Are you thinking about creating a non-existing namespace for the gh-pages app to use?

**Comment by quartzmo** [comment]
That's all I can think of, yes. Probably called "DataTypes"!!!

**Comment by quartzmo** [comment]
Although, the types in jsondoc do not have a strict definition. In the Angular app, they are called "services".

**Comment by quartzmo** [comment]
Something like this: 
`google/datastore/v1/datatypes.json`
```js
{"id":"google/datastore/v1/datatypes","name":"Data Types","title":["Google","Datastore","V1","Data Types"],"description":" < table goes here >","source":null,"resources":[],"examples":[],"methods":[]}
```

**Comment by blowmage** [comment]
Okay.

**Comment by swcloud** [comment]
@quartzmo Looks like you figured out a way to add toc without changing gapic, can you confirm?

**Comment by quartzmo** [comment]
@swcloud Yes, confirmed: In PR #1224. Then, to the best of my knowledge, in #1250 I removed all of the TOC docs that I manually added to GAPIC files.
