### ISSUE TITLE
Document Speech low-level API (GAPIC code)

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1205]
Types such as [v1beta1/speech_api.rb](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-speech/lib/google/cloud/speech/v1beta1/speech_api.rb) are not currently published to the gh-pages documentation.

- [] Remove exclusions from `.yardopts`
- [] Add navigation to GAPIC/gRPC code

**Comment by blowmage** [comment]
Speech will need the functionality covered in #1180 in order to properly expose the GAPIC types. The GAPIC and Protobuf classes share a common namespace.
