### ISSUE TITLE
Cloud Speech Ruby Veneer:  Avoid "Job"

### ISSUE THREAD

**Issue by pbogle** [GoogleCloudPlatform/google-cloud-ruby#1207]
The veneer should avoid the use of the term “job” because this could cause confusion with first-class Job potentially added in a future version of the API. The V1 API will refer to this as LongRunningRecognize

**Comment by blowmage** [comment]
It is common for ruby libraries to call these types of objects "jobs". BigQuery uses the REST API but these objects are called "Job". A soon-to-be announced library uses GRPC and LongTermOperation, but the ruby library calls the object "Job". This is the standard term we have decided to use for the ruby Google Cloud libraries.

We aren't so much concerned with matching the terminology of the underlying service API, we are more concerned with providing a API surface area that will be familiar to ruby programmers. That said, if a future version of the Speech service API introduces new resources we can change the name of this object.

**Comment by pbogle** [comment]
As TL of the speech team, I need to make the call on this based on what I've been told by my OnePlatform API reviewers within Google.

Please feel free to escalate as appropriate if you have been told otherwise.

**Comment by blowmage** [comment]
I'm not trying to push back, just provide some context. 😄 

The current speech methods are [`recognize`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-speech/v0.21.1/google/cloud/speech/project?method=recognize-instance), [`recognize_job`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-speech/v0.21.1/google/cloud/speech/project?method=recognize_job-instance), and [`stream`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-speech/v0.21.1/google/cloud/speech/project?method=stream-instance). If we were to drop "job" we would need to rename the async method and the class of the returned object. What do you think of renaming the `recognize_job` method to `process`, and renaming the [Job](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-speech/v0.21.1/google/cloud/speech/job) class to Operation?

```ruby
require "google/cloud/speech"

speech = Google::Cloud::Speech.new

op = speech.process "path/to/audio.raw",
                    language: en,
                    encoding: :raw,
                    sample_rate: 16000

op_id = op.id
```

```ruby
require "google/cloud/speech"

speech = Google::Cloud::Speech.new

op = speech.operation op_id
```

**Comment by pbogle** [comment]
Our API reviewer recently asked to renamed AsyncRecognize to LongRunningRecognize in the v1 API, due to the "Async" prefix causing issues in some languages.  

How about "long_running_recognize" for Ruby as well, for consistency and clarity?

**Comment by blowmage** [comment]
Has the naming change had been made public? We are still waiting on updated protobufs so we can make the changes. That's why I was being cagey about a "a future version of the Speech service API" before.

We agree with the confusion with "sync" and "async", which is why we didn't use those terms when first implementing the ruby library for the Speech API.

We will add `long_running_recognize` as an alias for the method, and also add `recognize_job` as an alias for backwards compatibility. And we will add `streaming_recognize` as an alias for the `streaming` method while we are at it, for consistency.

**Comment by pbogle** [comment]
Please stay tuned.

**Comment by adziuk** [comment]
It looks like there's still an instance of "job" in audio.rb and operation.rb

**Comment by blowmage** [comment]
The instance of `job` you are referring to is an alias to the new method. This is addressed in my comment above:

> We will add `long_running_recognize` as an alias for the method, and also add `recognize_job` as an alias for backwards compatibility.
