### ISSUE TITLE
Cloud Speech Ruby Veneer: Sample code doesn't show how to wait until recognition is complete

### ISSUE THREAD

**Issue by pbogle** [GoogleCloudPlatform/google-cloud-ruby#1209]
In stream.rb, none of the samples show how to wait until recognition completes; in fact they will potentially exit early before all processing is done.  Could you illustrate best practices in Ruby for doing this?

**Comment by quartzmo** [comment]
@pbogle Thank you for reporting this issue. If I understand correctly, the `5.times do` block used in the example below to take microphone input is problematic in that does not wait for a result? My understanding of the example is that the callback block given to `on_result` will continue to handle recognition results even after `stream.stop` is called. @blowmage any comment?

```ruby
require "google/cloud/speech"

speech = Google::Cloud::Speech.new

stream = speech.stream encoding: :raw, sample_rate: 16000

# register callback for when a result is returned
stream.on_result do |results|
  result = results.first
  puts result.transcript # "how old is the Brooklyn Bridge"
  puts result.confidence # 0.9826789498329163
end

# Stream 5 seconds of audio from the microphone
# Actual implementation of microphone input varies by platform
5.times do
  stream.send MicrophoneInput.read(32000)
end

stream.stop
```

**Comment by pbogle** [comment]
It's very possible I don't understand how the Ruby streaming framework works;  perhaps will block until all results are sent and that side of the stream is closed and we've verified that with a test?

**Comment by pbogle** [comment]
I mean to say, perhaps stop() will block until all results are delivered to on_result?

**Comment by quartzmo** [comment]
I do not believe that the `stop` call will block. Very likely this example was developed in console, and thus execution was continued until all responses were received. 

@blowmage While you work on Speech this week, can you modify the example so that it works if execution ceases after the last line? (Run it from a file, basically...)

**Comment by blowmage** [comment]
I think if you put that code in a file and run it directly, the process will quit as soon as all the last line is run, and it will not wait until a result is returned. This is because the example code is written assuming it is being run as part of a longer running process.

**Comment by quartzmo** [comment]
@blowmage Are you saying the example should remain as it is now?

**Comment by blowmage** [comment]
I'm saying I think the code as it is written now is fine, it just has some assumptions about where is is going to be used. But it would be preferable to add a helper method to block until the stream is completed.

**Comment by pbogle** [comment]
Please document those assumption in comments in the code; Ruby code doesn't necessarily run in a something that will wait for the stream to be completed. If we have a helper method to block until the stream is completed as suggested, couldn't we add it to the sample code?
