### ISSUE TITLE
Add Long Running Operations veneer

### ISSUE THREAD

**Issue by darrennix** [GoogleCloudPlatform/google-cloud-ruby#1214]
Since asynchronous Speech recognize relies on Long Running Operations to communicate when processing is complete, it would be very handy to have a veneer around long-running ops as well.

```wait_until_done!``` is probably not going to get a lot of production use since that would tie up threads for a very long time, indeed.

Thanks for the excellent library @quartzmo

**Comment by quartzmo** [comment]
@darrennix You're welcome! But the real credit for this lib goes to @blowmage.

Anyway, sounds good. Feel free to provide a code example if you want, just to ensure that everyone is on the same page.

**Comment by quartzmo** [comment]
@darrennix Thank you! I'm going to assign this now to @blowmage, who is currently working on Speech.

**Comment by blowmage** [comment]
I think I understand what you are asking for now. How about the following implementation of this functionality?

```ruby
speech = Google::Cloud::Speech.new()

audio = speech.audio(
    ['gs://', Rails.application.secrets.google_cloud_storage_transcription_bucket, '/', media_recording_id, '.wav'].join,
    encoding: :LINEAR16,
    sample_rate: 8000,
    language: 'en-US'
)
google_job = audio.recognize_job
```

Retrieving a job by id will be provided by the Ruby Speech API:

```ruby
# Get the id from the job
google_job_id = google_job.id
RecursiveLongRunningOpsPollingJob.set(wait: wait_interval.seconds).perform_later(google_job_id)

class RecursiveLongRunningOpsPollingJob < BaseJob
  def perform(job_id)
    speech = Google::Cloud::Speech.new()
    google_job = speech.job job_id

    if google_job && google_job.done?
      audio_results = google_job.results
      # process audio results
    else
      # requeue logic
    end
  end
end
```

Would this work for you?

**Comment by darrennix** [comment]
Yup! That would be even better.  If I didn't have to interact with an LRO veneer and instead could just ping the Cloud Speech job for status asynchronously, that would be optimal.

Bear in mind that most people will probably be doing the pinging with ActiveJob, which can have trouble deserializing objects depending on the underlying provider (DJ / Sidekiq) so it's safest to just pass around ids (as you did in your example with ```job_id```).

**Comment by darrennix** [comment]
I tried to shortcut this in the mean time by marshalling the job but no dice when loading it back up
```ruby
google_job = audio.recognize_job
marshalled_google_job = Marshal.dump(google_job)

# If this works, can pass to  MediaRecordingGoogleResultsJob.perform_in(5.seconds, media_recording_id, marshalled_google_job)

google_job = Marshal.load(marshalled_google_job)

TypeError: no _dump_data is defined for class Google::Longrunning::Operation
```

**Comment by blowmage** [comment]
We have some changes coming to Speech soon, and this change will be part of that. Hopefully it will become public soon.

**Comment by blowmage** [comment]
@darrennix To help get you unstuck, you can use the following to accomplish what you are trying to do:

```ruby
require "google/cloud/speech"

speech = Google::Cloud::Speech.new

# get the initial job
job = audio.recognize_job encoding: :raw, sample_rate: 16000

# get the job's id
id = job.grpc.name

# construct a new job object from the id
job2 = Google::Cloud::Speech::Job.from_grpc(OpenStruct.new(name: id), speech.service).refresh!

# verify the jobs are the same
job.grpc.name == job2.grpc.name #=> true
```

This is using many private methods, and because of that is very specific to the current release. Which means this code may not work in the future when a proper public API is added for this functionality. Fair warning, we won't support this code in any way. :)

**Comment by darrennix** [comment]
Oh sick - thank you!  I'm following updates to the library closely and will reimplement when the public API is added.

**Comment by Carpela** [comment]
Is there a workaround I can use here to execute that Operation lookup from id for v 0.22.2. 
i.e. creating a job object such that it will look up and reload the operation  just using the id.
Or could you at least tell me which version this was working for so I can try and pick through the code to mirror it?

**Comment by blowmage** [comment]
@Carpela This functionality was added in [google-cloud-speech 0.24.0](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-speech%2Fv0.24.0).

```ruby
require "google/cloud/speech"

speech = Google::Cloud::Speech.new

audio = speech.audio "path/to/audio.raw",
                     encoding: :linear16,
                     language: "en-US",
                     sample_rate: 16000

op = audio.process
# get the operation's id
id = op.id #=> "1234567890"

# construct a new operation object from the id
op2 = speech.operation id

# verify the jobs are the same
op.id == op2.id #=> true

op2.done? #=> false
op2.wait_until_done!
op2.done? #=> true

results = op2.results
```
