### ISSUE TITLE
Consider dropping GRPCUtils

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1215]
Some of the internal shared code in google-cloud-core are some helper methods for dealing with common protobuf types such as `Google::Protobuf::Value`. It was assumed that all libraries would use these common types the same way, so these helper methods would be shared. However, we've learned that some libraries use these common types in slightly different ways, and the little reuse we were hoping for hasn't panned out.

I think it would be simpler to have all these helper methods local to the library. Yes, there will be some duplication of these helper methods, but in practice only a few methods are used by any service.

**Comment by quartzmo** [comment]
@blowmage You want to leave this open until we remove `GRPCUtils`?

**Comment by blowmage** [comment]
Not sure, I can see closing, and I can see keeping it open.

**Comment by blowmage** [comment]
This change was made. All gems now own their own logic for dealing with core Protobuf types.
