### ISSUE TITLE
Add logging to Google Cloud libraries

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1216]
It might be useful to add a ruby Logger to the Google Cloud libraries. This would allow users to optionally tap into the runtime of the libraries and get debug, info, warn, error, and fatal messages generated by the library.

```ruby
# Set up a new logger
my_logger = Logger.new
Google::Cloud.logger = my_logger

# Logger is used by Google Cloud libraries
datastore = Google::Cloud::Datastore.new
# warn: something happened!
```

**Comment by blowmage** [comment]
Should setting a Google::Cloud Logger object also override the Logger objects used by GRPC and the Google API Client?

```ruby
require "google/cloud/storage"

Google::Cloud.logger = Logger.new("/logs/myapp")
Google::Cloud.logger.level = 0 # Log all messages!

storage = Google::Cloud::Storage.new

bucket = storage.bucket "my-bucket" # API call logged to Google::Cloud.logger?
file = bucket.file "path/to/my-file.ext" # API call logged to Google::Cloud.logger?
```

In other words, does setting a Google Cloud logger also change the logging performed by the clients used to make the API calls? I ask because I was originally hopping to simply set the logger object on the client instance objects, but it turns out both GRPC and Google API Client use a global logger object.

```ruby
# Set GRPC logger, this raises a already initialized constant warning
GRPC::DefaultLogger::LOGGER = Google::Cloud.logger

# Set the Google API Client logger
Google::Apis.logger = Google::Cloud.logger
```

**Comment by blowmage** [comment]
Actually, setting a client instance object logger may be possible with Google API Client, but isn't possible yet with GRPC. But this might be something we could add to google-gax...

**Comment by blowmage** [comment]
@geigerj ^ What do you think about this? How deep into the dependency chain should setting `Google::Cloud.logger` affect?

**Comment by blowmage** [comment]
> setting a client instance object logger may be possible with Google API Client

Nope, this isn't possible right now. It must be set using the following:

```ruby
# Set the Google API Client logger
Google::Apis.logger = Google::Cloud.logger
```

**Comment by quartzmo** [comment]
What is the motivation for logging statements in the Veneer layer? As a user of these libraries, I think my goal would be to enable debug logging of **request** and **response** data, but I believe this can already be done through [grpc/logconfig.rb](https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/logconfig.rb) and/or [google-api-ruby-client#logging](https://github.com/google/google-api-ruby-client#logging). However, I do think it would probably be a good idea to add our own documentation explaining how to configure logging in these clients.

**Comment by blowmage** [comment]
This was an open question that was created as an issue back when we were using issues to track questions.  I do agree that logging the lower level API access libraries will likely be much more valuable than logging the Google Cloud (veneer) libraries. 

After exploring this today I don’t really see many instances where logging in the Google Cloud layer will be that useful. @geigerj what do you think about this?

**Comment by geigerj** [comment]
I generally agree with @quartzmo that request/response logging is probably better done with documentation than additional functionality in the libraries, unless we see a specific request for this logging within the libraries themselves.

**Comment by blowmage** [comment]
K, I'll stop working on this and close the issue and create a new issue to better document meaningful logging in these libraries.
