### ISSUE TITLE
Google Cloud Speech API - AAC filetype encoding?

### ISSUE THREAD

**Issue by echan00** [GoogleCloudPlatform/google-cloud-ruby#1218]
Any plans to include additional filetype encodings such as AAC audio?

**Comment by blowmage** [comment]
The ruby library is limited by the encodings supported by the API. When the API supports more encodings the ruby library will also start to support them.

Here are the encodings supported now:

https://cloud.google.com/speech/reference/rpc/google.cloud.speech.v1beta1#google.cloud.speech.v1beta1.RecognitionConfig.AudioEncoding

**Comment by echan00** [comment]
ok thanks!
