### ISSUE TITLE
Datastore with 0.6.3 gives error about Daily Limit exceeded

### ISSUE THREAD

**Issue by mattsarney** [GoogleCloudPlatform/google-cloud-ruby#1219]
I'm getting a daily limit exceeded response when calling find on a datastore using gcloud v0.6.3.  We are bound to v0.6.3 in our production environment because of some limitation or conflict with upgrading glibc.

Is there a way to get datastore working with v0.6.3?  I've captured the script and output below.  I get the datastore entity back (blob of XML in a property called 'xml') when using v0.10.0 or higher.  

```
$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

$ env | grep GOOGLE
GOOGLE_CLOUD_PROJECT=onix-api-dev
GOOGLE_CLOUD_KEYFILE=/Users/msarney/code/snippets/onix-dev.json

$ gem list gcloud

*** LOCAL GEMS ***

gcloud (0.11.0, 0.10.0, 0.9.0, 0.8.2, 0.8.0, 0.7.2, 0.7.1, 0.7.0, 0.6.3)

$ cat gc_dstest.rb 
gem 'gcloud', ' = 0.6.3'
require 'gcloud'

ds_namespace = 'ONIX'
ds_kind = 'ONIXMessage'
id = '9780077430887'

begin
  gcp = Gcloud.new
  ds = gcp.datastore
  key = ds.key(ds_kind, id) #, namespace: ds_namespace)
  ent = ds.find(key)
  puts ent['xml'] if ent['xml']

rescue Gcloud::Datastore::Error => e
  puts "Error: #{e.response.status}"
  puts "Body: #{e.response.body}"
  puts e
end

$ ruby gc_dstest.rb 
Error: 403
Body: Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/datastore/quotas?project=737483488206
API call to lookup was not successful
```

**Comment by mattsarney** [comment]
Hi @blowmage - our situation regarding glibc is in reference to #713 - I work with arparker.  Our production environment is on an older OS version that doesn't have a patching path to a newer glibc version, updating glibc for us requires a new OS version.

Is there any way to patch 0.6.3 to work with datastore calls, even deprecated version?  This would likely tide us over until our apps move into GCE/containers in the next few months.

**Comment by quartzmo** [comment]
@mattsarney We really sympathize with your need, but we can't prioritize this right now above some other urgent deliverables we are working to release. Can you fork from `v0.6.3` and adapt that to use [Google Cloud Datastore API `v1`](https://cloud.google.com/datastore/docs/reference/rest/)?

**Comment by mattsarney** [comment]
@quartzmo We are using cloud storage for this particular use case and seems to perform ok for what we need.  If for some reason our use of storage isn't working out we can fork or use the REST API directly for datastore.  We'll be moving to GCE soonish so can then use the current gem version.

**Comment by quartzmo** [comment]
@mattsarney Glad to hear it. OK to close this issue?

**Comment by mattsarney** [comment]
Yes
