### ISSUE TITLE
Features use gRPC not compatible with Ruby 2.4 

### ISSUE THREAD

**Issue by premist** [GoogleCloudPlatform/google-cloud-ruby#1228]
google-protobuf gem is [not compatible](https://github.com/google/protobuf/issues/2541) with Ruby 2.4 until version 3.1.0, and version 3.2.0 is not pushed to the RubyGems repository.

**Comment by blowmage** [comment]
We are unfortunately aware of this and waiting on new releases of GRPC and Protobuf to support Ruby 2.4. See https://github.com/grpc/grpc/pull/9291 and https://github.com/google/protobuf/issues/2541

**Comment by blowmage** [comment]
Today we released new versions of all GRPC-based gems. This release updates the dependencies on `grpc`, `google-protobuf`, and `google-gax` and adds Ruby 2.4 support.

@premist, can you verify these new releases for work you on Ruby 2.4?

**Comment by premist** [comment]
Hi @blowmage, I verified that `google-cloud-trace` gem works with Ruby 2.4! Feel free to close this issue.

**Comment by blowmage** [comment]
Wonderful! Thanks for verifying.
