### ISSUE TITLE
Unexpected error RST_STREAM using PubSub

### ISSUE THREAD

**Issue by Draiken** [GoogleCloudPlatform/google-cloud-ruby#1230]
We just migrated to Google Cloud today (yay) but we're having a zillion of these errors:
```
13:{"created":"@1487005780.331223974","description":"RST_STREAM","file":"src/core/ext/transport/chttp2/transport/frame_rst_stream.c","file_line":107,"http2_error":2}
```
I have no idea where this comes from or how to fix it.
We're using:

Dep | Version
-----  | ---------
ruby | 2.2.5
google-cloud-core | 0.21.1
google-cloud-pubsub | 0.21.0

**Comment by blowmage** [comment]
@nicolasnoble @murgatroid99 Can either of you shed some light on this?

**Comment by blowmage** [comment]
@swcloud Can we escalate this to the GRPC team?

**Comment by blowmage** [comment]
@Draiken Here is some context for the error. I'm not an expert at GRPC, so this is according to my own understanding. I hope others will correct me if needed. An [RST_STREAM frame](http://www.grpc.io/docs/guides/wire.html#http2-transport-mapping) is used when a message stream becomes corrupted. So this looks like it might be a network issue. Where is your app you hosted?

Also, the error message begins with "13", which is the [GRPC error code](https://godoc.org/google.golang.org/grpc/codes) for internal error. However, I don't know if this error is being raised from the server, or is being raised in the GRPC client as a response to the RST_STREAM frame.

That string looks like the information written to STDOUT (or STRERR) by the GRPC client, but all errors raised should be wrapped in a Google::Cloud::Error object. Are you seeing actual errors in your application to go along with these GRPC messages?

**Comment by Draiken** [comment]
This is being generated by background workers when publishing to pubsub. We're hosted on GKE so it's very unlikely that google's own networking is having so many problems.

We've had over 1M errors already (we flipped the switch to GKE today) and it's really hindering the performance of the workers. Seems completely random, didn't find any pattern on message size and we use just one topic.

We use Sidekiq (a ruby background job processor, you probably know it) and it uses threads for workers. Maybe that's the issue? We didn't have this error before and we've been testing this for months. First time we saw this was two weeks ago on one singular event which led us to discard it as an "one off" problem.

This is a full stacktrace: https://gist.github.com/Draiken/4e22e0f6dfc9aeb1565c5f7e87ead5a6

**Comment by blowmage** [comment]
Thank you for the backtrace. It shows the error is being wrapped by `Google::Cloud::InternalError`, so this is definitely an error that is being raised. From the backtrace it looks to me like it is being returned by the server, but I am not an expert and it may still be raised by the GRPC client. I don't see any API indents listed on the [Pub/Sub status](https://status.cloud.google.com) though.

The patten you are describing seems to describe an issue originating from API server. As I said before, code 13 means an internal error, so this doesn't seem like something that you are doing, or the google-cloud-pubsub client library is doing, but something happening on the server.

@swcloud Is this something that can be escalated to the Pub/Sub team? Being completely outside of Google, I don't know how to route customer support requests like this.

**Comment by blowmage** [comment]
@danoscarmike Is this related at all to the client changes being made to the Java and Go Pub/Sub libraries?

**Comment by danoscarmike** [comment]
Sorry for delay.  Stand by...

**Comment by apolcyn** [comment]
Not sure it's possible but does Sidekiq happen to be used in a way that it's forking off child processes?

**Comment by Draiken** [comment]
I believe it used threads, but it's possible they changed to forking. I'll
have a look at their source code/docs to give you a better answer as soon
as I can

**Comment by blowmage** [comment]
@Draiken What percentage of jobs are seeing this error?

**Comment by Draiken** [comment]
We send in average 1.2M messages a day and had 126k errors, so about 10%

On Thu, Feb 16, 2017, 10:35 PM Mike Moore <notifications@github.com> wrote:

@Draiken <https://github.com/Draiken> What percentage of jobs are seeing
this error?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1230#issuecomment-280512348>,
or mute the thread

**Comment by Draiken** [comment]
Sidekiq does not use forks, only threads to handle workers.

Is there any kind of setup we need to perform after each thread is initialized?

Can I help on this with anything else? I feel like my hands are tied :confused:

**Comment by blowmage** [comment]
@swcloud Has the Pub/Sub team been notified of this?

**Comment by swcloud** [comment]
@blowmage I just notified them.

**Comment by Draiken** [comment]
We went ahead and upgraded to 0.22.0 and the error finally disappeared...
Now I only have the occasional `DeadlineExceededError` which seems to be expected to happen sometimes

**Comment by blowmage** [comment]
@Draiken Great news! If you upgrade further to the 0.23.0 you should stop seeing those deadline exceeded errors, as that release contains a fix for the retry logic. Most requests that return that error should be automatically retried by the library.
