### ISSUE TITLE
Add Ruby 2.4 to CI

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1231]
Ruby 2.4 support is coming with new versions of the grpc, google-protobuf, and google-gax gems. Add Ruby 2.4  to the CI environments when this happens.

**Comment by blowmage** [comment]
Right now we have configured the library with 4 nodes on CircleCI. Ruby 2.4 would require a 5th node. However, we may want to rewrite the build script so that we can deal with an arbitrary number of CircleCI nodes, and an arbitrary number of Ruby versions.

**Comment by blowmage** [comment]
See https://circleci.com/docs/parallel-manual-setup/#env-splitting

**Comment by blowmage** [comment]
We can't add Ruby 2.4 to the build just yet. We have a development dependency on Rails 4, and unfortunately Rails 4 won't support Ruby 2.4 until Rails 4.2.8 is released.

We may also have to unpin rubocop in order to support Ruby 2.4. So this change may end up being larger than we had hoped.

**Comment by dazuma** [comment]
Rails 4.2.8 landed on Feb 21.

I've been able to run test, doctest, and rubocop across all libraries on Ruby 2.4.0, so I think we're okay without having to pin rubocop for now. Rainbow 2.1.0 is giving a Ruby 2.4 warning, but it's not fatal. I haven't tried acceptance tests yet.

**Comment by blowmage** [comment]
Yeah, I was originally thinking that we would have to upgrade to Rake 12, since it ships with Ruby 2.4, but this doesn't seem to be a problem as long as we `bundle exec` all the build calls. I've run the full build on Ruby 2.4 locally, including acceptance tests. But I would still like to update the build to use an arbitrary number of CircleCI nodes.

We do need to stay on the technology treadmill though, I don't like depending on non-current versions of other libraries, even if it is only for development.
