### ISSUE TITLE
Cloud Spanner Support?

### ISSUE THREAD

**Issue by reneklacan** [GoogleCloudPlatform/google-cloud-ruby#1232]
Hi, is there plan to add support for Cloud Spanner? If yes then any idea when?

**Comment by quartzmo** [comment]
Yes, for sure! Very soon!

**Comment by reneklacan** [comment]
@quartzmo Thank you for quick answer!

**Comment by quartzmo** [comment]
We are very excited about [Cloud Spanner](https://cloud.google.com/spanner/).

**Comment by blowmage** [comment]
We don't have an ETA for the Spanner client, but it remains a high priority.

Is this issue resolved? Can it be closed?

**Comment by quartzmo** [comment]
Yes, closing. Spanner coming soon!

**Comment by reneklacan** [comment]
👏

**Comment by reneklacan** [comment]
It's probably not scope of this repo but having ActiveRecord adapter from you guys would be really awesome and it would really help Spanner to get even more attention.

**Comment by quartzmo** [comment]
@reneklacan I'm glad you mentioned that!

**Comment by blowmage** [comment]
We have discussed an activerecord adapter, but there are several complications. I hope we can make something work.

**Comment by ukd1** [comment]
@quartzmo is their a ticket where we can follow this? We are also interested in Ruby support.

**Comment by quartzmo** [comment]
@ukd1 This is the only issue, so the branch is the way to watch for progress.

**Comment by blowmage** [comment]
Now that Spanner is public all future development will be happening on master. I'll remove the spanner branch.

**Comment by quartzmo** [comment]
Oh yeah, sorry @ukd1, the branch has been merged. Look for new PRs with the `API: spanner` label that is on this issue.

**Comment by reneklacan** [comment]
@quartzmo @blowmage hi guys, how does it please looks with AR adapter? any plans for it?

**Comment by reneklacan** [comment]
> That will have to happen on our personal time.

That is kind of stupid from your employer :-/ 

@blowmage Anything I can do to help?

**Comment by blowmage** [comment]
Contribute what you can to [supership-jp/activerecord-spanner-adapter](https://github.com/supership-jp/activerecord-spanner-adapter). It looks like @yugui has been making changes, but I'm sure she would appreciate more eyes on the project.
