### ISSUE TITLE
Transaction Retry Loop

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1234]
Transaction failing with an `ABORTED` status it needs to be retried, with backoff. The backoff value from the `RetryInfo` object should be used. *All* user operations done under the aborted transaction need to be retried.

**Comment by blowmage** [comment]
Reopening to track the discover of the backoff value from RetryInfo.

**Comment by vkedia** [comment]
I think this has been resolved? Please close in that case.

**Comment by blowmage** [comment]
Yes.
