### ISSUE TITLE
Resume broken streams

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1236]
The PartialResultSet object can contain a resume token which can be used to resume a broken stream. The resume token is not guaranteed to be in every message. Results should be buffered until a resume token is present before yielding.

If a stream is broken, a new API request should be made with the token, and results continued to yielded from the new streaming response. If the broken stream cannot be resumed a failure should be raised.

**Comment by blowmage** [comment]
We are not yet sure what constitutes a broken stream, or how the returned Enumerator will behave when a stream is broken.

**Comment by vkedia** [comment]
Broken stream essentially means that grpc threw an error while consuming results from the stream. The enumerator returned by grpc will not yield any more PartialResultSets after this. So you make a new request and pass in the resume token. That will give you a new enumerator. All this should happen behind the scenes and the user should be able to continue getting results.

**Comment by blowmage** [comment]
Reopening so we can track the requirement to get the delay value.

**Comment by blowmage** [comment]
Oops, wrong issue.
