### ISSUE TITLE
Write more integration tests for BigQuery

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-ruby#1238]
Please see email I sent about the details and test cases from @tswast . 

Also, C# has [some examples](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.IntegrationTests/ExhaustiveTypesTest.cs) that might be worth looking at.

/cc @jskeet @jba @tswast @danoscarmike

**Comment by blowmage** [comment]
The process of adding additional acceptance tests has uncovered several incomplete or missing features. New issues have been created for them.
