### ISSUE TITLE
Is OrderedHash needed?

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1243]
I've been going through the GRPC-based gems' dependencies and I noticed Logging's dependency on OrderedHash. I didn't know anything about this gem so I did some research. I couldn't find a repo for it, but I did notice that it hasn't had a release in [over eight years](https://rubygems.org/gems/orderedhash/versions/0.0.6). Looking at [the docs](http://www.rubydoc.info/gems/orderedhash/0.0.6/OrderedHash) doesn't tell us much about what this object is supposed to do. But it does seem similar to [ActiveSupport::OrderedHash](http://api.rubyonrails.org/classes/ActiveSupport/OrderedHash.html), and I am assuming that this gem is the origin of AS::OH.

AS::OH defines itself as a "hash that preserves insertion order". This makes sense, since Hash in Ruby 1.8 didn't preserve insert order. But ever since Ruby 1.9 Hash _has_ preserved insert order. In fact, ever since Rails dropped Ruby 1.8 support AS::OH has simply inherited from Hash and does nothing to affect order. Since all google-cloud-* gems require Ruby 2.0 or greater, is the dependency on `orderedhash` necessary? Or is OrderedHash being used for something other than preserving insert order?

**Comment by quartzmo** [comment]
It appears that @hxiong388 added this dependency on 10/13/16, so I'll wait for his comment. Afaik it should not be needed, but maybe there is some reason related to concurrency.

**Comment by hxiong388** [comment]
I used OrderedHash for that exact purpose, preserve insertion order. I didn't know Ruby's built-in Hash already supports this feature. I will refactor the Logging gem to remove this dependency.
