### ISSUE TITLE
Natural Language: Remove encoding argument

### ISSUE THREAD

**Issue by landrito** [GoogleCloudPlatform/google-cloud-ruby#1255]
Based on internal feedback, we should default the encoding based on the fact that the user is using Ruby v2.0+.

**Comment by landrito** [comment]
@danoscarmike Can you add this to the ML project.

**Comment by swcloud** [comment]
@blowmage Can you make this priority since we want to fix this before March 3.

**Comment by blowmage** [comment]
Yep.

**Comment by blowmage** [comment]
AFAICT this already happens. Actions that do not specify an encoding generate requests to the API that include `:UTF8`.

I submitted #1267 to update the documentation to make this more clear. Can this issue be closed?

**Comment by blowmage** [comment]
Closing as this is already implemented.

**Comment by landrito** [comment]
The encoding type is actually in regards to the encoding type the user expects from the API. Since Ruby's default encoding is UTF-8 for versions 2.0+ we should not even expose this parameter.

Heres the bit of documentation in regards to this: https://github.com/googleapis/googleapis/blob/master/google/cloud/language/v1/language_service.proto#L927

**Comment by blowmage** [comment]
@landrito Should the Ruby client always use `UTF8`? Or should it check if `Encoding.default_internal` is `Encoding::UTF_16` or `Encoding::UTF_32` and use that encoding?

**Comment by landrito** [comment]
Since the api supports utf16 and utf32 I think it would be best to use utf8 if `Encoding::UTF_8` is found, utf16 if `Encoding ::UTF_16` is found and, utf32 if `Encoding::UTF_32` is found. 

`Encoding.default_internal` can find other encodings besides utf8, utf16, or utf32. It's up in the air what we should do for that scenario. I'm leaning towards defaulting to utf8 if it is not utf16 or utf32. Thoughts?

**Comment by blowmage** [comment]
I think it would be best to use UTF8 unless the system is set to UTF-16 or UTF-32. So if the system is set to ISO-8859-1 the API call will be made with UTF8. Does that work for you?

**Comment by landrito** [comment]
Works for me.
