### ISSUE TITLE
NoMethodError·undefined method `page_descriptor' for nil:NilClass

### ISSUE THREAD

**Issue by Draiken** [GoogleCloudPlatform/google-cloud-ruby#1261]
This error seems to happen at random times on Sidekiq which leads me to believe it's a concurrency issue.

Happens on calls like
```
project.publish(topic, message)
```

Stacktrace: https://gist.github.com/Draiken/25a67cb8a38feed8bcf3e25854cbbad6
Ruby: 2.2.5
PubSub: 0.22.0

**Comment by blowmage** [comment]
How often?

**Comment by Draiken** [comment]
Pretty rare. I figured I'd report it otherwise it wouldn't ever be fixed,
but I imagine this will be low priority for you guys

**Comment by blowmage** [comment]
What version of grpc are you using?

**Comment by Draiken** [comment]
1.1.2

**Comment by blowmage** [comment]
@swcloud @landrito Do you guys want to look at this? It seems that when a GAPIC client is created the call settings object being passed into the GAX code is `nil`. But this only happens rarely. Thoughts?

**Comment by quartzmo** [comment]
@Draiken Have you seen this issue again?

**Comment by quartzmo** [comment]
@landrito Did you ever look into this?

**Comment by landrito** [comment]
I did look into this but never was able to repro :(

**Comment by blowmage** [comment]
Should this issue be kept open?

**Comment by landrito** [comment]
Lets close this since this was before we reimplemented pubsub and reopen if found again.

**Comment by quartzmo** [comment]
Thanks @landrito!
