### ISSUE TITLE
Document Translate low-level API (GAPIC code)

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/google-cloud-ruby#1263]
There's an issue to [Document Speech low-level API (GAPIC code)](https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1205) #1205 

Right now, the documentation for [Language](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.25.0/google/cloud/language) and [Vision](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.25.0/google/cloud/vision) has `V1` navigation items that navigate to low-level GAPIC API reference documentation.

I imagine this should be consistent across all ML APIs?  @quartzmo ?

Copied labels from the equivalent Speech issue.

**Comment by blowmage** [comment]
Right now there is no low level API for Translate. It used to use the Google API Client, but that was switched to use a custom implementation hitting the REST endpoints. The other low level API clients all use the GRPC endpoints, and that is what is being documented as the low level API. To fulfill this issue Translate would need to switch to a GRPC endpoint, but AFAIK that does not exist.

Can we remove the P1 and Blocking labels from this issue?

**Comment by quartzmo** [comment]
@remi Do you maybe want to change this to "Use GAPIC in Translation" or something? I don't know how to address the docs inconsistency on its own.

**Comment by danoscarmike** [comment]
@remi this one seems invalid.  Can we close?
