### ISSUE TITLE
Update Gapic Clients to use new http headers.

### ISSUE THREAD

**Issue by landrito** [GoogleCloudPlatform/google-cloud-ruby#1268]
This is a tracking meta-issue for updating the gapic clients to use the new http headers.

Each PR should:

  * The `lib_name` and `lib_version` keyword arguments to the GAPIC client for the clients that are wrapped by a hand-written layer.

Completion List:
  * [x] Datastore (#1269)
  * [x] Error Reporting (#1270)
  * [x] Language (#1271)
  * [x] Logging (#1272)
  * [x] Monitoring (#1273)
  * [x] PubSub (#1274)
  * [x] Spanner (#1275)
  * [x] Speech (#1276)
  * [x] Trace (#1277)
  * [x] Vision (#1278)

**Comment by landrito** [comment]
Hopefully doing it like this will reduce your cognitive load @blowmage!

**Comment by blowmage** [comment]
Closing as all these pull requests are now accepted.

**Comment by bjwatson** [comment]
@blowmage @landrito Can you let me know when all of these updates packages have been published?

**Comment by blowmage** [comment]
Should be later this week or early next week.

**Comment by bjwatson** [comment]
@blowmage Please make every effort to deploy this week, especially for Vision and Logging. Every day we wait, we're losing usage metrics.

**Comment by blowmage** [comment]
@bjwatson I can release them all today, except for Natural Language. Is that okay?

**Comment by bjwatson** [comment]
Sounds great! Thanks @blowmage.

**Comment by blowmage** [comment]
@bjwatson All these changes are released, except for Natural Language, which has some breaking changes and will be released with the next batch of major releases.

**Comment by bjwatson** [comment]
Thanks Mike!
