### ISSUE TITLE
Add Pub/Sub Data Types documentation

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1282]
#1274 adds the protobuf definitions to the generated GAPIC documentation. Add these classes to the jsondoc documentation.

**Comment by quartzmo** [comment]
The Pub/Sub documentation is already [configured for protobuf](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-pubsub/Rakefile#L133-L134), but is there something new that doesn't match the existing configuration?

**Comment by blowmage** [comment]
So strange, I was looking at that file and task and it didn't have the configuration. Perhaps I was looking at an older branch...
