### ISSUE TITLE
Datastore - what controls the batch size of query results?

### ISSUE THREAD

**Issue by bmclean** [GoogleCloudPlatform/google-cloud-ruby#1319]
What controls the batch size on the number of results returned from a datastore query?

For example, let's say I have 2000 recipes in datastore. 
```
datastore = Google::Cloud::Datastore.new
query = datastore.query "Recipe"
```
When I perform `run` on the query, I initially get 300 results.
`query_results = dataset.run query`

When I execute `all` on the QueryResults enumerator, I get all 2000 recipes 300 at a time.
`query_results.all`

But where is this batch size of 300 configured? Is it dynamically handled by datastore? Can it be overridden for testing? We just got caught where one of our query methods was missing the `.all`.

**Comment by blowmage** [comment]
Results are returned [in batches](https://cloud.google.com/datastore/docs/reference/rest/v1/projects/runQuery#QueryResultBatch), and the batch size is determined by the Datastore API. AFAIK there is no mechanism for controlling the size of a batch, but you can use [`Query#limit`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-datastore/v0.24.2/google/cloud/datastore/query?method=limit-instance) to control the total number of results that would be returned across all batches.

Batch size is not guaranteed. I believe it will be affected by the size of the data being returned, and by other forces such as how distributed and/or consistent the data in Datastore is.

Does this help? If not, can you ask a follow up question? If it does help, can you mark the issue closed?

Thanks @bmclean!

**Comment by bmclean** [comment]
Thanks @blowmage. Yes, that helps. I think we can add a regression test for the missing `all` by validating Enumerator vs Google::Cloud::Datastore::Dataset::QueryResults.
