### ISSUE TITLE
[Proposal] Make Google::Cloud::Storage::File#copy receive storage_class as a option.

### ISSUE THREAD

**Issue by hiroshi** [GoogleCloudPlatform/google-cloud-ruby#1328]
We got following error sometimes when copying a object to another bucket.
`Google::Cloud::Error: uploadTooLarge: Copy spanning locations and/or storage classes could not complete within 30 seconds. Please use the Rewrite method (https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite) instead.`
In the source bucket storage class of objects vary.

To avoid this error, instead of using rewrite, we are planning to copy a object with destination storage class. (then eventually move storage class by lifecycle.)

However `Google::Cloud::Storage::File#copy` doesn't seem to able to take `storage_class` as an option.
https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/19acd3c29e15d3b76d56cd860a437da67bbccfa0/google-cloud-storage/lib/google/cloud/storage/file.rb#L481

`gsutil cp` has `-s <class` option.
https://cloud.google.com/storage/docs/gsutil/commands/cp
> -s <class>	The storage class of the destination object(s). If not specified, the default storage class of the destination bucket is used. Not valid for copying to non-cloud destinations.

So I think we can specify storage class to copy operation. Right?

I'm willing to create a PR to this change, but I'm not sure how to...
https://cloud.google.com/storage/docs/json_api/v1/objects/copy
No mention about storage class option in REST API doc of `copy`.

**Comment by blowmage** [comment]
Related: #1196

**Comment by quartzmo** [comment]
@hiroshi I investigated this, and I am nearly certain that `gsutil cp` does a rewrite when invoked with a storage class change. This passage in [`storage/docs/gsutil/commands/cp`](https://cloud.google.com/storage/docs/gsutil/commands/cp) supports it:

> Copies spanning locations and/or storage classes cause data to be rewritten in the cloud, which may take some time (but still will be faster than downloading and re-uploading). Such operations can be resumed with the same command if they are interrupted

**Comment by quartzmo** [comment]
Thus, copying (vs rewriting) is not a solution to your issue. The correct API method for changing storage classes is `Objects.rewrite`, which is resumable using `rewriteToken` as mentioned in the passage above, and also in the [`Objects.rewrite` docs](https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite): 

> A token to use in subsequent requests to continue copying data. This token is present in the response only when there is more data to copy.

Thus, #1196 should resolve your issue. I will close this issue now, so please subscribe to #1196 for notifications.

**Comment by hiroshi** [comment]
I don't understand about `Objects.rewrite` yet, but what I want to do is `keep storage class on copy to avoid slow transfer`.

Anyway, I'll revisit the issue later.
