### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by arakanema** [GoogleCloudPlatform/google-cloud-ruby#1329]
In
[https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.26.0/google/cloud/datastore](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.26.0/google/cloud/datastore)

at **"Paginating records"**

❌ tasks.all do |task| 
⭕️ tasks.all do |t|

❌
```require "google/cloud/datastore"

datastore = Google::Cloud::Datastore.new

query = datastore.query("Task")
tasks = datastore.run query
tasks.all do |task|
  puts t["description"]
end
```
⭕️ 
```require "google/cloud/datastore"

datastore = Google::Cloud::Datastore.new

query = datastore.query("Task")
tasks = datastore.run query
tasks.all do |t|
  puts t["description"]
end
```

**Comment by quartzmo** [comment]
@arakanema Thank you very much!
