### ISSUE TITLE
Test top 4 APIs on GAE Flex, GKE, and GCP

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-ruby#1333]
Test BigQuery, Storage, Datastore, and Logging client libraries on all the GCP platforms (don't include GAE Standard).

Close this issue once we confirm it all works.

**Comment by blowmage** [comment]
@swcloud Any input on how to do this? Should this be automated?

**Comment by quartzmo** [comment]
I think the [Logging integration tests](https://github.com/GoogleCloudPlatform/google-cloud-ruby/tree/master/google-cloud-logging/integration) may serve as a foundation.

**Comment by thagomizer** [comment]
If it doesn't need to be automated I can help. I used logging on 2 flex apps (one in production). I used storage via fog but can switch to our storage library in both. And deploying that code to GCE and GKE is straightforward. I'm only testing the happy path but it is working great.

**Comment by quartzmo** [comment]
Thanks @thagomizer!

I will start down the automation path today, but manual tested may very well be needed depending on the schedule. 

I also propose creating separate issues for each package and each GCP platform.

**Comment by omaray** [comment]
Hey guys - if automating is too much work let's hold off and chat at the next meeting. The idea was indeed to sanity check first to make sure we're not hitting anything obvious here that our customers would hit simply by deploying and calling our libraries.

But if we can easily automate, then yes that would also be awesome.

**Comment by quartzmo** [comment]
@omaray I'll do a bit more research into test automation, so that we can have a better-informed discussion at the next meeting. I will also try to manually or semi-manually execute some tests as part of the exploration.

**Comment by quartzmo** [comment]
@hxiong388 I believe I have successfully executed your amazing (and amazingly involved) automated GAE and GKE testing for Error Reporting and Logging, and I am hoping to use expand it to run tests for the packages in this issue. These tests will be as simple as possible, which I believe still involves deploying them within a Sinatra web app. At this point, I'm wondering: What is your take on testing GCE?

**Comment by hxiong388** [comment]
GAE and GKE tests can be automated relatively easier, thanks to gcloud SDK and kubectl. While GCE may be a bit harder due to its IaaS nature. I think if we can get the tests automated on GAE and GKE, it may be sufficient to imply the coverage for GCE, because:
1. GAE and GKE are currently hosted from GCE vms. 
2. The GCE environment's two main services, metadata service accessibility and application default authentication, should both be covered by the GAE and GKE automation tests as well.

We can discuss more in our next meeting. Like what else do we wish to test on GCE that's not covered by GAE, GKE, and Travis automated tests. Then compare that with the effort involved to automate GCE  tests.
.

**Comment by quartzmo** [comment]
Thanks @hxiong388, this helps a lot.

**Comment by lukesneeringer** [comment]
@hxiong388 Poking you here to ask you to send me the explanation of what you decided to do on Ruby, as at some point I will be wanting to make a consistent automation plan for multiple languages. (My Google LDAP is the same as my GitHub username.)

**Comment by hxiong388** [comment]
@lukesneeringer For lack of better documentation, the current Ruby integration tests can be found at the [Rakefile ](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/853c00f3a933aec8bbe49c9a3e278f59aacd468e/Rakefile#L656-L741) and [integration test directory](https://github.com/GoogleCloudPlatform/google-cloud-ruby/tree/master/integration). I think the code is self-explanatory for Ruby developers, but if you have any questions about the code, feel free to ping me internally at hexiong@. FYI, the Ruby [doc samples](https://github.com/GoogleCloudPlatform/ruby-docs-samples/tree/master/spec) projec also does similar automated integration tests.

I will write an internal document that explains some of the design rationale, and share this doc with everyone later.

**Comment by lukesneeringer** [comment]
@hxiong388 I guess the question I was asking is, how did you automate this on GCE/GKE? (I manually created instances and ran tests.)

**Comment by hxiong388** [comment]
@lukesneeringer Almost forgot, we do have some [instructions ](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/CONTRIBUTING.md#integration-tests) on how to run the integration tests.

**Comment by hxiong388** [comment]
@lukesneeringer We don't automate GCE tests, because 1. it's really hard to automate configuration on GCE VM. 2. We think almost all the features for GCE scenario is covered by other automated tests.

For GKE, the testing GCP project does need to have a GKE cluster configured before hand. After that, you can automate docker image building, pushing to GCR, and GKE pod deployment using gcloud SDK and kubectl. See this [code section](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/853c00f3a933aec8bbe49c9a3e278f59aacd468e/integration/deploy.rb#L66-L162) on how I did all that.

**Comment by lukesneeringer** [comment]
Thanks @hxiong388, that was what I needed. I will try to create something even more complete in the future.

**Comment by hxiong388** [comment]
@lukesneeringer Sounds good. Let us know if you figure out an easy way to automate GCE tests. cc @nkubala, who is probably also interested in GCE automation.

**Comment by quartzmo** [comment]
Per today's offline meeting, all testing for this issue should be completed ASAP, with no automation needed. I will try to document what the manual steps I took as best I can.

### Google Compute Engine


#### bundle exec rake test

```sh
Finished in 8.550038s, 262.1041 runs/s, 2038.1195 assertions/s.
  1) Failure:
Google::Cloud::.translate#test_0001_gets defaults for api key [/home/quartzmo/google-cloud-ruby/
google-cloud-translate/test/google/cloud/translate_test.rb:116]:
Expected "redacted-91516" to be empty?.
  2) Failure:
Google::Cloud::.translate#test_0002_uses provided api key [/home/quartzmo/google-cloud-ruby/goog
le-cloud-translate/test/google/cloud/translate_test.rb:139]:
Expected "redacted-91516" to be empty?.
  3) Failure:
Google::Cloud::Translate.new#test_0001_gets defaults for api key [/home/quartzmo/google-cloud-ru
by/google-cloud-translate/test/google/cloud/translate_test.rb:217]:
Expected "redacted-91516" to be empty?.
  4) Failure:
Google::Cloud::Translate.new#test_0002_uses provided api key [/home/quartzmo/google-cloud-ruby/g
oogle-cloud-translate/test/google/cloud/translate_test.rb:240]:
Expected "redacted-91516" to be empty?.
  5) Failure:
Google::Cloud::ErrorReporting::Middleware::#initialize#test_0003_raises ArgumentError if empty p
roject_id provided [/home/quartzmo/google-cloud-ruby/google-cloud-error_reporting/test/google/cl
oud/error_reporting/middleware_test.rb:82]:
ArgumentError expected but nothing was raised.
2241 runs, 17426 assertions, 5 failures, 0 errors, 15 skips
```

@blowmage Are the unit test failures above consistent with your expectations for GCE?

**Comment by blowmage** [comment]
Those are all unit tests, which should be completely mocked out. So them failing surprises me.

But I thought we discussed running the acceptance tests on GAE/GKE/GCE, not the unit tests. Don't we want to hit the real API?

**Comment by lukesneeringer** [comment]
Yes re: acceptance tests, although if your unit tests are failing, that is likely a problem. ;-)

**Comment by quartzmo** [comment]
@blowmage I'll run acceptance tests too, I just need to modify the rake task(s), since they currently expect a special test auth configuration. I need to test the ordinary credentials in these environments.

I'll look into why those unit tests are failing.

**Comment by quartzmo** [comment]
I have run both unit and acceptance tests on GCE, with all tests passing for the entire project, except for a small number of tests which were written to depend on credentials present in the downloaded project keyfile that are not present in the GCE environment.

**Comment by quartzmo** [comment]
I have run both unit and acceptance tests on GKE as well. Unit tests passed. Acceptance tests for every gem passed with the exception of the 2 Sink tests in Logging and a number of Storage tests, which all failed on permissions for my service account. The service account has the "Owner" role so I'm a bit stumped. I am continuing to try to debug the issue.

**Comment by quartzmo** [comment]
Following @remi's [instructions for Ruby in a Google App Engine (GAE) flexible environment SSH session](https://gist.github.com/remi/ab8d9c6d998f56cf31a6ac2030ec1fe3), have run both unit and acceptance tests on GKE as well. Results were the same as with GKE. Unit tests passed. Acceptance tests for every gem passed with the exception of the 2 Sink tests in Logging and a number of Storage tests, which all failed on permissions for my service account.

**Comment by lukesneeringer** [comment]
Great. Thank you @quartzmo.
