### ISSUE TITLE
Question: is this snippet accurate?

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-ruby#1336]
Found this code below in this [doc page](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-bigquery/v0.24.0/google/cloud/bigquery).  Is it accurate? I feel the second require (when the job doesn't fail) should be for storage, and not for bigquery.

```
require "google/cloud/bigquery"

bigquery = Google::Cloud::Bigquery.new
dataset = bigquery.dataset "my_dataset"
source_table = dataset.table "baby_names"
result_table = dataset.create_table "baby_names_results"

sql = "SELECT name, number as count " \
      "FROM baby_names " \
      "WHERE name CONTAINS 'Sam' " \
      "ORDER BY count DESC"
query_job = dataset.query_job sql, table: result_table

query_job.wait_until_done!

if !query_job.failed?

  require "google/cloud/bigquery"

  storage = Google::Cloud::Storage.new
  bucket_id = "bigquery-exports-#{SecureRandom.uuid}"
  bucket = storage.create_bucket bucket_id
  extract_url = "gs://#{bucket.id}/baby-names-sam.csv"

  extract_job = result_table.extract extract_url

  extract_job.wait_until_done!

  # Download to local filesystem
  bucket.files.first.download "baby-names-sam.csv"

end
```

**Comment by blowmage** [comment]
The second require should be for storage.

**Comment by quartzmo** [comment]
Thanks @omaray!

**Comment by omaray** [comment]
Cool. Just out of curiosity though: shouldn't we have had tests to verify that? Or did we just miss that one?

**Comment by blowmage** [comment]
The way we need to set up our code example tests means that this would not fail. We have to mock our all the API calls, so we have another storage require in the mock setup.

**Comment by quartzmo** [comment]
@omaray wrote:

> shouldn't we have had tests to verify that? Or did we just miss that one?

Please see #1337 (and the other similar issues for Datastore, Logging, and Storage), which I opened yesterday and which refers to this issue.

**Comment by quartzmo** [comment]
@blowmage It occurred to me that this particular issue probably would not be caught by any unit test using mocks, since the mocks would have already performed the require.

**Comment by quartzmo** [comment]
@blowmage I'm wondering if we should have a policy that examples used in the guides MUST also be used (and therefore tested) in API docs. What do you think?

**Comment by blowmage** [comment]
Also agreed. I assumed that was the case already. We want the guides and class/method code examples to be as cohesive as possible.

**Comment by quartzmo** [comment]
I updated the title and description for the 4 issues listed above to reflect this policy: Instead of manually testing the guides, ensure that all guide examples are copied from tested API docs examples.
