### ISSUE TITLE
Test code examples in the Storage guide

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1339]
Because `yard-doctest` does not support testing the in-line examples in our guides (the long-form discussions formatted in markdown on the root package namespace), guide examples must be tested by ensuring that they are copied from API examples that are tested (these are marked with the`@example` tag).

**Comment by quartzmo** [comment]
@blowmage I manually tested the examples in the Storage guide (`storage.rb` docs) and encountered no errors. However, I did notice that the examples for [bucket iteration](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage.rb#L91-L101) and [file iteration](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage.rb#L168-L178) explicitly manage pagination using a token. This older style should be replaced by `List#all` (Enumerator) examples, correct?

**Comment by blowmage** [comment]
Yes, we should encourage use of `#all` in the guides.
