### ISSUE TITLE
(stack-driver) error name not shown in stack driver

### ISSUE THREAD

**Issue by samkelly** [GoogleCloudPlatform/google-cloud-ruby#1343]
I'm using the stack-driver integration with ruby which I love, however it's been very frustrating that the actual error name is not reported anywhere in stack driver, just the formatted stacktrace. Here is an example:

![screenshot from 2017-03-19 18 23 57](https://cloud.githubusercontent.com/assets/1855021/24085375/70d75eba-0cd1-11e7-968e-aaf43ecaa84e.png)

And even in detail view, impossible to see what the actual error was:

![screenshot from 2017-03-19 18 24 20](https://cloud.githubusercontent.com/assets/1855021/24085380/7ebb8e66-0cd1-11e7-885f-33b9d36b5eed.png)

clarification: by "error name" I mean the actual error message and error class that was thrown (if any)

**Comment by samkelly** [comment]
Looks like the stack driver API was inexplicably disabled for my project, which was causing this situation. After re-enabling, everything works again. Please disregard.

**Comment by dazuma** [comment]
@samkelly Thanks for the report. Apologies for the confusion here. The error reporting API is not currently enabled by default on new projects; you need to enable it explicitly for error reports to surface properly. It really ought to be enabled by default, and we have an internal bug open to fix that, but we could also try to make the current situation more clear in the documentation.

**Comment by samkelly** [comment]
@dazuma thanks -- no I know that already, but what's weird is I had it enabled and it must have turned itself off somehow. No idea why.
