### ISSUE TITLE
unable to deploy due to persistent timing out of random bundler network requests

### ISSUE THREAD

**Issue by samkelly** [GoogleCloudPlatform/google-cloud-ruby#1344]
This started happening today. Every time I try to deploy, I get an error like the following during the gem installation phase:

```
...
Installing rly 0.2.3
Installing zonefile 1.04
Installing stackdriver-core 0.21.0
Installing libv8 3.16.14.19 (x86_64-linux)
Installing rb-fsevent 0.9.8
Installing netrc 0.11.0
Installing mysql2 0.4.5 with native extensions
Installing puma 3.8.2 with native extensions
Using bundler 1.14.3
Installing redcarpet 3.4.0 with native extensions
Installing ref 2.0.0
Installing rspec-support 3.5.0
Installing rubyzip 1.2.1
Installing sass 3.4.23
Installing tilt 2.0.7
Installing websocket 1.2.4
Installing temple 0.7.7
Installing faker 1.7.3
Installing tzinfo 1.2.2
Installing nokogiri 1.7.1 with native extensions
Installing rack-test 0.6.3
Installing sprockets 3.7.1
Installing websocket-driver 0.6.5 with native extensions
Installing mime-types 3.1
Installing addressable 2.5.0
Installing childprocess 0.6.2
Gem::RemoteFetcher::UnknownHostError: timed out
(https://rubygems.org/gems/coffee-script-source-1.12.2.gem)
An error occurred while installing coffee-script-source (1.12.2), and Bundler
cannot continue.
Make sure that `gem install coffee-script-source -v '1.12.2'` succeeds before
bundling.
The command '/bin/sh -c bundle install && rbenv rehash' returned a non-zero code: 5
ERROR
ERROR: build step "gcr.io/cloud-builders/docker@sha256:fbdb50a2d9d93916ae0193abfd4796f4b580143f60a9406e546906c9bbe768a0" failed: exit status 5
ERROR: (gcloud.app.deploy) Error Response: [2] Build failed; check build logs for details
```

Every time it happens it is a different gem that times out. At first I was thinking maybe rubygems or google was having network issues, but it fails so consistently that I think maybe something else is wrong. It's been about a month since I deployed, so maybe some change has messed this up?

**Comment by blowmage** [comment]
@swcloud Who should this issue go to?

**Comment by samkelly** [comment]
update: tried another million times, always the same issue. Also tried building docker image locally and deploying manually, but ran into different problems with that where the server never starts.

**Comment by dazuma** [comment]
@samkelly Can you refile this issue in https://github.com/GoogleCloudPlatform/ruby-docker which is where we develop the runtime. (I assume you're doing App Engine Flex deployments here, right?)

Also, could you provide:

* Your gcloud version (run `gcloud --version`)
* Your Gemfile (and ideally Gemfile.lock). (Feel free to email it directly to me if you're concerned about posting it publicly).

**Comment by samkelly** [comment]
@dazuma OK will do

**Comment by blowmage** [comment]
Thanks @samkelly, I am going to close this issue now that the other issue is opened. All the best!
