### ISSUE TITLE
Download from Storage to IO

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/google-cloud-ruby#1356]
#1335 [Upload to Storage with IO](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1335) was recently merged, so I can now upload directly from a `StringIO`!!! 🎉  😄 

Now that you can upload IO-ish objects, it would be great if we could support downloading to IO-ish objects.

#friction #usecase I have test suites that upload/download lots of small bits of text to GCS and using tempfiles for uploading/downloading is not a great experience.

For reference, from what I can tell, Python supports this via [`download_as_string`](https://googlecloudplatform.github.io/google-cloud-python/stable/storage-blobs.html#google.cloud.storage.blob.Blob.download_as_string), C# supports this via [`DownloadObject`](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Storage.V1/api/Google.Cloud.Storage.V1.StorageClient.html#Google_Cloud_Storage_V1_StorageClient_DownloadObject_Google_Apis_Storage_v1_Data_Object_System_IO_Stream_Google_Cloud_Storage_V1_DownloadObjectOptions_System_IProgress_Google_Apis_Download_IDownloadProgress__), and Node.js supports this via [`createReadStream`](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.49.0/storage/file?method=createReadStream).

**Comment by blowmage** [comment]
I think this is doable. We are limited by Google API Client's capabilities, but it looks to support this now.
