### ISSUE TITLE
[Datastore] Query namespaced entities

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1357]
Hi all,

I had a customer question about how-to query namespaced entities. I couldn't find an example snippet in the gem documentation for Datastore Queries.

After reviewing [issue 404](https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/404), I found the following solution. This should be called out somewhere in the documentation.

```ruby
# Datastore service client
datastore = Google::Cloud::Datastore.new

# Create a new entry with a namespace
new_entry = datastore.entity "kind", namespace: "test-namespace" do |entry|
  entry["name"]  = "YOURNAME"
end

# Save in Datastore
datastore.save new_entry

# Query a namespaced entry
query = Google::Cloud::Datastore::Query.new
query.kind "kind"
datastore.run query, namespace: "test-namespace"
```

**Comment by blowmage** [comment]
@franklyn Are you happy with the API we are providing in that code example? Would you prefer a namespace object?

```ruby
# Datastore service client
datastore = Google::Cloud::Datastore.new

# Create a namespace
namespace = datastore.namespace "test-namespace"

# Create a new entry with a namespace
new_entry = namespace.entity "kind" do |entry|
  entry["name"]  = "YOURNAME"
end

# Save in Datastore
namespace.save new_entry

# Query a namespaced entry
query = namespace.query "kind"
results = namespace.run query
```

**Comment by frankyn** [comment]
I'm not sure if a namespace object would make me happy. At first glance, I thought `namespace.save` was a typo and I tried to fix it.

I first tried a naive approach to solve my problem by using what seem's to me as common usage in related snippets. I think a naive solution might help new users.

```Ruby
query = Google::Cloud::Datastore::Query.new
query.kind "kind"
query.namespace "test-namespace"
datastore.run query
```

**Comment by frankyn** [comment]
On second thought, that would reduce the number of keystrokes needed when using namespaces, and could also create awful bugs if the correct namespace object isn't used.

**Comment by blowmage** [comment]
I believe there were valid reasons why we didn't add a `Query#namespace=` method.

**Comment by frankyn** [comment]
@blowmage I'll bring it up in the ruby-cloud standup. Can we add this to the docs until we decide? I don't have a definite answer at this moment.

**Comment by blowmage** [comment]
I'll defer to @quartzmo on that.

**Comment by quartzmo** [comment]
> I had a customer question about how-to query namespaced entities. I couldn't find an example snippet in the gem documentation for Datastore Queries.

@frankyn The `namespace` option is demonstrated [here](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-datastore/lib/google/cloud/datastore/dataset.rb#L425-L432) and [here (GQL)](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-datastore/lib/google/cloud/datastore/dataset.rb#L443-L450) for `Dataset#run`, and [here](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-datastore/lib/google/cloud/datastore/transaction.rb#L253-L262) for `Transaction#run`. It is also demonstrated [here](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-datastore/lib/google/cloud/datastore/dataset.rb#L671-L681) for `Dataset#key`.

I noticed that there is no example for `Dataset#entity`. Would it be sufficient to add one there, or are you thinking of something else?

**Comment by frankyn** [comment]
Thanks @quartzmo! I would expect it to be in https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.26.0/google/cloud/datastore.

**Comment by quartzmo** [comment]
@frankyn The "guide" in that file has been the subject of some debate. It is intended to be something like the README in smaller GitHub projects: A guided tour of the API demonstrating only the most common use cases. I do not personally think it should cover all issues and options. The section "Querying records" ends with [a reference to the API docs](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-datastore/lib/google/cloud/datastore.rb#L149-L150):

```ruby
    # See {Google::Cloud::Datastore::Query} and
    # {Google::Cloud::Datastore::Dataset#run}
```

However, in the real world, it is always a challenge to find what you need by digging deeper. So if you feel the `namespace` use case is important enough to be added to the guide, I'm happy to do it.

**Comment by frankyn** [comment]
I think it would be helpful. Could you add it to the following page?
https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.26.0/google/cloud/datastore/query

**Comment by quartzmo** [comment]
Sure, will do.

**Comment by leechou** [comment]
> @Franklyn Are you happy with the API we are providing in that code example? Would you prefer a namespace object?
> 
> ```ruby
> # Datastore service client
> datastore = Google::Cloud::Datastore.new
> 
> # Create a namespace
> namespace = datastore.namespace "test-namespace"
> 
> # Create a new entry with a namespace
> new_entry = namespace.entity "kind" do |entry|
>   entry["name"]  = "YOURNAME"
> end
> 
> # Save in Datastore
> namespace.save new_entry
> 
> # Query a namespaced entry
> query = namespace.query "kind"
> results = namespace.run query
> ```

Is there an update to this?  are there plans to make a better interface to using namespaces?

**Comment by leechou** [comment]
@blowmage 
I realize that it's only a suggestion, but it would be useful for how I'm using datastore. I haven't found a method to query by key. 

It seems like there's no way of setting up the query such that it's only searching for the namespace 

`datastore.run datastore.query "MyKind" ` would only return things from the namespace "" and filters wouldn't be able to retrieve entities from other namespaces.

**Comment by blowmage** [comment]
You can specify namespace when running a query:

```ruby
require "google/cloud/datastore"

datastore = Google::Cloud::Datastore.new

empty_query = Google::Cloud::Datastore::Query.new

entities = datastore.run empty_query, namespace: "example-ns"
```

**Comment by leechou** [comment]
thanks for the response~ sorry that I wasn't clear about what I wanted to do. I'm trying to make model objects that will wrap the datastore so that the way the data is stored is separated from from how to access the data.  
Using ancestor key for strong consistency models can be hidden by making default queries that have that key, but it seems like namespaced data can't be done in a similar way. It seems like the easiest way to do it with the current implementation is to wrap `datastore.run` as well as `datastore.query` into the new abstraction.
