### ISSUE TITLE
Cloud Storage lib v0.24 docs are irrelevant to actual gem

### ISSUE THREAD

**Issue by ababich** [GoogleCloudPlatform/google-cloud-ruby#1368]
Example:

Doc says that you can upload `String.IO`

The same time change [0d72f5a](https://github.com/GoogleCloudPlatform/google-cloud-ruby/commit/0d72f5a738f0381c123edc55c8c27cf0285a7360#diff-122338ec8adc682e620848e917b3e6ec) was pushed way later than `0.24` version of gem and docs at https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-storage/v0.24.0/guides/authentication are incorrect

Please, make sure docs and gem versions are in sync

**Comment by quartzmo** [comment]
Hi @ababich, thank you for reporting this issue with the documentation.

Just to be sure I understand, are you reporting that the [`0.24.0` gem](https://rubygems.org/gems/google-cloud-storage/versions/0.24.0) has a different API (or other behavior) than is described in the [`0.24.0` docs](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-storage/v0.24.0/google/cloud/storage)? If so, can you please specify exactly where? We have not been able to find any inconsistency.

**Comment by ababich** [comment]
I mentioned initially

> Doc says that you can upload String.IO

But I posted wrong link, sorry about that - http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-storage/master/google/cloud/storage/bucket?method=create_file-instance
and yes, as I mentioned, it is about current, `0.24` docs

**Comment by ababich** [comment]
Same mentioned in Storage guide http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-storage/master/google/cloud/storage

under section "Creating a File"

**Comment by quartzmo** [comment]
You are now linking to [docs for `master` branch](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-storage/master/google/cloud/storage). Does the mention of uploading StringIO appear in the docs for the [docs for the `v0.24.0` tag](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-storage/v0.24.0/google/cloud/storage)?

**Comment by quartzmo** [comment]
I can only find the instructions for creating a file in the [`master` branch docs](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-storage/master/google/cloud/storage):

> Files can also be created from an in-memory StringIO object

This example is not present in the [`0.24.0` tag docs](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-storage/v0.24.0/google/cloud/storage), which is the correct version of the documentation to reference when using the  gem version `0.24.0`.
