### ISSUE TITLE
Objects.rewrite operations should support multiple requests

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1369]
Currently, `File#storage_class=` and `File#rotate` use `Objects.rewrite`, but do not provide for multiple requests in case of an incomplete operation (incomplete rewrites should return a `rewriteToken`).

Similarly, a solution for #1196 and #1328 based on `Objects.rewrite` should support multiple requests using `rewriteToken`.

From [Objects.rewrite](https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite):

> This method copies data using multiple requests so large objects can be copied with a normal length timeout per request rather than one very long timeout for a single request. 

and

> **rewriteToken string** Include this field (from the previous rewrite response) on each rewrite request after the first one, until the rewrite response 'done' flag is true. Calls that provide a rewriteToken can omit all other request fields, but if included those fields must match the values provided in the first rewrite request.

**Comment by blowmage** [comment]
Are you meaning that the public API should expose the `rewriteToken`? Or that `File#storage_class=` and `File#rotate` should make multiple calls when needed, maintaining the existing API?

**Comment by quartzmo** [comment]
@blowmage The latter. My assumption is that the default behavior should be to automatically make multiple calls when needed. However, we could expose a `single_request` option (default: `false`) for cases in which the timeout is preferable to multiple requests.

**Comment by blowmage** [comment]
Understood. I actually thought we already supported multiple API calls using `rewriteToken`. FWIW, I agree with you, but would prefer to not expose `single_request`. :+1:

**Comment by quartzmo** [comment]
Ok, at this time I will not add an option for limiting the operation to a single request.

**Comment by blowmage** [comment]
Interestingly enough, `File#rotate` does make multiple API calls to `objects.rewrite`, but `File#storage_class=` does not. I will add code to fix this.
