### ISSUE TITLE
Add unit tests for the superset of expected responses.

### ISSUE THREAD

**Issue by lukesneeringer** [GoogleCloudPlatform/google-cloud-ruby#1374]
There was [a bug][] in the Node.js Vision client which was effectively that the client raised an exception if it ever got a key that it did not expect. This is relatively easy to do for any number of reasons:

```python
# `raw_response` is a dict that came back from the API.
key_map = {
    'alphaObject': 'alpha_object',
    'betaObject': 'beta_object',
}
new_response = {}
for k, v in raw_response.iteritems():
    new_response[key_map[k]] = v
```

This is an anti-pattern, because it strongly assumes that you will never get a new key that is not already in your key map. If the API adds a `gammaObject` key and this (Python) code were to run, suddenly what used to work now raises `KeyError`.

The solution: Add unit tests in each spot where we transform an API response into a custom object to ensure that unexpected key-value pairs are either passed through or dropped.

  [a bug]: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2034

**Comment by blowmage** [comment]
@lukesneeringer Did you mean to create this on google-cloud-python?

**Comment by lukesneeringer** [comment]
I created a copy on all six languages.

**Comment by blowmage** [comment]
I'm going to close this since google-cloud-ruby does not use this approach to response conversion. We have had new values returned without generating these types of errors.
