### ISSUE TITLE
[Storage] List associated ACL permissions for a bucket using on an email

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1379]
Hi,

Is it possible to get a list of associated ACL permissions for a bucket using an email? I'm looking for a shorter way of doing the following:

```
require "google/cloud/storage"                                                
 
storage = Google::Cloud::Storage.new project: project_id                      
bucket  = storage.bucket bucket_name                                          

puts "Permissions for #{user_email}:"                                         
puts "\tOWNER" if bucket.acl.owners.include?   user_email                      
puts "\tWRITER" if bucket.acl.writers.include?   user_email                     
puts "\tREADER" if bucket.acl.readers.include? user_email
```

Thank you!

**Comment by blowmage** [comment]
There is no alternate API to collect permission roles by entity. What you have provided is the way the API works.

Do note that ACL entities values need to be prepended with the type. For an individual user that would be `"user-"`. Per the [documentation](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-storage/v0.24.0/google/cloud/storage/bucket/acl?method=add_owner-instance):

> The entity holding the permission, in one of the following forms:
> 
> * user-userId
> * user-email
> * group-groupId
> * group-email
> * domain-domain
> * project-team-projectId
> * allUsers
> * allAuthenticatedUsers

**Comment by frankyn** [comment]
Thanks @blowmage!

**Comment by Capstan** [comment]
[testIamPermissions](https://cloud.google.com/storage/docs/json_api/v1/buckets/testIamPermissions) was recently released to Alpha. There's not a lookup for the pre-IAM roles of `OWNER`, `WRITER` and `READER`, but rather individual permissions, like `storage.objects.create` and `storage.objects.get`.

**Comment by frankyn** [comment]
@Capstan I closed this seconds before you posted your comment. Although, I'm not sure I follow what you meant.

**Comment by blowmage** [comment]
@Capstan We are waiting on an upstream release to add IAM support to Storage. Hope to have this released soon!
