### ISSUE TITLE
Support IAM methods in File

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1383]
The IAM methods have been added to Storage Bucket and FIle/Object. These methods are considered Alpha, and should be added to the Ruby Storage client.

**Comment by quartzmo** [comment]
The google-api-client dependency will need to increase to `0.10.3` to support this feature.

**Comment by geigerj** [comment]
Assuming this continues to be blocked on API server-side support, downgrading priority to P2+.

**Comment by blowmage** [comment]
Moved to [feature backlog](https://github.com/GoogleCloudPlatform/google-cloud-ruby/wiki/Feature-backlog).
