### ISSUE TITLE
Recognize timeout needs to be > 185 seconds (instead of 60)

### ISSUE THREAD

**Issue by pbogle** [GoogleCloudPlatform/google-cloud-ruby#1385]
In client_config.json, we have

  "Recognize": {
          "timeout_millis": 60000, // This is too short.
          "retry_codes_name": "idempotent",
          "retry_params_name": "default"
        },

This rpc timeout need to be at least 185 seconds.  (60 * 3 + 5)

**Comment by blowmage** [comment]
This has been changed in the googleapis repo and in the speech-v1 PR.
