### ISSUE TITLE
Language: Support for AnalyzeEntitySentiment.

### ISSUE THREAD

**Issue by landrito** [GoogleCloudPlatform/google-cloud-ruby#1388]
[`AnalyzeEntitySentiment`](https://github.com/googleapis/googleapis/blob/master/google/cloud/language/v1beta2/language_service.proto#L47) method was introduced. Support for this method would be great.

**Comment by blowmage** [comment]
@landrito Are you going to submit a PR adding the `v1beta2` GAPIC files?

**Comment by landrito** [comment]
Closing for now.

The method responses from v1beta2 are not of GA quality yet so we do not want to add them to the main surface. We do, however, want to give the user the ability to use the v1beta2 endpoint. This can be done by including the v1beta2 gapic in the package.

**Comment by remi** [comment]
@landrito How can I analyze entity sentiment today using google-cloud-language?

**Comment by landrito** [comment]
Sorry, The issue should read. **Language: Support for AnalyzeEntitySentiment in manual layer**.

After the next release cycle of NL. The way to analyze entity sentiment would be through the v1beta gapic.
