### ISSUE TITLE
google-cloud-language requires 2.3 or above

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/google-cloud-ruby#1398]
Running with mac system ruby (2.0.0) I get this error:

/Users/ajahammerly/.gem/repos/machine-learning/gems/google-cloud-language-0.26.0/lib/google/cloud/language/annotation.rb:673:in `<class:Annotation>': undefined method `DelegateClass' for Google::Cloud::Language::Annotation:Class (NoMethodError)
	from /Users/ajahammerly/.gem/repos/machine-learning/gems/google-cloud-language-0.26.0/lib/google/cloud/language/annotation.rb:43:in `<module:Language>'
	from /Users/ajahammerly/.gem/repos/machine-learning/gems/google-cloud-language-0.26.0/lib/google/cloud/language/annotation.rb:20:in `<module:Cloud>'
	from /Users/ajahammerly/.gem/repos/machine-learning/gems/google-cloud-language-0.26.0/lib/google/cloud/language/annotation.rb:19:in `<module:Google>'
	from /Users/ajahammerly/.gem/repos/machine-learning/gems/google-cloud-language-0.26.0/lib/google/cloud/language/annotation.rb:18:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/ajahammerly/.gem/repos/machine-learning/gems/google-cloud-language-0.26.0/lib/google/cloud/language/document.rb:16:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/ajahammerly/.gem/repos/machine-learning/gems/google-cloud-language-0.26.0/lib/google/cloud/language/project.rb:19:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/ajahammerly/.gem/repos/machine-learning/gems/google-cloud-language-0.26.0/lib/google/cloud/language.rb:17:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from sentence_diagram_initial.rb:2:in `<main>'

**Comment by blowmage** [comment]
We have CI set up to run against ruby 2.0, 2.1, 2.2, 2.3, and 2.4. 

I don't fully understand why you are getting that error with your system ruby. DelegateClass is present [in ruby 1.9 at least](https://ruby-doc.org/stdlib-1.9.3/libdoc/delegate/rdoc/Object.html), and I'm pretty sure it was in 1.8. Is the mac system ruby incomplete? Is it missing parts of the standard library?

**Comment by blowmage** [comment]
Ah, this could actually be as simple as a missing require.

**Comment by blowmage** [comment]
This is fixed in Release Natural Language 0.26.1.

**Comment by thagomizer** [comment]
Thanks @blowmage. Much appreciated.
