### ISSUE TITLE
image-annotator::error(12)

### ISSUE THREAD

**Issue by miguelmyers8** [GoogleCloudPlatform/google-cloud-ruby#1399]
Google::Cloud::InternalError

image-annotator::error(12): We can not access the URL currently. Please download the image and pass it in.

Has anyone run into this error before? I am too far into my app to download images and pass it in.

**Comment by quartzmo** [comment]
@miguelmyers8 Thank you for reporting this.

Unfortunately, my understanding is that there is nothing that we can do about this at the client level (this project).

A Google Cloud Vision [Internal Error](https://cloud.google.com/vision/docs/reference/rest/v1/Code) is defined as follows:

> Internal errors. This means that some invariants expected by the underlying system have been broken. This error code is reserved for serious errors.

Yes, this has been [encountered recently](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2087) by another user of the service (using a different client library).

**Comment by geigerj** [comment]
Thank you for filing this issue. We investigated and determined that this is actually a server-side issue. Please re-file it with the appropriate Google Cloud issue tracker: https://cloud.google.com/support/docs/issue-trackers. If you believe that part of this issue still needs to be addressed in this client library, then feel free to re-open this issue with more information.
