### ISSUE TITLE
Inline audio is not allowed with LongRunningRecognize. Please use a GCS URI.

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1414]
Users are no longer able to process audio inline. When attempted, they receive the following error:

`Google::Cloud::InvalidArgumentError: 3:Inline audio is not allowed with LongRunningRecognize. Please use a GCS URI.`

This has been working before last Friday, when the API behavior changed.

**Comment by remi** [comment]
This change has been reversed.  No code changes are required ~ tests should now be passing again.

**Comment by blowmage** [comment]
Thanks @remi!

**Comment by Bellman281** [comment]
Sir I still get the same error (using R functions to connect to the API) : (my file is 6.68 MB and 8 min length) 
async <- gl_speech(audio, asynch = TRUE)
Request failed [400]. Retrying in 1.6 seconds...
Request failed [400]. Retrying in 1 seconds...
2018-05-05 16:02:10> Request Status Code: 400
Scopes: https://www.googleapis.com/auth/cloud-platform
Method: service_json
Error: API returned: Inline audio exceeds duration limit. Please use a GCS URI.

**Comment by blowmage** [comment]
@Bellman281 The error you describe is different than the one discussed on this issue. Your error is because the audio (8 minutes) is too long for being inline. See [audio limits](https://cloud.google.com/speech-to-text/quotas).
