### ISSUE TITLE
segfault with stackdriver 0.5.0

### ISSUE THREAD

**Issue by tmc** [GoogleCloudPlatform/google-cloud-ruby#1419]
details: https://gist.github.com/tmc/4bc91e3ff01e28b2281b6a75ef8628fa

ruby: 2.2.0
grpc: 1.2.2

**Comment by blowmage** [comment]
Is this consistent? Or intermittent?

Can you post some code that will reproduce this?

**Comment by tmc** [comment]
Fairly consistent. Let me see if I can whittle it down to a shareable example.

**Comment by hxiong388** [comment]
@tmc grpc v1.3.4 that was released last week have fixed a number of bugs. Does the segfault still happen to you with the new grpc gem?

**Comment by geigerj** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
