### ISSUE TITLE
Full YARD parameter type is not displayed in documentation

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/google-cloud-ruby#1422]
I'm trying to successfully call [MetricServiceClient#create_time_series](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.28.0/google/cloud/monitoring/v3/metricserviceclient?method=create_time_series-instance) and the param table only shows `Array` as the type.

![screen shot 2017-04-13 at 1 00 02 am](https://cloud.githubusercontent.com/assets/280/24995690/96af2e80-1fe4-11e7-9740-01541eb19175.png)

The actual type specified in the YARD doc for the param is `[Array<Google::Monitoring::V3::TimeSeries>]`
[metric_service_client.rb#L617](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/73d9895a76e3206383f2c5df91a83db4f6cdfdff/google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client.rb#L617)

The full type should show in the docs.

**Comment by blowmage** [comment]
I wonder if the angular app is not properly escaping the value, and it thinks the angle brackets are an html element.

**Comment by blowmage** [comment]
If you look at the [JSON](https://googlecloudplatform.github.io/google-cloud-ruby/json/google-cloud/master/google/cloud/monitoring/v3/metricserviceclient.json) that powers the angular app, you will see that the "create_time_series" method has a "time_series" argument with type of "Array<Google::Monitoring::V3::TimeSeries>".

**Comment by quartzmo** [comment]
Moved to the public [planning wiki](wiki/Planning) due to the delay in implementing the new documentation site.
