### ISSUE TITLE
Update Speech Client parameter from :raw to :LINEAR16

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1426]
Hi,

We received a comment about updating samples to use :LINEAR16 instead of the file type :raw.

> Both RAW and WAV can encapsulate both LINEAR16 and Mulaw.

It may be a good idea to update snippets to use `:LINEAR16` instead of `:raw`. 

[1] https://github.com/GoogleCloudPlatform/ruby-docs-samples/issues/166
[2] https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/168

**Comment by remi** [comment]
Is the request to remove the `:raw` alias?

Currently, `:raw`, `:linear`, and `:linear16` are all acceptable values/aliases for LINEAR16.

See: [the aliases](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/52b512b09ac5070a6c038f058793ecaa1f1267fe/google-cloud-speech/lib/google/cloud/speech/project.rb#L625-L630).

**Comment by frankyn** [comment]
Based on the original comment, my request was to update the snippets to use `:linear16` or `:linear` instead of `:raw`. 

Also, it may be helpful to document the different available aliases found [here](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/52b512b09ac5070a6c038f058793ecaa1f1267fe/google-cloud-speech/lib/google/cloud/speech/project.rb#L625-L630)

**Comment by merla18** [comment]
raw: :LINEAR16 is not correct.  raw can be multiple different formats (e.g., mulaw, linear16, amr)
so mapping raw to linear16 is not really correct

**Comment by frankyn** [comment]
Thanks @blowmage!
