### ISSUE TITLE
Request: a way to run multiple types of Vision detection on a single Image

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/google-cloud-ruby#1437]
I have a program that runs multiple types of detection on an image.  I make a `vision.image` and then call `image.text` and `image.landmarks` and `image.labels` and more.  But this is slow *and* effects my Vision API quota.

So I looked for a method that I could call on my Vision::Image to detect multiple things in one API call, eg. `image.detect landmarks: true, text: true`.

Being very familiar with the Vision API, I happen to know that these use the `annotate` rpc method and I had previously scrolled past an `annotate` method in the docs for Vision.

But today, when I had a use-case for it, I was surprised to see that Image has no method that will run multiple types of detection (one annotate call) AFAICT!

I see that Project#annotate exists and accepts multiple images.

My ask is for a new method Image#annotate which returns the same Annotation object but for only that image.  I found it confusing that the Image didn't have this method available.

**Comment by quartzmo** [comment]
@remi I also feel that this would be a helpful addition to the API, and thank you for bringing it to our attention. I will add `Image#annotate` (and aliases) as soon as possible.
