### ISSUE TITLE
Force google-cloud-logging client lib to use V2 format when calling Logging API

### ISSUE THREAD

**Issue by qingling128** [GoogleCloudPlatform/google-cloud-ruby#1438]
After the issue in https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1239 had been fixed, we were able to get partial success error details in `metadata`. However the format is weird:

```
error:
#<GRPC::BadStatus: 3:Illegal character ':' in log name>
error metadata =
{"google.rpc.debuginfo-bin"=>"\x12\xBE\x03[ORIGINAL ERROR] generic::invalid_argument: Illegal character ':' in log name [google.rpc.error_details_ext] { message: \"Illegal character \\':\\' in log name\" details { type_url: \"type.googleapis.com/google.logging.v2.WriteLogEntriesPartialErrors\" value: \"\\n)\\010\\000\\022%\\010\\003\\022!Illegal character \\':\\' in log name\\n)\\010\\001\\022%\\010\\003\\022!Illegal character \\':\\' in log name\\n\\034\\010\\002\\022\\030\\010\\007\\022\\024User not authorized.\" } }"}
```

And the index info is missing. (The error details should include mappings between the index and the error). After some investigation with Logging API team it turned out that this is because when calling Logging API, by default the V1 format is used, so we get something like:

```
      {
        "@type": "type.googleapis.com/google.rpc.DebugInfo",
        "detail": "[ORIGINAL ERROR] generic::invalid_argument: Illegal character ':' in log name [google.rpc.error_details_ext] { message: \"Illegal character \\':\\' in log name\" details { type_url: \"type.googleapis.com/google.logging.v2.WriteLogEntriesPartialErrors\" value: \"\\n)\\010\\000\\022%\\010\\003\\022!Illegal character \\':\\' in log name\\n\\034\\010\\001\\022\\030\\010\\007\\022\\024User not authorized.\" } }"
      }
```

While if we indicate we want to use V2 format, we will get some well-formed json:

```
      {
        "@type": "type.googleapis.com/google.logging.v2.WriteLogEntriesPartialErrors",
        "logEntryErrors": {
          "0": {
            "code": 3,
            "message": "Illegal character ':' in log name"
          },
          "1": {
            "code": 7,
            "message": "User not authorized."
          }
        }
      },
```

To force v2 format, the client should use either the query param: `$apiFormat=2` or the header: `X-GOOG-API-FORMAT-VERSION: 2`. Can we force this client to use V2 format?

**Comment by quartzmo** [comment]
@qingling128 Thank you for submitting this issue.

@dazuma @swcloud Do either of you know if `X-GOOG-API-FORMAT-VERSION` can and should be used in this context to force the V2 format? My understanding is that the V2 format is currently always the default.

**Comment by qingling128** [comment]
I checked with the Logging API folks. Seems the format in the sample error metadata

```
error:
#<GRPC::BadStatus: 3:Illegal character ':' in log name>
error metadata =
{"google.rpc.debuginfo-bin"=>"\x12\xBE\x03[ORIGINAL ERROR] generic::invalid_argument: Illegal character ':' in log name [google.rpc.error_details_ext] { message: \"Illegal character \\':\\' in log name\" details { type_url: \"type.googleapis.com/google.logging.v2.WriteLogEntriesPartialErrors\" value: \"\\n)\\010\\000\\022%\\010\\003\\022!Illegal character \\':\\' in log name\\n)\\010\\001\\022%\\010\\003\\022!Illegal character \\':\\' in log name\\n\\034\\010\\002\\022\\030\\010\\007\\022\\024User not authorized.\" } }"}
```

implies the ruby client is using V1 format.

**Comment by quartzmo** [comment]
@dazuma @hxiong388 Any idea about this? I've looked through the project but everything appears to be on `V2` as far as I can see. Is there something special that needs to be explicitly set?

**Comment by blowmage** [comment]
FWIW, I think this is something that should be set in the GAPIC layer, if it does need to be set.

**Comment by hxiong388** [comment]
The [red warning message](https://cloud.google.com/logging/docs/migration-v2) from Logging Doc that states `March 30, 2017: The v1 API is shut down. All code using the v1 API stops working` make it sound like the Logging API shouldn't default anything to V1 format anymore.

@qingling128 Who did you contact from the Logging API team? We should get in touch with them directly to figure out where's the best place to fix this.

**Comment by qingling128** [comment]
Synced with @hxiong388 offline about whom to reach to internally. Stay tuned.

**Comment by qingling128** [comment]
BTW, the v1 and v2 format is an One Platform thing when it comes to error format. It's separate from Logging API's version V1 and V2. There's more information in the internal ticket. I've sent the ticket number to @hxiong388. Let me know if there is anything I could help. Thanks!

**Comment by quartzmo** [comment]
@qingling128 Thanks for the clarification on the versioning, that explains a lot!

**Comment by hxiong388** [comment]
@geigerj After talking with @qingling128 and reading through the internal discussion, I think it makes sense to set the `X-GOOG-API-FORMAT-VERSION: 2` header in GAPIC client. Let us know what you think.

**Comment by quartzmo** [comment]
@blowmage commented:

> FWIW, I think this is something that should be set in the GAPIC layer, if it does need to be set.

And I agree, that sounds fine, although it may be good to be able to override this setting.

**Comment by qingling128** [comment]
Is this going to be a breaking change for the Ruby client if we enforce V2 format by default? If we have to provide a flag in the Ruby client to enforce V2 format, I'm fine with explicitly setting that too.

**Comment by blowmage** [comment]
What is the `format` that is being set to V2? Why is it set via header and not in the API request?

The only place I am aware that API version is configurable is on [LogSink](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_config.rb#L51-L57). But that is a separate issue for writing log entries, right?

**Comment by qingling128** [comment]
Yeah, the `LogSink` format is a different thing, which is specific to Logging API. The error format here is generic to all Google APIs built on the same framework I believe. I did not find any external documentation about this format though except that it's briefly mentioned in GMB API [here](https://developers.google.com/my-business/content/support#detailed_error_responses).

Quoting some documentation I found about the `format`:

```
We also support JSON error format that is backward-compatible with Apiary client libraries. We call this error format version 1, while the newer error format described above is version 2.

...

In addition, clients can explicitly choose the error format through either a header or a parameter:

using a header: "X-GOOG-API-FORMAT-VERSION: 2";
using a parameter: "&.xgafv=2".
```

Shreekanth from the framework team mentioned a parameter `$apiFormat=2` should also work though.

**Comment by blowmage** [comment]
Okay, so the format version here is 100% orthogonal to the Logging API version?

**Comment by qingling128** [comment]
Yeah, that sounds right.

**Comment by geigerj** [comment]
@hxiong388 @quartzmo Sure, we should be able to change the GAPIC layer to set this header everywhere. I'm going to confirm that changing this header actually does produce the desired result first, and will update then.

**Comment by blowmage** [comment]
If so, the difference is that the V1 embeds the additional data's protobuf binary representation in the JSON, where V2 returns the additional data as JSON.  Is that correct?

**Comment by qingling128** [comment]
@blowmage Yes.

**Comment by blowmage** [comment]
Okay, then I think this change won't break existing behavior. We don't specify this format anywhere AFAIK.

**Comment by qingling128** [comment]
Good to know.

**Comment by blowmage** [comment]
Where is WriteLogEntriesPartialErrors defined? I don't see it in the protobufs or GAPIC code. (I'm looking into an issue for another library that is using trailing metadata and not sure I am reproducing the behavior described in this issue correctly.)

**Comment by qingling128** [comment]
I saw the definition in `google/logging/v2/logging.proto` internally. I did not see it in the GitHub though. Is [this](https://github.com/googleapis/googleapis/blob/master/google/logging/v2/logging.proto) the public one? Maybe we need to somehow sync them? I'm not very sure how it is being handled.

**Comment by geigerj** [comment]
@qingling128 Yes, there is a process to sync them. I'll follow up with you internally.

**Comment by qingling128** [comment]
@geigerj Sure. Thanks! You can find me by `lingshi@`.

**Comment by geigerj** [comment]
@qingling128 I am seeing the misformatted error even after I set the header. (Note: this is using the GAPIC layer, not the manually written client library.)

```
require "google/api/monitored_resource_pb"
require "google/cloud/logging/v2"
require "google/logging/v2/log_entry_pb"
require "google/gax"

LoggingClient = Google::Cloud::Logging::V2::LoggingServiceV2Client
logging_client = LoggingClient.new
entries = [
  Google::Logging::V2::LogEntry.new(
    {
      log_name: 'projects/gapic-test/logs/my-log',
      resource: Google::Api::MonitoredResource.new({ type: 'gce_instance' }),
      text_payload: 'pass'
    }),
  Google::Logging::V2::LogEntry.new(
    {
      log_name: 'projects/gapic-test/logs/bad:log',
      resource: Google::Api::MonitoredResource.new({ type: 'gce_instance' }),
      text_payload: 'fail'
    }),
]

begin
  logging_client.write_log_entries(
    entries,
    partial_success: true,
    options: Google::Gax::CallOptions.new(
      {kwargs: {:"x-goog-api-format-version" => "2"}}
    )
  )
rescue => error
  puts "error:\n#{error.inspect}\n"
  puts "error metadata =\n#{error.cause.metadata.inspect}\n"
end
```

which prints

```
error:
#<Google::Gax::RetryError: GaxError Exception occurred in retry method that was not classified as transient, caused by 3:Log name contains illegal character :>
error metadata =
{"google.logging.v2.writelogentriespartialerrors-bin"=>"\n-\b\x01\x12)\b\x03\x12%Log name contains illegal character :", "google.rpc.debuginfo-bin"=>"\x12\xCC\x02[ORIGI\
NAL ERROR] generic::invalid_argument: Log name contains illegal character : [google.rpc.error_details_ext] { message: \"Log name contains illegal character :\" details \
{ type_url: \"type.googleapis.com/google.logging.v2.WriteLogEntriesPartialErrors\" value: \"\\n-\\010\\001\\022)\\010\\003\\022%Log name contains illegal character :\" \
} }"}
```

**Comment by geigerj** [comment]
Note: you can verify that the header `x-goog-api-format-version` is being set in the above snippet by running it with the env variables `GRPC_TRACE=http GRPC_VERBOSITY=DEBUG`

**Comment by qingling128** [comment]
@geigerj: Yeah, I was able to reproduce what you saw. When I call Logging API directly I got:

```
{
  "error": {
    "code": 400,
    "message": "Illegal character ':' in log name",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.logging.v2.WriteLogEntriesPartialErrors",
        "logEntryErrors": {
          "0": {
            "code": 3,
            "message": "Illegal character ':' in log name"
          },
          "1": {
            "code": 7,
            "message": "User not authorized."
          }
        }
      },
      {
        "@type": "type.googleapis.com/google.rpc.DebugInfo",
        "detail": "[ORIGINAL ERROR] generic::invalid_argument: Illegal character ':' in log name [google.rpc.error_details_ext] { message: \"Illegal character \\':\\' in log name\" details { type_url: \"type.googleapis.com/google.logging.v2.WriteLogEntriesPartialErrors\" value: \"\\n)\\010\\000\\022%\\010\\003\\022!Illegal character \\':\\' in log name\\n\\034\\010\\001\\022\\030\\010\\007\\022\\024User not authorized.\" } }"
      }
    ]
  }
}
```

Do you know where the error metadata is being set? Does `"google.logging.v2.writelogentriespartialerrors-bin"` map to `"@type": "type.googleapis.com/google.logging.v2.WriteLogEntriesPartialErrors"`?

BTW the original internal ticket is b/36393329.

**Comment by qingling128** [comment]
Seems @geigerj is OOO this week and potentially not available early next week either due to the Summit. Does anyone else know the answer to Shreekanth's question in b/36393329#comment33?

>Client changes seem correct.
Note that the -bin headers are binary serialized protos. Does the client library deserialize them?

**Comment by hxiong388** [comment]
cc @swcloud @landrito 

Do you guys know the answer to Shreekanth's question?

**Comment by qingling128** [comment]
Hi, any news on this one?

**Comment by qingling128** [comment]
Hi, friendly ping. Anyone got a sec for Shreekanth's question related to this issue in b/36393329#comment33?

**Comment by blowmage** [comment]
@geigerj, can you follow up with @swcloud on this?

**Comment by geigerj** [comment]
I will follow up on the internal discussion. As I noted above, the proposed header change didn't seem to work, so guidance from Shreekanth or the logging team would be appreciated.

**Comment by qingling128** [comment]
Sounds good. Thanks for checking!

**Comment by qingling128** [comment]
Hi Jacob, I just verified the fix in the ruby client lib for non-grpc/REST path (https://github.com/google/google-api-ruby-client/issues/544). Seems Shreekanth's suggestion to enforce V2 format worked there. (See details in that ticket). So the remaining issue is only exclusive to gRPC side.

Looking at the actual fix (https://github.com/google/google-api-ruby-client/pull/583/files#diff-09b6e5f1a05c6001b27101be36662d36R133), the way to parse error between V1 format and V2 format is slightly different. Maybe what we are lacking is the equivalent logic in `google-cloud-ruby` lib or at the gRPC client stub level.

**Comment by qingling128** [comment]
Hi, do we know if this is an issue with `google-cloud-ruby` or `gRPC` yet? I wonder if I should bother them instead... Keep me posted. Thanks!

**Comment by geigerj** [comment]
@qingling128 Sorry for the slow response. The GAPIC library (i.e., `Google::Cloud::Logging::V2::LoggingServiceV2Client`) simply wraps the gRPC error -- it doesn't do any processing of the error itself. @apolcyn may be able to help with any changes required on the gRPC side.

**Comment by apolcyn** [comment]
When I run that repro posted above by @geigerj, I get:

```
error:
#<Google::Gax::RetryError: GaxError Exception occurred in retry method that was not classified as transient, caused by 3:Log name contains illegal character :>
error metadata =
{"google.logging.v2.writelogentriespartialerrors-bin"=>"\n-\b\x01\x12)\b\x03\x12%Log name contains illegal character :"}
```

This received headers and trailers received shows:
(traced with `GRPC_TRACE=all,-queue_pluck,-queue_timeout`)
```
I0609 17:48:34.355901701    3190 parsing.c:500]              HTTP:1:HDR:CLI: :status: 32 30 30 '200'
I0609 17:48:34.355956396    3190 parsing.c:500]              HTTP:1:HDR:CLI: content-type: 61 70 70 6c 69 63 61 74 69 6f 6e 2f 67 72 70 63 'application/grpc'
I0609 17:48:34.355971663    3190 parsing.c:500]              HTTP:1:HDR:CLI: date: 46 72 69 2c 20 30 39 20 4a 75 6e 20 32 30 31 37 20 31 37 3a 34 38 3a 33 34 20 47 4d 54 'Fri, 09 Jun 2017 17:48:34 GMT'
I0609 17:48:34.356265174    3190 parsing.c:580]              HTTP:1:TRL:CLI: grpc-status: 33 '3'
I0609 17:48:34.356304939    3190 parsing.c:580]              HTTP:1:TRL:CLI: grpc-message: 4c 6f 67 20 6e 61 6d 65 20 63 6f 6e 74 61 69 6e 73 20 69 6c 6c 65 67 61 6c 20 63 68 61 72 61 63 74 65 72 20 3a 'Log name contains illegal character :'
I0609 17:48:34.356327126    3190 parsing.c:580]              HTTP:1:TRL:CLI: google.logging.v2.writelogentriespartialerrors-bin: 0a 2d 08 01 12 29 08 03 12 25 4c 6f 67 20 6e 61 6d 65 20 63 6f 6e 74 61 69 6e 73 20 69 6c 6c 65 67 61 6c 20 63 68 61 72 61 63 74 65 72 20 3a '.-...)...%Log name contains illegal character :'
```

It looks like grpc is attaching the `grpc-message` and the custom trailers received, to the thrown error, as intended. It wouldn't ever be doing any extra processing on the received trailing metadata before bubbling up.

I'm a little unclear here though, shoudl `google.logging.v2.writelogentriespartialerrors-bin` be serialized json?

**Comment by qingling128** [comment]
I would guess so, but I'm not sure. Seems it's kind of hard to locate the root cause with multiple components involved: Ruby client, gRPC, Logging API, One Platform. I just set up a quick real-time sync tomorrow and invited Jacob, Alexander, Shreekanth and you. Hopefully that could help shed some light on the issue.

**Comment by geigerj** [comment]
From offline discussion:
- This problem is almost certainly not Ruby- or logging-specific
- V1 vs V2 is irrelevant for gRPC; all gRPC errors are V2
- gRPC cannot handle deserialization of custom error types, since it doesn't know about the custom error protos
- The responsibility of handling deserialization should therefore fall on the GAPIC layer
- @geigerj to follow up internally about getting this feature into the GAPIC client libraries

**Comment by qingling128** [comment]
Thanks @geigerj for summarizing this! And thanks to everyone for helping out. Glad we were able to figure out an approach. :)

**Comment by geigerj** [comment]
Actually, still need to add the error types to this repo before GAX will be able to deserialize them.

**Comment by qingling128** [comment]
Just verified the fix. Working perfectly! Thanks everyone. :)

```
$ gem list | grep google-cloud-logging
google-cloud-logging (1.2.3)
```

```
$ gem list | grep google-gax
google-gax (0.8.12)
```

```
$ cat grpc.rb
require "google/api/monitored_resource_pb"
require "google/cloud/logging/v2"
require "google/logging/v2/log_entry_pb"
require "google/gax"

LoggingClient = Google::Cloud::Logging::V2::LoggingServiceV2Client
logging_client = LoggingClient.new
entries = [
  Google::Logging::V2::LogEntry.new(
    {
      log_name: 'projects/gapic-test/logs/my-log',
      resource: Google::Api::MonitoredResource.new({type: 'gce_instance'}),
      text_payload: 'pass'
    }),
  Google::Logging::V2::LogEntry.new(
    {
      log_name: 'projects/gapic-test/logs/bad:log',
      resource: Google::Api::MonitoredResource.new({type: 'gce_instance'}),
      text_payload: 'fail'
    }),
]

begin
  logging_client.write_log_entries(
    entries,
    partial_success: true
  )
rescue => error
  puts "error:\n#{error.inspect}\n"
  puts "error details:\n#{error.details[0].log_entry_errors.inspect}\n"
end
```

```
$ ruby grpc.rb
error:
#<Google::Gax::RetryError: GaxError Exception occurred in retry method that was not classified as transient, caused by 7:User not authorized.>
error details:
{
    0=><Google::Rpc::Status: code: 7, message: "User not authorized.", details: []>,
    1=><Google::Rpc::Status: code: 3, message: "Log name contains illegal character :", details: []>
}
```

**Comment by qingling128** [comment]
BTW, the GAX gem dependency version is updated to `0.8.11` in https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1769.
