### ISSUE TITLE
Support IAM methods in Spanner

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1445]
The IAM methods have been added to Spanner for Instances, Instance operations, Databases, Database operations, and Sessions. All IAM methods listed in the guide [Access Control for Cloud Spanner](https://cloud.google.com/spanner/docs/iam) should be added to the Ruby Storage client.

When implementing tests, please note that:

> The following primitive roles are supported but not recommended. Prefer to use one of the [Spanner-specific roles] instead.

Thus, do not use the following roles in docs or testing:

> roles/viewer
> roles/writer
> roles/owner

**Comment by blowmage** [comment]
It looks like both Instance and Database have already implemented the IAM methods.
