### ISSUE TITLE
google-protobuf 3.3.0 causes errors in Datastore

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1457]
Last Friday [google-protobuf 3.3.0](https://rubygems.org/gems/google-protobuf/versions/3.3.0) was released. One of the [changes made](https://github.com/google/protobuf/blob/80f0c0ac40398858480fcc121b6771f40e5b02bb/CHANGES.txt#L98) was:

* Fixed `Message#to_h` for messages with map fields.

Unfortunately, this breaks API compatibility and caused failures on the Datastore CI build. I [released google-cloud-datastore 1.0.1](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-datastore%2Fv1.0.1) over the weekend to pin the dependency to ~> 3.2.0. But we should update Datastore to work with the new behavior.

**Comment by geigerj** [comment]
> But we should update Datastore to work with the new behavior.

@blowmage Has this already been done?

**Comment by blowmage** [comment]
No, not yet. I'll work on it this week.
