### ISSUE TITLE
google-cloud-logging causes delayed job to crash on production 

### ISSUE THREAD

**Issue by patrickbrownsync** [GoogleCloudPlatform/google-cloud-ruby#1462]
After installing google-cloud-logging via the stackdriver gem my production delayed_job task fails to start (my rails web server run via puma works fine)

Google cloud logging is configured like this for DJ:

```
logging_config = Google::Cloud::Logging::Railtie.parse_rails_config Rails.application.config

project_id = logging_config[:project_id]
keyfile = logging_config[:keyfile]
resource_type = logging_config[:resource_type]
resource_labels = logging_config[:resource_labels]
log_name = logging_config[:log_name]

logging = Google::Cloud::Logging.new(project: project_id, keyfile: keyfile)

resource =
    Google::Cloud::Logging::Middleware.build_monitored_resource resource_type,
                                                 resource_labels

Delayed::Worker.logger  = logging.logger log_name, resource
```

Which causes this command:

`export RAILS_ENV="google_cloud" ; /usr/bin/env bundle exec bin/delayed_job run`

to fail like this:

```
delayed_job: process with pid 32036 started.
E0509 17:03:04.440097738   32061 ev_epoll_linux.c:1971]      add_poll_object: {"created":"@1494349384.440051882","description":"polling_island_add_wakeup_fd","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":324,"referenced_errors":[{"crea
ted":"@1494349384.440040503","description":"OS Error","errno":1,"file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":503,"os_error":"Operation not permitted","syscall":"epoll_ctl (epoll_fd: 13) add wakeup fd: 7 failed with error: 1 (Operation
 not permitted)"}]}
E0509 17:03:04.450655266   32061 ev_epoll_linux.c:1971]      add_poll_object: {"created":"@1494349384.450615988","description":"polling_island_add_wakeup_fd","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":324,"referenced_errors":[{"crea
ted":"@1494349384.450591933","description":"OS Error","errno":1,"file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":503,"os_error":"Operation not permitted","syscall":"epoll_ctl (epoll_fd: 13) add wakeup fd: 7 failed with error: 1 (Operation
 not permitted)"}]}
E0509 17:03:04.568927218   32064 ev_epoll_linux.c:1971]      add_poll_object: {"created":"@1494349384.568896020","description":"polling_island_add_wakeup_fd","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":324,"referenced_errors":[{"crea
ted":"@1494349384.568891707","description":"OS Error","errno":1,"file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":503,"os_error":"Operation not permitted","syscall":"epoll_ctl (epoll_fd: 15) add wakeup fd: 7 failed with error: 1 (Operation
 not permitted)"}]}
E0509 17:03:04.569006376   32064 ev_epoll_linux.c:1971]      add_poll_object: {"created":"@1494349384.568989106","description":"polling_island_add_wakeup_fd","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":324,"referenced_errors":[{"crea
ted":"@1494349384.568986677","description":"OS Error","errno":1,"file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":503,"os_error":"Operation not permitted","syscall":"epoll_ctl (epoll_fd: 15) add wakeup fd: 7 failed with error: 1 (Operation
 not permitted)"}]}
E0509 17:03:04.569616745   32064 ev_epoll_linux.c:621]       assertion failed: pi->fd_cnt == 0
Aborted
```

However if the only thing I change is changing my logging config to this:

`Delayed::Worker.logger = Logger.new(File.join(Rails.root, 'log', 'delayed_job.log'))`

Then the delayed job worker starts fine:

`delayed_job: process with pid 7663 started.`

Also, if I start my delayed job task like this (suboptimal as it does not daemonize):

`bundle exec rake RAILS_ENV=google_cloud jobs:work`

It also works fine

**Comment by hxiong388** [comment]
@patrickbrownsync Thanks for reporting the issue. We'll look into the issue.

/cc @dazuma

**Comment by patrickbrownsync** [comment]
Any solutions?

**Comment by hxiong388** [comment]
@patrickbrownsync Sorry for the delayed response. This issue seems to be caused at the gRPC level, as discussed in several gRPC issues like [this one](https://github.com/grpc/grpc/issues/7951). When you configure the DJ logger in an initializer or environment file, it creates the gRPC client before forking the processing using the `daemons` gem, resulting the gRPC client to crash after the forking.

After investigating the `delayed_job` gem source code, I didn't find an easy way to customize the logger after forking. But I got this monkey patching solution to work:
```ruby
# config/initializers/delayed_job.rb

module Delayed
  class Worker
    class << self
      alias_method :original_after_fork, :after_fork

      def after_fork
        original_after_fork

        require "google/cloud/logging"
        project_id = "some-project-id"
        log_name = "delayed_job-log"
        logging = Google::Cloud::Logging.new(project: project_id)
        resource = Google::Cloud::Logging::Middleware.build_monitored_resource
        logger = logging.logger log_name, resource

        Delayed::Worker.logger = logger
        Delayed::Worker.logger.info "Hello from delayed_job"
      end
    end
  end
end
```

Let me know if this solution works for you.

**Comment by patrickbrownsync** [comment]
This did not work for me, it still crashes with the same error

**Comment by hxiong388** [comment]
If you're seeing the same error, likely the gRPC client may still be instantiated prior to the process forking. Can you please double check `require "google/cloud/logging"` and `Google::Cloud::Logging.new` are only invoked after process fork.

Meanwhile, please provide the version of gems you're using. Such as rails, delayed_job, daemons, google-cloud-logging, etc.

Finally, we can also try disable the threading of the `Google::Cloud::Logging::Logger` to reduce some of the complexity (You probably won't need async logger anyways for being in separate process). You can do that by instantiating the logger this way:

```ruby
# config/initializers/delayed_job.rb

module Delayed
  class Worker
    class << self
      alias_method :original_after_fork, :after_fork

      def after_fork
        original_after_fork

        require "google/cloud/logging"
        project_id = "some-project-id"
        log_name = "delayed_job-log"
        logging = Google::Cloud::Logging.new(project: project_id)
        resource = Google::Cloud::Logging::Middleware.build_monitored_resource
        logger = Google::Cloud::Logging::Logger.new logging, log_name, resource  # Explicitly instantiate Logger

        Delayed::Worker.logger = logger
        Delayed::Worker.logger.info "Hello from delayed_job"
      end
    end
  end
end
```

**Comment by hxiong388** [comment]
@patrickbrownsync  Actually, it would be better if you can provide the full Gemfile.lock.

**Comment by patrickbrownsync** [comment]
@hxiong388 I had other google cloud gems installed via stackdriver, after disabling those and using your solution it seemed to work.

Thanks!

**Comment by hxiong388** [comment]
Ahhhhh, right, all the google-cloud-ruby gems/clients that use gRPC share this same problem on process forking. Hope gRPC can fix this problem in the future.
