### ISSUE TITLE
Improve client library doc landing page for monitoring gem

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/google-cloud-ruby#1470]
If you click "Client Library Documentation" from the monitoring readme it directs you to an almost blank page. [https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-monitoring/v0.24.0/google/monitoring/v3](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-monitoring/v0.24.0/google/monitoring/v3)

![screen shot 2017-05-11 at 12 30 14 pm](https://cloud.githubusercontent.com/assets/479249/26114628/a1abf42e-3a12-11e7-86ea-7429f85840f7.png)

**Comment by geigerj** [comment]
Closing as duplicate of https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1181.
