### ISSUE TITLE
Monitoring gem should use the same authentication as other gems

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/google-cloud-ruby#1471]
The monitoring API doesn't take a keyfile in object creation. It also doesn't appear to use the environment variables the other gems use. All our gems should support the same authentication schemes. 

Compare: [https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-logging/v1.0.1/google/cloud/logging?method=new-class](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-logging/v1.0.1/google/cloud/logging?method=new-class)
and 
[https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-logging/v1.0.1/guides/authentication](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-logging/v1.0.1/guides/authentication)

to 

[https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-monitoring/v0.24.0/google/cloud/monitoring/v3/metricserviceclient?method=initialize-constructor](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-monitoring/v0.24.0/google/cloud/monitoring/v3/metricserviceclient?method=initialize-constructor)

**Comment by geigerj** [comment]
@thagomizer We currently support this through the `chan_creds` parameter of the client object constructor (https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-monitoring/v0.24.0/google/cloud/monitoring/v3/metricserviceclient?method=initialize-constructor). We don't necessarily intend to support the exact same format as the manually written surfaces as long as it's not overly complicated to configure client authentication using a keyfile -- it seems like the `chan_creds` should make this possible.

Does that seem reasonable?

**Comment by thagomizer** [comment]
We can take this offline but the expectation of the user community is that all of the gems should support the same authentication schemes. There is shared code that's available to be used for this.

**Comment by geigerj** [comment]
Sure, let's discuss offline.

**Comment by geigerj** [comment]
After some discussion in the team, we've decided to support passing a path to a keyfile for channel credentials. Tracking the code generator change as https://github.com/googleapis/toolkit/issues/1324.

**Comment by geigerj** [comment]
Closing as code generator change is tracked in googleapis/toolkit#1324.
