### ISSUE TITLE
Monitoring gem reuqires submitting the project name with every request

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/google-cloud-ruby#1472]
The monitoring gem requires submitting a specially formatted project name with every request. The other gems do not require this and the experience should be consistent between libraries in the same lanugage.

Also, requiring the specially formatted project name is inconsistent with the other gems as well.

**Comment by geigerj** [comment]
Note: there's a larger discussion between @anthmgoogle and others about this, but there are no immediate plans to address this at the GAPIC level.

**Comment by geigerj** [comment]
This feature request was escalated to @anthmgoogle and is now being tracked through internal documents. There is no immediate plan to make this change in the external codegen.
