### ISSUE TITLE
MetricServiceClient#list_time_series filter argument is too specific 

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/google-cloud-ruby#1475]
This might be an issue with the underlying API. 

Parameterizing your filter with list_time_series is awkward in Ruby because you *must* use double quotes around the metric name. 

The following don't work:
filter = "metric.type = '#{metric}'"
filter = "metric.type=#{metric}"
filter = "metric.type = 'appengine.googleapis.com/system/memory/usage'"
filter = "metric.type = appengine.googleapis.com/system/memory/usage"
 
In order use a metric type from a variable with string interpolation I have to do this:
filter = "metric.type = \"#{metric}\""  

Ideally I could use single or double quotes around the metric name.

**Comment by geigerj** [comment]
ISTM this would be better tracked server-side rather than client side. Feel free to follow up with me internally.
