### ISSUE TITLE
Can't figure out how to create a Google::Protobuf::RepeatedField of Google::Monitoring::V3::Point

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/google-cloud-ruby#1477]
In order to create a custom metric you must pass in a RepeatedField. To instantiate a RepeatedField you must pass in the class type that the RepeatedField will contain. 

I spent 30 minutes trying to figure out how to do this. Here are some things I tried: 
points = Google::Protobuf::RepeatedField.new("Google::Monitoring::V3::Point".to_sym) 
points = Google::Protobuf::RepeatedField.new("Google::Monitoring::V3::TimeSeries".to_sym)
points = Google::Protobuf::RepeatedField.new("Google::Monitoring::V3::Point") 
points = Google::Protobuf::RepeatedField.new("Google::Monitoring::V3::TimeSeries")

None of those worked. This is an odd pattern for Ruby so there should be documentation in the examples of how to do this.

**Comment by geigerj** [comment]
Acknowledged. @omaray is driving the general solution of getting us to comprehensive autogen samples across all methods/APIs.

**Comment by blowmage** [comment]
@geigerj This issue is falling outside of the SLO. Is there an issue on another repo to update the documentation to demonstrate how to use `RepeatedField`?

**Comment by Nakilon** [comment]
As far as I remember the trick was that you don't have explicitly create repeated fields -- they are kind of created by gem and you just push items to it. Here is simplified old code for example
```
log = lambda do |type, timestamp, value, resource: nil, labels: nil|
  time_series = Google::Monitoring::V3::TimeSeries.new(                                   # google-cloud-monitoring-0.24.0/lib/google/monitoring/v3/metric_pb.rb
    metric: Google::Api::Metric.new(                                                      # googleapis-common-protos-1.3.5/lib/google/api/metric_pb.rb
      type: "custom.googleapis.com/#{type}",
      **(labels ? {labels: labels} : {}),
    ),
    **(resource ? {resource: Google::Api::MonitoredResource.new(**resource)} : {})        # googleapis-common-protos-1.3.5/lib/google/api/monitored_resource_pb.rb
  )
  time_series.points.push Google::Monitoring::V3::Point.new(                              # google-cloud-monitoring-0.24.0/lib/google/monitoring/v3/metric_pb.rb
    interval: Google::Monitoring::V3::TimeInterval.new(
      start_time: Google::Protobuf::Timestamp.new(seconds: timestamp.to_i),
      end_time: Google::Protobuf::Timestamp.new(seconds: timestamp.to_i),
    ),
    value: Google::Monitoring::V3::TypedValue.new(**value)                                # google-cloud-monitoring-0.24.0/lib/google/monitoring/v3/common_pb.rb
  )
  fail if client.create_time_series(project_path, [time_series])
end
```
where you see I didn't create `points` on my own.

**Comment by geigerj** [comment]
This particular issue seems to be with protobuf usage, but we can and should mitigate the problem by showing how to create repeated fields in the autogenerated method samples. We're tracking upstream progress on autogenerate, correctly initialized method samples in the code generator (at https://github.com/googleapis/toolkit/issues/1809), so I'm closing this issue.

**Comment by stedied** [comment]
Hello everyone,

does this issue still exist or is there a solution to it? I'm trying to do something similar but was not able to create a RepeatedList with a specific custom type in Ruby so far:

messageContexts = Google::Protobuf::RepeatedField.new("Google::Cloud::Dialogflow::V2::Context".to_sym)

Thank you in advance for your support.

**Comment by blowmage** [comment]
The discussion has moved to https://github.com/protocolbuffers/protobuf/issues/4969.

**Comment by gbirchmeier** [comment]
Maybe it's just me, but I would not describe Nakilon's using the word "simplified".  I would probably choose an antonym of that.

**Comment by gbirchmeier** [comment]
For @thagomizer's original question, the answer is to _not_ create the RepeatingField of Points, but to instead create *the message that contains it*, and then append points to that empty array.

So if there's a message e.g. 

```
message Foo {
    ...
    repeated Points points = 6;
    ...
}
```

Then you want to do this:

```
foo = Foo.new # contains an empty points RepeatedField
points1 = create_points(blah) # returns Google::Monitoring::V3::Point
points2 = create_points(blah) 
foo.push points1
foo.push points2
```

You don't need to call `RepeatedField.new`, and I still don't know how to even use that with anything but a basic ruby type.

**Comment by aseure** [comment]
If anyone else is having the same issue in 2020, even though @gbirchmeier's solution works, it seems that the Ruby generated code has been updated since 2019 and it is now possible to set the field using an array (official documentation seems outdated as it doesn't mention it at the moment).

Here's how to do it now, based on the previous example from @gbirchmeier:

```
points = [
    create_points(blah) # returns Google::Monitoring::V3::Point
    create_points(blah)
]

foo = Foo.new(
    points: points,
)
```
