### ISSUE TITLE
No documentation how to use Google cloud Language gem for V1Beta2 Api

### ISSUE THREAD

**Issue by HimanshuLakra** [GoogleCloudPlatform/google-cloud-ruby#1480]
I am unable to understand how to pass content and project id as argument to document(Google::Cloud::Language::V1beta2::Document) object in following code.

require "google/cloud/language/v1beta2"

Document = Google::Cloud::Language::V1beta2::Document
LanguageServiceClient = Google::Cloud::Language::V1beta2::LanguageServiceClient

language_service_client = LanguageServiceClient.new
document = Document.new 
response = language_service_client.analyze_sentiment(document)

**Comment by blowmage** [comment]
It looks like the `Google::Cloud::Language::V1beta2::Document` class (and `Google::Cloud::Language::V1::Document` class) is not making its way to the HTML documentation. The code docs can be seen [here](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-language/lib/google/cloud/language/v1beta2/doc/google/cloud/language/v1beta2/language_service.rb#L19-L46). The Document class has the attributes `type`, `content`, `gcs_content_uri`, and `language`. I can see something like the following working:

```ruby
document = Document.new content: "Hello world!", type: :PLAIN_TEXT, language: "en-US"
```

@quartzmo We probably need to figure out why this class isn't being shown, and see if the GAPIC documentation can be updated with better examples.

**Comment by HimanshuLakra** [comment]
@blowmage how do I pass api_key or project_id to link call with my project on google cloud ,as earlier it was passed in language object 
 language  = Google::Cloud::Language.new project: project_id

**Comment by blowmage** [comment]
You don't. The code in the issue description is using the low level API. The code in your last comment is using the ruby API. When using the low level API you need to create a credential object using Google Auth.

I would recommend using the ruby API and not the low level API.

**Comment by HimanshuLakra** [comment]
Thanks @blowmage

**Comment by geigerj** [comment]
@quartzmo Did you have a chance to look into this? Do you know if there something we're doing wrong with the GAPIC docs that causes these classes not to be displayed?

**Comment by quartzmo** [comment]
@geigerj No, sorry. Taking a quick look now.

**Comment by quartzmo** [comment]
The issue is the inclusion of files such as [`language_service_pb.rb`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-language/lib/google/cloud/language/v1beta2/language_service_pb.rb) in the YARD output. The `Document` constant in `language_service_pb.rb` shadows the `Document` class in the `docs` directory. I will submit a PR excluding these non-documentation files from the YARD output.
