### ISSUE TITLE
Spanner Pool Changes

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1485]
The following changes have been requested:

- [x] Change max to 100
- [x] Create new sessions/transactions outside of mutex
- [x] Ensure Pool#close does not block waiting threads
- [x] Use signal instead of broadcast
- [x] Synchronize when calling keepalive
- [x] Track last used time on session, use for more intelligent keepalive
- [x] Handle errors when calling Session#delete_session
- [x] Add threading to Pool#init, so it won't block
- [x] Cull idle sessions
- [ ] ~Change Transaction#keepalive to call BeginTransaction~

**Comment by vkedia** [comment]
Can you also add cleanup of idle sessions to this list?

**Comment by blowmage** [comment]
The Transaction#keepalive item has been removed from the list.

**Comment by blowmage** [comment]
Delivered in #1502
