### ISSUE TITLE
Update BigQuery related doc to reflect recent changes

### ISSUE THREAD

**Issue by dlackty** [GoogleCloudPlatform/google-cloud-ruby#1496]
As 41cfacca49ab6fb7075970dba7d0c9026dbeb3d9 merged into master and new version released, the README example and related code snippets on Google Developers site need to get updated as well.

**Comment by quartzmo** [comment]
@dlackty Thanks for opening this issue! I will make the update for the README and API docs for this library. Unfortunately I have no control over snippets on the Google Developers site.
