### ISSUE TITLE
[Storage] Download a public file without a service-account.

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1503]
Hi,
I tried downloading the public file `gs://cloud-ml-sandbox/video/chicago.mp4` using the Storage client, but I'm not able to because I don't have access to the `cloud-ml-sandbox` storage bucket. 

Is there a way to download a public file using the storage client?

I tried using:
```
require "google/cloud/storage"

storage_client = Google::Cloud::Storage.new project: 'test-project-name'

# Attempt to download video from "gs://cloud-ml-sandbox/video/chicago.mp4"
bucket = storage_client.bucket 'cloud-ml-sandbox'
file = bucket.file '/video/chicago.mp4'
file.download 'chicago.mp4'
```

Error:
```
Caller does not have storage.buckets.get access to bucket cloud-ml-sandbox. (Google::Cloud::PermissionDeniedError)
```

**Comment by blowmage** [comment]
You cannot use the Google Cloud Storage client to access buckets you do not have access to. However, instead of using the GCS URL, you can use a public HTTP URL: http://storage.googleapis.com/cloud-ml-sandbox/video/chicago.mp4

```ruby
require "open-uri"

download = open "http://storage.googleapis.com/cloud-ml-sandbox/video/chicago.mp4"
```

**Comment by frankyn** [comment]
Thanks @blowmage, Is there a reason why the client library doesn't support this?

**Comment by blowmage** [comment]
The Google Cloud Storage ruby library doesn't support loading of a file by the GCS URL, even if you had access. But it sounds like you don't really want the file object, you just want the contents, which is what the public URL provides.

**Comment by frankyn** [comment]
Ah, sorry, I didn't explain myself well. I had a question come up about downloading a file using the client similar to `File#download` but for public files. I understand you can download it without using the client library. 

This is not a request and only a question about it being the library.

**Comment by blowmage** [comment]
I don't understand your expectations. Can you share some sample code of what you expected the ruby library to do?

**Comment by frankyn** [comment]
I don't mean to confuse you. My original question, can the client library download public files. The answer at the moment is no. I was just wondering.

I **thought** the client library could download public files by using:
```
storage = Google::Cloud::Storage.new

bucket = storage.bucket 'public_bucket'

bucket.file('public_file').download('local_public_file')
```

**Comment by blowmage** [comment]
In order for that code to work you would need permissions to the bucket and file resources through the Storage API. Accessing a file's contents with a public URL can be configured in the Storage API, but the library itself doesn't access content with the public URL, only through the Storage API.

**Comment by frankyn** [comment]
Understood! Thanks @blowmage!

**Comment by immadikiran** [comment]
I just tried with Chicago4 video. It worked well. If I want to analyze my own video now, do I need to place that video in the Google cloud storage?  Appreciate your inputs. Appreciate your help.

**Comment by blowmage** [comment]
It doesn’t sound like your question is the same as downloading a file from GCS. Can you open a new issue with all the relevant details?
