### ISSUE TITLE
"Magic" Image Urls?

### ISSUE THREAD

**Issue by dts** [GoogleCloudPlatform/google-cloud-ruby#1509]
There's documentation of automatic image resizing in other clients ( e.g. https://cloud.google.com/appengine/docs/standard/python/blobstore/ ) via a mechanism varyingly named "Magic URLs" or "Public Urls".

Is such a thing available in Ruby?  I couldn't find any documentation of the mechanism underlying this behavior, though it could be as easy as hashing a few things and sending a request to googleusercontent.com...

**Comment by blowmage** [comment]
I am not very familiar with the AppEngine offerings, but it looks like Blobstore is part of the AppEngine Standard environment, which doesn't have Ruby support. The AppEngine Flex environment is the one that has Ruby support. So it doesn't look like it will be supported.

**Comment by quartzmo** [comment]
@dts Did this response answer your question? Or is there any more information you can add to move this forward?

**Comment by dts** [comment]
It did - but it does seem unfortunate that this feature is limited in this way.

**Comment by quartzmo** [comment]
@dts Nevertheless, thanks for asking. It will hopefully serve as feedback for product owners.

**Comment by dts** [comment]
@JustinBeckwith - not sure what I can contribute here, but let me know if I'm missing something!
