### ISSUE TITLE
Update Translation for end of Premium Edition (Beta)

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1523]
The Translation API release notes from April 6 state:

> The Google Cloud Translation API is no longer taking requests for access to the Premium Edition (Beta). Instead, the premium features of the Google Cloud Translation API have been made generally available in the Standard Edition.

Should we remove discussion of Premium Edition and Beta (service, not library) from docs?

**Comment by geigerj** [comment]
I'm following up and will update when I know more.

**Comment by geigerj** [comment]
Communication from the API team was to go ahead and remove all mentions of Premium Edition/Beta from the docs.
