### ISSUE TITLE
beginOffset for AnalyzeEntitySentiment is always -1

### ISSUE THREAD

**Issue by RavenXce** [GoogleCloudPlatform/google-cloud-ruby#1524]
Reproduction script:

```
def annotate(text)
    require "google/cloud/language/v1beta2"

    Document = Google::Cloud::Language::V1beta2::Document
    EncodingType = Google::Cloud::Language::V1beta2::EncodingType
    Features = Google::Cloud::Language::V1beta2::AnnotateTextRequest::Features
    LanguageServiceClient = Google::Cloud::Language::V1beta2::LanguageServiceClient

    language_service_client = LanguageServiceClient.new
    document = Document.new(content: text, type: :PLAIN_TEXT)
    features = Features.new(extract_entity_sentiment: true, extract_syntax: true)
    encoding_type = EncodingType::NONE
    language_service_client.annotate_text(document, features, encoding_type)
end
```

`annotate(text).entities.first.mentions.first.text.begin_offset` always gives `-1`. It should instead return the entity's position within the original text. 

See: https://cloud.google.com/natural-language/docs/analyzing-entity-sentiment

**Comment by quartzmo** [comment]
@RavenXce Thank you for reporting this issue. I'll take a look at it later today and let you know what I find.

**Comment by RavenXce** [comment]
Hi @quartzmo, I just realized the issue is on my incorrect usage of the API, sorry. 

Setting the encoding type as `None` caused the above to happen (as specified by the API): https://cloud.google.com/natural-language/docs/reference/rest/v1/EncodingType?hl=pt
