### ISSUE TITLE
Google::Cloud::Logging::AsyncWriter terminates prematurely.

### ISSUE THREAD

**Issue by hxiong388** [GoogleCloudPlatform/google-cloud-ruby#1526]
If the application is terminated while calling `Google::Cloud::Logging::AsyncWriter#write_entries`, it would error out and drop all the queued entries without submitting them, because of [this line](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/12eb9d41d52ab7d1092e60f3a4b5031fce30bce3/google-cloud-logging/lib/google/cloud/logging/async_writer.rb#L149).

**Comment by geigerj** [comment]
@dazuma @hxiong388 Please attach the appropriate priority label to this bug. Thanks!

**Comment by hxiong388** [comment]
Assigned P2, for backlog.

**Comment by quartzmo** [comment]
This issue is falling outside of SLO for closure. Any update?

**Comment by dazuma** [comment]
Closing this, as it does not seem to be an issue. An application should not be terminated in the middle of a call to `AsyncWriter#write_entries`, as that call happens in the context of a request. If it does happen, it would be an error. And much more would go wrong, as the request itself would be interrupted in the middle of its execution (before it ever got to that raise).
