### ISSUE TITLE
Undefined method silence for Rails 5.1.1

### ISSUE THREAD

**Issue by sidguptajhs** [GoogleCloudPlatform/google-cloud-ruby#1527]
I'm running a standard rails web app with Rails 5.1.1
In rendering the assets I'm getting this error.

> 2017-06-08 10:54:29 +0530: Rack app error handling request { GET /assets/application-211d4d6c18ff3e3fad281ddaa8661eccf49a48f39316a9c4f03a73220eee3d66.css }
#<NoMethodError: undefined method `silence' for #<Google::Cloud::Logging::Logger:0x000000060f0608>>
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/quiet_assets.rb:11:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google-cloud-logging-1.1.0/lib/google/cloud/logging/middleware.rb:88:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/request_id.rb:25:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/static.rb:125:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/engine.rb:522:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.9.0/lib/puma/configuration.rb:224:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.9.0/lib/puma/server.rb:602:in `handle_request'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.9.0/lib/puma/server.rb:435:in `process_client'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.9.0/lib/puma/server.rb:299:in `block in run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.9.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
2017-06-08 10:54:29 +0530: Rack app error handling request { GET /assets/application-c4c308e5377b25ef2254118c05a2ea593323e0d00da370378e417c5326e84457.js }
#<NoMethodError: undefined method `silence' for #<Google::Cloud::Logging::Logger:0x000000060f0608>>
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/quiet_assets.rb:11:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google-cloud-logging-1.1.0/lib/google/cloud/logging/middleware.rb:88:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/request_id.rb:25:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/static.rb:125:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/engine.rb:522:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.9.0/lib/puma/configuration.rb:224:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.9.0/lib/puma/server.rb:602:in `handle_request'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.9.0/lib/puma/server.rb:435:in `process_client'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.9.0/lib/puma/server.rb:299:in `block in run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.9.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
2017-06-08 10:54:30 +0530: Rack app error handling request { GET /assets/logo-9472f3fef3b4dbafda005740198f4e5688f5fb28b59b354f51f280fc64ce86f7.ico }
#<NoMethodError: undefined method `silence' for #<Google::Cloud::Logging::Logger:0x000000060f0608>>
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/quiet_assets.rb:11:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google-cloud-logging-1.1.0/lib/google/cloud/logging/middleware.rb:88:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/request_id.rb:25:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/static.rb:125:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/engine.rb:522:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.9.0/lib/puma/configuration.rb:224:in `call'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.9.0/lib/puma/server.rb:602:in `handle_request'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.9.0/lib/puma/server.rb:435:in `process_client'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.9.0/lib/puma/server.rb:299:in `block in run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/puma-3.9.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'

**Comment by hxiong388** [comment]
Hi @sidguptajhs. Thanks for reporting the issue. The `Google::Cloud::Logging::Logger` is implemented to match `::Logger` specs, but it doesn't have the additional methods that `ActiveSupport::Logger` adds on top of `::Logger`, such as `ActiveSupport::Logger#silence`. We'll look into filling the gap.

/cc @dazuma

**Comment by hxiong388** [comment]
@sidguptajhs It seems like `ActiveSupport::Logger` actually injects the "#silence" method onto `Google::Cloud::Logging::Logger` in development environment, but not in production. Are you using the 'config.assets.quiet = true' in your production configuration? You may be temporarily workaround this error by disabling this setting for now.

**Comment by sidguptajhs** [comment]
Thanks. I'd done an alternate workaround by implementing the missing methods. Seems like that has been addressed in #1551
