### ISSUE TITLE
Create, configure and load table in one call

### ISSUE THREAD

**Issue by AlfonsoUceda** [GoogleCloudPlatform/google-cloud-ruby#1528]
Regarding to issue https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/939 I'm opening this issue to allow the creation of `Dataset#load`.

@blowmage as you said me in this comment https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/939#issuecomment-284005734 

> I can see an argument for a Dataset#load method that will allow the creation of a table, configuring of a schema, and loading of data in a single BigQuery API call. If that is what is wanted I would respectfully ask that a new issue be opened for that.

I would like to know if this operation can be supported, we have this use case: we create the table or truncate it with the attached schema and loading data in only one call. I think this can be helpful for more people, you can do it with `bq` command, why not with ruby? In addition, I'd like to get rid of my fork and use the official gem.

**Comment by quartzmo** [comment]
> I'm opening this PR to allow the creation of `Dataset#load`.

@AlfonsoUceda Are you opening a pull request?

**Comment by AlfonsoUceda** [comment]
@quartzmo sorry I wanted to say: issue

**Comment by quartzmo** [comment]
OK, thanks for the clarification. I'll let @blowmage comment on it. But I would be happy to work on the pull request for it if there is agreement that it should be added.

**Comment by quartzmo** [comment]
@AlfonsoUceda We are planning to begin work on this feature today.

**Comment by AlfonsoUceda** [comment]
@quartzmo thank you so much :)
