### ISSUE TITLE
Improve Spanner test coverage

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1529]
This issue is from @danoscarmike:

> There are a number of files in google-cloud-ruby/google-cloud-spanner that have <=90% code coverage.

> As we push past Alpha and head for Beta can you please review and get relevant files up to an 80% minimum threshold?

> Screenshot of [coveralls report](https://coveralls.io/github/GoogleCloudPlatform/google-cloud-ruby) attached.  Search term: "spanner"

<img width="1147" alt="screen shot 2017-06-08 at 10 53 55 am" src="https://user-images.githubusercontent.com/205445/26949043-aba2f7e8-4c55-11e7-997a-32961ad36825.png">

**Comment by quartzmo** [comment]
The lowest 3 in this report are GAPIC code that should be excluded:

`/lib/google/cloud/spanner/v1/spanner_client.rb`
`...spanner/admin/database/v1/database_admin_client.rb`
`...spanner/admin/instance/v1/instance_admin_client.rb`

**Comment by danoscarmike** [comment]
@lukesneeringer @geigerj can you look at updating CI to exclude the 3 x GAPIC files identified by @quartzmo above?  TY!
