### ISSUE TITLE
Publishing messages without data

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1535]
The current Pub/Sub API allows messages to be published without a data payload.

```ruby
require "google/cloud/pubsub"

pubsub = Google::Cloud::Pubsub.new

topic = pubsub.topic "my-topic"
topic.publish
```

Should this continue to be allowed? Or is `data` required for publishing to a topic?

**Comment by geigerj** [comment]
@tbkneeland

**Comment by lukesneeringer** [comment]
@tbkneeland The use case for this would be if you wanted attributes, but no data. There is code in the Ruby client only that allows this, and you can send just the attributes as the first argument (it figures it out because you send a hash).

**Comment by tbkneeland** [comment]
Our publicly documented API should be clearer on this point. Better language would be:

"Each message must contain either non-empty data, or at least one attribute."

I've filed an (internal) bug to clarify the docs (b/62701766)

**Comment by tbkneeland** [comment]
That is, my position is that every language's client library must allow users to publish all of:

- Message with data only
- Message with attributes only
- Message with both data and attributes

As for a message with no data or attributes: I don't think we should get into the business of client-side validation (beyond that which is necessary to avoid string/bytes confusion as discussed elsewhere). A request with neither data nor attributes can be used to create a well defined proto, which the server will reject with a friendly error message.

I'd imagine each language might have its own idiomatic ways to spell this, so I don't think consistency in this regard is crucial. (And again, my personal preference would be for users to interact with protos directly so we don't have to be in the business of type conversions at all... but that's moot)

**Comment by blowmage** [comment]
Fantastic! Thank you very much for the clarification.

**Comment by lukesneeringer** [comment]
Great. Thank you @tbkneeland.
