### ISSUE TITLE
Add public Schema creation, and schema option to Dataset#create_table and Dataset#load

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1537]
From @AlfonsoUceda's comments in PR #1533:

> is there a change to pass the schema as an option instead a block? for example the following snippet:

```ruby
bigquery.dataset("my_dataset").load "my_table", file, write: "truncate", schema: schema
```

> We create schema objects `#from_gapi(nil)` because then we inject them in the `table#load` using our fork. I know `#from_gapi` method is private but is there a way to create schema objects from a public interface? have you though in that?

More on  @AlfonsoUceda's usage:

> we have our custom reporter component, I mean an ETL process. We have schema separated by files, every schema its class, so we can inject them in our ETL class, every ETL has a file and we define a extractor, transformer and loader (csv). When the CSV file is created then with this file and a generated schema object we inject into our bigquery loaders class to create or truncate the table.

> This is because we can't test our schema in a separate test or because we share schemas by ETLs.

```ruby
bigquery_loader.load(file, schema: schema)

# inside `#load`
table.load file, write: 'truncate', schema: schema # this is because of our fork
```

**Comment by AlfonsoUceda** [comment]
@quartzmo thanks!
