### ISSUE TITLE
jsondoc doesn't handle URL links

### ISSUE THREAD

**Issue by eoogbe** [GoogleCloudPlatform/google-cloud-ruby#1584]
The YARD format for URL links is `{url title}`, e.g. `{https://cloud.google.com/logging/quota-policy quota limit}` which should look like [quota limit](https://cloud.google.com/logging/quota-policy). When generating the docs for a page with correctly formatted URL links, jsondoc will issue a warning like:
```
[warn]: In file `lib/google/cloud/logging/v2/logging_service_v2_client.rb':296: Cannot resolve link to https://cloud.google.com/logging/quota-policy from text:
	{https://cloud.google.com/logging/quota-policy quota limit}...
```
and the page will show the URL instead of the title. This looks weird when the text is in the middle of a sentence, e.g. `To improve throughput and to avoid exceeding the https://cloud.google.com/logging/quota-policy for calls to entries.write...` I believe the logic for this is in [Gcloud::Jsondoc::MarkupHelper#linkify](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/gcloud-jsondoc/lib/gcloud/jsondoc/markup_helper.rb#L39). `linkify` should be able to process URLs and fallback on the title, rather than the address, when the URL cannot be resolved.

**Comment by quartzmo** [comment]
@eoogbe Can you format the links in markdown instead? `[title](url)`, e.g. `[quota limit](https://cloud.google.com/logging/quota-policy)`.

The project's `.yardopts` configurations specify: `--markup markdown`

**Comment by eoogbe** [comment]
Thanks, the markdown link format works.

**Comment by quartzmo** [comment]
@eoogbe OK to close this issue?
