### ISSUE TITLE
[datastore] Undefined method `value_type' for #<Hash:0x007fea54bdc180>

### ISSUE THREAD

**Issue by semmiverian** [GoogleCloudPlatform/google-cloud-ruby#1587]
Hi i've been trying to do a queries to the data store on ruby with this corresponding code

`query = dataset.query('builder-callout-extensions')
                                                                         .where('language', '=', language)
                                                                         .where('vertical', '=', vertical)
                dataset.run query`

but i've got this corresponding error

```undefined method `value_type' for #<Hash:0x007fea54bdc180>```

is there something wrong with my code or is there any mistake that i made?

thanks

**Comment by blowmage** [comment]
I don't get that error. What version of google-cloud-datastore are you using? What version of ruby are you using? What platform are you using?

**Comment by semmiverian** [comment]
Hi @blowmage thanks for the reply

i don't know why but when i delete the gemfile.lock and redoing the bundle install, everything works fine 😄

**Comment by blowmage** [comment]
Glad to hear it resolved itself!  If you have any other problems please open another issue.
