### ISSUE TITLE
list folders in a bucket

### ISSUE THREAD

**Issue by mtricolici** [GoogleCloudPlatform/google-cloud-ruby#1590]
```
storage = Google::Cloud::Storage.new(...)
storage.service.list_files('some-bucket', delimiter: '/')
```

code above lists only files. How to see folders?

**Comment by mtricolici** [comment]
```
def get_files(bucket)
  storage = Google::Cloud::Storage.new(
    project: 'this-is-ignored-anyway',
    keyfile: 'service.json',
    scope: 'https://www.googleapis.com/auth/devstorage.read_only')

  result = Array.new

  token = nil
  while true do
    files = storage.service.list_files(bucket, delimiter: '/', max: 10000, token: token)

    files.items.each do |obj|
      result.push obj.name
      puts "file: #{obj.name}"
    end unless files.items.nil?

    files.prefixes.each do |p|
      result.push p
      puts "dir: #{p}"
    end unless files.prefixes.nil?

    token = files.next_page_token
    break if token.nil?
  end

  result
end
```

**Comment by quartzmo** [comment]
Please note that the example above is NOT RECOMMENDED as it uses undocumented access to `storage.service` to use the underlying [google-api-client](http://www.rubydoc.info/gems/google-api-client/Google/Apis/StorageV1/StorageService) implementation. This implementation is subject to change at any time without warning, and has in fact been changed in many of the other packages in google-cloud-ruby. Should it change in the future for google-cloud-storage, the above code will no longer work.

The correct way to print or return the "directory" names (as defined by a delimiter value such as `"/"`) that are contained within a bucket is as follows:

```ruby
require "google/cloud/storage"

storage = Google::Cloud::Storage.new

bucket = storage.bucket "my-bucket"
files = bucket.files delimiter: "/"
loop do

  files.prefixes.each do |p| 
    puts "dir: #{p}"
  end

  break unless files.next?
  files = files.next
end
```

**Comment by mtricolici** [comment]
thanks @quartzmo . unfortunately your example requires service account to have 'storage.buckets.list' permission.

**Comment by quartzmo** [comment]
See #1588 for discussion of bucket access.
