### ISSUE TITLE
List available methods in class documentation

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/google-cloud-ruby#1593]
Some libraries, like Monitoring, include a list of available methods after the class overview

![screen shot 2017-07-13 at 7 57 06 pm](https://user-images.githubusercontent.com/280/28196432-801ccb82-6805-11e7-9f4a-915af46de473.png)

Most other libraries don't currently list the available methods for a documented class.

The index is really helpful.

Request: can we add this to all documented classes?

**Comment by blowmage** [comment]
The reason the list is missing is that the Angular documentation app has this list as part of the constructor method documentation. Most of the Google Cloud Ruby classes hide the constructor, as instances should be created by calls on other objects, so this list isn't shown.

This list can be added, but we need to change how the Angular app is designed/implemented to do it.

**Comment by remi** [comment]
Ack. I'd file this under *"annoying but not super critical"*

For what it's worth, the way that I consume the https://googlecloudplatform.github.io/google-cloud-ruby class documentation is to ⌘f search the page for instances of "#" to browse the class's methods. I've also used irb to print class.methods.sort - Object.methods instead of the documentation on occasion 😕

It would be a greatly appreciated enhancement 😄

**Comment by quartzmo** [comment]
Fixed by GoogleCloudPlatform/gcloud-common#227
