### ISSUE TITLE
Add code examples demonstrating usage of file generation/versions

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1601]
Hi! 

Is it possible to list available file generations using the Storage Client? Also is it possible to select a generation when accessing a file from a bucket?

Thank you!

**Comment by quartzmo** [comment]
Yes, both of these are supported:

1. To list available generations for a file, call [`Bucket#files`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage/bucket.rb#L493) with the `prefix` option set to the name of the file and the `versions` option set to `true`. The `versions` option:
    > If `true`, lists all versions of an object  as distinct results. The default is `false`. 
1. To select a generation when accessing a file from a bucket, call [`Bucket#file`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage/bucket.rb#L534) with the `generation` option set to the desired generation number. This option:
    > When present, selects a specific revision of this object. Default is the latest version.

For general information on this topic, see [Object Versioning](https://cloud.google.com/storage/docs/object-versioning).

**Comment by frankyn** [comment]
Thanks @quartzmo! I missed these two options in the docs. As always your help is greatly appreciated!

**Comment by quartzmo** [comment]
@frankyn Feel free to make a case for adding code examples to demonstrate file versioning if you feel it is important.

**Comment by frankyn** [comment]
Reopened to use as a request: 

I was doing a parity check on functionality of the Storage client. After reviewing the documentation, it would be helpful to have examples of using different generations of a file. The library uses version and generation interchangeably and that confused me when searching for versioning related information about the client. 

Example: `Bucket#file` uses parameter generation and `Bucket#files` uses versions.

**Comment by quartzmo** [comment]
> it would be helpful to have examples of using different generations of a file.

I feel this is a valid request. We can update the title of this issue to match it.

> Bucket#file uses parameter generation and Bucket#files uses versions.

The option names `generation` and `versions` match the names in the service API. For continuity with official documentation, I feel it is important to keep these names unchanged. However, adding a discussion of versioning to our [Storage guide](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/master/google/cloud/storage) should help to clarify their meaning.

**Comment by blowmage** [comment]
This might be a good candidate to use a helper method. Perhaps something like `File#generations` that would return multiple File objects for each generation tracked in GCS.

**Comment by quartzmo** [comment]
@frankyn Thanks for testing through the lifecycle, and good observation!

(FYI I think you used `bucket.copy` and `bucket.delete` when you must have meant `file.`)

**Comment by frankyn** [comment]
@quartzmo yes! I have updated the description. Sorry about the confusion!

@blowmage it would be a great helper method to list generations of a file!

**Comment by blowmage** [comment]
The `File#generations` method is [released in 1.4.0](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-storage%2Fv1.4.0).

**Comment by frankyn** [comment]
Thanks @blowmage !!!
