### ISSUE TITLE
Generate clients for missing APIs?

### ISSUE THREAD

**Issue by bootstraponline** [GoogleCloudPlatform/google-cloud-ruby#1604]
I'm using `google-api-ruby-client` to interact with Google Sheets. That library has been put in maintenance mode in favor of using `google-cloud-ruby`. What is the migration path for non-google-cloud APIs like sheets?

What does `google-cloud-ruby` use to generate the client bindings?

- https://github.com/google/google-api-ruby-client/pull/597#issuecomment-314051742

**Comment by danoscarmike** [comment]
Right now there is no migration plan.

"Maintenance mode" means that the `google-api-ruby-client` are considered mature and complete; so we do not expect to add any more major features.

We will continue to support these libraries, fix bugs, and add minor features as required to support ongoing changes.  And we will continue to release new versions of all API libraries as they are available.

I'll close this issue for now.  If I haven't answered your question please feel free to re-open.

Thanks!

**Comment by bootstraponline** [comment]
> I'll close this issue for now. If I haven't answered your question please feel free to re-open.

Would you clarify the relationship between the code generation tech used in `google-cloud-ruby` and the new approach as described on [googleapis/toolkit](https://github.com/googleapis/toolkit)?

It looks like there's [some sort of effort](https://github.com/GoogleCloudPlatform/google-cloud-go/issues/266#issuecomment-221083266) to use clients generated from toolkit?

**Comment by bootstraponline** [comment]
> If I haven't answered your question please feel free to re-open.

FYI there is no option for regular users to re-open an issue. They'd have to be made a member of the project or otherwise granted permission.

**Comment by blowmage** [comment]
The toolkit repo is used to generate low level API clients built on top of the gRPC library accessing the gRPC API endpoints, where Google API Client is an older effort that build low level API clients on top of the JSON API endpoints. The Google Cloud libraries are (mostly) high level, hand-written clients built on top of the low level clients, which provide several conveniences and adhere to many Ruby idioms.

**Comment by bootstraponline** [comment]
Cool. Thanks for explaining.

**Comment by danoscarmike** [comment]
> FYI there is no option for regular users to re-open an issue.

My apologies!  I'll look into that.  And thanks @blowmage for jumping in 👍
