### ISSUE TITLE
Can't create link to headings/methods on the latest version of the docs

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/google-cloud-ruby#1610]
I'm trying to create URLs to link directly to headings and methods in the https://googlecloudplatform.github.io/google-cloud-ruby documentation for the *latest* version, but #heading-ids and ?method=querystrings are being stripped out.

Steps to reproduce...

### Link to heading

To get to the latest spanner page:
https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-spanner/latest/google/cloud/spanner

To get to a heading (by manually browsing the latest version):
https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-spanner/v0.22.0/google/cloud/spanner#writing-data

URL that should take me to this heading on the latest version of the docs:
https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-spanner/latest/google/cloud/spanner#writing-data

🐞 But this just redirects me to the main page (heading #hash is stripped out):
https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-spanner/v0.22.0/google/cloud/spanner

### Link to instance method

To get to the latest spanner Client reference page:
https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-spanner/latest/google/cloud/spanner/client

To get to an instance method (by manually browsing the latest version):
https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.35.0/google/cloud/spanner/client?method=commit-instance

URL that should take me to this heading on the latest version of the docs:
https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-spanner/latest/google/cloud/spanner/client?method=commit-instance

🐞 But this just redirects me to the main page (?method query string is stripped out):
https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-spanner/v0.22.0/google/cloud/spanner/client

**Comment by remi** [comment]
@frankyn FYI

**Comment by quartzmo** [comment]
@remi I opened a gcloud-common site PR that fixes this issue (for me locally at least ;)).

**Comment by quartzmo** [comment]
Fixed by GoogleCloudPlatform/gcloud-common#226

**Comment by blowmage** [comment]
@quartzmo I think this issue may need to be reopened. I just tried the examples in the description, and while this works for query string (after the `?`) it doesn't work for the bookmarks (after the `#`). Thoughts?
