### ISSUE TITLE
[Spanner] Quiet Client#update error

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1614]
Hi,

I was using the Spanner client library to debug a bug from a sample. I found that the Client#update method doesn't raise an error when adding a secondary index and a column it uses doesn't exist. I provided an example below along with the error.

Open-question, should this be handled by users? If so, could an example be added for handling these errors? 

Expected error to be raised:
```ruby
Index AlbumsByAlbumTitle2 specifies nonexistent stored column MarketingBudget.
```

Example to reproduce:
```ruby
require "google/cloud/spanner"

project_id  = "project-id"
instance_id = "instance-id"
database_id = "database-id"

spanner  = Google::Cloud::Spanner.new project: project_id
instance = spanner.instance instance_id

job = instance.create_database database_id, statements: [
  "CREATE TABLE Singers (
    SingerId     INT64 NOT NULL,
    FirstName    STRING(1024),
    LastName     STRING(1024),
    SingerInfo   BYTES(MAX)
  ) PRIMARY KEY (SingerId)",

  "CREATE TABLE Albums (
    SingerId     INT64 NOT NULL,
    AlbumId      INT64 NOT NULL,
    AlbumTitle   STRING(MAX)
  ) PRIMARY KEY (SingerId, AlbumId),
  INTERLEAVE IN PARENT Singers ON DELETE CASCADE"
]

puts "Waiting for create database operation to complete"
job.wait_until_done!
puts "Created database #{database_id} on instance #{instance_id}"

database = job.database

job = database.update statements: [
  "CREATE INDEX AlbumsByAlbumTitle2 ON Albums(AlbumTitle)
   STORING (MarketingBudget)"
]

puts "Waiting for database update to complete"
job.wait_until_done!
puts "Added the AlbumsByAlbumTitle2 storing index"
```

Returned Database#Job:
```ruby
#<Google::Cloud::Spanner::Database::Job:0x00561bab77ec10 @grpc=#<Google::Gax::Operation:0x00561bab77ec88 @grpc_op=<Google::Longrunning::Operation: name: "projects/spec-test-ruby-samples/instances/test-instance-ruby-samples/databases/database-id/operations/_auto_1501050315663967", metadata: <Google::Protobuf::Any: type_url: "type.googleapis.com/google.spanner.admin.database.v1.UpdateDatabaseDdlMetadata", value: "\nZprojects/spec-test-ruby-samples/instances/test-instance-ruby-samples/databases/database-id\x12PCREATE INDEX AlbumsByAlbumTitle2 ON Albums(AlbumTitle) STORING (MarketingBudget)">, done: true, error: <Google::Rpc::Status: code: 3, message: "Index AlbumsByAlbumTitle2 specifies nonexistent stored column MarketingBudget.", details: []>, response: nil>, @client=#<Google::Longrunning::OperationsClient:0x00561baa8d1de8 @operations_stub=#<Google::Longrunning::Operations::Stub:0x00561baa889cc8 @ch=#<GRPC::Core::Channel:0x00561baad8df30>, @host="spanner.googleapis.com:443", @propagate_mask=nil, @timeout=1969-12-31 15:59:59 -0800>, @get_operation=#<Proc:0x00561baa889728@path/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-gax-0.8.3/lib/google/gax/api_callable.rb:240>, @list_operations=#<Proc:0x00561baa8893b8@path/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-gax-0.8.3/lib/google/gax/api_callable.rb:240>, @cancel_operation=#<Proc:0x00561baa889278@path/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-gax-0.8.3/lib/google/gax/api_callable.rb:240>, @delete_operation=#<Proc:0x00561baa889138@path/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-gax-0.8.3/lib/google/gax/api_callable.rb:240>>, @call_options=nil, @result_type=Google::Protobuf::Empty, @metadata_type=Google::Spanner::Admin::Database::V1::UpdateDatabaseDdlMetadata, @callbacks=[]>, @service=Google::Cloud::Spanner::Service(spec-test-ruby-samples)>
```

**Comment by blowmage** [comment]
The job is done but that doesn't mean the job was successful. `job.error?` returns `true`, `job.error` returns the error information, and `job.database` will return `nil`.

Because the operation is asynchronous it us up to the user to handle this. @quartzmo has recently updated this in #1595, but I do not believe those changes are released yet. Are those documentation changes sufficient?

**Comment by frankyn** [comment]
Thanks @blowmage, this will help. As a follow-up request, would it be too extraneous to include the error handling on each sample where appropriate, because it may confuse developers not seeing that they need to handle errors in contrast to say Storage which raises errors instead?

**Comment by quartzmo** [comment]
@frankyn I'm thinking of closing this, since we do not show error handling as a rule in job examples. Are you ok with that?

**Comment by frankyn** [comment]
I'd still push to have one example handling the error. Is there more information why this is a rule?

**Comment by quartzmo** [comment]
@frankyn I am not aware of any special reason that we have rarely shown error handling in examples, I guess we've mostly just wanted to emphasize the happy path. However, I did find this `BigQuery::Job` example showing basic error handling:

```ruby
require "google/cloud/bigquery"

bigquery = Google::Cloud::Bigquery.new

job = bigquery.query_job "SELECT COUNT(word) as count FROM " \
                         "publicdata.samples.shakespeare"

job.wait_until_done!

if job.failed?
  puts job.error
else
  puts job.data.first
end
```

Personally I'm not opposed to updating many or most of the `Job` examples in BigQuery and Spanner to show this type of simple error handling, if it is acceptable. (Or something like: `log_error job.error`, for a bit more realism.) @blowmage what's your opinion?

**Comment by blowmage** [comment]
I generally prefer to keep the docs as-is, but that is not a strong opinion. I've found it is usually wise to defer to @quartzmo's instincts on these matters.

**Comment by quartzmo** [comment]
And I'll defer to @frankyn! There are currently about 20 examples across BigQuery and Spanner that test for `job.failed?` (BigQuery) or `job.error?` (Spanner; not sure why the method name is different). Would you recommend changing all of them to the `if/else` block above, or just a few?

**Comment by frankyn** [comment]
Referencing [#1595](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1595/files#diff-5d0eec9af06babe5b16d930b718321a4R38). I see an example of using `job.error?` without a conditional block was added in this PR, but I don't see it the current published docset for Spanner.

**Update to the original request**: Add a conditional example of handling errors similar to 
the BigQuery example, to the [top-level spanner example for visibility](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.44.0/google/cloud/spanner). I agree with not showing the error handling for all samples to emphasize on the "happy path". Although, at the moment I can't find documentation on the `job.error?` or `job.error` methods.
