### ISSUE TITLE
Support querying external data sources

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1628]
This feature is also known as "external tables." See [Querying External Data Sources](https://cloud.google.com/bigquery/external-data-sources) for requirements.

**Comment by danoscarmike** [comment]
Hi MIke, is this really P0?

**Comment by blowmage** [comment]
At standup on Monday I was told this was P0.

**Comment by quartzmo** [comment]
I believe that although this deliverable is P0 internally, it should be P1 on GitHub, similar to the other BigQuery "P0" issues that @geigerj changed to P1 some time ago (see log above.)

**Comment by blowmage** [comment]
Ah, that does seem familiar. I'll move it back.

**Comment by danoscarmike** [comment]
Thanks guys.  Yes, I think the BigQuery "P0" just means absolutely required for next release.  Issue label P0 means drop everything, the house is on fire :)

**Comment by quartzmo** [comment]
Closed by #1711 and #1725.
