### ISSUE TITLE
Add insert method that creates table if not found

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1635]
Add a new streaming insert method that calls `TableData.insertAll` and creates a destination table if the named table is not found.

Behavior: 

* Add `Dataset#insert`
* If insert does not find the table, try creating using exponential backoff with first delay >= 1m
* Retry insert, create table if failed, wait another minute, repeat

**Comment by quartzmo** [comment]
@blowmage 

> Is `Dataset#insert` the correct method?

Should this be an option on `Dataset#insert` or a new method? (And for either choice, what should the new option or method be named?)

**Comment by blowmage** [comment]
I think adding this functionality in `Dataset#insert` makes a lot more sense.

**Comment by blowmage** [comment]
When we've done this in other libraries we have used the `autocreate` method argument.

**Comment by quartzmo** [comment]
Well, this is embarrassing. It turns out that `Dataset#insert` doesn't exist. Should I add it, with this signature?

` def insert table, rows, skip_invalid: nil, ignore_unknown: nil, create: nil`

**Comment by blowmage** [comment]
Yes, please.

**Comment by quartzmo** [comment]
@tswast The suggestions for retry behavior (above) are a bit contradictory/fuzzy (emphasis mine):

They state: "try creating using **exponential** backoff with first delay >= 1m" and "if failed, wait **another minute**, repeat". Do you think the delay should start at 1 minute, double to 2 minutes, and then exponentially increase (4 min, 16 min...) with no limit? Any other ideas or guidance? Afaik, no other platform has implemented this yet.

**Comment by quartzmo** [comment]
@tswast While working on the PR for this issue, I think I discovered why the requirements ask for a retry backoff that begins with 1 min delay. My [initial approach during development](https://github.com/quartzmo/google-cloud-ruby/blob/8688a02516ff7672306d4da87f5ab626e9f2637b/google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb#L1161-L1169) was to retry the insert just 10 seconds after creating the missing table. The system test for this implementation consistently fails with `NotFoundError`. Even adding a single delay of 1 min consistently fails with this error, implying that only with a subsequent retry of several minutes is the method likely to finally succeed.

This failure to allow inserts for tables created "mid stream" is a known behavior of the service, as discussed in this [SO answer](https://stackoverflow.com/a/30406747/901096).

We believe a better approach is to [perform a lookup of the table before attempting the first insert](https://github.com/quartzmo/google-cloud-ruby/blob/bd3433da896c8e44602c30876061f53ee661ef25/google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb#L1153-L1161) (if automatic creation is desired). Is this acceptable?

**Comment by quartzmo** [comment]
@jskeet Do you have any knowledge of the reason for this requirement? (Specifically, to let insertAll fail on a missing table, then wait a minimum of 1 minute before creating the table and attempting insertAll again.)

**Comment by jskeet** [comment]
No, I haven't implemented this one yet, and was looking for more details myself. I would personally not want to create a delay of a whole minute automatically.

@jba may have more details.

**Comment by tswast** [comment]
The `tabledata.insertAll` 404 response is cached by the backend for 1m, so that indeed should be the minimum time before trying to insert the rows again.

The `table.insert` request should happen sooner than 1 minute, but at a random delay. The reason for a random delay is that the `table.insert` method is a low QPS method whereas `tabledata.insert` is a high QPS method, so there might be lots of workers trying to write data and we don't want them to overwhelm the `table.insert` method.

**Comment by quartzmo** [comment]
@tswast Thank you. A couple of questions:

1. What is the best sequence of delays for retrying `tabledata.insertAll`? Exponential delays starting at 1 min (1m, 2m, 4m, 16m, ...)? Or something like exponential starting at x seconds with an initial "base" delay of 1m (1m+1s, 1m+2s, 1m+4s, 1m+16s, ...)?

1. If the call to `table.insert` fails because the table has been created by another worker during the random delay, the operation proceeds to retrying `tabledata.insertAll`, correct?

**Comment by tswast** [comment]
Regarding (1) I'm asking for more clarification. The requirements that Jeremy wrote say "Retry insert, create table if failed, wait another minute, repeat" but also "Use exponential backoff with first delay >= 1m". Based on the email I got from him this morning, I think he may have meant to say random instead of exponential.

(2) Correct. If `table.insert` fails because it already exists, wait 1 minute and retry the the `tabledata.insertAll`

**Comment by quartzmo** [comment]
Closed by #1707.
