### ISSUE TITLE
Plugin system for experimental features

### ISSUE THREAD

**Issue by zedalaye** [GoogleCloudPlatform/google-cloud-ruby#1638]
Don't know if you care or already have ideas on this subject but I just found that and think you could be interrested in to build a plugin system and have toggleable experimental features :

https://twin.github.io/the-plugin-system-of-sequel-and-roda/

**Comment by quartzmo** [comment]
@zedalaye Thank you for this suggestion.

**Comment by quartzmo** [comment]
Closing for now since we are not going to implement this immediately. Appreciate the link though!

**Comment by blowmage** [comment]
We've definitely looked into it previously. There are design decisions that we have made that makes supporting a plugin system a challenge. Especially if we have multiple plugins trying to modify the same code that calls an API endpoint.
