### ISSUE TITLE
Support templateSuffix option in Tabledata.insertAll

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1692]
The `templateSuffix` option in [`Tabledata.insertAll`](https://cloud.google.com/bigquery/docs/reference/rest/v2/tabledata/insertAll) is currently marked `[Experimental]`, but should the [template tables](https://cloud.google.com/bigquery/streaming-data-into-bigquery#template-tables) feature be supported for Beta/GA?

See #1635 for another issue related to table creation while streaming data.

/cc @tswast

**Comment by tswast** [comment]
I'm checking with the backend folks. I need to figure out how template tables interact with writing to partitions.

**Comment by tswast** [comment]
Template tables are a low priority feature. Not required for GA by the client libraries. They are mostly obsolete now that tables can be partitioned.

**Comment by quartzmo** [comment]
Closing, based on the comment above that this feature is now mostly obsolete.
