### ISSUE TITLE
Please add a quick start to the Readme

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/google-cloud-ruby#1695]
Ideally I'd like a Rails Quick Start and a separate Rack Quick Start. @remi says there is specific support for Sinatra built in to this gem and calling that out would be helpful too.

**Comment by bobber205** [comment]
What's the Sinatra support?

**Comment by hxiong388** [comment]
The `google-cloud-error_reporting` gem under `stackdriver` gem has [code](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/8e93817078b9990a8ec1d6810bb82a7172161c8a/google-cloud-error_reporting/lib/google/cloud/error_reporting/middleware.rb#L77-L81) to capture and report exceptions from Sinatra even if Sinatra error handling mechanism is enabled.

As far as I remember, this is currently the only Sinatra specific support we have. @dazuma, am I missing any other Sinatra features?

**Comment by quartzmo** [comment]
@dazuma Do you want to take this issue?

**Comment by blowmage** [comment]
@dazuma This issue is falling outside of the SLO. Do you have an update on this?
