### ISSUE TITLE
Speech Api - Long Running Responses - How do you store the operation to come back later?

### ISSUE THREAD

**Issue by Carpela** [GoogleCloudPlatform/google-cloud-ruby#1700]
There doesn't seem an obvious way to store the operation via the id such that you can return to a long running response and get the results through the Ruby library. 
Am I missing something obvious? (I'm using v0.22.2 but have looked at the latest and while there's an 'id' method, there doesn't appear to be any way of using it). 

[so_question](https://stackoverflow.com/questions/45980266/save-google-cloud-speech-api-operationjob-object-to-retrieve-results-later/45983782#45983782)

**Comment by blowmage** [comment]
@Carpela If you upgrade to [google-cloud-speech 0.24.0](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-speech%2Fv0.24.0) or later you can use [`Operation#id`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-speech/latest/google/cloud/speech/operation?method=id-instance) and [`Project#operation`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-speech/latest/google/cloud/speech/project?method=operation-instance) to accomplish this.

```ruby
require "google/cloud/speech"

speech = Google::Cloud::Speech.new

audio = speech.audio "path/to/audio.raw",
                     encoding: :linear16,
                     language: "en-US",
                     sample_rate: 16000

op = audio.process
# get the operation's id
id = op.id #=> "1234567890"

# construct a new operation object from the id
op2 = speech.operation id

# verify the jobs are the same
op.id == op2.id #=> true

op2.done? #=> false
op2.wait_until_done!
op2.done? #=> true

results = op2.results
```
