### ISSUE TITLE
Add high-level (synchronous) BigQuery operations

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1720]
Add new high-level (synchronous) convenience methods that encapsulate waiting for a job to complete. These should be similar to `#query`, except that polling should use `jobs.get` instead of `jobs.getQueryResults`. The naming of the new methods should be consistent with the pairing of `#query` (high-level) and `#query_job` (low-level). The following methods should be added:

- [x] `#copy`
- [x] `#extract`
- [x] `#load`

Existing low-level methods with these names should be renamed with the `_job` suffix, for consistency as noted above.

**Comment by quartzmo** [comment]
I was originally thinking it would be ok for these methods to return `Job` subtypes, but in response to [your comment](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1722#pullrequestreview-62923233) on the PR, should they all simply return `true` if successful?

**Comment by blowmage** [comment]
I do. I think the "high level" methods should return `true`, and the "low level" methods return the job object.

**Comment by quartzmo** [comment]
Closed by #1722, #1726, #1730.
