### ISSUE TITLE
Deprecated parameters warning

### ISSUE THREAD

**Issue by G-Bianchi** [GoogleCloudPlatform/google-cloud-ruby#1723]
The `channel`, `chan_creds`, and `updater_proc` parameters will be removed on 2017/09/08

**Comment by blowmage** [comment]
Which gem?

**Comment by G-Bianchi** [comment]
Sorry, google-cloud-speech

**Comment by blowmage** [comment]
Thanks. I'll release an update to stop triggering the warning. Thanks for opening the issue!

**Comment by blowmage** [comment]
So apparently the version of the `googleapis-common-protos` gem that was released this week is raising that deprecation warning. We probably need to address this for all gems that use `Google::Longrunning::OperationsClient`.

**Comment by blowmage** [comment]
Right now it looks like Spanner and Speech are the only gems affected.

**Comment by blowmage** [comment]
Today all google-cloud-* gems were refreshed and released, and I've ensured that none of the gems raise warnings during their normal usage. Closing this issue as fixed. If you continue to see warnings, please open a new issue. Thank you for your contribution!
