### ISSUE TITLE
Batch-and-flush option for Dataset and Table #insert

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1736]
* Buffers rows on client for ~10s before sending.
* Option (or separate method.)
* Needs parameters to control batching.
* Needs mechanism to flush accumulated data when done streaming.
* See google-cloud-python for possible implementation.

**Comment by blowmage** [comment]
Does the create on insert behavior apply here as well? It would be unfortunate do have multiple batches attempt to create the table at the same time...

**Comment by blowmage** [comment]
@tswast ^

**Comment by quartzmo** [comment]
@tswast Do you know if any other platform has implemented this feature? I looked at google-cloud-python, but I didn't find it.

**Comment by tswast** [comment]
I know that Java doesn't have it and neither does Python (it was wrongly marked as done in the tracking spreadsheet).

Not sure about create-on-insert. I'll ping Jeremy in the requirements doc. My guess is the existing insert method would be used by the batching method and inherit the same behavior.

**Comment by blowmage** [comment]
I'll continue on the insert-only path I'm on for this then. Thanks!

**Comment by blowmage** [comment]
@tswast We have done a similar asynchonous batch publisher thing for Pub/Sub. They had three thresholds for publishing a batch:

1) How old the batch is (0.25 seconds)
2) How many messages the batch contains (1,000)
3) The total size of the batch (10MB)

Do you want users to be able to specify similar threshold amounts for the asynchronous batch BigQuery inserter? We had to set special GRPC headers to be able to make 10MB RPC calls to Pub/Sub, so I assume BigQuery has a different max size limit. Do you know what that is?

**Comment by tswast** [comment]
The limit is documented to be 10 MB for streaming insert. https://cloud.google.com/bigquery/quotas#streaminginserts

**Comment by blowmage** [comment]
Oh, that's excellent. There is a max of 10,000 rows per batch, but recommended 500. Perfect. Thanks!
