### ISSUE TITLE
Very slow and cpu intensive

### ISSUE THREAD

**Issue by brauliobo** [GoogleCloudPlatform/google-cloud-ruby#1740]
I'm running `UPDATE` queries with 20 threads that is enough to make the bigquery calls use 100% of one intel i7 6700hq core!

It seems the problem isn't related to bigquery itself but to the HTTP calls and likely authentication.

**Comment by brauliobo** [comment]
Confirmed the problem also with jruby and 10 threads

**Comment by blowmage** [comment]
How much data are you sending in each thread? Can you post some code to reproduce this?

**Comment by brauliobo** [comment]
Sorry, my mistake, it was another big loop in the code.
