### ISSUE TITLE
pubsub: streaming pull needs keepalive

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-ruby#1757]
With default configuration, streaming pull will hang if the stream is idle for a few minutes. This usually happens when the subscription has no more messages. In Go, we set gRPC keepalive to 5 minutes [(CL)](https://code-review.googlesource.com/#/c/gocloud/+/17070/). A similar option should be available in Ruby, though I'm not sure what the code to pass in the option looks like.

**Comment by blowmage** [comment]
@apolcyn Does the grpc ruby gem have a keepalive setting?

**Comment by apolcyn** [comment]
"channel args" can be passed down by passing the name/value of a channel arg in one of the ruby "channel" or "stub" constructors. [I believe this is the channel arg for specifying a keepalive](https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h#L218).

At the same time though, when you mention that the stream hangs in this scenario, this seems a little strange - attempting to read from a grpc ruby bidi stream should raise a `GRPC::Unavailable` exception if the remote endpoint is unreachable, rather than hang.....

**Comment by blowmage** [comment]
@geigerj Is this something we should set on the GRPC channel args? Or is this something that should be part of the GAPIC/GAX configuration?

**Comment by geigerj** [comment]
@blowmage You should set this on the gRPC channel args. However, the GAPIC doesn't currently provide an easy way to do that. (Currently, AFAICT, you'd have to construct the channel yourself and pass it to the GAPIC.) Temporarily re-assigning to myself to provide an a way to expose the gRPC channel arguments via a new hash-type parameter on the GAPIC client initializer.

**Comment by blowmage** [comment]
@geigerj We actually [already do set channel args on Pub/Sub](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb#L48-L51) to allow for messages larger than 4MB, so I imagine adding a new arg would be straightforward.

**Comment by geigerj** [comment]
@blowmage Ah, I see -- you're already constructing the channel yourself. In that case, let's just add a new arg.

Is this something we do frequently enough among other APIs that it might be useful for the client to accept an optional `channel_args` parameter directly?

**Comment by blowmage** [comment]
> is constructing the channel explicitly something we do frequently enough among other APIs that it might be useful for the client to accept an optional channel_args parameter directly?

Pub/Sub is the only service that needs this so far. But I do think that being able to specify these args is essential.

**Comment by pongad** [comment]
@apolcyn I don't completely understand the network world myself, but my current understanding is this.

To determine whether the connection is broken, we send some packet from client to server, with the expectation that the server should respond within some amount of time. If the server doesn't, we consider the connection "broken".

When a pubsub stream is idle (the client acked all messages it got and there's no more messages left), the server understandably never sends the client anything, and the client just sits there waiting for new messages with no expectation about when it might arrive. When a firewall sees that the connection has been idle for a long time and terminates it, neither the server nor the client notices.

With keepalive, we instruct the client to periodically (in our case 5 minutes) send a packet to the server, expecting it to respond soon (I think gRPC default is 20 sec). If the connection is still good, the server will respond back, the firewall will realize that the connection isn't idle, and everything should keep working. If the connection is bad (maybe you unplugged the ethernet cable), the server won't respond back, gRPC will realize it, and return back an error.

I'm sure I'm missing a lot of details, but to the best of my knowledge, that's "kind of sort of approximately accurate" description.

**Comment by apolcyn** [comment]
ok, I believe that this case in which the connection breaks silently is a valid use, thanks for the info. I am not sure atm if there is a lower bound for these keepalive times though, will double check that...

**Comment by blowmage** [comment]
@apolcyn In addition to setting `grpc.keepalive_time_ms`, should we also set values for `grpc.keepalive_timeout_ms` and `grpc.keepalive_permit_without_calls`?

**Comment by pongad** [comment]
@blowmage FWIW, at least for Go, we thought the defaults are reasonable. I believe the timeout is 20s which should definitely be long enough.

**Comment by apolcyn** [comment]
```
@blowmage FWIW, at least for Go, we thought the defaults are reasonable. I believe the timeout is 20s which should definitely be long enough.
```

+1

we should keep `keepalive_timeout_ms` should be ok at it's default. `keepalive_permit_without_calls` should also be left alone (that will allow sending pings when there are no active calls, but that shouldn't be needed since it looks like there is a always an outstanding RPC when we are interested in ping behavior in here).
