### ISSUE TITLE
Video Intelligence API docs say it is alpha, not beta

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/google-cloud-ruby#1764]
http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-video_intelligence/v0.23.0/google/cloud/videointelligence

Says alpha, not beta at the top.

**Comment by quartzmo** [comment]
@geigerj This is in the generated files at [video_intelligence.rb#L23](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-video_intelligence/lib/google/cloud/video_intelligence.rb#L23) and [overview.rb#L20](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/overview.rb#L20), as well as in `v1beta1.rb` and `v1beta2.rb`. Should you take this one?

**Comment by geigerj** [comment]
Yup, I'll take this one.

**Comment by blowmage** [comment]
@geigerj These generated files still say "Alpha". Should we manually update them to "Beta"?

**Comment by geigerj** [comment]
@blowmage Yes, please.
