### ISSUE TITLE
[Spanner] Ambiguous documentation with using staleness reads

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1782]
While using the staleness parameter with `Google::Cloud::Spanner::Client#snapshot`, I found the [documentation](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.44.0/google/cloud/spanner/client?method=snapshot-instance) confusing on what a Numerical value could be for this staleness parameter. 

After reviewing the code, I found that the value provided to the staleness parameter is [converted](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/service.rb#L345) into a Protobuf Duration object using [`Google::Cloud::Spanner::Convert#number_to_duration`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/convert.rb#L212). 

Based on implementation I'm expecting that a Float value will be converted to seconds and nanoseconds. This should be documented with values or explain how values are interpreted, because cloud.google.com [documentation](https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.v1#readonly) defines this parameter to be of Protobuf Duration object which can't be used to define this parameter at this time.

**Comment by blowmage** [comment]
Can you suggest revised wording that add the clarification you are seeking?

**Comment by frankyn** [comment]
Current documentation:

> "Executes all reads at a timestamp that is +staleness+ old. The timestamp is chosen soon after the read is started.
> Guarantees that all writes that have committed more than the specified number of seconds ago are visible. Because Cloud Spanner chooses the exact timestamp, this mode works even if the client’s local clock is substantially skewed from Cloud Spanner commit timestamps.
> 
> Useful for reading at nearby replicas without the distributed timestamp negotiation overhead of single-use +staleness+."

Suggested documentation:

> "Executes all reads at a timestamp that is +staleness+ old determined by a `Float`. For example
> the number `10.1` is translated to `10` seconds and `1` nanosecond.
> 
> Guarantees that all writes that have committed more than the specified number of seconds ago are visible. Because Cloud Spanner chooses the exact timestamp, this mode works even if the client’s local clock is substantially skewed from Cloud Spanner commit timestamps.
> 
> Useful for reading at nearby replicas without the distributed timestamp negotiation overhead of single-use +staleness+."

**Comment by blowmage** [comment]
K, I'll submit a PR to update the docs with your description, but I'll correct some of the specifics. For example, the value doesn't have to be a Float, it can be any Numeric, including Integer, Float, BigDecimal, or Rational. And 10.1 is 10 seconds and 100,000,000 nanoseconds (or 100 milliseconds). :)

**Comment by frankyn** [comment]
Ah, misunderstood that translation! Thanks for the clarity 👍
