### ISSUE TITLE
Support `skip_lookup` for Dataset and Table

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1785]
Support the `skip_lookup` argument for Dataset and Table object creation.

**Comment by quartzmo** [comment]
Will this become the preferred approach for operations that do not involve dataset or table metadata/management? So that with `Table#insert`, for example, after this change, should the example be the following?

```ruby
dataset = bigquery.dataset "my_dataset", skip_lookup: true
table = dataset.table "my_table", skip_lookup: true

rows = [
  { "first_name" => "Alice", "age" => 21 },
  { "first_name" => "Bob", "age" => 22 }
]
table.insert rows

**Comment by blowmage** [comment]
My opinion is the main code example should show the default behavior which is to perform the lookup, but should also have additional named code examples that show skipping the lookup. Similar to how main code example for [Pub/Sub's `Project#topic`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-pubsub/latest/google/cloud/pubsub/project?method=topic-instance) shows the lookup, but an additional named code example shows the `skip_lookup` option.
