### ISSUE TITLE
Improve AsyncInserter error handling

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1787]
Currently, only row-level errors are exposed by the batching for streaming data provided by `AsyncInserter`. Because `AsyncInserter` uses a background thread, any top-level error returned by `TableData.insertAll` will not be raised in the main thread. Here is the example (which should probably be updated to show error handling):

```ruby
dataset = bigquery.dataset "my_dataset"
table = dataset.table "my_table"
inserter = table.insert_async do |response|
  log_insert "inserted #{response.insert_count} rows " \
    "with #{response.error_count} errors"
end

rows = [
  { "first_name" => "Alice", "age" => 21 },
  { "first_name" => "Bob", "age" => 22 }
]
inserter.insert rows

inserter.stop.wait!
```

`AsyncInserter` needs to somehow expose RPC errors in the callback provided to `Table#insert_async`.

**Comment by blowmage** [comment]
This will become even more important when BigQuery objects support the `skip_lookup` optional argument.

**Comment by quartzmo** [comment]
@blowmage I was thinking this should be done before #1785, what do you think?

**Comment by blowmage** [comment]
I think it could be done before. Or both changes could be made in the same pull request.
