### ISSUE TITLE
Add "round-trip" acceptance test for requester_pays and user_project

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1788]
We need to add a test or tests demonstrating the interaction between setting the `Bucket#requester_pays` property and the `user_project` option (available on multiple methods). This will involve using a second project.

Some questions:

1. How should the second project be configured? In environment variables? Should the tests be conditional to only run if the second project is configured, or should they fail if the second project is not configured?
1. Should the tests cover every API method supporting `user_project`, or just a subset? (There are a lot... most if not all methods support `user_project`.)

**Comment by blowmage** [comment]
IMO the tests should check for specific environment variables and only run the tests if those env vars are present. I don’t think we need to have acceptance tests every method, but we should test most of them.
