### ISSUE TITLE
Expose error details when converting Google::Gax::GaxError to Google::Cloud::Error

### ISSUE THREAD

**Issue by qingling128** [GoogleCloudPlatform/google-cloud-ruby#1791]
When `Google::Gax::GaxError` gets converted to `Google::Cloud::Error`, it does not expose the error details to extract `partial_success` info.

When calling `Google::Cloud::Logging::V2::LoggingServiceV2Client.write_log_entries` directly, we get a `Google::Gax::GaxError` with `partial_success` info.

```ruby
cat write_log_entries.rb
require "google/api/monitored_resource_pb"
require "google/cloud/logging/v2"
require "google/logging/v2/log_entry_pb"
require "google/gax"

LoggingClient = Google::Cloud::Logging::V2::LoggingServiceV2Client
logging_client = LoggingClient.new
entries = [
  Google::Logging::V2::LogEntry.new(
    {
      log_name: 'projects/gapic-test/logs/my-log',
      resource: Google::Api::MonitoredResource.new({type: 'gce_instance'}),
      text_payload: 'pass'
    }),
  Google::Logging::V2::LogEntry.new(
    {
      log_name: 'projects/gapic-test/logs/bad:log',
      resource: Google::Api::MonitoredResource.new({type: 'gce_instance'}),
      text_payload: 'fail'
    }),
]

begin
  logging_client.write_log_entries(
    entries,
    log_name: 'projects/gapic-test/logs/my-log',
    resource: Google::Api::MonitoredResource.new(
      type: 'gce_instance',
      labels: {}
    ),
    labels: {},
    partial_success: true
  )
rescue => error
  puts "error:\n#{error.inspect}\n"
  puts "error details:\n#{error.details[0].log_entry_errors.inspect}\n"
end
```

```
$ ruby write_log_entries.rb
error:
#<Google::Gax::RetryError: GaxError Exception occurred in retry method that was not classified as transient, caused by 7:User not authorized.>
error details:
{
    0=><Google::Rpc::Status: code: 7, message: "User not authorized.", details: []>,
    1=><Google::Rpc::Status: code: 3, message: "Log name contains illegal character :", details: []>
}
```

However, if we follow the official instruction at https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-logging/README.md to use the write_entries function.

```
$ cat cleaner_way.rb
require "google/cloud/logging"

logging = Google::Cloud::Logging.new
entries = [
  logging.entry(
    payload: "Job started.",
    log_name: "my_app_log",
    resource: logging.resource("gce_instance", {
       instance_id: "1294753745",
       zone: "20150925t173233"
    })
  ),
  logging.entry(
    payload: "Job started.",
    log_name: "bad:log",
    resource: logging.resource("gce_instance", {
       instance_id: "1294753745",
       zone: "20150925t173233"
    })
  )
]

begin
  logging.write_entries entries, partial_success: true
rescue => err
  puts err.inspect
  puts err.instance_variables.inspect
end
```

```
$ ruby cleaner_way.rb
#<Google::Cloud::InvalidArgumentError: 3:Log name contains illegal character :>
[]
```

Looking at the code that converts the error:
```ruby
        def execute
          yield
        rescue Google::Gax::GaxError => e
          # GaxError wraps BadStatus, but exposes it as #cause
          raise Google::Cloud::Error.from_error(e.cause)
        end
```
Seems we are not exposing `error.details`.

How should this be exposed? I can submit a PR if we can agree on the expected behavior.

Also, is it recommended to use `Google::Cloud::Logging::V2::LoggingServiceV2Client.write_log_entries` directly?

**Comment by qingling128** [comment]
BTW, I was testing this with a gem I built from this PR (Add partial_success in write_entries method: https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1790)

**Comment by qingling128** [comment]
Hi @blowmage - I'm not sure if it's recommended to use `Google::Cloud::Logging::V2::LoggingServiceV2Client.write_log_entries` directly. But that workaround works for us. I'm happy to switch to `write_entries` when it exposes the error. Before that we can live with the workaround (using `Google::Cloud::Logging::V2::LoggingServiceV2Client.write_log_entries` directly. So I won't deem this very urgent.

**Comment by blowmage** [comment]
We are working on a fix for this, but you can always get the inner GaxError using [`Error#cause`](https://ruby-doc.org/core-2.4.2/Exception.html#method-i-cause).

**Comment by blowmage** [comment]
[Logging 1.3.0](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-logging%2Fv1.3.0) was released today and updates the google-gax dependency to `~> 0.10.1`. 

In previous versions of google-gax you were using `GaxError#details` to access this information. However, this method has been renamed to `GaxError#status_details` starting in version 0.10.0. Similarly, you can access this value through `Google::Cloud::Error#status_details` starting with this release. Please update your code accordingly. Thank you for your contribution!
