### ISSUE TITLE
PubSub StreamingPull example doesn't work

### ISSUE THREAD

**Issue by rxbynerd** [GoogleCloudPlatform/google-cloud-ruby#1795]
:wave:

[The example code for StreamingPull](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb#L743) doesn't produce any output with Ruby 2.4.2 and google-cloud-pubsub 0.27.2.

The exact script I'm running:

```ruby
require "logger"
require "google/cloud/pubsub/v1/subscriber_client"

LOGGER = Logger.new(STDOUT)

module GRPC
  def self.logger
    LOGGER
  end
end

StreamingPullRequest = Google::Pubsub::V1::StreamingPullRequest
SubscriberClient = Google::Cloud::Pubsub::V1::SubscriberClient

subscriber_client = SubscriberClient.new
formatted_subscription = SubscriberClient.subscription_path("rubynerd-net", "testing")
stream_ack_deadline_seconds = 30
request = StreamingPullRequest.new
request.subscription = formatted_subscription
request.stream_ack_deadline_seconds = stream_ack_deadline_seconds
requests = [request]
subscriber_client.streaming_pull(requests).each do |element|
  # Process element.
  puts element
end
```

This is an amalgamation of the example from the `SubscriberClient` docs, and the recommended way of pulling debug logs out of gRPC.

The output:

```
D, [2017-10-29T23:03:23.570283 #14191] DEBUG -- : calling pubsub.googleapis.com:443:/google.pubsub.v1.Subscriber/StreamingPull
D, [2017-10-29T23:03:23.937198 #14191] DEBUG -- : bidi-read-loop: starting
D, [2017-10-29T23:03:23.937259 #14191] DEBUG -- : bidi-read-loop: 0
D, [2017-10-29T23:03:23.937314 #14191] DEBUG -- : bidi-write-loop: starting
D, [2017-10-29T23:03:23.937355 #14191] DEBUG -- : bidi-write-loop: 0
D, [2017-10-29T23:03:23.937504 #14191] DEBUG -- : bidi-write-loop: 1 writes done
D, [2017-10-29T23:03:23.937542 #14191] DEBUG -- : bidi-write-loop: client sent 1, waiting
D, [2017-10-29T23:03:23.937620 #14191] DEBUG -- : bidi-write-loop: done
D, [2017-10-29T23:03:23.937653 #14191] DEBUG -- : bidi-write-loop: finished
D, [2017-10-29T23:03:24.269365 #14191] DEBUG -- : bidi-read-loop: null batch #<struct Struct::BatchResult send_message=nil, send_metadata=nil, send_close=nil, send_status=nil, message=nil, metadata={"date"=>"Sun, 29 Oct 2017 23:03:24 GMT", "alt-svc"=>"quic=\":443\"; ma=2592000; v=\"41,39,38,37,35\""}, status=nil, cancelled=nil>
D, [2017-10-29T23:03:24.269493 #14191] DEBUG -- : bidi-read-loop: done status #<struct Struct::Status code=0, details="", metadata={}>
D, [2017-10-29T23:03:24.269522 #14191] DEBUG -- : bidi-read-loop: done reading!
D, [2017-10-29T23:03:24.269545 #14191] DEBUG -- : bidi-read-loop: finished
```

[The equivalent Python sample code](https://cloud.google.com/pubsub/docs/pull#pubsub-pull-messages-async-python) works correctly, and correctly streams responses from Google Cloud.

Fully aware this is marked as experimental in the source code, and this is a risk I'm aware of, but if Python can at least have working sample code, I don't see why Ruby shouldn't. Additionally, as the documentation recommends, I've emailed `cloud-pubsub@google.com`, but I haven't received a response.

Happy to assist in any way I can, but because my experience with Python is very limited, I'm struggling to reverse-engineer the Python implementation to figure out the differences, and therefore why Python works and Ruby doesn't.

**Comment by rxbynerd** [comment]
Not confident this is a problem with the library, rather gRPC, as my reimplementation has the same issue:

```ruby
require "pry"
require "logger"
require "googleauth"
require "google/cloud/pubsub/v1/subscriber_client"
require "google/pubsub/v1/pubsub_pb"
require "google/pubsub/v1/pubsub_services_pb"

LOGGER = Logger.new STDOUT

module GRPC
  def self.logger
    LOGGER
  end
end

scopes = %w{https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/pubsub}

auth_creds = Google::Auth.get_application_default(scopes)
updater_proc = auth_creds.updater_proc
call_creds = GRPC::Core::CallCredentials.new(updater_proc)
chan_creds = GRPC::Core::ChannelCredentials.new.compose(call_creds)

stub = Google::Pubsub::V1::Subscriber::Stub.new("pubsub.googleapis.com:443", chan_creds)

streaming_pulls = [Google::Pubsub::V1::StreamingPullRequest.new(subscription: Google::Cloud::Pubsub::V1::SubscriberClient.subscription_path('rubynerd-net', 'testing'), stream_ack_deadline_seconds: 10)]

stub.streaming_pull(streaming_pulls.each).each do |response|
  puts response
  binding.pry
end

binding.pry
```

**Comment by blowmage** [comment]
I have run some tests and can confirm that using an Array's `each` Enumerator does not seem to work. I agree this looks to be a gRPC issue, and not something specific to the Google Cloud libraries, or the GAPIC/Gax code.

FWIW, the Google Cloud libraries do not pass an Array's `each` Enumerator to gRPC, but use a version of EnumeratorQueue as described in the [gRPC documentation](https://grpc.io/docs/tutorials/basic/ruby.html). Here is a simple implementation:

```ruby
require "queue"

class EnumeratorQueue
  def initialize sentinel = nil
    @queue    = Queue.new
    @sentinel = sentinel
  end

  def push obj
    @queue.push obj
  end

  def each
    return enum_for(:each) unless block_given?

    loop do
      obj = @queue.pop
      break if obj.equal? @sentinel
      yield obj
    end
  end
end
```

Using this class, the original code with the following changes does work for me:

```ruby
request_queue = EnumeratorQueue.new
request_queue.push request
subscriber_client.streaming_pull(request_queue.each).each do |element|
  # Process element.
  puts element
end
```

**Comment by blowmage** [comment]
I have a working theory, but this is just a theory. It looks like gRPC is keeping the stream open as long as the Enumerator provided to the streaming method is blocking. As soon as the Enumerator ends the stream is closed. This is why using an Array's Enumerator is not showing output, because the stream is closed as soon as the Enumerator is done, which is pretty much instantaneous. For Google Cloud libs, the EnumeratorQueue's Enumerator is blocked until there is a new value is added to the queue. And only when the sentinel is passed in does the Enumerator end.

@apolcyn does this seem right to you?

**Comment by rxbynerd** [comment]
Confirmed this a bug upstream, and using `EnumeratorQueue` in place of `Array#each` works for Cloud Pub/Sub.

Thank you @blowmage, I'll look to get a PR for the docs up soon, and feed this upstream to gRPC.

**Comment by rxbynerd** [comment]
Ah sorry, closed this issue before seeing your response! Happy to re-open if you want to keep it tracked here?

**Comment by apolcyn** [comment]
@blowmage in the general case, the stream/RPC will stay open until both the sender's enumerator/stream has been sent, and the receiving end has indicated it's end-of-stream (by sending a status).

Not sure what the problem is right away, will need to take a closer look

**Comment by blowmage** [comment]
@apolcyn thanks for the update! Looking forward to hearing what you find.
