### ISSUE TITLE
Update Datastore GAPIC for TransactionOptions

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1796]
The official googleapi Datastore protos now [support TransactionOptions](https://github.com/googleapis/googleapis/blob/master/google/datastore/v1/datastore.proto#L347-L373). Can we get updated Datastore GAPIC generated files?

**Comment by blowmage** [comment]
@geigerj Is this something you can take?

**Comment by quartzmo** [comment]
@geigerj Any ETA on this?

**Comment by blowmage** [comment]
I believe this is included in #1804.

**Comment by quartzmo** [comment]
You're correct, [class TransactionOptions is included](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1804/commits/5157b08d49b4019ca83c7379fd562e401a1be619#diff-207f52728246f84e330393c58608d8b0R280) in #1804. Thanks @blowmage!

**Comment by geigerj** [comment]
Fixed by #1804.
