### ISSUE TITLE
New release for google-cloud-logging

### ISSUE THREAD

**Issue by qingling128** [GoogleCloudPlatform/google-cloud-ruby#1799]
Can we do a new release for `google-cloud-logging` to pick up this commit below?

Update google-gax dependency
The latest partial success support requires some changes that were added in google-gax 0.8.11.
https://github.com/GoogleCloudPlatform/google-cloud-ruby/commit/bc749e871757d9e0634b01935dc5039db850fe27#diff-43e7ec6ea7110b556828ce59bd21fd0c

Right now only `google-gax` `v0.8.10` gets installed when we install `google-cloud-logging` `v1.2.3`.

**Comment by blowmage** [comment]
The current release google-cloud-logging has a dependency on google-gax set as `~> 0.8.0`. There is no reason why google-gax 0.8.12 cannot be installed and used with it. However, google-gax 0.8.11 was yanked, and so will not be able to be installed or used.

I am not in favor of making a release right now. We are expecting a new google-gax 0.9.0 release any day that will bring updated dependencies on grpc 1.7.1 and googleauth 0.6.0. When that happens, we will release new versions of every gem, including all unreleased changes that are already merged into master.

**Comment by blowmage** [comment]
Canyon verify the code you are expecting to be in google-gax 0.8.11 is also in google-gax 0.8.12?

**Comment by qingling128** [comment]
Yes, I've verified that. We can pin the `google-gax` at `0.8.12` separately as a workaround for now. When `google-gax 0.9.0` get released and there is a new `google-cloud-logging` is released, we will update accordingly.

**Comment by geigerj** [comment]
GAX 0.9.0 depends on gRPC 1.7.1, which has a bug that drops support for Ruby 2.0. @apolcyn is working on a gRPC patch release, after which I'll release GAX.

**Comment by qingling128** [comment]
@geigerj - Thanks for the heads up!

Seems `GAX 0.8.12` also depends on `gRPC 1.7.1`. For our case, we don't really support `Ruby 2.0`. So the workaround should work for us for now. We'll stay tuned. But take you time. :D

**Comment by geigerj** [comment]
Sounds good. (`GAX 0.8.12` depends on `gRPC ~> 1.6.6` so it should work with Ruby 2.0.)

**Comment by apolcyn** [comment]
grpc 1.7.2 was just released btw, which fixes the ruby 2.0 breakage.

**Comment by quartzmo** [comment]
@qingling128 Can we close this issue?

**Comment by qingling128** [comment]
@quartzmo - Seems we are still waiting for a `google-cloud-logging` release to go out?

**Comment by quartzmo** [comment]
@qingling128 You're right, somehow your changes were never released. I'm sorry about that. #1804 is likely to be merged soon and [will update GAX to `0.9.0`](https://github.com/geigerj/google-cloud-ruby/blob/4440f5e74f9ba66f3a4c137511eb120117a250d5/google-cloud-logging/google-cloud-logging.gemspec#L23). A release with GAX at `0.9.0` should also resolve this issue, correct?

**Comment by blowmage** [comment]
[Logging 1.3.0](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-logging%2Fv1.3.0) was released today and includes updated dependencies. So I'm closing this issue. If you have any other concerns or requests please open a new issue. Thank you for your contribution!
