### ISSUE TITLE
Support Datastore reserve_ids

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1812]
The recent PR #1804 updated the Datastore GAPIC/Protobuf code and added a new API call `reserve_ids`. Should this be supported in the high-level Ruby API?

**Comment by quartzmo** [comment]
Moving to [wiki/Feature-backlog](https://github.com/GoogleCloudPlatform/google-cloud-ruby/wiki/Feature-backlog) since this request is now more than 180 days old.

**Comment by quartzmo** [comment]
I forgot to close this after moving to Feature Backlog. Closing now.
