### ISSUE TITLE
New Natural Language features

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1813]
The recent PR #1804 updated the Natural Language GAPIC/Protobuf code and added the following:

* `LanguageServiceClient.analyze_entity_sentiment`
* `LanguageServiceClient.classify_text`
* `Features.extract_entity_sentiment`
* `Features.classify_text` 
* `EntityMention#sentiment`
* `AnnotateTextResponse.categories` (and `ClassificationCategory`)

Should these be supported in the high-level Ruby API?

**Comment by geigerj** [comment]
No, the high-level API will be replaced by a GAPIC in a subsequent release.

**Comment by quartzmo** [comment]
Closing per @geigerj's answer.
