### ISSUE TITLE
Support Logging Exclusions

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1814]
The recent PR #1804 updated the Logging GAPIC/Protobuf code and added a new resource and API calls for exclusions. Should exclusions be supported in the high-level Ruby API?

The PR also added the following new values to existing resources:

* `HttpRequest#protocol`
* `LogEntry#receive_timestamp`

**Comment by quartzmo** [comment]
Moving to [wiki/Feature-backlog](https://github.com/GoogleCloudPlatform/google-cloud-ruby/wiki/Feature-backlog) since this request is now more than 180 days old.
