### ISSUE TITLE
Updated Pub/Sub Snapshot features

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1816]
The recent PR #1804 updated the Pub/Sub GAPIC/Protobuf code and added `Snapshot#labels` as well as a new API call to update Snapshot. Should these be supported in the high-level Ruby API?

**Comment by quartzmo** [comment]
Moving to [wiki/Feature-backlog](https://github.com/GoogleCloudPlatform/google-cloud-ruby/wiki/Feature-backlog) since this request is now more than 180 days old.
