### ISSUE TITLE
Updated Spanner features

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1817]
The recent PR #1804 updated the Spanner GAPIC/Protobuf code and a new API call to list sessions. Should these be supported in the high-level Ruby API, even though we don't expose Session currently?

The following attributes were also added to the Session resource:

* `Session#labels`
* `Session#create_time`
* `Session#approximate_last_use_time`

**Comment by vkedia** [comment]
We don't need to support list sessions, unless someone asks for it.
But we do need to support Session#labels. They way to support it would be to take in a map of labels as a configuration to session pool. All sessions created in that pool would be assigned to that label.
This is how I am doing it in Java:
https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2606
