### ISSUE TITLE
Verification fails incorrectly on gzipped file

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1835]
This general issue was first reported in GoogleCloudPlatform/google-cloud-dotnet#1641. Thank you @jskeet for bringing this to our attention!

The problem appears to be that the client library is decompressing the gzipped content before verification, with the result that`File::Verifier`  is comparing a hash of the uncompressed data against the hash of the compressed data that is returned by the service in the file's metadata.

### Steps to reproduce

The public test file `gs://storage-library-test-bucket/gzipped-text.txt` contains "hello world" compressed with gzip.

1. Download the file with `verify: :none` and read its contents. Observe that the contents are "hello world".
1. Download the file with default (`:md5`) verification. Observe that verification fails.
1. Download the file with `verify: :crc32c`. Observe that verification fails.

```sh
irb(main):017:0> bucket = storage.bucket "storage-library-test-bucket"
=> #<Google::Cloud::Storage::Bucket:0x007fa3f08dae28 @service=Google::Cloud::Storage::Service(bustling-kayak-91516), @gapi=#<Google::Apis::StorageV1::Bucket:0x007fa3f08cb270 @etag="CAI=", @id="storage-library-test-bucket", @kind="storage#bucket", @location="US", @metageneration=2, @name="storage-library-test-bucket", @project_number=149776848335, @self_link="https://www.googleapis.com/storage/v1/b/storage-library-test-bucket", @storage_class="MULTI_REGIONAL", @time_created=#<DateTime: 2017-03-24T19:51:28+00:00 ((2457837j,71488s,197000000n),+0s,2299161j)>, @updated=#<DateTime: 2017-03-27T07:09:43+00:00 ((2457840j,25783s,574000000n),+0s,2299161j)>>, @user_project=nil>
irb(main):018:0> file = bucket.file "gzipped-text.txt"
=> #<Google::Cloud::Storage::File:0x007fa3f10cea30 @service=Google::Cloud::Storage::Service(bustling-kayak-91516), @gapi=#<Google::Apis::StorageV1::Object:0x007fa3ec1b9490 @bucket="storage-library-test-bucket", @content_type="text/plain", @crc32c="T1s5RQ==", @etag="CMz2oI+RvtcCEAI=", @generation=1510664852486988, @id="storage-library-test-bucket/gzipped-text.txt/1510664852486988", @kind="storage#object", @md5_hash="xhF4M6pNFRDQnvaRRNVnkA==", @media_link="https://www.googleapis.com/download/storage/v1/b/storage-library-test-bucket/o/gzipped-text.txt?generation=1510664852486988&alt=media", @metageneration=2, @name="gzipped-text.txt", @self_link="https://www.googleapis.com/storage/v1/b/storage-library-test-bucket/o/gzipped-text.txt", @size=31, @storage_class="MULTI_REGIONAL", @time_created=#<DateTime: 2017-11-14T13:07:32+00:00 ((2458072j,47252s,185000000n),+0s,2299161j)>, @time_storage_class_updated=#<DateTime: 2017-11-14T13:07:32+00:00 ((2458072j,47252s,185000000n),+0s,2299161j)>, @updated=#<DateTime: 2017-11-14T13:08:29+00:00 ((2458072j,47309s,671000000n),+0s,2299161j)>, @content_encoding="gzip">, @user_project=nil>
irb(main):019:0> io = file.download verify: :none
=> #<StringIO:0x007fa3f08fec10>
irb(main):020:0> io.string
=> "hello world"
irb(main):021:0> io = file.download
Google::Cloud::Storage::FileVerificationError: The downloaded file failed MD5 verification.
	from /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-storage/lib/google/cloud/storage/file/verifier.rb:34:in `verify_md5!'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-storage/lib/google/cloud/storage/file.rb:1081:in `verify_file!'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-storage/lib/google/cloud/storage/file.rb:498:in `download'
	from (irb):21
irb(main):022:0> io = file.download verify: :crc32c
Google::Cloud::Storage::FileVerificationError: The downloaded file failed CRC32c verification.
	from /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-storage/lib/google/cloud/storage/file/verifier.rb:42:in `verify_crc32c!'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-storage/lib/google/cloud/storage/file.rb:1082:in `verify_file!'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-storage/lib/google/cloud/storage/file.rb:498:in `download'
	from (irb):22
```

Background: Google Cloud Storage [Transcoding of gzip-compressed files](https://cloud.google.com/storage/docs/transcoding).

**Comment by blowmage** [comment]
This has been previously discussed in #1360

**Comment by quartzmo** [comment]
google-cloud-node has a [solution](https://github.com/googleapis/nodejs-storage/blob/05fa3f709e80b5c4228a47ca049838b13d413861/src/file.js#L509) in which the hash is computed before decompression, and a supporting [system test](https://github.com/googleapis/nodejs-storage/blob/05fa3f709e80b5c4228a47ca049838b13d413861/system-test/storage.js#L1540).

**Comment by quartzmo** [comment]
@blowmage Thanks for linking the previous issue.

**Comment by quartzmo** [comment]
I'm attempting to apply the google-cloud-node solution (decompress after computing the verification hash), but I think I'm blocked by the `transparent_gzip_decompression = true` called on the `HTTPClient` instance in [this line](https://github.com/google/google-api-ruby-client/blob/0.17.1/lib/google/apis/core/base_service.rb#L403) in google-api-ruby-client.

**Comment by quartzmo** [comment]
See also: https://cloud.google.com/storage/docs/transcoding

**Comment by quartzmo** [comment]
I tried re-compressing the file content on the client, but it doesn't seem to produce the correct hash:

```ruby
          if gzip
                ::File.open(Pathname(local_file).to_path, "rb") do |f|
                  wio = StringIO.new("w")
                  w_gz = Zlib::GzipWriter.new(wio)
                  w_gz.write(f.read)
                  w_gz.close
                  ::Digest::MD5.base64digest wio.string
                end
              else
         ...
```

```sh
gcloud_digest: xhF4M6pNFRDQnvaRRNVnkA==
local_digest: DyIxtHwRqXcPOv8TvLpERA==
```

**Comment by jskeet** [comment]
Recompressing could work in some cases, but only if you happen to recompress to the same form. There's no canonical compressed form, unfortunately.

**Comment by quartzmo** [comment]
Thanks @jskeet, I'll drop that idea.

**Comment by quartzmo** [comment]
The question came up offline if this client should decompress file data with a `Content-Type` of `application/gzip`.

And the answer is that for a `Content-Encoding` of `gzip`, it's reasonable for us to decompress. If the `Content-Type` is `application/gzip` instead, then we  shouldn't be decompressing it.
