### ISSUE TITLE
Ruby syntax error in Google::Cloud::Monitoring::Credentials prevents auth

### ISSUE THREAD

**Issue by jrun** [GoogleCloudPlatform/google-cloud-ruby#1837]
These two word lists defined in `Google::Cloud::Monitoring::Credentials` shouldn't be delimited by commas. I discovered this issue because `Google::Cloud::Monitoring::Credentials.default` fails.

```ruby
PATH_ENV_VARS = %w(MONITORING_KEYFILE, GOOGLE_CLOUD_KEYFILE, GCLOUD_KEYFILE)
JSON_ENV_VARS = %w(MONITORING_KEYFILE_JSON, GOOGLE_CLOUD_KEYFILE_JSON, GCLOUD_KEYFILE_JSON)
```

These libraries have the issue:

* bigtable (`bigtable/credentials.rb` and `bigtable/admin/credentials.rb`)
* language
* monitoring
* video_intelligence
* spanner (`spanner/admin/database/credentials.rb` and `spanner/admin/instance/credentials.rb`)

**Comment by blowmage** [comment]
Thank you for opening this issue. I can confirm this is indeed an issue. I am updating these libraries now and will be deploying new versions for all of them very soon.

All of these files were created through code generation, and we will follow up with that process and ensure that these files are generated correctly and properly tested.

**Comment by blowmage** [comment]
This has been corrected in the following releases:

* [Natural Language 0.28.1](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-language%2Fv0.28.1)
* [Monitoring 0.26.1](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-monitoring%2Fv0.26.1)
* [Spanner 1.1.1](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-spanner%2Fv1.1.1)
* [Video Intelligence 0.24.1](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-video_intelligence%2Fv0.24.1)

Previously the env var names would include `","`:

```ruby
require "google/cloud/monitoring/credentials"

Google::Cloud::Monitoring::Credentials::PATH_ENV_VARS
#=> ["MONITORING_KEYFILE,", "GOOGLE_CLOUD_KEYFILE,", "GCLOUD_KEYFILE"]
```

But the new releases correct this:

```ruby
require "google/cloud/monitoring/credentials"

Google::Cloud::Monitoring::Credentials::PATH_ENV_VARS
#=> ["MONITORING_KEYFILE", "GOOGLE_CLOUD_KEYFILE", "GCLOUD_KEYFILE"]
```

**Comment by blowmage** [comment]
@jrun Thanks for your contribution!

**Comment by blowmage** [comment]
@geigerj FYI.

**Comment by geigerj** [comment]
Thank you @jrun for the report, and @blowmage for the prompt fix and release. I've filed a PR in the code generator to fix this, and an issue to add test coverage for these files.
