### ISSUE TITLE
Datastore 1.2.0 - prints deprecation warnings when using emulator

### ISSUE THREAD

**Issue by bmclean** [GoogleCloudPlatform/google-cloud-ruby#1844]
After upgrading to `google-cloud-datastore 1.2.0' our development and test logs are filled with this:

> `service_path`and `port` parameters are deprecated and will be removed

It looks like it is being generated [here](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/b0e936c65717db7df2a6693e5ec9c8b590e314c0/google-cloud-datastore/lib/google/cloud/datastore/v1/datastore_client.rb#L114).

To use the datastore emulator we configure the ENV['DATASTORE_EMULATOR_HOST'] with something like 'localhost:8180'. The warning is because 'datastore.googleapis.com' doesn't match 'localhost:8180'.

What do we need to do to address the deprecation?

**Comment by blowmage** [comment]
Several of the low level arguments were recently deprecated, and as part of the 1.2.0 release we tried to make sure that none of these warnings were being raised. However, we obviously missed the warnings when for connecting to the emulator.

I don't believe there is anything you can do to avoid these warnings until we can get a new release out that avoids using these arguments.

**Comment by bmclean** [comment]
Thanks @blowmage!
