### ISSUE TITLE
Google Language API documentation points to wrong URL

### ISSUE THREAD

**Issue by Merovex** [GoogleCloudPlatform/google-cloud-ruby#1856]
The [Natural Language API Readme](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-language/README.md) points to a dead URL. Correct URL follows.

https://cloud.google.com/natural-language/

**Comment by geigerj** [comment]
This URL is autogenerated from API metadata in [googleapis/googleapis](https://github.com/googleapis/googleapis/). We should investigate how the canonical URL for product documentation on cloud.google.com is formed, and ensure we generate it correctly from the given metadata. Note that the current link does already redirect to the right URL.

**Comment by Merovex** [comment]
I just checked the link, which led to a 404 page. Perhaps I am clicking the wrong link?

**Comment by blowmage** [comment]
The URL https://cloud.google.com/language gives me a 404 as well.

**Comment by geigerj** [comment]
Thanks for the correction. (Strangely the behavior seems to depend on whether you're inside Google or not...) Filed #1858 as a temporary fix until we can update the code generator.

**Comment by geigerj** [comment]
Tracking this issue upstream in the code generator as https://github.com/googleapis/toolkit/issues/1811, and closing this issue. For the time being, we should continue to manually maintain documentation links that the code generator mishandles.
