### ISSUE TITLE
annotate_video providing input_content always times out

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/google-cloud-ruby#1862]
If I try to annotate a local video file by passing its base64 encoded bytes as input_content, my request hangs forever.

The same request works if I provide input_uri to the same file stored in Google Cloud Storage
The same request using content_uri works in other language's Video client libraries

```ruby
require "google/cloud/video_intelligence" # 0.25.0
require "base64"

video = Google::Cloud::VideoIntelligence.new

encoded_video = Base64.encode64 File.read("small-local-video.mp4")

operation = video.annotate_video input_content: encoded_video, features: [:LABEL_DETECTION] do |operation|
  raise operation.results.message? if operation.error?
  puts "Finished processing"
end

puts "Processing video for label annotations:"
operation.wait_until_done!
```

Example video: http://storage.googleapis.com/demomaker/cat.mp4

This seems to hang forever for me.

/cc @geigerj @lukesneeringer Any thoughts?

**Comment by blowmage** [comment]
Why are you base64 encoding the video? I’ve seen that as a requirement for sending binary data to REST APIs, but VideoIntelligence is GRPC and for those APIs we’ve been sending BINARY encoded Ruby strings.

**Comment by geigerj** [comment]
@blowmage Able to confirm that's correct; the repro code above succeeds without base64 encoding.

**Comment by blowmage** [comment]
@geigerj Can you give us an update?

**Comment by geigerj** [comment]
IIRC this was fixed in https://github.com/GoogleCloudPlatform/ruby-docs-samples/ by not base64 encoding the input.
