### ISSUE TITLE
Google::Cloud::Language classes should implement #to_s

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/google-cloud-ruby#1868]
When working in irb trying to build up a script to interact with language it is hard to figure out what properties/fields each class has because they don't all implement #to_s. To understand what's going on you have to use #inspect. It would be handy if they all implemented #to_s. 

For example, compare
```ruby
> puts syn.tokens[1]
#<Google::Cloud::Language::V1::Token:0x007ff8a40cc368>
```

to 

```ruby
> puts syn.tokens[1].inspect
<Google::Cloud::Language::V1::Token: text: <Google::Cloud::Language::V1::TextSpan: content: "cat", begin_offset: -1>, part_of_speech: <Google::Cloud::Language::V1::PartOfSpeech: tag: :NOUN, aspect: :ASPECT_UNKNOWN, case: :CASE_UNKNOWN, form: :FORM_UNKNOWN, gender: :GENDER_UNKNOWN, mood: :MOOD_UNKNOWN, number: :SINGULAR, person: :PERSON_UNKNOWN, proper: :PROPER_UNKNOWN, reciprocity: :RECIPROCITY_UNKNOWN, tense: :TENSE_UNKNOWN, voice: :VOICE_UNKNOWN>, dependency_edge: <Google::Cloud::Language::V1::DependencyEdge: head_token_index: 2, label: :NSUBJ>, lemma: "cat">
```

The second one helps me see what fields I can call and makes learning the library faster.

**Comment by geigerj** [comment]
I think this is best treated as a feature request for [google/protobuf](https://github.com/google/protobuf/tree/master/src/google/protobuf), rather than for the client libraries.

**Comment by geigerj** [comment]
Filed as https://github.com/google/protobuf/issues/3998.
