### ISSUE TITLE
Segmentation Fault when using logging

### ISSUE THREAD

**Issue by nambrot** [GoogleCloudPlatform/google-cloud-ruby#1872]
We have been very happy with GCP so far, but running into a seemingly nasty issue. We do all our logging from our background workers in Rescue, but it seems like from time to time, they will segfault when using `google-cloud-logging`. (What's worse is that this won't register a failing process in Kubernetes, but this is a separate issue)

```
E usr/local/bundle/gems/google-cloud-logging-1.2.3/lib/google/logging/v2/logging_pb.rb:13: [BUG] Segmentation fault at 0x000000000000a8
E  ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
 
E  
 
E  -- Control frame information -----------------------------------------------
 
c:0137 p:---- s:0553 e:000552 CFUNC  :build
c::0136 p:0081 s:0550 e:000549 TOP    /usr/local/bundle/gems/google-cloud-logging-1.2.3/lib/google/logging/v2/logging_pb.rb:13 [FINISH]

```

I'll try to update the relevant gems, but just wanted to note it here

**Comment by blowmage** [comment]
Hi @nambrot, thank you for opening this issue. It looks to me that this is the same issue that has been reported against google-protobuf. The most recent report is google/protobuf#3925. Thankfully, it looks to be corrected in google/protobuf#4011. If you can test out the protobuf team's fix I'm sure they would love to get feedback on it.

I'll keep this issue one until the fix has been released. As soon as we have a release I'll make a note here and ask you to upgrade and let us know if it solves the problem for you.

Thanks!

**Comment by nambrot** [comment]
Thanks for pointing me to the fix. We are unfortunately not yet on Ruby 2.4, but will let you know if we make it there. Since this seems to be the root cause, feel free to close this ticket

**Comment by blowmage** [comment]
I believe when the fix it released it will be applied to all ruby versions. I think the PR was just poorly named.

**Comment by nambrot** [comment]
Great to hear!

**Comment by quartzmo** [comment]
@nambrot Were you able to test out the protobuf fix?

**Comment by nambrot** [comment]
I have not yet deployed it, yet it seems like it is no longer happening (at
least in the last week)

**Comment by blowmage** [comment]
Closing as this looks to be fixed by the google-protobuf gem.
