### ISSUE TITLE
BigQuery schema management from a configuration file

### ISSUE THREAD

**Issue by jeremywadsack** [GoogleCloudPlatform/google-cloud-ruby#1919]
In [this comment](https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/367#issuecomment-146251415) the author used a YML file passed to `create_table` that specified the schema. It appears this feature was removed in preference for only programatic schema definitions. I'd really prefer to have a the schema defined in a configuration file and so I re-created that functionality myself.

I'm thinking of the interface being something like this:

```
table_schema = YAML.load_file(File.join(root, "config", "big_query", "schema.yml"))
dataset.create_table(table_id) do |table|
  table.schema_from(table_schema)
end
```

Or going back to the previous interface:

```
table_schema = YAML.load_file(File.join(root, "config", "big_query", "schema.yml"))
dataset.create_table(table_id, schema: table_schema)
```

Would this be a feature you'd be open to a PR for?

**Comment by blowmage** [comment]
The gcloud CLI uses a [JSON schema file](https://cloud.google.com/bigquery/docs/schemas#using_a_json_schema_file) to define the schema when making these calls. I think it would be advantageous to support creating and loading these files as part of the Ruby API. To support this I would add the following methods to `Schema`:

* `Schema#load source`
* `Schema#dump source`

The source argument would be treated like `Marshal.load`'s `source` argument. Either an IO to write to/from, or a String that defines the file path to read to/from.

So here is how I would envision that system working:

```ruby
require "google/cloud/bigquery"

bigquery = Google::Cloud::Bigquery.new

dataset = bigquery.dataset "my_dataset"

table = dataset.create_table "my_new_table" do |table|
  table.schema.load "path/to/schema.json"
end
```

Would this work for you, @jeremywadsack?

**Comment by jeremywadsack** [comment]
Aligning with the `gcloud` API makes sense. The implementation you suggest works fine for me. Being able to write the current schema is a good point.

Question: if the API already works this way, is there a short-cut that we could use to directly read/write this from the `service` or should I parse the JSON, verify the field types and modes, and update the `Schema` object from that (which is what I'm doing currently doing using `Schema#add_field`)?

I can work on a PR for this. I'll likely have something together later this month.

I would also like to support _migrations_ but that's trickier — especially as BigQuery is very limited on what you can change. (Or maybe that makes it simpler.) But I'll save that for a separate effort.

**Comment by blowmage** [comment]
I don't believe the API supports the JSON schema files. They are specific to the gcloud CLI AFAIK.

@quartzmo and I spent time time discussing this. Here is a quick sketch of how we would approach an implementation. There are some methods called here that are not yet implemented, but this should be enough to get started.

https://gist.github.com/blowmage/e86d4b8d5b07b0d496d1234064b49e7f

**Comment by jeremywadsack** [comment]
Wow, thanks for the starter code. I'll need to dig more into how the whole `gapi` model works — I haven't really gotten my head around that yet.

Out of curiosity, any reason to push the parsing down into the `gapi` instead of just using `Schema#add_field` to iteratively and recursively add the fields?

https://gist.github.com/jeremywadsack/b45bb85fb3d4e08f3c156ed447af2f9c

**Comment by quartzmo** [comment]
> Out of curiosity, any reason to push the parsing down into the gapi instead of just using Schema#add_field to iteratively and recursively add the fields?

I'm pretty sure @blowmage had this idea as well, we just didn't put it into the gist.

**Comment by quartzmo** [comment]
Any progress on a PR for this feature?

**Comment by jeremywadsack** [comment]
Not yet. It's on my list but we've been busy with other things and I haven't had time. I hope to get to it soon

**Comment by lsimoneau** [comment]
FWIW this would be super useful for my team as well.

**Comment by quartzmo** [comment]
@jeremywadsack Any update on this one?

**Comment by jeremywadsack** [comment]
I've got a start on it with working code for loading and an acceptance test. I need to figure out how to write a doctest and then add unit tests. Then write the `dump` code and class methods and test those.

I noticed there aren't any unit tests for the `Schema` class. Are you ok if I add one? I think it's more "unit" and also makes it easier to write a test rather than having to put tests into `table`, `table_reference`, `dataset`, and `dataset_reference`. In fact, I didn't see very many tests covering schemas.

**Comment by quartzmo** [comment]
@jeremywadsack Sounds good!

The unit tests for the `Schema` class are in [schema_test.rb](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-bigquery/test/google/cloud/bigquery/schema_test.rb). If all the logic is in `Schema`, then personally I think it's ok to just add tests there. The tests at the level of `table`, `table_reference`, `dataset`, and `dataset_reference` are more to specify the API contract than to verify the logic.

**Comment by quartzmo** [comment]
If you have any trouble with doctest, please ping me here.

**Comment by jeremywadsack** [comment]
Ah, I see that Mike added those schema unit tests last week, which is why I didn't see it. :) Great. I'll rebase and add to that. All the logic is in `Schema`.

**Comment by jeremywadsack** [comment]
@blowmage I just noticed, in the new `test/google/cloud/bigquery/schema_test.rb` you used  `Google::Apis::BigqueryV2::TableSchema.from_json`. I didn't know about that call.

I had written up something like you suggested (and similar to what we're using) to iterate through the fields and add them ([diff here](https://github.com/GoogleCloudPlatform/google-cloud-ruby/compare/master...keylimetoolbox:1e8db50)), but it seems like maybe I could just call that instead?

```
  def load source
    if source.respond_to?(:rewind) && source.respond_to?(:read)
      source.rewind
      source = source.read
      source_json = String source
    elsif source.is_a? Hash
      source_json = source.to_json
    else
      source_json = String source
    end
    Google::Apis::BigqueryV2::TableSchema.from_json source_json
  end
```

One differences is that in the code you suggested the `schema.json` content would look like this:

```
[
  {"name":"name","type":"STRING","mode":"REQUIRED"}
  ...
]
```

And in the implementation above it would look like this:

```
{
      "fields": [
        {"name":"name","type":"STRING","mode":"REQUIRED"},
        ...
      ]
    }
```

But I could write the method to read adapt to the first format.


Two questions:

1) Am I missing any reason why not to use `from_json`?
2) Do you have a preference on the schema file? I'm partial to the first format as it's simpler, but maybe there are other things that could go into the JSON in addition to `fields` so it would be important to include that in there?

**Comment by blowmage** [comment]
We should use th same format as the [CLI JSON File](https://cloud.google.com/bigquery/docs/schemas#using_a_json_schema_file).

**Comment by jeremywadsack** [comment]
Oh, right. You said that before. :) And I did.

Can you think of any reason why I shouldn't use `Google::Apis::BigqueryV2::TableSchema.from_json` in place of more parsing code in this gem? (I can modify the JSON to match the expected format for that call.)

**Comment by blowmage** [comment]
As long as the API is correct and the tests pass it doesn’t matter to me (much) how it is implemented. Using the private `.from_json` is fine for the implementation.
