### ISSUE TITLE
README has wrong arguments for Bigquery

### ISSUE THREAD

**Issue by playerfm** [GoogleCloudPlatform/google-cloud-ruby#1921]
I found this to be out of date, unless I'm missing something:

```
bigquery = Google::Cloud::Bigquery.new(
  project_id: "my-todo-project",
  credentials: "/path/to/keyfile.json"
)
```

What worked for me was `project` and `keyfile` arguments.

**Comment by blowmage** [comment]
It depends on what version of the gem you are using. If you are using the latest version then the `project_id` and `credentials` arguments are supported. If you are using an older version, before the `project_id` and `credentials` arguments were added, then they won't be supported.

The `project` and `keyfile` arguments are considered deprecated in the latest version, but we have no plans to remove support for them. You are fine to continue to use them if you would like.

The README always reflects the latest version of the gem.

**Comment by playerfm** [comment]
You're right, thanks, bundle had installed 0.27 not 0.30 due to some dependency issue.
