### ISSUE TITLE
Inconsistent behavior when using 'offset' with queries

### ISSUE THREAD

**Issue by NickTitle** [GoogleCloudPlatform/google-cloud-ruby#1922]
To paginate data in datastore (gem v 1.2.1), we are using int offsets (instead of cursors) so that we can skip to predictable places in the result set. Instead of only `next/prev` which cursors would support, we want "go to page 7", which I understand you need an int offset for.

In the following code, I execute queries, following cursors until hitting `more_after_limit` or `no_more`. Our behavior on returned results seems broken when using offsets. Here's my output, and underneath is our lib code written on top of a vanilla datastore client.

Could you help me understand the actual behavior, or if I am making a bad assumption here?

##### setup
```ruby
c = Ghost::Collection::Result.set_client(< AR Object >)
=> #<Kolide::GCP::Datastore::Client:0x0000555f5d61b450 @client_id="kolide-74-8do9prZygmozipVq", @kind="CollectionResults-10", @namespace=<snip>>

c.kind
=> "CollectionResults-10"

 c.client
=> #<Google::Cloud::Datastore::Dataset:0x0000555f5d5fecd8 @service=Google::Cloud::Datastore::Service(<project-id>)>

c.client.query
=> #<Google::Cloud::Datastore::Query:0x0000555f5d0e5508 @grpc=<Google::Datastore::V1::Query: projection: [], kind: [], filter: nil, order: [], distinct_on: [], start_cursor: "", end_cursor: "", offset: 0, limit: nil>>

c.client.query.kind(c.kind).offset(50)
=> #<Google::Cloud::Datastore::Query:0x0000555f5d6a1a78 @grpc=<Google::Datastore::V1::Query: projection: [], kind: [<Google::Datastore::V1::KindExpression: name: "CollectionResults-10">], filter: nil, order: [], distinct_on: [], start_cursor: "", end_cursor: "", offset: 50, limit: nil>>
```
----

##### using it
```ruby
c.run_query(c.client.query.kind(c.kind)).count
=> 496

c.run_query(c.client.query.kind(c.kind).offset(495)).count
=> 1

c.run_query(c.client.query.kind(c.kind).offset(450)).count
=> 46

c.run_query(c.client.query.kind(c.kind).offset(400)).count
=> 96

c.run_query(c.client.query.kind(c.kind).offset(200)).count
=> 296

c.run_query(c.client.query.kind(c.kind).offset(150)).count
=> 300

c.run_query(c.client.query.kind(c.kind).offset(100)).count
=> 300
```

----
##### our lib code that executes queries

```ruby
def run_query(query=base_query)
  all_results = []
  tmp_results = client.run query, namespace:namespace
  while tmp_results.any?
    all_results += tmp_results
    break if query_complete?(tmp_results)
    query = query.cursor(tmp_results.cursor)
    tmp_results = client.run query, namespace:namespace
  end
  all_results
end

def query_complete?(results)
  # see https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-datastore/v1.1.0/google/cloud/datastore/dataset/queryresults
  results.more_after_limit? || results.no_more?
end
```

**Comment by blowmage** [comment]
Huh, this is an interesting question. I'm not a Datastore expert, but my understanding is that you should use `limit` in conjunction with `offset`, and try to keep all results in a single batch. I believe that `offset` it being applied *after* the `cursor`.

Let's take the following query:

```ruby
c.run_query(c.client.query.kind(c.kind).offset(150)).count
=> 300
```

The first batch starts at index 0, applies the offset of 150 to the index, making the index 150, and returns a batch. I believe the default batch size is 300. So the end cursor is at index 450. The next query uses the previous query's cursor to start at index 450, and again applies the offset of 150 to the index, making the index 600. That query returns no results.

Again I'm not an expert so I may be giving you bad information. @pcostell, can you weigh in here?

If you were unaware, there is the following note on the [Cursors, limits, and offsets](https://cloud.google.com/datastore/docs/concepts/queries#cursors_limits_and_offsets) section of the Datastore Queries guide:

> **Although Cloud Datastore supports integer offsets, you should avoid using them.** Instead, use cursors. Using an offset only avoids returning the skipped entities to your application, but these entities are still retrieved internally. The skipped entities do affect the latency of the query, and your application is billed for the read operations required to retrieve them. Using cursors instead of offsets lets you avoid all these costs.

**Comment by NickTitle** [comment]
@blowmage thanks so much for weighing in so quick - while we'd love to use cursors, doesn't that make it impossible to jump to arbitrary pages?

in the interim i'll try my same experiment with a limit of '25' and post my findings

**Comment by bmclean** [comment]
@blowmage I believe the default batch size is 300. We have yet to see any batch results differ. I think the size can vary based on distribution and consistency though.

The first few examples (counts of 1, 46, 96) would also fail if the total number of entities was greater than 600. For example, try an offset of 1 with greater than 600 entities. You will get entities 2 to 301 in the first batch, entities 303 to 602 in the second batch, etc.

The following examples are using a limit of 25 with 1790 same kind entities in datastore:
```
query.limit(25).offset(1)
=> entities 2 to 26

query.limit(25).offset(325)
=> entities 326 to 350

query.limit(25).offset(632)
=> entities 633 to 657

query.limit(25).offset(987)
=> entities 988 to 1012

query.limit(25).offset(1001)
=> 0 entities. Can the offset not exceed 1000?
```

**Comment by blowmage** [comment]
> `Can the offset not exceed 1000?`

`offset` will still pull all those records, but skip them and return only the results afterwards. (But you still pay for pulling the results AFAIK.) It would not surprise me if there are issues with large offsets, since they are intended to be used on a single page/batch of results.

**Comment by blowmage** [comment]
> For example, try an offset of 1 with greater than 600 entities. You will get entities 2 to 301 in the first batch, entities 303 to 602 in the second batch, etc.

I believe #1930 will fix this.

**Comment by blowmage** [comment]
I believe this is fixed in #1930. @NickTitle, you can apply the same fix by change your code to set the query's `offset` to 0 in your `while` loop.

```ruby
def run_query(query=base_query)
  all_results = []
  tmp_results = client.run query, namespace:namespace
  while tmp_results.any?
    all_results += tmp_results
    break if query_complete?(tmp_results)
    query = query.cursor(tmp_results.cursor)
    # APPLY FIX TO OFFSET
    query.offset(0)
    tmp_results = client.run query, namespace:namespace
  end
  all_results
end
```

**Comment by NickTitle** [comment]
@blowmage thanks so much for investigating! will this make its way out to a versioned release soon? i'm adding the patch in the interim

**Comment by blowmage** [comment]
I expect we will have releases in the next week or so.
