### ISSUE TITLE
Support autonaming of Pub/Sub Subscriptions

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#193]
The [Pub/Sub documentation](https://cloud.google.com/pubsub/reference/rest/v1/projects.subscriptions/create) states:

> If the name is not provided in the request, the server will assign a random name for this subscription on the same project as the topic.

We are unable to make an API call to create a subscription without a name. We suspect this is an issue with the Google API Client library, since `ArgumentError` is being raised.

**Comment by stephenplusplus** [comment]
@tmatsuo - sorry if you've already been pinged about this elsewhere, but I couldn't find anything. Do you know if support for auto-named subscriptions is real, or if this was a documentation error?

**Comment by stephenplusplus** [comment]
@tmatsuo friendly ping :)

**Comment by tmatsuo** [comment]
I just found this issue! Sorry for the late reply.

Yes, it is not currently supported on the API surface (although the internal core server supports it, thus the documentation discrepancy). Sorry about the confusion.

**Comment by blowmage** [comment]
@tmatsuo Hah! Thanks for clarifying! We removed the docs from gcloud-ruby about this and made the name required. Glad to know the reason. 

Is this a feature that will be supported in future API versions?

**Comment by Draiken** [comment]
It' been one year and I still got bitten by this issue after following the documentation [here](https://googlecloudplatform.github.io/gcloud-ruby/#/docs/v0.11.0/gcloud/pubsub)
Is there anything I can do to help fix this issue?
