### ISSUE TITLE
BigQuery error running example from README

### ISSUE THREAD

**Issue by Paxa** [GoogleCloudPlatform/google-cloud-ruby#1935]
```
/ruby/lib/ruby/gems/2.4.0/gems/google-cloud-bigquery-1.0.0/lib/google/cloud/bigquery/service.rb:675:in `rescue in execute': invalid: No schema specified on job or table. (Google::Cloud::InvalidArgumentError)
	from /ruby/lib/ruby/gems/2.4.0/gems/google-cloud-bigquery-1.0.0/lib/google/cloud/bigquery/service.rb:669:in `execute'
	from /ruby/lib/ruby/gems/2.4.0/gems/google-cloud-bigquery-1.0.0/lib/google/cloud/bigquery/service.rb:306:in `load_table_file'
	from /ruby/lib/ruby/gems/2.4.0/gems/google-cloud-bigquery-1.0.0/lib/google/cloud/bigquery/table.rb:2008:in `load_local'
	from /ruby/lib/ruby/gems/2.4.0/gems/google-cloud-bigquery-1.0.0/lib/google/cloud/bigquery/table.rb:1488:in `load_job'
	from /ruby/lib/ruby/gems/2.4.0/gems/google-cloud-bigquery-1.0.0/lib/google/cloud/bigquery/table.rb:1630:in `load'
	from try_bigquery.rb:22:in `<main>'
```

Is there any working example with which can "just run"? (with CSV file included)

**Comment by quartzmo** [comment]
Have you tried following this guide? https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-bigquery/v1.0.0/google/cloud/bigquery

**Comment by Paxa** [comment]
Yes, and it worked. Should we copy that examples to README? or remove examples from README?

**Comment by quartzmo** [comment]
Yes, we should probably update/expand the README examples.

**Comment by blowmage** [comment]
The quickest fix might be to add a schema to the create_table call.

**Comment by quartzmo** [comment]
@Paxa We want to replace the README example with one from the guide. Which do you think is the best choice? For example [(1) Creating a table without insert](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-bigquery/lib/google/cloud/bigquery.rb#L281-L292) or [(2) A query of public data that does not show table creation](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-bigquery/lib/google/cloud/bigquery.rb#L209-L219)? Or a different one?

**Comment by quartzmo** [comment]
I'm going to go with a `create_table`, `load` (make-believe CSV from GCS), and `query` example that includes a schema as requested by @blowmage. There will be no real CSV available, however.

**Comment by Paxa** [comment]
Thank you
