### ISSUE TITLE
Deprecation Warning in google-cloud-logging gem

### ISSUE THREAD

**Issue by qingling128** [GoogleCloudPlatform/google-cloud-ruby#1938]
We are seeing some deprecation warning in `google-cloud-logging` gem starting with `v1.3.0`.

**The warning**
The `channel`, `chan_creds`, and `updater_proc` parameters will be removed on 2017/09/08.

**The script to reproduce**
```
$ cat call_api.rb
require "grpc"
require "google/api/monitored_resource_pb"
require "google/cloud/logging/v2"
require "google/logging/v2/log_entry_pb"
require "google/gax"
require 'googleauth'

ssl_creds = GRPC::Core::ChannelCredentials.new
authentication = Google::Auth.get_application_default
creds = GRPC::Core::CallCredentials.new(authentication.updater_proc)
creds = ssl_creds.compose(creds)

client = Google::Cloud::Logging::V2::LoggingServiceV2Client.new(
  channel: GRPC::Core::Channel.new('logging.googleapis.com', nil, creds)
)
client.write_log_entries([
  Google::Logging::V2::LogEntry.new(
    {
      log_name: 'projects/<PROJECT_ID>/logs/testwarning',
      resource: Google::Api::MonitoredResource.new({
        type: 'gce_instance',
        labels: {
          'instance_id' => '<INSTANCE_ID>',
          'project_id' => '<PROJECT_ID>',
          'zone' => '<ZONE>'
        }
      }),
      text_payload: 'test'
    }
  )
])
puts 'successful'
```
**v1.2.3 does not have the warning**
```
$ gem list | grep google-cloud-logging
google-cloud-logging (1.2.3)
$ ruby call_api.rb
successful
```

**v1.3.0 - v1.4.0 all have this warning**
```
$ gem list | grep google-cloud-logging
google-cloud-logging (1.4.0)
$ ruby call_api.rb
The `channel`, `chan_creds`, and `updater_proc` parameters will be removed on 2017/09/08
successful
```

Potentially related issue: https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1723

**Comment by geigerj** [comment]
@qingling128 A number of GAPIC constructor arguments, including `channel`, were deprecated and replaced by a [catch-all `credentials` argument](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/e06b63c73fcdbdf3b5636088e11292c2fe3e47d6/google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb#L123) which can accept a GRPC Channel instance, among other things. Can you try updating your code to do

```
...
client = Google::Cloud::Logging::V2::LoggingServiceV2Client.new(
  credentials: GRPC::Core::Channel.new('logging.googleapis.com', nil, creds)
)
```

instead?

**Comment by igorpeshansky** [comment]
Looks like https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/206 worked.

**Comment by qingling128** [comment]
Yup, Igor beat me to fix that. I'm closing this. Thanks @geigerj and @igorpeshansky!
