### ISSUE TITLE
Heavy CPU/memory usage on inserts compared to postgresql/redshift

### ISSUE THREAD

**Issue by brauliobo** [GoogleCloudPlatform/google-cloud-ruby#1943]
To insert hashes into bigquery requires a lot of cpu usage, aproximately 10 times more when inserting the same hashes into postgresql or redshift. My guess is that the protocol is heavy to encode. It also uses 50%+ more memory usage.

**Comment by blowmage** [comment]
Hi, can you give us more information on how you are inserting data into BigQuery? For example, are you calling Table#insert? Or are you using Table.insert_async? How many rows are you inserting? What type and how many fields does each row have? Thanks.

**Comment by brauliobo** [comment]
hi, the project/table is `bigquery-174210:test.reviews`, there is around 20 fields, with three repeated (array of strings). I'm using `#insert` with 10 concurrent threads (using `ruby-concurrent` gem), so I don't think it makes sense to switch to `insert_async`. I'm inserting no more than 1000 rows per `insert`, but most times much less as it is a sync operation from another database.

**Comment by blowmage** [comment]
@brauliobo Would it be possible for you to use a branch with some changes to address performance? If you have a Gemfile you can do this by adding the following:

```ruby
 gem "google-cloud-bigquery" github: "blowmage/gcloud-ruby", branch: "bigquery-insert-perf"
 gem "google-cloud-core" github: "blowmage/gcloud-ruby", branch: "bigquery-insert-perf"
```

I suspect we won't be able to match the performance of postgresql, but I am seeing some performance improvement with this branch so far.  Here are some benchmarks that show a decrease in CPU usage when using `Table#insert`. I am curious how CPU utilization with your data would be affected.

| # of rows | before | after |
| - | - | - |
| 500 | 0.060000 | 0.040000 |
| 1000 | 0.120000 | 0.060000 |
| 2000 | 0.240000 | 0.120000 |
| 5000 | 0.600000 | 0.340000 |

**Comment by blowmage** [comment]
@brauliobo Have you been able to use the benchmark the code improvements?

**Comment by blowmage** [comment]
Closing as we have made fairly significant improvements to BigQuery performance and haven't heard from back the user. If there are more concerns about performance please open a new issue and reference this issue. Thanks!

**Comment by brauliobo** [comment]
thanks @blowmage, it looks promissing!
