### ISSUE TITLE
Syntax error raised when attempting to use named parameters in query

### ISSUE THREAD

**Issue by boris-layvant** [GoogleCloudPlatform/google-cloud-ruby#1951]
I have a Rails 5.1.4 application with ruby 2.4.1 and the following Google cloud gems:

    google-cloud-bigquery (1.0.0)
      concurrent-ruby (~> 1.0)
      google-api-client (~> 0.17.0)
      google-cloud-core (~> 1.1)
      googleauth (~> 0.6.2)
    google-cloud-core (1.1.0)
      google-cloud-env (~> 1.0)
    google-cloud-env (1.0.1)

The app defines a class which utilizes Google::Cloud::Bigquery as follows:

`require 'google/cloud/bigquery'`

`class BigQuery`
&nbsp; &nbsp; `PROJECT = ENV["BIGQUERY_PROJECT"]`
&nbsp; &nbsp;  `KEYFILE = ENV["BIGQUERY_AUTHENTICATION_FILE"]`

  &nbsp; &nbsp; `attr_reader :data_location, :cohort`

   &nbsp; &nbsp; `def initialize data_location:, cohort:`
   &nbsp; &nbsp;  &nbsp; &nbsp; `@data_location = data_location`
    &nbsp; &nbsp;  &nbsp; &nbsp; `@cohort = cohort`
   &nbsp; &nbsp; `end`

   &nbsp; &nbsp;  `def results`
   &nbsp; &nbsp; &nbsp; &nbsp; `big_query.query sql, params: {data_location: data_location, cohort: cohort}`
  &nbsp; &nbsp;  `end`

  &nbsp; &nbsp; `private`

  &nbsp; &nbsp; `def big_query`
  &nbsp; &nbsp; &nbsp; &nbsp;   `@big_query ||= Google::Cloud::Bigquery.new project: PROJECT, keyfile: KEYFILE`
  &nbsp; &nbsp;  `end`

  &nbsp; &nbsp;  `def sql`
  &nbsp; &nbsp; &nbsp; &nbsp;   `"SELECT * FROM @data_location WHERE cohort = @cohort"`
  &nbsp; &nbsp;  `end`
`end`

Upon calling the 'results' method on an instance of the class, the following error is raised:

Google::Cloud::InvalidArgumentError: Syntax error: Unexpected "@" at [1:15]
	from lib/big_query.rb:15:in `results'
	from (irb):2

My understanding is that the error stems from the usage of query parameters, but I cannot identify any issues with my implementation. Any help would be appreciated.

**Comment by blowmage** [comment]
BigQuery's [query parameters](https://cloud.google.com/bigquery/docs/parameterized-queries) are used for the parameters only; the conditionals after the `WHERE` in the query. Unfortunately, you are using a parameter for the table name. This is not part of the BigQuery API and not allowed by the Cloud service, which is why you are getting an error.

If you made the following changes it should work:

```ruby
def results
  big_query.query sql, params: {cohort: cohort}
end

def sql
 "SELECT * FROM #{data_location} WHERE cohort = @cohort"
end
```

**Comment by boris-layvant** [comment]
Thank you for the clarification.
