### ISSUE TITLE
Add support for BigQuery customer-managed encryption keys

### ISSUE THREAD

**Issue by choenden** [GoogleCloudPlatform/google-cloud-ruby#1960]
BigQuery customer-managed encryption keys allow users to specify a Cloud KMS key to protect their BigQuery table.

- [x] Jobs: https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs `destinationEncryptionConfiguration` field, which indicates which Cloud KMS key should be used for the destination.
  - [x] Add `destinationEncryptionConfiguration` field to query job configuration.
  - [x] Add `destinationEncryptionConfiguration` field to copy job configuration.
  - [x] Add `destinationEncryptionConfiguration` field to load job configuration.
- [x] Tables: https://cloud.google.com/bigquery/docs/reference/rest/v2/tables In a table, there is a encryptionConfiguration field, which indicates which Cloud KMS key protects (or should protect in case of CreateTable) a BigQuery table.
  - [x] Add `encryptionConfiguration` to table.
- [ ] (Lower priority) Support for `getServiceAccount` https://cloud.google.com/bigquery/docs/reference/rest/v2/projects/getServiceAccount
Note that unlike the other methods mentioned above, this would generally only be called once and the resulting value (the email address) does not change - so it can easily also be called from UI/API/CLI without much hindrance (hence lower priority).
  - [ ] Add `get_service_account` method to `project` class.

**Comment by blowmage** [comment]
@geigerj @jbolinger The features being asked for here are marked `experimental`. The policy has been not to implement experimental features, but exceptions have been made. What can you tell us about this feature?

**Comment by geigerj** [comment]
This feature request is not currently on our feature roadmap, so I would not make an exception in this case.

@danoscarmike FYI; do you know whether there's any internal tracking of this feature that I'm not aware of?

**Comment by choenden** [comment]
Hey, to clarify, the experimental tag has been removed and this is awaiting rollout. I will send internal bugs and docs your way.

**Comment by geigerj** [comment]
Thanks for the clarification, @choenden!

**Comment by tswast** [comment]
FYI: I won't be able to resume work on this until Wednesday, so if this is still time sensitive someone will need to follow-up my PRs with one that adds the key to query and copy jobs.

**Comment by quartzmo** [comment]
Thanks. Do you want us to take care of it?

**Comment by tswast** [comment]
Yeah, when you get a chance. No rush.

**Comment by quartzmo** [comment]
@tswast OK, will do.
