### ISSUE TITLE
Test against Ruby 2.5

### ISSUE THREAD

**Issue by geigerj** [GoogleCloudPlatform/google-cloud-ruby#1967]
gRPC has just released 1.9.1, which adds Ruby 2.5 support. We should add Ruby 2.5 to the CI configuration. @quartzmo @blowmage could one of you take this on?

cc @jbolinger

**Comment by blowmage** [comment]
Currently working on this on the [ruby-2.5 branch](https://github.com/GoogleCloudPlatform/google-cloud-ruby/tree/ruby-2.5).

**Comment by blowmage** [comment]
We've run into an issue running doctests on Ruby 2.5. We have some failures and it isn't clear why. I am currently working through the `yard-doctest` source to try to get more information about the failures. No ETA yet.

**Comment by blowmage** [comment]
You can see the builds here:

* [CircleCI](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-ruby/tree/ruby-2.5)
* [Travis-CI](https://travis-ci.org/GoogleCloudPlatform/google-cloud-ruby/builds/341211298)

**Comment by blowmage** [comment]
The [ruby-2.5 branch](https://github.com/GoogleCloudPlatform/google-cloud-ruby/tree/ruby-2.5) has been merged into master, and both CircleCI and Travis-CI are running builds against Ruby 2.5.
