### ISSUE TITLE
Ruby NLP API side bar links broken

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/google-cloud-ruby#1969]
<img width="284" alt="screen shot 2018-02-14 at 12 17 07 pm" src="https://user-images.githubusercontent.com/6519888/36226011-6e2160f2-1181-11e8-9c11-efb84ab40ca5.png">  

The side bar from [this page](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.49.0/google/cloud/language) has broken links to [Project](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.49.0/google/cloud/language/project) , [Document](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.49.0/google/cloud/language/document)  and [Annotation](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.49.0/google/cloud/language/annotation)

**Comment by quartzmo** [comment]
Thanks for finding this. These types were removed from the Natural Language API, but the nav for the `google-cloud` meta-package was never updated, although the nav for the `google-cloud-language` package was correctly updated. I'll fix it now. Please refer to the [`google-cloud-language` docs](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-language/v0.29.0/google/cloud/language) for now.
