### ISSUE TITLE
Datastore.new API is incredibly confusing

### ISSUE THREAD

**Issue by ohboyotero** [GoogleCloudPlatform/google-cloud-ruby#1972]
The following code is an abuse of programming concepts, leads to user confusion, and exacerbates the already confusing documentation.

```ruby
datastore = Google::Cloud::Datastore.new
puts datastore.class    # => "Dataset"
```

![image](https://user-images.githubusercontent.com/110791/36281792-d1dcfd0e-1253-11e8-9207-c069935853e9.png)

A constructor for the type `Datastore` should not return a different type!

To make matters worse, all of the documentation uses the variable name `datastore` to hold an object of type `Dataset`, making the confusion greater. It's all the more confusing when the docs for the `Datastore` object have only the `#new` method, and yet the code examples on the very same page suggest that there exist other methods (e.g., `datastore.entity()`).

If you want this sort of pattern, please, ***please*** change the method name to `Datastore.new_dataset` or something like that.

**Comment by quartzmo** [comment]
This is generally true of other packages as well:

```sh
irb(main):002:0> bigquery = Google::Cloud::Bigquery.new
irb(main):003:0> bigquery.class
=> Google::Cloud::Bigquery::Project
```

**Comment by dazuma** [comment]
I agree it can be confusing to see that the "constructor" for `Google::Cloud::Datastore` (which btw is a module, not a class) creates an object whose class has a different name. However, I'd also remind the reader that that Ruby types are fundamentally duck types, not class-based types. The actual class of an object (the fact that it is a `Dataset` or a `Bigquery::Project` or any other class) is an implementation detail in Ruby code, and it's generally an antipattern to expect or rely on specific classes or class names. The important thing is whether the interface (i.e. which methods an object `respond_to?`) is clear and documented. If it isn't, we should figure out how to address that.

**Comment by ohboyotero** [comment]
@dazuma totally agree with the superficials, and if this was C++/C#/Java and `Datastore` was an interface or abstract class, and there was some implementation called `Dataset` which implemented that public API, that'd be great.

But that's not what's happening here.

1. You're right that a) Ruby doesn't actually have "constructors" per se, and b) Datastore is a module. But the choice was made to use the pattern `ConstantName.new` which is a built-in Ruby paradigm used to create new instances of objects. So whatever the source code says, to a Ruby user it will read as `Class.new` even if it's actually a module, and a Ruby user will assume that it returns a `Datastore` object, not some other object (unless that other object is a subclass that is completely interchangeable...which `Dataset` is absolutely not).

2. You're right that Ruby is both dynamically typed and duck typed and so it's a faux-pas to care too much about implementation class as long as the "API contract" is upheld.

But there's one critical problem with that from a "Ruby API user knowing what to do" standpoint. *Precisely* because it is a duck-typed language without any formal construct for "interface", there is no easy way to tell the user what behavior they can actually expect in an implementation-independent way. The set of public methods for `Dataset` ***is*** the API and from the user's perspective, `Datastore.new` is just a global factory function.

For a Ruby API, the only way to know what methods you can call and what their parameters, side-effects, and error cases are, is for there to be a) a concrete class to look at (since interfaces and abstract classes don't exist in the language), and b) enough documentation to make up for the general wigglyness of the Ruby language (e.g., metaprogramming).

At the end of the day, I'm really asking for a minor, minor change: **don't use `Datastore.new` as the method name**. The method is really just a factory method for a different class (`Dataset`) and should be named appropriately.

The moment you say `Datastore.get_dataset` or equivalent, I as a user know a) this isn't an object constructor, and b) `Datastore` is not the object/class/module/whatever I should be looking at.

It doesn't even have to be a breaking change. Just introduce the new method, keep and deprecate the old one, and update the documentation. I'm happy to help with the legwork if that's an issue.

**Comment by dazuma** [comment]
Ah, okay. I'm hearing that when you see `Datastore.new`, you (rightly) expect that you can find the *documentation* for the resulting object under the class `Datastore`, and it's surprising and confusing that you have to look for a different class `Dataset` for this information.

A different name for the factory method does seem like a reasonable approach. @blowmage What do you think? We were trying to keep the "toplevel client object" paradigm in place while lazy requiring of the files, but it is a good point that from a documentation perspective, users already have to know the actual class of the object (e.g. "Project"). Maybe it's okay for the factory method to make that explicit.

**Comment by blowmage** [comment]
These are great points and I generally agree with them. I can explain the history behind how we got here if you are interested. Unfortunately, however, I am very unlikely to support changing the names at this point in time.

I am sorry that the original naming decision has elicited such a strong negative reaction. Our goal has always been to craft a delightful and productive experience.

**Comment by ohboyotero** [comment]
Mostly I'm interested in the reasoning behind your standpoint so I can understand. If that includes a history lesson, that's fine with me!

If the names are set in stone, what room is there to improve the documentation? What is auto-generated vs. human-specified?

**Comment by quartzmo** [comment]
As I remember the history, these libraries originally exposed their top-level types through module methods such as [`Google::Cloud.datastore`](http://www.rubydoc.info/gems/google-cloud-datastore/1.3.0/Google/Cloud#datastore-class_method), and they still do. At some point there was a request to provide creation of these types via `new`, and the method was added.

**Comment by quartzmo** [comment]
> what room is there to improve the documentation? What is auto-generated vs. human-specified?

We'd love to get your help improving the documentation. The docs source for `Datastore.new` is [here](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-datastore/lib/google/cloud/datastore.rb#L569-L617) and is not generated. Feel free to open a PR (or just post some changes on this issue if that's easier.)

**Comment by quartzmo** [comment]
@ohboyotero Is there anything else to discuss on this issue, or can I close it?
