### ISSUE TITLE
The "audio_config" method uses a "words" argument for "enable_word_time_offsets"

### ISSUE THREAD

**Issue by ndbroadbent** [GoogleCloudPlatform/google-cloud-ruby#1984]
In this method: https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/4d806dfcc991bb976b0fbb31e459fdc9c5923eb0/google-cloud-speech/lib/google/cloud/speech/project.rb#L618-L633

The method has the arguments: `phrases: nil, words: nil`.  I think it's confusing that the `words` argument actually controls `enable_word_time_offsets`.

[The examples for all the other programming languages](https://cloud.google.com/speech/docs/async-time-offsets#speech-async-recognize-gcs-ruby) use: `enable_word_time_offsets`, `setEnableWordTimeOffsets`, `EnableWordTimeOffsets`, `enableWordTimeOffsets`, etc.

**Comment by quartzmo** [comment]
@ndbroadbent Thanks for raising this issue. I completely understand your confusion: The choice of the option name `words` is reductionist to the point that most of the information provided by the original name is lost.

A big change is in the works for this library (PR #1977) that will replace the API surface above with a slightly lower-level API that uses the original names from the Cloud Speech API. Therefore, I'm going to close this issue now. As I [commented](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1977#issuecomment-368661542) a few days ago, #1977 is just waiting for some external documentation that will assist users with the transition. If you are curious about the status, please post a comment on #1977.
