### ISSUE TITLE
google-cloud-core uses signet and googleauth but does not depend on them

### ISSUE THREAD

**Issue by grosser** [GoogleCloudPlatform/google-cloud-ruby#1985]
they should either depend on them or maybe do a `gem 'signet'` before trying to just require files from these gems

Usecase: only using google-cloud-core since I only need `Google::Cloud::Credentials`

**Comment by blowmage** [comment]
`Google::Cloud::Credentials` was never part of the public API and is deprecated. You should use `Google::Auth::Credentials` instead.

**Comment by grosser** [comment]
thx, works! 🎉 

switched that for:
```
gem 'googleauth'
require 'googleauth'
```
