### ISSUE TITLE
How to authenticate Google Language using API keys

### ISSUE THREAD

**Issue by Orevarc** [GoogleCloudPlatform/google-cloud-ruby#1999]
I am looking to authenticate with the Google Language platform using API keys. According to the docs [here](https://cloud.google.com/docs/authentication/api-keys), Google Language is a service that supports API key authentication. 

When going through the docs and source for the `google-cloud-ruby` client, I am unable to determine how to authenticate with a given `project_id` and `api_key`. I only see support for authenticating using a `keyfile`. How would I be able to instantiate a `Google::Cloud::Language` client with an `api_key`?

**Comment by blowmage** [comment]
@geigerj @jbolinger Do you guys have an answer for this? Do the GAPIC-only clients have support, or plan to support, use of API Keys instead of service account credentials?

**Comment by jbolinger** [comment]
There is no plan to support this.

**Comment by blowmage** [comment]
@Orevarc, the direction given for authentication with the Google Cloud libraries has been to support service accounts as the primary authentication mechanism. The only library that currently supports API Keys is Translate (google-cloud-translate). Looking at the [Using API Keys](https://cloud.google.com/docs/authentication/api-keys) document you linked to, it also says that service accounts should be the primary mechanism as well.

I'm not 100% sure on this, but my understanding is that API Keys would only be able to be used on REST API endpoints. The Google Cloud gems for Natural Language, Speech, and Vision all use gRPC to access the RPC API endpoints. This may explain why there are no plans to support API Keys in those gems.

**Comment by Orevarc** [comment]
@blowmage @jbolinger Thank you for both the quick responses! Looks like I'll either have to switch to querying the REST API endpoint or obtain service account credentials and use this gem.

**Comment by blowmage** [comment]
Thanks for the question. Best of luck!
