### ISSUE TITLE
pubsub: hanging in alpine

### ISSUE THREAD

**Issue by jadekler** [GoogleCloudPlatform/google-cloud-ruby#2008]
I'm trying to use pubsub. I have a very basic subscriber - [full code here](https://gist.github.com/jadekler/ac4fde6c7fe45e8c274dad579921f415). I have a very basic alpine dockerfile - [full code here](https://gist.github.com/jadekler/ac8ef447662cad3ae13ad70abfac7cc3).

When I run this dockerfile, `require 'google/cloud/pubsub'` hangs forever.

What gives?

edit: For the record, it works fine outside the docker image on my mac.

edit2: _Only_ happens when I require `google/cloud/pubsub`. Other requires work fine.

edit3: Happens with and without compiling gems from source (`BUNDLE_FORCE_RUBY_PLATFORM=1`).

**Comment by jadekler** [comment]
Possibly related to https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1351

**Comment by blowmage** [comment]
Hi @jadekler, I'm looking into this, but what you are describing is certainly perplexing. Have you tried replacing your code with only the require to see if it also hangs?

When you say it works on other requires, what requires do you mean? Does it work with Google Cloud Datastore?

**Comment by blowmage** [comment]
How are you running your Docker container? Are you running it locally on your mac? If so, are you running Docker for Mac or Docker Toolbox? Or are you running this on a server? If so, where?

**Comment by jadekler** [comment]
Wayyyy later I get this error:

```
#<Thread:0x00005599632d12f0@/usr/local/bundle/gems/google-cloud-pubsub-0.30.1/lib/google/cloud/pubsub/subscriber/stream.rb:270 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/google-cloud-pubsub-0.30.1/lib/google/cloud/pubsub/subscriber/stream.rb:242:in `rescue in background_run': 16:Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project. (Google::Cloud::UnauthenticatedError)
	from /usr/local/bundle/gems/google-cloud-pubsub-0.30.1/lib/google/cloud/pubsub/subscriber/stream.rb:193:in `background_run'
	from /usr/local/bundle/gems/google-cloud-pubsub-0.30.1/lib/google/cloud/pubsub/subscriber/stream.rb:271:in `block in start_streaming!'
#<Thread:0x00005599632c3808@/usr/local/bundle/gems/google-cloud-pubsub-0.30.1/lib/google/cloud/pubsub/subscriber/stream.rb:270 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/google-cloud-pubsub-0.30.1/lib/google/cloud/pubsub/subscriber/stream.rb:242:in `rescue in background_run': 16:Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project. (Google::Cloud::UnauthenticatedError)
	from /usr/local/bundle/gems/google-cloud-pubsub-0.30.1/lib/google/cloud/pubsub/subscriber/stream.rb:193:in `background_run'
	from /usr/local/bundle/gems/google-cloud-pubsub-0.30.1/lib/google/cloud/pubsub/subscriber/stream.rb:271:in `block in start_streaming!'
#<Thread:0x00005599632d2b50@/usr/local/bundle/gems/google-cloud-pubsub-0.30.1/lib/google/cloud/pubsub/subscriber/stream.rb:270 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/google-cloud-pubsub-0.30.1/lib/google/cloud/pubsub/subscriber/stream.rb:242:in `rescue in background_run': 16:Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project. (Google::Cloud::UnauthenticatedError)
	from /usr/local/bundle/gems/google-cloud-pubsub-0.30.1/lib/google/cloud/pubsub/subscriber/stream.rb:193:in `background_run'
	from /usr/local/bundle/gems/google-cloud-pubsub-0.30.1/lib/google/cloud/pubsub/subscriber/stream.rb:271:in `block in start_streaming!'
#<Thread:0x00005599632d0738@/usr/local/bundle/gems/google-cloud-pubsub-0.30.1/lib/google/cloud/pubsub/subscriber/stream.rb:270 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/google-cloud-pubsub-0.30.1/lib/google/cloud/pubsub/subscriber/stream.rb:242:in `rescue in background_run': 16:Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project. (Google::Cloud::UnauthenticatedError)
	from /usr/local/bundle/gems/google-cloud-pubsub-0.30.1/lib/google/cloud/pubsub/subscriber/stream.rb:193:in `background_run'
	from /usr/local/bundle/gems/google-cloud-pubsub-0.30.1/lib/google/cloud/pubsub/subscriber/stream.rb:271:in `block in start_streaming!'
```

I've also tried installing `ca-certificates` to no avail.

**Comment by jadekler** [comment]
@blowmage 

- Removing everything except the require, no more problem. So, must be further down despite my logging (logs not working as I'd expect for some reason?). Looking into this more..
- I've tried `require json` and it works fine
- This is running locally on docker for mac. I'm using `docker run foo`; no bells and whistles

**Comment by jadekler** [comment]
So, another update: I've individually remove line by line and there doesn't seem to be any issue with any individual line. When I place the loop [1] back in, that's when I start having issues - my logs apart from the very first one before the `require` don't work, I never receive any messages, etc. I'm wondering whether the loop is the problem. What's the idiomatic way to "wait for messages forever"?

1: 

```
loop do
  sleep 300
end
```

**Comment by blowmage** [comment]
We usually encourage calling sleep with no arguments.

**Comment by jadekler** [comment]
Right on. I put that in, same problem. @blowmage any other ideas?

**Comment by jadekler** [comment]
This fails on other OSes too; just tried jessie.

**Comment by jadekler** [comment]
New error:

```
#<Thread:0x00005603797b3658@/usr/local/bundle/gems/grpc-1.10.0/src/ruby/lib/grpc/generic/bidi_call.rb:74 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/grpc-1.10.0/src/ruby/lib/grpc/generic/bidi_call.rb:158:in `run_batch': call#run_batch failed somehow (GRPC::Core::CallError)
	from /usr/local/bundle/gems/grpc-1.10.0/src/ruby/lib/grpc/generic/bidi_call.rb:158:in `write_loop'
	from /usr/local/bundle/gems/grpc-1.10.0/src/ruby/lib/grpc/generic/bidi_call.rb:75:in `block in run_on_client'
```

**Comment by blowmage** [comment]
> This fails on other distros too; just tried jessie.

To be clear, this is failing for you on debian _inside_ a docker container? Not in a normal VM, right?

**Comment by blowmage** [comment]
Can you make a couple changes and let us know what output you get. (If its too big for a comment can you put it in a gist?)

Set the following environment variables: `GRPC_TRACE=all` and `GRPC_VERBOSITY=debug`

When you create the subscriber object, can you pass the argument `streams: 1`? This will reduce the number of messages a bit and make the output easier to follow.

**Comment by jadekler** [comment]
Hey @blowmage. I probably won't have time to today, and I'm about to go on vacation unfortunately. I'll check in on this issue periodically, and @jonparrott may also. The code above should be enough to repro, though - let me know if you're not able to.

**Comment by jadekler** [comment]
And, yessir, a container running on a mac.

**Comment by blowmage** [comment]
Unfortunately, I have yet to successfully reproduce the behavior you are seeing. I have [posted my repro files here](https://gist.github.com/blowmage/8f65e8c186a5a822c85ab26d7aeea386). The only substantive change I made was to remove the custom SSL certificate and creating the `SSL_CERT_FILE` environment variable. From my tests so far I don't think a custom SSL cert is needed when running on Alpine Linux, and ultimately I think might be a candidate to explain the behavior described in this issue.

In the directory with my repro files (with all the necessary values added) I build the container which will download and compile the `grpc` and `google-protobuf` gems:

```
$ docker build -t gcps .
Sending build context to Docker daemon  10.24kB
Step 1/9 : FROM ruby:2.5.0-alpine3.7
 ---> 8ea9c590ec75
Step 2/9 : RUN apk update
 ---> Using cache
 ---> 42ff52238df6
Step 3/9 : RUN apk add gcc musl-dev cmake alpine-sdk linux-headers
 ---> Using cache
 ---> d46e1c694df3
Step 4/9 : ENV GOOGLE_CLOUD_PROJECT <project-id>
 ---> Using cache
 ---> 4462f6b89a7e
Step 5/9 : ENV GOOGLE_CLOUD_CREDENTIALS /rb-app/creds.json
 ---> Using cache
 ---> 02978ddc1c1e
Step 6/9 : ADD . /rb-app
 ---> dce64b894f48
Step 7/9 : WORKDIR /rb-app
Removing intermediate container 9cbd0046d810
 ---> 319271cdb5fb
Step 8/9 : RUN BUNDLE_FORCE_RUBY_PLATFORM=1 bundle install
 ---> Running in 34cf2c644335
Fetching gem metadata from https://rubygems.org/........
Fetching public_suffix 3.0.2
Installing public_suffix 3.0.2
Fetching addressable 2.5.2
Installing addressable 2.5.2
Using bundler 1.16.1
Fetching concurrent-ruby 1.0.5
Installing concurrent-ruby 1.0.5
Fetching multipart-post 2.0.0
Installing multipart-post 2.0.0
Fetching faraday 0.14.0
Installing faraday 0.14.0
Fetching google-cloud-env 1.0.1
Installing google-cloud-env 1.0.1
Fetching google-cloud-core 1.2.0
Installing google-cloud-core 1.2.0
Fetching google-protobuf 3.5.1.2
Installing google-protobuf 3.5.1.2 with native extensions
Fetching googleapis-common-protos-types 1.0.1
Installing googleapis-common-protos-types 1.0.1
Fetching jwt 2.1.0
Installing jwt 2.1.0
Fetching little-plugger 1.1.4
Installing little-plugger 1.1.4
Fetching multi_json 1.13.1
Installing multi_json 1.13.1
Fetching logging 2.2.2
Installing logging 2.2.2
Fetching memoist 0.16.0
Installing memoist 0.16.0
Fetching os 0.9.6
Installing os 0.9.6
Fetching signet 0.8.1
Installing signet 0.8.1
Fetching googleauth 0.6.2
Installing googleauth 0.6.2
Fetching grpc 1.10.0
Installing grpc 1.10.0 with native extensions
Fetching googleapis-common-protos 1.3.7
Installing googleapis-common-protos 1.3.7
Fetching rly 0.2.3
Installing rly 0.2.3
Fetching google-gax 1.0.1
Installing google-gax 1.0.1
Fetching grpc-google-iam-v1 0.6.9
Installing grpc-google-iam-v1 0.6.9
Fetching google-cloud-pubsub 0.30.1
Installing google-cloud-pubsub 0.30.1
Bundle complete! 1 Gemfile dependency, 24 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
Removing intermediate container 34cf2c644335
 ---> 5ac2e03f31a6
Step 9/9 : CMD ruby /rb-app/app.rb
 ---> Running in 6c40529ccda0
Removing intermediate container 6c40529ccda0
 ---> 94cfc1fc33b1
Successfully built 94cfc1fc33b1
Successfully tagged gcps:latest
```

Then I run the container:

```
$ docker run -itP gcps
req
Ruby starting up
Creating new
Sub exists/creates
Sub listen
Ruby receiving..
```

In a separate local IRB session running on my development machine, outside of docker, I publish a topic and see it printed in the running container's output:

```
Ruby received 56499154387317 hello docker!
```

I let the process run for the next ~30 minutes, occasionally publishing new topics and seeing the messages printed in the container's output:

```
Ruby received 56501839940861 hello again docker!
Ruby received 56506532299010 hello docker, thrice!
```

After ~30 minutes I see the following printed in the container's output:

```
#<Thread:0x0000561f9919d598@/usr/local/bundle/gems/grpc-1.10.0/src/ruby/lib/grpc/generic/bidi_call.rb:74 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	2: from /usr/local/bundle/gems/grpc-1.10.0/src/ruby/lib/grpc/generic/bidi_call.rb:75:in `block in run_on_client'
	1: from /usr/local/bundle/gems/grpc-1.10.0/src/ruby/lib/grpc/generic/bidi_call.rb:158:in `write_loop'
/usr/local/bundle/gems/grpc-1.10.0/src/ruby/lib/grpc/generic/bidi_call.rb:158:in `run_batch': call#run_batch failed somehow (GRPC::Core::CallError)
```

This is due to an internal error within GRPC. The streaming connection that the Pub/Sub Subscriber uses may fail. GRPC is a little too chatty and has printed the preceding message to stdout. However, the Pub/Sub Subscriber is resilient to these types of failures and has silently recovered and recreated the streaming connection. I publish another message and see it show up in the container's output:

```
Ruby received 56513448444006 hello docker, quad!
```

So far I haven't been able to get a container running Google Cloud Pub/Sub code on Alpine Linux to fail in any unexpected ways. But I haven't yet fully completed my tests specifying a custom SSL cert. So if a custom SSL cert is necessary for this issue then there may still be a problem somewhere.

I'll post another reply once I've completed the next set of tests.

**Comment by blowmage** [comment]
I should add that I am also using Docker for Mac, Version 17.12.0-ce-mac55 (23011).

**Comment by jadekler** [comment]
AH. `-it`. It was working fine, but for some reason the `STDIN` must have been getting unattached. Man. Thank you, you rock.

**Comment by quartzmo** [comment]
Yes, great work @blowmage!
