### ISSUE TITLE
pubsub: errors warning every 10 minutes

### ISSUE THREAD

**Issue by jadekler** [GoogleCloudPlatform/google-cloud-ruby#2010]
Every 10 minutes, on the dot, I get errors about bidi connections. These do not seem to be preventing the app from pulling messages, or crashing the app, but they are quite concerning. Any idea what's going on here?

![screen shot 2018-03-17 at 4 37 49 pm](https://user-images.githubusercontent.com/3584893/37561047-c203abd8-2a01-11e8-917a-646a43d4a7ec.png)

![screen shot 2018-03-17 at 4 41 46 pm](https://user-images.githubusercontent.com/3584893/37561059-222e63a4-2a02-11e8-8f0e-6a1488e0b602.png)
![screen shot 2018-03-17 at 4 41 51 pm](https://user-images.githubusercontent.com/3584893/37561060-2246ca48-2a02-11e8-830c-ad59f008f609.png)
![screen shot 2018-03-17 at 4 41 54 pm](https://user-images.githubusercontent.com/3584893/37561061-225afcac-2a02-11e8-85fa-c5f1597b8102.png)
![screen shot 2018-03-17 at 4 41 58 pm](https://user-images.githubusercontent.com/3584893/37561062-227013a8-2a02-11e8-9705-05ea20cd8c79.png)

**Comment by jadekler** [comment]
Under load (~30 million messages in the subscription), the app entirely stops receiving new messages.

Here's the app:

```
ruby app.rb

require 'google/cloud/pubsub'

puts 'Ruby starting up'

PROJECT_ID = 'some-project'
TOPIC_ID = 'some-topic'
SUBSCRIPTION_ID = 'some-ruby-subscription'

pubsub = Google::Cloud::Pubsub.new(
    project_id: PROJECT_ID,
    credentials: ENV['GOOGLE_APPLICATION_CREDENTIALS']
)

topic = pubsub.topic TOPIC_ID
subscription = topic.subscription SUBSCRIPTION_ID

puts 'Ruby sub exists/creates'

if subscription == nil || !subscription.exists?
  subscription = topic.subscribe SUBSCRIPTION_ID
end

subscriber = subscription.listen do |received_message|
  puts "Ruby received #{received_message.message_id} #{received_message.data}"
  received_message.acknowledge!
end

puts 'Ruby receiving..'

subscriber.start

sleep

subscriber.stop.wait!
```

Here's a graph show this:

![screen shot 2018-03-17 at 5 40 00 pm](https://user-images.githubusercontent.com/3584893/37561367-3faa517e-2a0a-11e8-8e0e-cdb9b29db474.png)

**Comment by blowmage** [comment]
The GAPIC client is configured to keep streaming connections open for 10 minutes. After 10 minutes it closes the streaming connection and raised an error. The Pub/Sub Subscriber handles the error by recreating the streaming connection, adding the messages in the stream inventory to the new connection. So this is not something to be concerned about. 

We would love to be able to keep a streaming connection open indefinitely, but this does not seem possible with the current GAPIC client.

**Comment by blowmage** [comment]
Your second comment seems to be a completely different issue. Can you open a new issue with any additional information, such as GRPC logs? If you stop and restart the process does it do the same thing?

**Comment by jadekler** [comment]
Done! https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/2011
