### ISSUE TITLE
pubsub: consumer crashes / stops receiving messages after couple minutes

### ISSUE THREAD

**Issue by jadekler** [GoogleCloudPlatform/google-cloud-ruby#2011]
Under load (~30 million messages in the subscription), the app entirely stops receiving new messages.

Here's the app:

```
ruby app.rb

require 'google/cloud/pubsub'

puts 'Ruby starting up'

PROJECT_ID = 'some-project'
TOPIC_ID = 'some-topic'
SUBSCRIPTION_ID = 'some-ruby-subscription'

pubsub = Google::Cloud::Pubsub.new(
    project_id: PROJECT_ID,
    credentials: ENV['GOOGLE_APPLICATION_CREDENTIALS']
)

topic = pubsub.topic TOPIC_ID
subscription = topic.subscription SUBSCRIPTION_ID

puts 'Ruby sub exists/creates'

if subscription == nil || !subscription.exists?
  subscription = topic.subscribe SUBSCRIPTION_ID
end

subscriber = subscription.listen do |received_message|
  puts "Ruby received #{received_message.message_id} #{received_message.data}"
  received_message.acknowledge!
end

puts 'Ruby receiving..'

subscriber.start

sleep

subscriber.stop.wait!
```

Here's a graph show this:

![screen shot 2018-03-17 at 5 40 00 pm](https://user-images.githubusercontent.com/3584893/37561367-3faa517e-2a0a-11e8-8e0e-cdb9b29db474.png)

At this point, the app no longer emits any logs. And, although kubernetes tells me the app is still alive, its CPU is at 0.

![screen shot 2018-03-17 at 5 42 04 pm](https://user-images.githubusercontent.com/3584893/37561376-88368caa-2a0a-11e8-90d0-73d0eef1a392.png)

**Comment by blowmage** [comment]
Does this happen as soon as the Ruby process is started? Or does the Ruby process run for a while, and then the spike happens?

**Comment by blowmage** [comment]
@jadekler Can you answer these questions? Also, about how long does it run, and about how many messages does it acknowledge, before it stops processing?

**Comment by jadekler** [comment]
Hey Mike, sorry for the long delay. I'm out of the country atm (and south africa has very inconsistent wifi availability) so I'll be pretty slow next couple weeks in replying. The failure happened some 10 minutes after the process started. About 300,000 messages were acked at a rate of about 37,000 per minute.

I was able to repro this just now by just restarting the pod. This is all being run on a very minimal / no-special-config docker image that I stuck on GKE.

<img width="694" alt="screen shot 2018-03-20 at 10 29 18 pm" src="https://user-images.githubusercontent.com/3584893/37695691-55a0c0b8-2c8e-11e8-9509-24d3dd3cbd11.png">

**Comment by blowmage** [comment]
@jadekler We have released google-cloud-pubsub 0.30.2, which works around an [GRPC client issue](grpc/grpc#14853) as well as adds some performance tweaks. I've been able to process 10 million records in ~30 minutes on a 1vCPU GCE compute instance. Can you please update to the latest release and try your perf test again?

**Comment by jadekler** [comment]
@blowmage Prelim results look good! I'll leave it running for ~3 days

![screen shot 2018-04-02 at 11 55 10 am](https://user-images.githubusercontent.com/3584893/38210594-b777c7b8-366c-11e8-9c27-db30d5d19624.png)

**Comment by jadekler** [comment]
Looks great! Chugged through 50m messages with no problems 👍
