### ISSUE TITLE
Support service account creds in VideoIntelligenceApi

### ISSUE THREAD

**Issue by andresbravog** [GoogleCloudPlatform/google-cloud-ruby#2018]
# What

The Authentication Docs stand that we can use `GOOGLE_CLOUD_PROJECT`  and `GOOGLE_CLOUD_KEYFILE_JSON` pair for credentials but `VideoIntelligenceApi` uses https://github.com/google/google-auth-library-ruby/blob/v0.6.0/lib/googleauth/credentials_loader.rb#L74 that only looks at `GOOGLE_APPLICATION_CREDENTIALS` being impossible to set up without a json cred file.

**Comment by blowmage** [comment]
@andresbravog The [Credentials configuration](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-video_intelligence/lib/google/cloud/video_intelligence/credentials.rb#L24-L25) lists `GOOGLE_CLOUD_KEYFILE_JSON`, so this should be supported. Can you post an example of the code you are using that is not using this? Are you calling `Google::Cloud::VideoIntelligence.new` to get the client object?

I don't see where a project_id is used in the API calls, so I don't know where `GOOGLE_CLOUD_PROJECT` would be used. But libraries like Video Intelligence, that are generated code only for calling the APIs only, typically don't use that environment variable anyway. The project_id value is usually an argument provided API methods. The `GOOGLE_CLOUD_PROJECT` environment variable is used in libraries like Datastore and Storage, that offer a more traditional Ruby API on top of the generated code to call the underlying Google service.

**Comment by andresbravog** [comment]
Thanks @blowmage, that's the expected behavior, to have the `Google::Cloud::VideoIntelligence` using `GOOGLE_CLOUD_KEYFILE_JSON`, but is not, you get a failure unless you set `GOOGLE_APPLICATION_CREDENTIALS`.

In this example you can see how you can easily replicate this issue having `GOOGLE_CLOUD` env vars set and `VideoIntelligence` will fail while `Vision` will work nicely:

```ruby
[6] pry(main)> ENV['GOOGLE_CLOUD_PROJECT'].present? && ENV['GOOGLE_CLOUD_KEYFILE_JSON'].present?
=> true
[7] pry(main)> @api = Google::Cloud::VideoIntelligence.new
RuntimeError: Could not load the default credentials. Browse to
https://developers.google.com/accounts/docs/application-default-credentials
for more information
from /box/gems/googleauth-0.5.1/lib/googleauth.rb:119:in `get_application_default'
[8] pry(main)> @api = Google::Cloud::Vision.new
NameError: uninitialized constant Google::Cloud::Vision
from (pry):8:in `<main>'
[9] pry(main)> require "google/cloud/vision"
=> true
[10] pry(main)> @api = Google::Cloud::Vision.new
=> #<Google::Cloud::Vision::Project:0x000000000626c608 @service=Google::Cloud::Vision::Service(my-project-id)>
```

This is because `Google::Cloud::VideoIntelligence` uses `google-auth-library` for authentication what just checks for `GOOGLE_APPLICATION_CREDENTIALS` env var. The code looks good to me, it seems to first look into the right ENV var:

https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/5b3202177038ede37840bf5e7853e539a41fbb62/google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/video_intelligence_service_client.rb#L101

```ruby
credentials ||= Google::Cloud::VideoIntelligence::Credentials.default
```

https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/5b3202177038ede37840bf5e7853e539a41fbb62/google-cloud-video_intelligence/lib/google/cloud/video_intelligence/credentials.rb#L25

```ruby
        JSON_ENV_VARS = %w(VIDEO_INTELLIGENCE_KEYFILE_JSON GOOGLE_CLOUD_KEYFILE_JSON GCLOUD_KEYFILE_JSON)
```

https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/874c5297b1c9e03364fe632a8b5e7a56f0eab709/google-cloud-core/lib/google/cloud/credentials.rb#L88
```ruby
module Google
  module Cloud
    ##
    # @private
    # Represents the OAuth 2.0 signing logic.
    # This class is intended to be inherited by API-specific classes
    # which overrides the SCOPE constant.
    class Credentials
      TOKEN_CREDENTIAL_URI = "https://accounts.google.com/o/oauth2/token"
      AUDIENCE = "https://accounts.google.com/o/oauth2/token"
      SCOPE = []
      PATH_ENV_VARS = %w[GOOGLE_CLOUD_KEYFILE GCLOUD_KEYFILE]
      JSON_ENV_VARS = %w[GOOGLE_CLOUD_KEYFILE_JSON GCLOUD_KEYFILE_JSON]
      DEFAULT_PATHS = ["~/.config/gcloud/application_default_credentials.json"]

...

      ##
      # Returns the default credentials.
      #
      def self.default scope: nil
        env  = ->(v) { ENV[v] }
        json = ->(v) { JSON.parse ENV[v] rescue nil unless ENV[v].nil? }
        path = ->(p) { ::File.file? p }

        # First try to find keyfile file from environment variables.
        self::PATH_ENV_VARS.map(&env).compact.select(&path).each do |file|
          return new file, scope: scope
        end
        # Second try to find keyfile json from environment variables.
        self::JSON_ENV_VARS.map(&json).compact.each do |hash|
          return new hash, scope: scope
        end
        # Third try to find keyfile file from known file paths.
        self::DEFAULT_PATHS.select(&path).each do |file|
          return new file, scope: scope
        end
        # Finally get instantiated client from Google::Auth.
        scope ||= self::SCOPE
        client = Google::Auth.get_application_default scope
        new client
      end

...
```

https://github.com/google/google-auth-library-ruby/blob/c148fc12bb2fee7dc53e2dc2157f2aa6fa6378d8/lib/googleauth/application_default.rb#L57
```ruby
...

    def get_application_default(scope = nil, options = {})
      creds = DefaultCredentials.from_env(scope) ||
              DefaultCredentials.from_well_known_path(scope) ||
              DefaultCredentials.from_system_default_path(scope)
      return creds unless creds.nil?
      raise NOT_FOUND_ERROR unless GCECredentials.on_gce?(options)
      GCECredentials.new
    end

...
```

https://github.com/google/google-auth-library-ruby/blob/v0.6.0/lib/googleauth/credentials_loader.rb#L74
```ruby
module Google
  # Module Auth provides classes that provide Google-specific authorization
  # used to access Google APIs.
  module Auth
    # CredentialsLoader contains the behaviour used to locate and find default
    # credentials files on the file system.
    module CredentialsLoader
      extend Memoist
      ENV_VAR = 'GOOGLE_APPLICATION_CREDENTIALS'.freeze

...

 # Creates an instance from the path specified in an environment
      # variable.
      #
      # @param scope [string|array|nil] the scope(s) to access
      def from_env(scope = nil)
        if ENV.key?(ENV_VAR)
          path = ENV[ENV_VAR]
          raise "file #{path} does not exist" unless File.exist?(path)
          File.open(path) do |f|
            return make_creds(json_key_io: f, scope: scope)
          end
        elsif service_account_env_vars? || authorized_user_env_vars?
          return make_creds(scope: scope)
        end
      rescue StandardError => e
        raise "#{NOT_FOUND_ERROR}: #{e}"
      end

...
```

but seems to not work as expected:

```ruby
[2] pry(main)> ENV['GOOGLE_APPLICATION_CREDENTIALS'] = nil
=> nil
[3] pry(main)> ENV['GOOGLE_CLOUD_PROJECT'].present? && ENV['GOOGLE_CLOUD_KEYFILE_JSON'].present?
=> true
[4] pry(main)> Google::Cloud::VideoIntelligence.new
RuntimeError: Could not load the default credentials. Browse to
https://developers.google.com/accounts/docs/application-default-credentials
for more information
from /box/gems/googleauth-0.5.1/lib/googleauth.rb:119:in `get_application_default'
[5] pry(main)> Google::Cloud::VideoIntelligence
=> Google::Cloud::VideoIntelligence
[6] pry(main)> Google::Cloud::VideoIntelligence::Credentials.default
RuntimeError: Could not load the default credentials. Browse to
https://developers.google.com/accounts/docs/application-default-credentials
for more information
from /box/gems/googleauth-0.5.1/lib/googleauth.rb:119:in `get_application_default'
[7] pry(main)> Google::Cloud::VideoIntelligence::Credentials::JSON_ENV_VARS
=> ["VIDEO_INTELLIGENCE_KEYFILE_JSON,", "GOOGLE_CLOUD_KEYFILE_JSON,", "GCLOUD_KEYFILE_JSON"]
[8] pry(main)>
```

Will keep the investigation.

**Comment by andresbravog** [comment]
@blowmage, actually, I saw the issue, check trailing commas here

```ruby
[7] pry(main)> Google::Cloud::VideoIntelligence::Credentials::JSON_ENV_VARS
=> ["VIDEO_INTELLIGENCE_KEYFILE_JSON,", "GOOGLE_CLOUD_KEYFILE_JSON,", "GCLOUD_KEYFILE_JSON"]
```

**Comment by andresbravog** [comment]
fixed on https://github.com/GoogleCloudPlatform/google-cloud-ruby/commit/b1802995b869aa518bd4ee7c27fd230e3909657d#diff-3c8bc4993d803145ca54225578109f7c

**Comment by andresbravog** [comment]
I just need to bump the gem version. We can close this, sorry for the inconvenience.

**Comment by blowmage** [comment]
Glad you got it figured out! Thanks for opening the issue. Hopefully it will be found by others who run into this.
