### ISSUE TITLE
Updated monitoring functionality

### ISSUE THREAD

**Issue by krogebry** [GoogleCloudPlatform/google-cloud-ruby#2023]
Monitoring service recently started supporting policy things.  Can we please have an update which would include functionality for these shiny new bits?

My use case for this is to be able to create lots of awesome policies so we can move away from the old, crufty thing we're using in AWS::CloudWatch.

I was thinking about trying to crank out the work myself, but it almost seems like you have a way to scrape the APIs and automagically generate large parts of the code.  If that's not the case, happy to try throwing down on this functionality, I figured I'd at least ask first.

**Comment by blowmage** [comment]
@dazuma Can you take this issue?

**Comment by krogebry** [comment]
If possible, I'd love to know how you ended up doing this.  Was it just a matter of writing the code, or do you have fancy scripts to make this easier?  I'm happy to throw down on this if someone could maybe throw me a checklist of things that would need to be done.

**Comment by dazuma** [comment]
[google-cloud-monitoring](https://rubygems.org/gems/google-cloud-monitoring) 0.28 was released a couple weeks ago, covering the v3 API. Closing.
