### ISSUE TITLE
Bucket#signed_url for resumable uploads

### ISSUE THREAD

**Issue by pugsiman** [GoogleCloudPlatform/google-cloud-ruby#2024]
Hey, I've been reading a lot lately about how to initiate resumable uploads for my bucket.
I'm trying to implement a feature where I directly upload a file to a bucket from the UI in a resumable fashion. I thought a good way to implement that would be to get a signed url back from my back-end and PUT directly to it. I had great success with the normal method of uploading this way, but sadly it doesn't look like the gem supports a way to initiate it in a resumable fashion. Am I missing something here?

For reference, I'm referring to these:
~~https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload~~
https://cloud.google.com/storage/docs/xml-api/resumable-upload
https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.51.1/google/cloud/storage/bucket?method=signed_url-instance

**Comment by quartzmo** [comment]
@pugsiman Thanks for opening this issue, and sorry for the delay in responding. We'll look into this today for you.

**Comment by quartzmo** [comment]
Sorry for the delay. I found some additional background info:

* [Using signed URLs with resumable uploads](https://cloud.google.com/storage/docs/access-control/signed-urls#signing-resumable)
* [JSON API - Performing a Resumable Upload](https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload)
* [`createResumableUpload` in google-cloud-node/storage](https://cloud.google.com/nodejs/docs/reference/storage/1.6.x/File#createResumableUpload)
* [stephenplusplus/gcs-resumable-upload](https://github.com/stephenplusplus/gcs-resumable-upload)

I'm wondering if you can use `Bucket#signed_url` with `method: "PUT"` (and other options as needed) to initiate the sequence explained in [JSON API - Performing a Resumable Upload](https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload), then handle the rest of the sequence yourself? That's what you want to do, right? Have you tried it? Sorry in advance if I'm misunderstanding.

**Comment by quartzmo** [comment]
@stephenplusplus I'm wondering if you might be able to take a quick look at what we have now, and perhaps comment on what we might consider adding? We have [`Bucket#signed_url`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage/bucket.rb#L850-L956) (which delegates to [`File::Signer#signed_url`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage/file/signer.rb#L107)) and [`Bucket#create_file`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage/bucket.rb#L562-L738).

**Comment by stephenplusplus** [comment]
This sounds like something we recently implemented in Node.js, and were caught off guard by that it even existed (as such, advanced apologies that I'm not as good of a resource as @frankyn might be).

Here's the issue we got: [whole thing](https://github.com/googleapis/nodejs-storage/issues/20) or [just the important part](https://github.com/googleapis/nodejs-storage/issues/20#issuecomment-331293506), and the PR: https://github.com/googleapis/nodejs-storage/pull/129.

Hopefully we're in the right neighborhood of what @pugsiman is looking for.

**Comment by quartzmo** [comment]
@stephenplusplus Thank you!

@frankyn Do you have any suggestions regarding this request?

**Comment by frankyn** [comment]
Hi all, 
Clarifying, `storage.googleapis.com` is the XML API endpoints for GCS. I'd recommend following documentation [here](https://cloud.google.com/storage/docs/xml-api/resumable-upload). Signed URLs only work for the XML API.  

IIUC @pugsiman you want to generate a signedURL with `POST` method.  Then forward that to the UI then use a Javascript AJAX request to perform the `PUT`.

Unless I have misunderstood, the Ruby client doesn't need to be changed to generate a signed url for resumable uploads: (_However, it would be nice to have a simpler way of generating a resumable upload session URL as it's a pain._)

```ruby
require "google/cloud/storage"
require "net/http"

storage = Google::Cloud::Storage.new
bucket = storage.bucket "bucket-name"
file = bucket.file "test-file", skip_lookup: true # file may not exist.
signed_url = file.signed_url(method: "POST",
                             content_type: "image/jpeg",
                             headers: {'x-goog-resumable':'start'})

# Ruby example of getting the resumable session.
# Create the HTTP object
uri = URI.parse(signed_url)
https = Net::HTTP.new(uri.host, uri.port)
https.use_ssl = true
# https.set_debug_output $stderr # debugging purposes only

# Prepare POST request to get resumable session
headers = {'x-goog-resumable': 'start'}
request = Net::HTTP::Post.new(uri.request_uri, headers)
request.content_type = "image/jpeg"

# Send POST request to get resumable session URL.
response = https.request(request)

# Process response
resumable_session_url =  response["location"] # You can continue onto step 3 with follow-up PUT requests.

# Continue with PUTs
```

**Comment by frankyn** [comment]
Full example with **no error recovery**. Example reads from STDIN and can be ran by using:
```bash
cat file.ext | ruby stream_upload.rb
```

### stream_upload.rb
```ruby
require "google/cloud/storage"
require "net/http"

storage = Google::Cloud::Storage.new
bucket = storage.bucket "bucket-name"
file = bucket.file "test-file", skip_lookup: true # file may not exist.
signed_url = file.signed_url(method: "POST",
                             content_type: "text/plain",
                             headers: {"x-goog-resumable":"start"})

# Ruby example of getting the resumable session.
# Create the HTTP object
uri = URI.parse(signed_url)
https = Net::HTTP.new(uri.host, uri.port)
https.use_ssl = true
# https.set_debug_output $stderr # debugging purposes only

# Prepare POST request to get resumable session
headers = {"x-goog-resumable": "start"}
request = Net::HTTP::Post.new(uri.request_uri, headers)
request.content_type = "text/plain"

# Send POST request to get resumable session URL.
response = https.request(request)

# Process response
resumable_session_url =  response["location"]

# Continue with PUTs
# chunk_size can be increased but uploaded chunks need to be a multiple of 256 kibibytes or 262,144 bytes.
chunk_size = 256*1024
last_byte = 0
total_bytes = 0
headers = {}

file = STDIN
while !file.eof?
  chunk = file.read(chunk_size)
  total_bytes += chunk.size

  if chunk.size == chunk_size && !file.eof?
    headers["Content-Range"] = "bytes #{last_byte}-#{last_byte+chunk_size-1}/*"
  else
    headers["Content-Range"] = "bytes #{last_byte}-#{last_byte+chunk.size-1}/#{total_bytes}"
  end
  headers["Content-Length"] = chunk.size.to_s
  last_byte += chunk.size

  request = Net::HTTP::Put.new(resumable_session_url, headers)
  request.content_type = "text/plain"
  request.body = chunk
  response = https.request(request)

  case response.code
  when "200"
    puts "Completed upload"
  when "308"
    puts response["Range"]
  else
    raise "Unhandled response code #{response.code}"
  end
end
```

**Comment by quartzmo** [comment]
@frankyn Thank you for these solutions, and perhaps most critically, for identifying [Resumable Uploads with the XML API](https://cloud.google.com/storage/docs/xml-api/resumable-upload) as the best instructions for resumable uploads with Google Cloud Storage. (@frankyn noted also that: "Signed URLs only work for the XML API.") I will update my earlier comment on background info.

**Comment by quartzmo** [comment]
@pugsiman Can you try @frankyn's [solution](https://gist.github.com/frankyn/9a5344d1b19ed50ebbf9f15f0ff92032) and let us know if it works for you?

**Comment by pugsiman** [comment]
@quartzmo @frankyn @stephenplusplus Thank you everyone for helping! I was sick in the last week so I didn't get a chance to try frankyn's solution, I'll update here my results as soon as I have the chance.

**Comment by frankyn** [comment]
Thanks for getting back to us!

Are you using the script or did you try implementing your own? Could you
share what you have?

If you are using the script it may be a mismatch between headers and query
parameters with the signed url. The request needs to match the signed url
form.

**Comment by quartzmo** [comment]
@pugsiman Please let us know what we still need to do to close this issue, thanks!

**Comment by pugsiman** [comment]
Well I ran it again and it worked, I have no idea what was changed so forgive me. My JS code looks something like this:
```
    var xhr = new XMLHttpRequest();
    document.querySelector('input[type="submit"]').addEventListener('click', function() {
        let signedURL = 
        xhr.open('POST', signedURL, true)
        xhr.setRequestHeader('Content-Type', 'csv/text');
        xhr.setRequestHeader('x-goog-resumable', 'start');

        xhr.onload = function() {
            if (this.status >= 200 && this.status < 400) {
                uploadCsvToGcloud(this.getResponseHeader('location'));
            }
        }

        xhr.send();
    });

    function uploadCsvToGcloud(responseURL) {
        let csv = document.querySelector('input[type="file"]').files[0]

        xhr.open('PUT', responseURL, true);
        xhr.onload = function() {
            console.log('uplodaed to bucket');
            doSomething();
        };

        xhr.send(csv);
    }
```

**Comment by bibendi** [comment]
It seems the Gist doesn't work anymore.
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidAuthentication</Code><Message>The provided authentication header is invalid.</Message><Details>Cannot use Query String params with form POST.</Details></Error>
```
