### ISSUE TITLE
Logs within Kubernetes Namespace appear in wrong namespace

### ISSUE THREAD

**Issue by chrisface** [GoogleCloudPlatform/google-cloud-ruby#2025]
We've been using `google-cloud-logging` for an application that is running on Kubernetes in GKE.

After applying namespaces to our applications in K8s we saw that could filter the logs by the GKE namespace. The namespaced logs however only included logs from STDOUT and STERR, those coming directly from the running containers.

Application logs that were being reported via `google-cloud-logging` were still going to the `default` namespace.

I did a bit of digging and found that there was this environment variable that was not set:

https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/60cc7d83af544ece52cbf8234100bf892d88fa91/google-cloud-env/lib/google/cloud/env.rb#L286-L295

Setting this environment variable manually does result in the application logs going to the correct namespace but the comment implies that this environment variable should have been set automatically.

Am I misunderstanding this comment or am I expected to set this manually? It was not obvious that this needed to be set and I couldn't find any documentation regarding it.

**Comment by blowmage** [comment]
@dazuma What can you tell us about this? Is this a value that can be retrieved from the instance metadata?

**Comment by dazuma** [comment]
Sorry for the delay. I'm getting caught up on issues now.

It indeed looks like the environment variable in question is no longer being set in recent versions of kubernetes engine. I'll review the settings here and try to find alternative sources.
