### ISSUE TITLE
pubsub: consumer receives many grpc errors

### ISSUE THREAD

**Issue by jadekler** [GoogleCloudPlatform/google-cloud-ruby#2037]
![screen shot 2018-04-02 at 2 48 57 pm](https://user-images.githubusercontent.com/3584893/38217987-2cafd8c8-3685-11e8-943a-efa68a26b8ba.png)

No special config / setup. Unbounded queue.

**Comment by blowmage** [comment]
@jadekler I believe this is the same issue covered in grpc/grpc#14853. We can work around the unhandled errors raised by GRPC, but we cannot prevent them.

/cc @apolcyn @jonparrott

**Comment by jadekler** [comment]
Ah! Super, you're already on it. I'll close out this issue in that case.
