### ISSUE TITLE
Firestore Delete Collection Error

### ISSUE THREAD

**Issue by ryanmats** [GoogleCloudPlatform/google-cloud-ruby#2051]
Hi! I'm trying to run a piece of code to delete all documents in a Firestore collection. Here is [the code I'm using](https://gist.github.com/ryanmats/6c587c4feec696e19b6cd99cfa2c1422).

However, when I run this, I get [this error message](https://gist.github.com/ryanmats/c2084909aca7bc0a84119438de18a438). (Note that line 70 in the error message corresponds to line 10 in the gist).

I have been able to get basic deletion of a single document working using [this code](https://gist.github.com/ryanmats/277e665cca6b597f8ecdc84b672c78f9).

Thanks!

**Comment by omnisyle** [comment]
Thank you for the fix, can you do a release for this fix? We're encountering the same bug and specifying github repo with master branch in Gemfile doesn't pull this fix :(

**Comment by blowmage** [comment]
Sorry, I didn't realize these changes were still unreleased. This is released in [google-cloud-firestore 0.21.1](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-firestore%2Fv0.21.1).

**Comment by ryanmats** [comment]
hey @blowmage ! Thanks for updating the library.

One small issue is that I'm getting a warning message when I run my code (although it is working fine). Any idea what this may be?

`Key :firestore already exists. It will be replaced. at /Library/Ruby/Gems/2.3.0/gems/google-cloud-firestore-0.21.1/lib/google-cloud-firestore.rb:111:in `<top (required)>'`

**Comment by blowmage** [comment]
Are you doing any custom configuration? If so, you’ll want to require the gem before you perform the configuration
