### ISSUE TITLE
Broken links in Dialogflow docs

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#2052]
While releasing Dialogflow I discovered that the URL used for the product (https://cloud.google.com/dialogflow) appears to be incorrect or outdated. The current URL is https://cloud.google.com/dialogflow-enterprise. 

While https://cloud.google.com/dialogflow forwards to https://cloud.google.com/dialogflow-enterprise, https://cloud.google.com/dialogflow/docs does not forward to https://cloud.google.com/dialogflow-enterprise/docs, resulting in broken links. I used the correct URL in the top-level README, but there are similar links in source code docs comments that still need to be fixed.

I also found [a broken console link in the README](https://github.com/GoogleCloudPlatform/google-cloud-ruby/commit/e6db951571f3a0b3cff1de5ffa9ce30419bae3fe#diff-4b71b7081dc3502ab4d9fc3491df9e3b) that I fixed.  It would probably be a good idea to test all links to the product in this package.

**Comment by jbolinger** [comment]
Addressed in #2055
