### ISSUE TITLE
Batch request for Vision API "web"?

### ISSUE THREAD

**Issue by 9mm** [GoogleCloudPlatform/google-cloud-ruby#2063]
Hey, is there a way to send batch requests when using the Vision API (`.image` and `.web` methods specifically)

**Comment by blowmage** [comment]
There is a way to submit a single API request for multiple images. You can do this using the [`Project#annotate`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-vision/v0.28.0/google/cloud/vision/project?method=annotate-instance) method:

```ruby
require "google/cloud/vision"

vision = Google::Cloud::Vision.new

face_img = vision.image "path/to/face.jpg"
landmark_img = vision.image "path/to/landmark.jpg"
text_image = vision.image "path/to/text.png"

annotations = vision.annotate do |annotate|
   annotate.annotate face_img, faces: true, labels: true
   annotate.annotate landmark_img, landmarks: true
   annotate.annotate text_image, text: true
end
```

`Image#web` will only annotate the single image. To process multiple images you must use `Project#annotate`.

**Comment by quartzmo** [comment]
@9mm Does this work for you? If so, can you close the issue? Thanks!

**Comment by 9mm** [comment]
Thanks! I'll give it a shot, I didn't get a chance yet.
