### ISSUE TITLE
List links to other language doc pages in alphabetical order (and add link to C++)

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-ruby#2070]
Please update drop down menu of [Ruby docs page(s)](https://googlecloudplatform.github.io/google-cloud-ruby/#/)

### Expected Behavior

.NET, C++, Go, Java, Node.js , PHP, Python, Ruby

### Actual Behavior

.NET, Go, Java, Node.js, PHP, Python, Ruby

![image](https://user-images.githubusercontent.com/6241635/39552042-892ddc90-4e35-11e8-9210-3f8153b44322.png)

**Comment by blowmage** [comment]
Manually updated the docs site with the new Angular code.
