### ISSUE TITLE
Working on GCP Composer

### ISSUE THREAD

**Issue by tareksamni** [GoogleCloudPlatform/google-cloud-ruby#2095]
Hi,

I'll be working on [Cloud Composer](https://cloud.google.com/composer/) client. I'll follow the same design patterns and structure used in this project. I expect to finish it by next week.

Do you recommend that I open a WIP PR? to follow the progress or to just go and create the PR when I'm done?

Thanks

**Comment by blowmage** [comment]
Hi @tareksamni, thanks for opening the issue. I think either would work. If you want input during development then a PR would be a good vehicle for that. If not, then its up to you.

/cc @jbolinger

**Comment by tareksamni** [comment]
Yes, I think I would need input (my first big contribution to this project). and with the fact that there is no slack for this project or any other way of communication I'd love to have a WIP PR.

Thanks

**Comment by blowmage** [comment]
> the fact that there is no slack for this project

There is a Slack for GCP. You can [sign up here](https://gcp-slack.appspot.com/), and find us in the the general `#ruby` channel or the project specific `#google-cloud-ruby` channel. We aren't heavy users of these slack channels, but we do maintain a presence there to discuss these gems with the community.

> or any other way of communication

Our intention is to use GitHub issues and pull requests for as much of our communication as possible, so opening a WIP PR is fine.

**Comment by blowmage** [comment]
Closing as the questions seems to be answered.
