### ISSUE TITLE
Bigtable : Protobuf `UpdateAppProfileMetadata` class is missing and Longrunning operation needed Google::Gax::Operation wrapper

### ISSUE THREAD

**Issue by jiren** [GoogleCloudPlatform/google-cloud-ruby#2101]
- Protobuf class missing for `UpdateAppProfileMetadata` in [bigtable_instance_admin_pb.rb](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-bigtable/lib/google/bigtable/admin/v2/bigtable_instance_admin_pb.rb)
Ref: [bigtable_instance_admin.proto](https://github.com/googleapis/googleapis/blob/46890c7e15d18423b26572c0ce90905f5dfefe74/google/bigtable/admin/v2/bigtable_instance_admin.proto#L472)

- Some of the `Google::Longrunning::Operation` jobs are not wrapped into `Google::Gax::Operation`
1. `partial_update_instance`
https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/bdfe9bcc71f91bb9c9a6e83c61ec523a7b57644b/google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client.rb#L569

2. `update_app_profile `
https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/bdfe9bcc71f91bb9c9a6e83c61ec523a7b57644b/google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client.rb#L1024

3. `snapshot_table`
https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/bdfe9bcc71f91bb9c9a6e83c61ec523a7b57644b/google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin_client.rb#L763

I think GAPIC code need to regenerate to fix missing class and longrunning operation wrapper.

**Comment by jbolinger** [comment]
Yes, this is correct. I regenerated locally and it looks like all of those updates were included. 

There were also a few other minor changes that it pulled in. I'll follow up with a PR shortly.

**Comment by jbolinger** [comment]
Fixed by #2102.
