### ISSUE TITLE
undefined method `download' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by Raghavan1993** [GoogleCloudPlatform/google-cloud-ruby#2107]
Running into this error trying to download a file from GCS:
```
bucket = storage.bucket "birthdays"
birthday = bucket.file "2000.json"
# Download the file to the local file system
birthday.download "/birthday-2000"
```
following this : https://cloud.google.com/storage/docs/downloading-objects

**Comment by quartzmo** [comment]
@Raghavan1993 Hi, thanks for opening this issue. Can you paste in the error backtrace? I don't see it.

**Comment by blowmage** [comment]
I think the problem is this line:

```ruby
birthday = bucket.file "2000.json"
```

If the file does not exist it will return `nil`. So trying to call `#download` on that `nil` object will raise the error you are reporting. I’d check to make sure you get a File object.

**Comment by Raghavan1993** [comment]
That was it  file naming automation script messed up Thanks !!
