### ISSUE TITLE
Create an array column in Bigquery table

### ISSUE THREAD

**Issue by meddario** [GoogleCloudPlatform/google-cloud-ruby#2119]
Hi,
from the docs i see that Bigquery supports array columns (https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#array-type), is there any way to create a column of this type from the ruby client? 

Reading the [source](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-bigquery/lib/google/cloud/bigquery/schema.rb) the only explicit types I can find are:
* string
* integer
* float
* numeric
* boolean
* bytes
* timestamp
* time
* datetime
* date
* record

Maybe there is a way using the record type?

Thanks in advance!

**Comment by blowmage** [comment]
The Ruby BigQuery gem does support creating array columns. The terminology used in the BigQuery API is a "repeated" column. So as you define your columns you specify the column type and indicate that it is repeated (using the [`mode` optional named argument](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-bigquery/v1.5.0/google/cloud/bigquery/schema?method=string-instance)).

A code example used in the Ruby documentation shows defining a repeated "cities_lived" column.

```ruby
require "google/cloud/bigquery"

bigquery = Google::Cloud::Bigquery.new
dataset = bigquery.dataset "my_dataset"
table = dataset.create_table "my_table"

table.schema do |schema|
  schema.string "first_name", mode: :required
  schema.record "cities_lived", mode: :repeated do |nested_schema|
    nested_schema.string "place", mode: :required
    nested_schema.integer "number_of_years", mode: :required
  end
end
```

The data returned is a Ruby Array of values, depending on the type of the column.

**Comment by meddario** [comment]
Hi, sorry for the delay, thanks for the answer, for now I switched to a fixed schema approach (not using the repeated columns), because of the easier integration with a CSV import (from the documentation i see that there isn't support to load repeated data from a CSV file). 

Anyway, thank you very much for the answer, I'll keep the example for the next time!
