### ISSUE TITLE
Lots of threads used in Pub/Sub, is this expected?

### ISSUE THREAD

**Issue by ianks** [GoogleCloudPlatform/google-cloud-ruby#2120]
I created a very simple example illustrating that a single subscriber will grow from 10 to 63 threads allocated after receiving published messages to a topic. In my application, I have many subscribers so this amount of thread usage may cause issues.

Can you clarify if using this number of threads this is the correct behavior? If so, what is the best way to minimize resource usage for many subscriptions?

#### Gist

Here is a gist showing the thread growth: https://gist.github.com/ianks/65b45a3d24f26992dafea2f0e7b09fd6

1. Start a pub sub emulator (you can use `docker-compose up -d` in this gist)
2. Then in one terminal, run: `ruby subscriber.rb`
3. In another terminal: run: `watch -n 1 ruby publisher.rb`
4. You will see the thread usage growing

**Comment by blowmage** [comment]
This behavior is correct and intended. Each subscriber has a number of gRPC streams. Each stream has a thread to receive messages off the stream, and two thread pools, one to process callbacks, one to send batched acknowledge and delay messages. You can control the number of streams and the size of the streams' thread pools by passing `streams` and `threads` values to [`Subscription#listen`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-pubsub/v0.30.2/google/cloud/pubsub/subscription?method=listen-instance)

For example:

```ruby
require "google/cloud/pubsub"

pubsub = Google::Cloud::Pubsub.new

sub = pubsub.subscription "my-topic-sub"

subscriber = sub.listen streams: 2, threads: { callback: 4, push: 2 } do |rec_message|
  # store the message somewhere before acknowledging
  store_in_backend rec_message.data # takes a few seconds
  rec_message.acknowledge!
end

# Start background threads that will call block passed to listen.
subscriber.start
```

**Comment by ianks** [comment]
I think so. One last question: does each RPC stream need it's own thread, or would it be possible to use a thread pool for all RPC streams?

**Comment by blowmage** [comment]
Each stream object needs its own background thread to pull messages from the GRPC stream connection.

**Comment by quartzmo** [comment]
@ianks Do you want further investigation, or OK to close this issue?

**Comment by ianks** [comment]
@blowmage @quartzmo

Having used pubsub in production for awhile now, we have accumulated a large number of subscribers. We are hitting issues with the number of threads and database connections, etc.

Would using a shared pool between subscribers be feasible in this gem?

**Comment by quartzmo** [comment]
@ianks I'm assuming you're using as few threads as possible per subscriber, but still running into limits, is that right? Do you believe a lot of the threads are sitting idle?

I think it would be quite difficult to share threads among subscribers, but I haven't researched it exhaustively.
