### ISSUE TITLE
ResourceExhaustedError in Instance Clusters::bigtable#test_0002_create cluster, update and delete

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#2162]
Over the past 24 hours, all `master` branch builds on Circle CI either errored or timed out on [this acceptance test](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-bigtable/acceptance/bigtable/cluster_test.rb#L36). I added `skip` to the test to disable it and allow the build to succeed, but it needs to be re-enabled (remove `skip`) with changes to the test and/or service configuration to ensure that it consistently passes.

The error message was typically:

```sh
  1) Error:
Instance Clusters::bigtable#test_0002_create cluster, update and delete:
Google::Cloud::ResourceExhaustedError: 8:Insufficient node quota. You requested a node count of 5 nodes for your cluster, but this request would exceed your project's node quota of 30 nodes total across all clusters in this zone. Contact us to request a quota increase: https://goo.gl/pf2Su8
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/service.rb:432:in `rescue in execute'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/service.rb:430:in `execute'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/service.rb:265:in `update_cluster'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/cluster.rb:202:in `save'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/acceptance/bigtable/cluster_test.rb:50:in `block (2 levels) in <top (required)>'
```

To reproduce locally:

1. Remove `skip` from the test.
1. Place `focus` on the line above the test. (This speeds the process.)
1. Open at least 5 terminal sessions.
1. Set the auth credentials in each session to the same project.
1. Paste `bundle exec rake acceptance` into each session.
1. Enter return to execute the above command in each session, as quickly as possible.

@jiren Can you address this issue in a new pull request?

**Comment by jiren** [comment]
Production instance cluster required minimum 3 nodes. I will update cluster test case with development instance which will work with single cluster node.

**Comment by quartzmo** [comment]
We are getting repeated timeouts on `master` branch Circle CI builds (For example: [build 4143](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-ruby/4143) with the following message:

```sh
Instance Clusters::bigtable#test_0002_create cluster, update and delete = 
command ruby build/test.rb took more than 10 minutes since last output
```

**Comment by jiren** [comment]
@quartzmo Looking into it.

Also, there is an issue with token quota 
Token quota limit: [Build 4124](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-ruby/4124)

```
Instance Tables::bigtable#test_0004_modify column families:

Google::Cloud::ResourceExhaustedError: 8:Insufficient tokens for quota 'TablesWriteGroup' and limit 'USER-100s' of service 'bigtableadmin.googleapis.com' for consumer 'project_number:xxxxxxxxx`
```

**Comment by sduskis** [comment]
The number of instances should remain below 30 per zone.  I would guess that the "*Insufficient node quota. You requested a node count of 5 nodes for your cluster, but this request would exceed your project's node quota of 30 nodes total across all clusters in this zone. Contact us to request a quota increase: https://goo.gl/pf2Su8*" message is due to the fact that the system tests are not cleaning up after themselves, or too many are running concurrently.

The *Insufficient tokens for quota 'TablesWriteGroup' and limit 'USER-100s' of service 'bigtableadmin.googleapis.com' for consumer 'project_number:xxxxxxxxx`* is a different type of issue, and means that too many table creations / modifications happening concurrent.

I'll speak with @jiren about cleanup.  Who can I speak with offline to discuss the frequency of these tests?

**Comment by jiren** [comment]
> The number of instances should remain below 30 per zone. I would guess that the "Insufficient node quota. You requested a node count of 5 nodes for your cluster, but this request would exceed your project's node quota of 30 nodes total across all clusters in this zone. Contact us to request a quota increase: https://goo.gl/pf2Su8" message is due to the fact that the system tests are not cleaning up after themselves, or too many are running concurrently.

Above issue is solved using randomly selecting zone.

https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/c020f5aebfced458f3f78a669e3ac7923b6fffe8/google-cloud-bigtable/acceptance/bigtable_helper.rb#L140-L150 

Also, I am working on reducing admin API  frequency call for both API and test cases.
- APIs changes:  Perform table operations without fetching tables
- Test changes: Create a  table on the start to perform table operations test cases.

**Comment by sduskis** [comment]
Yes, you got around the fact that there should only be 30 nodes per zone.  I think that there needs to be additional changes:

1) The main instance for table / data testing should be a standard instance
2) There needs to be a step to delete old instances from "instance admin tests" that failed before in test clean up.

**Comment by sduskis** [comment]
@jiren and @blowmage, has this been fixed?

**Comment by blowmage** [comment]
I believe so, yes. I will close this issue.
