### ISSUE TITLE
logging reading next does not work

### ISSUE THREAD

**Issue by walterking** [GoogleCloudPlatform/google-cloud-ruby#2163]
https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-logging/lib/google/cloud/logging/entry/list.rb#L73-L76

Because none of the instance variables are passed into the from_grpc method, the api responds with an error any time you call next with any parameters:

```
logging = Google::Cloud::Logging.new project_id: project_id
entries = logging.entries(filter:filter_thats_not_null)
entries.next
Google::Cloud::InvalidArgumentError: 3:page_token doesn't match arguments from the request
```

it seems like the from_grpc in the list.next should be called with all the params as https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-logging/lib/google/cloud/logging/project.rb#L152

**Comment by blowmage** [comment]
I've reproduced this and am working on a fix. This defect is present in multiple places, unfortunately.
