### ISSUE TITLE
Google cloud storage docs don't clearly indicate parameter types

### ISSUE THREAD

**Issue by ludwick** [GoogleCloudPlatform/google-cloud-ruby#2176]
The docs for google storage do not clearly indicate which parameters to a method are position or named. For example, the docs for bucket create_file on [this page](http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-storage/master/google/cloud/storage/bucket?method=create_file-instance), have parameters `file` (required), `path` (may be nil), `acl`, etc. The first two are positional and the rest are named. You can sometimes infer from the examples where the named parameters start, but it's not always clear and I've had to check the source code on some methods. The inline source code links (at least for master) don't always work (v1.13.0 ones do).

**Comment by quartzmo** [comment]
@ludwick Thanks for opening this issue. Please take a look at the same documentation on [rubydoc.info/gems/google-cloud-storage](https://www.rubydoc.info/gems/google-cloud-storage/Google/Cloud/Storage). Does the rubydoc.info version resolve all of the issues? If not, please let us know. We are in the process of transitioning to standard YARD generated documentation, very similar to what you see at rubydoc.info.

**Comment by ludwick** [comment]
Yep! That looks a lot better. Thank you!
