### ISSUE TITLE
The Bucket::Acl class is not included the the documentation.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-ruby#2192]
At least I cannot find it.  The documentation for the `acl` method in `Storage::Bucket` is here:

https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-storage/v1.13.0/google%2Fcloud%2Fstorage%2Fbucket?method=acl-instance

it references a `Bucket::Acl` class, but that class is not included in the list of classes on the left panel.

**Comment by quartzmo** [comment]
@coryan Thank you for identifying this issue. While the `Bucket::Acl` class [is included in the documentation](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-storage/v1.13.0/google/cloud/storage/bucket/acl), as you correctly observe it is not linked from the `Bucket#acl` method. This should be considered a bug in the documentation and should be fixed.

The left nav in the Angular site app was never intended to be a complete index of types. However, we are in the process of transitioning to standard YARD generated documentation, which will be very similar to what you can view already at [rubydoc.info/gems/google-cloud-storage](https://www.rubydoc.info/gems/google-cloud-storage/Google/Cloud/Storage/). This standard YARD documentation features a full list of types in the left nav.
