### ISSUE TITLE
Storage: add support get_service_account method

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#2193]
Feature request to add support for [projects.serviceAccount](https://cloud.google.com/storage/docs/json_api/v1/projects/serviceAccount/get) 

The request gets the GCS managed service account that is used by GCS PubSub notifications and CMEK to allow GCS to access to PubSub and a KMS key respectively.

Examples of existing implementations:
* [PHP](https://github.com/GoogleCloudPlatform/google-cloud-php/pull/1173)
* [Java](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java#L987)

**Comment by quartzmo** [comment]
Are you OK with the [google-cloud-bigquery implementation](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-bigquery/lib/google/cloud/bigquery/project.rb#L87-L96)?

**Comment by frankyn** [comment]
The implementation lgtm as the surface for accessing the GCS managed service. 

Thanks Chris!
