### ISSUE TITLE
Ruby program with the line 'Google::Cloud::Speech::V1.new' is not terminating

### ISSUE THREAD

**Issue by ManuSakrepatna** [GoogleCloudPlatform/google-cloud-ruby#2200]
I have  a ruby script with the following 3  lines of code

require "google/cloud/speech/v1"
speech_client = Google::Cloud::Speech::V1.new
puts 'Hi'

It Works, authentication success, but program is not terminating after diplaying 'Hi'

What is the root cause, and what is my mistake?

**Comment by blowmage** [comment]
Hi, thanks for the question. I am unable to reproduce the behavior you are describing. Is there more you can tell us about hour system?

Here is my repro, where I created and ran the file:

```
$ cat speech_terminate.rb 
require "google/cloud/speech/v1"
speech_client = Google::Cloud::Speech::V1.new
puts 'Hi'
$ gem install google-cloud-speech
The 0.30.0 release introduced breaking changes relative to the previous release, 0.29.0. For more details and instructions to migrate your code, please visit the migration guide: https://cloud.google.com/speech-to-text/docs/ruby-client-migration.
Successfully installed google-cloud-speech-0.30.0
1 gem installed
$ ruby ./speech_terminate.rb 
Hi
$
```

Can you give us the OS version, Ruby version, and google-cloud-speech gem version you are using?

**Comment by ManuSakrepatna** [comment]
Hi, Thank you very much for your support.

I am working under Windows 7 - Professional -64 bit
My Ruby version is 2.1.8
google-cloud-speech gem  version is 0.30.0

**Comment by blowmage** [comment]
How are you running the ruby code? Are you passing a file to `ruby.exe` or are you doing something else?

**Comment by ManuSakrepatna** [comment]
The above 3 lines of code is stored in sample.rb file. And I am using the command        ruby sample.rb

**Comment by ManuSakrepatna** [comment]
Yes Sir, I am closing it here. Thank you.
