### ISSUE TITLE
Google Cloud Speech Support Speaker Diarization

### ISSUE THREAD

**Issue by brianarpie** [GoogleCloudPlatform/google-cloud-ruby#2212]
Google Speech API V1p1beta1 now supports a bunch of new recognition configurations.

I have forked this library in order to be able to pass values for these new parameters to the API.

I've added `enableSpeakerDiarization` and `diarizationSpeakerCount` to my fork, though there may be other new parameters the API now accepts that would be useful for other users of this library.

Also, the response object needs to include `speaker_tag` for the enabling of the diarization to be useful.

Here is the commit from my fork to help explain what I added to gain access to this new feature: https://github.com/aloeai/google-cloud-ruby/commit/d3cd520c5c5ec90e639a5d3f9188c78253fefc3f

**Comment by blowmage** [comment]
@dazuma These attributes look to have been added to `v1p1beta1` 3 weeks ago in https://github.com/googleapis/googleapis/commit/475d72b7405c92f06d7f2d4aba866278eb5ad8e9. Shouldn't these changes have already been propagated to this repo by now?

**Comment by snkashis** [comment]
Is there an ETA on when these options will be rolled in here?

**Comment by blowmage** [comment]
I believe these were added in #2227. We are in the process of automating the generation of the ruby files when the underlying protobuf files are updated. Once that process is complete and we are confident everything is up to date we will release. I'm thinking later this week, or early next week.

**Comment by blowmage** [comment]
This is included in the most recent release.

http://googlecloudplatform.github.io/google-cloud-ruby/docs/google-cloud-speech/latest/Google/Cloud/Speech/V1p1beta1/RecognitionConfig.html#enable_speaker_diarization-instance_method
