### ISSUE TITLE
Google Cloud Speech V1p1beta Fetch Long Running Recognize Operation

### ISSUE THREAD

**Issue by brianarpie** [GoogleCloudPlatform/google-cloud-ruby#2213]
In order to take advantage of the asynchronous long running recognize method, I needed to be able to check on the status of a long running recognition without blocking the process it was initialized in while waiting for it to complete. My solution was to store the operation's name `operation.name` and periodically fetch the operation by it's name, wrapping the response as an instance of  `LongRunningRecognizeResponse`.

Here is the commit from my fork:
https://github.com/aloeai/google-cloud-ruby/commit/ff042eee4b32bd9e1d7b449ee0087c7ec04ef351

**Comment by blowmage** [comment]
@jbolinger @dazuma We had this functionality exposed as the [`Project#operation`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-speech/v0.29.0/google/cloud/speech/project?method=operation-instance) method back when Speech was a hand-written gem. But now that all value objects and API calls are generated code we are missing this. Is this something that can be added to the generated client code?

**Comment by jbolinger** [comment]
It sounds useful to me and I can't think of any reason not to add it back. I think we'd want to add it as a single method like `Project#operation` that worked for any operation in a client rather than having one for each method like in the example (although for this library the distinction doesn't make any difference).

It might help to get input from the folks working with @dazuma to see if this is something that should be done consistently across the API, as it's not really specific to Ruby.

**Comment by blowmage** [comment]
Interesting. Do some clients create more than one `@operation_client`?

**Comment by blowmage** [comment]
Are there any other methods on `@operations_client` other than `get_operation` that should also be delegated from the main client?

**Comment by jbolinger** [comment]
No, there's only one `@operation_client`. I suspect that delegating the get operation would be enough in most cases because you could fetch it, check the status, and then use the returned object to do whatever else.

**Comment by blowmage** [comment]
Yep, agreed.

**Comment by blowmage** [comment]
@jbolinger Can you give us an update on this request?

**Comment by jbolinger** [comment]
No updates from my side @blowmage. I'd like to roll all new feature requests into the larger generator refresh unless there is some urgency, but that will take some time. Do you think we can wait and use the suggested workaround for the next few months or do you think this is a high priority?

**Comment by blowmage** [comment]
We can add a workaround on our side until the generator is updated, if everyone is okay with us modifying the GAPIC files. But the change we would make depends on what is wanted. Do you want to expose and document the client's `operations_client` object, and have users chain calls to get the operation? (`client.operations_client.get_operation op_name`) Or do you want a `get_operation` method added to the client? (`client.get_operation op_name`)

How much time will the larger generator refresh take?

**Comment by jbolinger** [comment]
@blowmage the timing is what I wanted to chat about next week. It should be a this year thing, but still not sure exactly when it's going to happen.

I think we should keep as much as possible within `Google::Gax::Operation` (i.e. cancel, delete, etc.) but we could add something for get and list. I don't have a strong opinion on adding the methods to the client vs. exposing the `operations_client` but if we do the latter we'll need to change the `operations_client`. I agree with you that as-is it's probably not something we should expose.

**Comment by blowmage** [comment]
The more I've looked at it, the more I strongly favor adding methods to the client. I understand the arguments for only adding the `get_operation` and `list_operations` methods, and I would be okay with just those two.

@dazuma could this be added to `synth.py` as a gap solution until the new generator is implemented?

**Comment by dazuma** [comment]
Since speech is already a partial GAPIC, can we just add the methods to the `helpers.rb` files that are already present?

**Comment by blowmage** [comment]
This was added in #2309 and [released in `0.31.0`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-speech%2Fv0.31.0). Closing.
