### ISSUE TITLE
String#unpack1 not available on Ruby 2.3

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#2214]
Bigtable is currently using [`String#unpack1`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/196c9fae7cdb7bb99cfad0e1402c8d74e351a94a/google-cloud-bigtable/lib/google/cloud/bigtable/row.rb#L65), but this method does not exist on Ruby 2.3 and [CI is failing](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-ruby/4367) because of this.

**Comment by blowmage** [comment]
@jiren, can you take this issue?

**Comment by jiren** [comment]
Sure, I will fix and create pull request against it.

**Comment by blowmage** [comment]
Great. Can you assign this issue to yourself then? Thanks!
