### ISSUE TITLE
v1p1beta1 does not recognise options 

### ISSUE THREAD

**Issue by romanvbabenko** [GoogleCloudPlatform/google-cloud-ruby#2216]
- enable_automatic_punctuation - OK
- `initialize': Unknown field name 'enable_word_confidence'
- alternative_language_codes fails the same as enable_word_confidence

**Comment by blowmage** [comment]
This is currently being discussed on #2212.

**Comment by blowmage** [comment]
Oops, my mistake, that issue is for different options.

**Comment by blowmage** [comment]
@romanvbabenko Can you give us your gem and ruby versions, as well as a simple script to reproduce the behavior you are seeing?

**Comment by romanvbabenko** [comment]
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
gem 'google-cloud-ruby', github: 'google-cloud-ruby'

**Comment by blowmage** [comment]
This is, in fact, the same issue as #2212.

**Comment by blowmage** [comment]
Closing as this is now supported.
