### ISSUE TITLE
Remove GAPIC generated API version documentation

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#2231]
Now that the version-specific documentation has been moved, we now have duplicate documentation. Because of the way YARD loads documentation, the [API version documentation we want to see](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/fa3b2cafc0d04e736f897e80f7bb33b2f2e7b392/google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1.rb#L24-L111) is not being shown, but the [generated docs we don't want to see](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/fa3b2cafc0d04e736f897e80f7bb33b2f2e7b392/google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/cloud/videointelligence/v1/video_intelligence.rb#L18-L28) is being shown.

Video Intelligence has't been released since these files were updated, but you can see the wrong documentation being shown on the [JSONDoc Angular site](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-video_intelligence/v1.0.0/google/cloud/videointelligence/v1) for master, as well as generating the YARD HTML files locally.

We are close to removing the JSONDoc Angular app for our documentation, and instead use the YARD HTML output, and when we make this transition JSONDoc concepts like "Data Types" will no longer work. So the GAPIC-generate duplicate documentation should be removed IMO.

**Comment by blowmage** [comment]
@jbolinger Is this something in your control?

**Comment by blowmage** [comment]
@dazuma Any thoughts on this?

**Comment by jbolinger** [comment]
@blowmage I believe it is. So, you want content at the second link to simply be removed? Does anything else need to be done?

**Comment by blowmage** [comment]
Nope, I believe removing the content at the second link should make a big improvement.

**Comment by dazuma** [comment]
Agreed, the content in the second link should be removed.

**Comment by dazuma** [comment]
Fixed in artman, and regenerated all libraries. Closing.
