### ISSUE TITLE
GAPIC client OperationsClient class showing in documentation

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#2235]
The OperationsClient that a GAPIC client creates is not being hidden from the generated YARD documentation. This class looks to be used by the client object only, and probably should be excluded from the generated documentation.

It might make sense to mark this class `@private` when the `get_operation` method is added to the client.

**Comment by blowmage** [comment]
@jbolinger @dazuma Thoughts on this?

**Comment by dazuma** [comment]
Can you point out an example of this class?

**Comment by blowmage** [comment]
VideoIntelligence has it when generating the YARD HTML docs.

**Comment by blowmage** [comment]
Now that we have YARD producing HTML, I can link to an example. Here is one from Speech:

http://googlecloudplatform.github.io/google-cloud-ruby/docs/google-cloud-speech/v0.30.0/Google/Cloud/Speech/V1p1beta1/SpeechClient/OperationsClient.html

If this is to remain as part of the public API, then I suggest that an accessor be added to the GAPIC client class to the instance object, and both the Client's `OperationClient` class and the `Google::Longrunning::OperationsClient` class it inherits from are properly documented.

**Comment by dazuma** [comment]
Fixed via a synth transform. googleapis/gapic-generator#2232 will track fixing it in the generator.
