### ISSUE TITLE
Do we test our example code anywhere?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-ruby#226]
Example code (`@example` in our doc strings) needs automated testing. This is done with [yard-doctest](https://github.com/p0deje/yard-doctest) and a new `doctest` Rake task.

Done for the following core packages:

- [x] BigQuery
- [x] Datastore
- [x] Logging 
- [x] Storage

Also needs to be completed soon for the ML packages:

- [x] Language
- [x] Speech
- [x] Translation
- [x] Vision 

Followed by Pub/Sub, which was originally in the core group:

- [ ] Pub/Sub

And finally, for these remaining packages:

- [x] DNS
- [ ] Error Reporting
- [ ] Resource Manager

**Comment by blowmage** [comment]
We've been testing the example code manually. We don't have any automated tests for code examples. There isn't a generally accepted library for automating doc code like python's doctest.

**Comment by jgeewax** [comment]
We thought that too for Node... and tossed something together ourselves.. Can we consider doing that? At least for testing to typos?

/cc @stephenplusplus @ryanseys @callmehiphop

**Comment by blowmage** [comment]
The syntax highlighting and colors won't be applied to the code examples if the code can't be parsed by ruby. I've caught a couple of typos in code examples by just looking at the documentation. :)

There are a couple of projects that attempt to implement a doctest for ruby, but they are all pretty rough. I'll look into it a bit more. I agree it would be nice to catch code examples that can't be parsed by ruby.

**Comment by quartzmo** [comment]
I agree, this would be great!

**Comment by quartzmo** [comment]
Now that we are using YARD, I think extracting the examples and testing that they are valid Ruby should be pretty easy to do.

**Comment by quartzmo** [comment]
Bump! Is yard doc test an option?

**Comment by jgeewax** [comment]
https://github.com/p0deje/yard-doctest

**Comment by quartzmo** [comment]
As discussed offline with @jgeewax, these tests will be unit tests against mocked service implementations.

**Comment by quartzmo** [comment]
Adding a checklist to the description, since this will be done service-by-service.

**Comment by quartzmo** [comment]
In order to test that all examples can be run without error, yard-doctest appears to require modifications to support the following:

1. Execute all examples, including examples without output assertions (`#=>`).
1. Execute output assertions (`#=>`) that occur within blocks (see [comment on PR #969](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/969#issuecomment-254089595)).

**Comment by blowmage** [comment]
Sounds like doctest should be using something like rubyparser instead of splitting the example source code string on `#=>`.

**Comment by blowmage** [comment]
Either that, or the example source code string could be modified to add the assertions, but only eval'd once.

**Comment by swcloud** [comment]
We will close this issue and @quartzmo will file separate issues for remaining APIs.

**Comment by quartzmo** [comment]
The remaining work in the description checklist is now covered by #1320, #1321, #1322. Closing.
