### ISSUE TITLE
Storage download monkey patch leaking into documentation

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#2266]
The code to correct some download behavior is leaking into the documentation. See [here](http://googlecloudplatform.github.io/google-cloud-ruby/docs/google-cloud-storage/master/Google/Apis/StorageV1/StorageService.html).

**Comment by quartzmo** [comment]
[Google/Apis/Core/DownloadCommand.html](http://googlecloudplatform.github.io/google-cloud-ruby/docs/google-cloud-storage/master/Google/Apis/Core/DownloadCommand.html) is also leaking into the docs.
