### ISSUE TITLE
Delay when waiting for Pub/Sub Subscriber to stop

### ISSUE THREAD

**Issue by Draiken** [GoogleCloudPlatform/google-cloud-ruby#2271]
Hi there!

We wrap PubSub and [have a spec](https://gist.github.com/Draiken/889de426a8503814e3410414d69e31df) that ensures we correctly publish messages. I've noticed that RSpec would hang a bit longer with an error message:

```
E0809 17:05:14.171328706   12218 backup_poller.cc:110]       run_poller: {"created":"@1533845114.171295122","description":"Shutting down timer system","file":"src/core/lib/iomgr/timer_generic.cc","file_line":704}
```

After some retries, I didn't get the message all the time. I then decided to add a `sleep 0.1` **after** calling `subscriber.stop.wait!` and the error message disappeared.

It seems to me there is a race condition on the `wait!` method that is triggering this underlying error.

My environment:
```
Ruby: 2.5.1
Bundle:
  * google-cloud-core (1.2.2)
  * google-cloud-env (1.0.2)
  * google-cloud-pubsub (0.31.0)
  * google-gax (1.3.0)
  * google-protobuf (3.6.1)
  * googleapis-common-protos (1.3.7)
  * googleapis-common-protos-types (1.0.2)
  * googleauth (0.6.4)
  * grpc (1.14.1)
  * grpc-google-iam-v1 (0.6.9)
```

**Comment by blowmage** [comment]
This message is printed by the `grpc` library during its cleanup. It is not an error. We have been told it is benign. See grpc/grpc#14180.

**Comment by Draiken** [comment]
I don't care much about the message, but the spec process hangs around a lot longer when that message pops up (2-3 seconds) which leads me to think it's not just a message

**Comment by blowmage** [comment]
I'll look into it.

**Comment by blowmage** [comment]
We have recently updated the threading implementation used by Subscriber, and we think it should be more reliable. This will go out in the next release.

**Comment by blowmage** [comment]
@Draiken Please try google-cloud-pubsub 0.32.0. It overhauled the Subscriber threading and hopefully won't cause additional GRPC cleanup. Let us know how it performs and if it satisfies this issue.

**Comment by Draiken** [comment]
@blowmage seems to have fixed this issue for me. Thank you very much.
