### ISSUE TITLE
Google Pub/Sub 14:Deadline Exceeded and Google::Cloud::UnavailableError

### ISSUE THREAD

**Issue by sgringwe** [GoogleCloudPlatform/google-cloud-ruby#2322]
Environment: GKE 1.10.2. 
Library version: 0.31.1

Gemfile.lock section:

```
    google-cloud-core (1.2.2)
      google-cloud-env (~> 1.0)
    google-cloud-env (1.0.2)
      faraday (~> 0.11)
    google-cloud-pubsub (0.31.1)
      concurrent-ruby (~> 1.0)
      google-cloud-core (~> 1.2)
      google-gax (~> 1.0)
      grpc-google-iam-v1 (~> 0.6.9)
    google-cloud-storage (1.12.0)
      digest-crc (~> 0.4)
      google-api-client (~> 0.19.0)
      google-cloud-core (~> 1.2)
      googleauth (~> 0.6.2)
    google-gax (1.3.0)
      google-protobuf (~> 3.2)
      googleapis-common-protos (>= 1.3.5, < 2.0)
      googleauth (~> 0.6.2)
      grpc (>= 1.7.2, < 2.0)
      rly (~> 0.2.3)
    google-protobuf (3.6.1)
    googleapis-common-protos (1.3.7)
      google-protobuf (~> 3.0)
      googleapis-common-protos-types (~> 1.0)
      grpc (~> 1.0)
    googleapis-common-protos-types (1.0.2)
      google-protobuf (~> 3.0)
      growl (1.0.3)
    grpc (1.14.1)
      google-protobuf (~> 3.1)
      googleapis-common-protos-types (~> 1.0.0)
    grpc-google-iam-v1 (0.6.9)
      googleapis-common-protos (>= 1.3.1, < 2.0)
      grpc (~> 1.0)
```

We are seeing a "bad state" that our pods get into. So far, this has only affected publishing. When a pod gets into a bad state, publishing of messages gives frequent errors that look like below stacktrace.

We have discovered that about 10 minutes before a pod goes into this bad state, we see two log messages like this:

```
#<Thread:0x00007f26bdb43a08 run> terminated with exception (report_on_exception is true):
Header value '�|&' has invalid characters (ArgumentError)
```

I'm not yet sure what on our end would be causing that ArgumentError.

I think this might be coming from https://github.com/grpc/grpc/blob/master/src/ruby/ext/grpc/rb_call.c#L436?

10 minutes later is when the first exception is raised. Sidekiq reports that it failed after a little over 10 minutes. The pod from that point forward continues to have the same issue. I can't tell if *every* call has the issue, but the number of these exception raised is at least correlated with throughput.

[stacktrace.txt](https://github.com/GoogleCloudPlatform/google-cloud-ruby/files/2302860/stacktrace.txt)

**Comment by blowmage** [comment]
@apolcyn can you give us some insight on this error?

**Comment by apolcyn** [comment]
```
We have discovered that about 10 minutes before a pod goes into this bad state, we see two log messages like this:

#<Thread:0x00007f26bdb43a08 run> terminated with exception (report_on_exception is true):
Header value '���|&�' has invalid characters (ArgumentError)
```

This is definitely strange. The two places where this seemingly bad header could be coming from would be:
1) something above the gRPC library is passing this header in as RPC "custom metadata"
2) the metadata that is attached by call credentials (e.g. OAuth creds)

**Comment by blowmage** [comment]
@apolcyn If you look at the backtrace, the call is coming from google-cloud-pubsub. We aren't setting any custom metadata, and we don't expose a way to set custom metadata in the Ruby API. If this were something in the call credentials, would it be something that could be set after auth token refresh?

**Comment by blowmage** [comment]
@sgringwe How are you authenticating? Are you using a service account's `keyfile.json` file? Something else?

**Comment by blowmage** [comment]
@sgringwe Also, have you experienced this behavior on google-cloud-pubsub 0.32.0?

**Comment by apolcyn** [comment]
> If this were something in the call credentials, would it be something that could be set after auth token refresh?

I'm not familiar with ruby's google call creds implementation, but I believe so - the metadata hash that the call cred is returning <i>could</i> possibly be triggering this error.

**Comment by sgringwe** [comment]
@blowmage We are authenticating using GOOGLE_CLOUD_KEYFILE_JSON. We'll be upgrading to 0.32.0 today. Usually it takes a day or so for this error to occur on one of the pods, so it will be at least a few days before we know if 0.32.0 fixes it.

**Comment by blowmage** [comment]
@apolcyn Well, we aren't doing anything unusual with the call credentials, as you can see here:

https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb#L58

We basically pass the credential object's `updater_proc` as-is. The credential's `updater_proc` is defined here:

https://github.com/google/google-auth-library-ruby/blob/master/lib/googleauth/service_account.rb#L157-L180

it looks to me like it is only setting the `authorization` header.

@sgringwe What is the system's default encoding that is running this job?

**Comment by sgringwe** [comment]
@blowmage This is what I am getting from ruby prompt, let me know if there is another preferred method or debug call to make

```
[1] production(main)> Encoding.default_external
=> #<Encoding:UTF-8>
[2] production(main)> "string".encoding
=> #<Encoding:UTF-8>
```

**Comment by blowmage** [comment]
Thanks @sgringwe, that all looks fine. A couple more questions:

1) Can you look into your authentication environment variable and tell us what the auth_uri and token_uri values are? Are they "https://accounts.google.com/o/oauth2/auth" or are they something else?

2) Do you happen to know how many messages you are publishing at a time? How large are the messages?

**Comment by sgringwe** [comment]
@blowmage 

1. Yes - the values are like that string

2. Currently we aren't sending anymore than ~10k/minute. When this issue started happening we were at an even smaller scale of ~2k/minute. Message sizes vary. They will typically be small, but may have some large text fields from time to time.

**Comment by blowmage** [comment]
K, if you are doing 10k publishes a minute, that is ~166 API calls a second. I wonder if this might be some concurrency issue with updating the access token. Perhaps a call sees that the token is about to expire and starts the process of refreshing it. But at nearly the same time, another process tries to make a call with the same token.

As it is, I have been unable to reproduce this behavior.

**Comment by sgringwe** [comment]
@blowmage interesting thought. I should clarify that the 10k/minute number is a mix of `publish` and `publish_async`, with most of those being `publish_async`. We have noticed that this issue has only been caused by `publish` calls, and has not yet been caused by a `publish_async` call. Does `publish_async` have the same potential concurrency issue updating the access token? How often is the access token refreshed?

**Comment by blowmage** [comment]
`publish_async` was created for your exact use case. You have many concurrent updates and you want to batch them together to minimize the total number of API calls being made. It theoretically has the same concurrency issue with updating the access token, but practically you would need an order of magnitude more messages to hit it.

That said, I have not verified this is an issue with token refresh. I am only speculating since I have yet to reproduce the behavior described.

**Comment by sgringwe** [comment]
@blowmage we have not seen this error since upgrading to 0.32.0 about a week ago. We're still on `publish` (not `publish_async`). Throughput is same / increased.

I think that 0.32.0 did fix this.

If it's helpful here is what upgrades happened during that gem upgrade:

* google-cloud-pubsub 0.31.1 -> 0.32.0
* google-gax 1.0 -> 1.3
* googleauth 0.6.4 -> 0.6.5
* signet 0.8.1 -> 0.9.0

Nothing else changed.

From our perspective, feel free to close.

**Comment by blowmage** [comment]
@sgringwe I am very glad to hear that!
