### ISSUE TITLE
GAPIC generated copyright header

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#2334]
The GAPIC generated files need to have 2 blank lines between the copyright header and the `require` lines or the generated code. Both the code files and the documentation files. This is because the copyright header is being recognized as documentation by YARD. If a comment is 2 or more blank lines between code YARD will not consider it documentation. 

This can be seen on the current Datastore docs. The `Google` module's has no documentation but is showing the copyright heading:

http://googlecloudplatform.github.io/google-cloud-ruby/docs/google-cloud-datastore/master/Google.html

Where the `Google::Cloud` also has no documentation and is not showing any:

http://googlecloudplatform.github.io/google-cloud-ruby/docs/google-cloud-datastore/master/Google/Cloud.html

**Comment by dazuma** [comment]
Ack I'll open an issue to track this in the generator, and patch it for now via a synth transform.

**Comment by dazuma** [comment]
@blowmage To clarify, does this mean we need two newlines (i.e. one blank line) or three newlines (i.e. two blank lines)?

**Comment by blowmage** [comment]
Two blank lines, so 3 newline characters. We need it to look like [this](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-datastore/lib/google/cloud/datastore.rb#L14-L15), not [this](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-datastore/lib/google/cloud/datastore/v1/datastore_client.rb#L21).

**Comment by blowmage** [comment]
(FWIW, the Protobuf-generated files don't need this because we are excluding them from the documentation.)
