### ISSUE TITLE
Labels on Pub/Sub topics not supported

### ISSUE THREAD

**Issue by UsmannK** [GoogleCloudPlatform/google-cloud-ruby#2344]
There doesn't seem to exist a way to retrieve labels on a Pub/Sub topic right now. Is this correct?

Thanks!

**Comment by quartzmo** [comment]
@UsmannK Thank you for this question.

You are correct. There is no way to set, modify, or retrieve user labels on Pub/Sub Topics or Subscriptions right now, although these features are available in the service API and we do plan to implement them soon.

How urgent is your need for user labels in Pub/Sub and how do you intend to use them?

**Comment by UsmannK** [comment]
@quartzmo Thanks for the quick response. 

We use labels to mark resources for things like whether or not they contain PII, so our cloud console and other downstream tools can treat them appropriately. It is not entirely urgent as I believe I can drop back to https://github.com/google/google-api-ruby-client/ which should do the trick? Please correct me if that's incorrect.

**Comment by quartzmo** [comment]
I'll ask how quickly we can implement this and try to get back to you Monday with an answer.

**Comment by blowmage** [comment]
You can always use the low-level API in this gem to hit the Pub/Sub service. You don’t need to use a different gem. 

```ruby
require "google/cloud/pubsub/v1/credentials"

client = Google::Cloud::Pubsub::V1::PublisherClient.new
```

**Comment by UsmannK** [comment]
Oh! That should work great. Cheers :)
