### ISSUE TITLE
Release GCS Ruby client library

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#2371]
Hi,

Is it possible to release the Storage client library for Ruby?

I'd like the new method service_account_email to be available. Unless there exist concerns.

**Comment by blowmage** [comment]
I believe that is already released. google-cloud-storage 1.13.1 was released August 21, 2018.

**Comment by frankyn** [comment]
Whoops, I missed that. Thanks @blowmage!

**Comment by frankyn** [comment]
Linking to: https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-storage%2Fv1.13.1
