### ISSUE TITLE
Document Storage::Bucket::Cors::Rule

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#2403]
[Storage::Bucket::Cors::Rule](http://googlecloudplatform.github.io/google-cloud-ruby/docs/google-cloud-storage/v1.13.1/Google/Cloud/Storage/Bucket/Cors/Rule.html) is not documented but is included in the documentation. My guess is that this class should be marked `@private` and excluded from the public api.

**Comment by quartzmo** [comment]
After discussion with @blowmage, the fix for this will be to document `Storage::Bucket::Cors::Rule`, since the class is indeed in the public API as shown below:

```ruby
require "google/cloud/storage"

storage = Google::Cloud::Storage.new

bucket = storage.bucket "my-todo-app"
bucket.cors.size #=> 2
rule = bucket.cors.first
rule.origin #=> ["http://example.org"]
rule.methods #=> ["GET","POST","DELETE"]
rule.headers #=> ["X-My-Custom-Header"]
rule.max_age #=> 3600
```

**Comment by blowmage** [comment]
Updated description.
