### ISSUE TITLE
The column family rules in the table admin sample are not correct

### ISSUE THREAD

**Issue by billyjacobson** [GoogleCloudPlatform/google-cloud-ruby#2431]
Please take a look at the column family example rules as they don't seem to be doing the correct thing as stated by their comments. 

https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/76b7f31b902ed4000c6a5f4bdc7db7955f15fc0c/google-cloud-bigtable/samples/tableadmin.rb#L98

**Comment by blowmage** [comment]
@jiren Can you take this issue? I am unable to assign issues to you, so you need to assign this issue to yourself.

**Comment by jiren** [comment]
@blowmage I will update example.
