### ISSUE TITLE
How can I access WebDetection

### ISSUE THREAD

**Issue by 9mm** [GoogleCloudPlatform/google-cloud-ruby#2434]
If you use the frontend debugging tool for Cloud Vision, it shows the page title and extra metadata about the website that it appeared on.

From what I have gathered, all I can get out of this ruby gem is the page `url` and `score`. How do I access all this extra info:

- `pagesWithMatchingImage` (I have URL but I don't have...)
  - `pageTitle` and `fullMatchingImages`
- `visuallySimilarImages`

https://googlecloudplatform.github.io/google-cloud-ruby/docs/google-cloud-vision/latest/Google/Cloud/Vision/V1/WebDetection/WebPage.html

**Comment by 9mm** [comment]
I actually see how to get label_annotations, but I can't find the extra fields about "pages"

**Comment by blowmage** [comment]
Unfortunately you won't be able to use `Google::Cloud::Vision.new` to access this functionality. You have to use a lower level API to access this, specifically using `Google::Cloud::Vision::V1::ImageAnnotatorClient`.

https://googlecloudplatform.github.io/google-cloud-ruby/docs/google-cloud-vision/latest/Google/Cloud/Vision/V1/ImageAnnotatorClient.html

```ruby
require "google/cloud/vision/v1"

image_annotator_client = Google::Cloud::Vision::V1::ImageAnnotatorClient.new
gcs_image_uri = "gs://gapic-toolkit/President_Barack_Obama.jpg"
source = { gcs_image_uri: gcs_image_uri }
image = { source: source }
type = :WEB_DETECTION
features_element = { type: type }
features = [features_element]
requests_element = { image: image, features: features }
requests = [requests_element]
response = image_annotator_client.batch_annotate_images(requests)
```

Does this answer your question?

**Comment by 9mm** [comment]
Yes it does, thank you!!!
