### ISSUE TITLE
[Documentation Issue] Links to cloud.google.com should be to 'memorystore' not to 'redis'

### ISSUE THREAD

**Issue by danoscarmike** [GoogleCloudPlatform/google-cloud-ruby#2451]
Replace 'cloud.google.com/redis' with 'cloud.google.com/memorystore' in http://googlecloudplatform.github.io/google-cloud-ruby/docs/google-cloud-redis/v0.1.0/Google/Cloud/Redis.html

**Comment by danoscarmike** [comment]
Actually -- this looks like an old page. Should there be redirects in place?

[This page](https://googlecloudplatform.github.io/google-cloud-ruby/docs/google-cloud-redis/latest/Google/Cloud/Redis/V1beta1.html) has the correct links.

**Comment by blowmage** [comment]
I don’t know if it is just me, but this URL works:

https://cloud.google.com/memorystore/

But this URL gives me a 404:

https://cloud.google.com/memorystore

**Comment by blowmage** [comment]
@danoscarmike Those old versions are all generated from the protobuf files using the GAPIC tools. I think @dazuma knows about those links and why they were changed. We don't really have a way to go back and replace code or documentation for a previously released gem.

**Comment by dazuma** [comment]
The page you cited with the broken links, was the gapic-generated documentation for an old version of the library before we had used synthtool to fix a bunch of incorrect links. Documentation for current versions of the library have the correct links. As Mike mentions, we don't have a way to go back and correct links in previously-released versions of the documentation, as they are connected to the previously-released code.

Won't fix---infeasible.

**Comment by danoscarmike** [comment]
Thanks for clarifying!
