### ISSUE TITLE
Upgrade to Google API Client 0.9

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#269]
The [next version](https://github.com/google/google-api-ruby-client/milestones/0.9) of Google API Client makes some major changes, including a new ruby API for connecting to services and a replacing Faraday for Hurley. This transition will require changes in tests to use Hurley's new test API.

**Comment by blowmage** [comment]
We will want to make sure that lostisland/hurley#18 is resolved as all our tests depend on this behavior.

**Comment by blowmage** [comment]
[Migrating notes](https://github.com/google/google-api-ruby-client/blob/master/MIGRATING.md)

**Comment by edwinkcw** [comment]
I think https://github.com/lostisland/hurley/issues/18 is resolved, could you please try and test it? Thanks

**Comment by blowmage** [comment]
Yes, lostisland/hurley#18 is resolved and Google Client API 0.9 has been released. But while that was happening GRPC has become viable and so we are in the process of migrating services to use GRPC. Once the GRPC-compatible services are migrated we will look at upgrading to Google Client API 0.9 and converting our tests to use the hurley mocks.

**Comment by blowmage** [comment]
This should have been closed by #733.
