### ISSUE TITLE
Make sure we work happily with windows?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-ruby#306]
Is there anything broken on Windows?

**Comment by quartzmo** [comment]
@jgeewax Not that we know of. We can certainly do some manual testing on Windows. Travis CI [does not offer a Windows env](https://github.com/travis-ci/travis-ci/issues/216#issuecomment-124138138), afaik.

**Comment by quartzmo** [comment]
The [four issues](https://github.com/GoogleCloudPlatform/gcloud-ruby/issues?utf8=%E2%9C%93&q=+is%3Aissue+author%3AVincentVanGoat+) from @VincentVanGoat show evidence of Storage working fine on Windows (apart from the issues, of course, but they are now closed.)
