### ISSUE TITLE
Update TTL on all zone records

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#316]
We think that it may be useful to have a convenience method to update the TTL value on all zone records. This would effectively replace all records, so there would be an expensive operation with lots of records changed.

``` ruby
zone.ttl = 25600 # updates all records
```

We consider this feature experimental or optional. This issue is here to gather feedback.

**Comment by blowmage** [comment]
@quartzmo Thoughts on this?

**Comment by quartzmo** [comment]
Let's remove it from 0.4.0; but keep it open, as you originally stated, to gather feedback.
