### ISSUE TITLE
Should we rename DNS Resource to ResourceSet?

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#361]
When we started work on DNS, we did not fully understand how the service aggregates traditional zone file resource records (RRs - as defined in RFC 1035 and RFC 1034) by `name` and `type`, as `rrdatas` in [ResourceRecordSet](https://cloud.google.com/dns/api/v1/resourceRecordSets) resources. Because of this, we named our class [`Record`](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/lib/gcloud/dns/record.rb) when it probably should be named `RecordSet`. I made an attempt to clarify this in the docs:

> Represents a set of DNS resource records (RRs) for a given name and type in a Zone. 

However, it would probably be best to rename the class and its usages. Users new to Cloud DNS who are familiar with RRs in the flat structure of a zone file are likely to experience some confusion.

**Comment by quartzmo** [comment]
@jgeewax I would love to get your opinion on 1) If you think this is actually helpful, and if so, 2) what sort of priority we should give this. In my experience this type of refactoring involves a lot of code changes, but goes quickly and is best done soon.

**Comment by blowmage** [comment]
I'm :-1: on this. I like the name. Simpler is better.

**Comment by blowmage** [comment]
Not sure if we will make this change, but if we do it should be before 1.0.

**Comment by blowmage** [comment]
Gonna keep the names as they are.
