### ISSUE TITLE
Create API for GCE Metadata

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-ruby#407]
There's a great metadata service for getting access to information on the VM. It would be great to have a structured API for this:
https://cloud.google.com/compute/docs/metadata?hl=en

**Comment by JustinBeckwith** [comment]
For reference, the Go implementation:
https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/compute/metadata/metadata.go

**Comment by blowmage** [comment]
Thanks for the issue @JustinBeckwith! The compute service is definitely on the roadmap, and I can't wait to get it implemented.

**Comment by dazuma** [comment]
This is now being worked on as part of the google-cloud-env gem (See https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1259)

**Comment by blowmage** [comment]
@dazuma Can this issue be closed now that `google-cloud-env` is released?

**Comment by quartzmo** [comment]
@dazuma Can we close this issue?

**Comment by dazuma** [comment]
Oh, yes. Sorry.

**Comment by quartzmo** [comment]
Thanks!
