### ISSUE TITLE
Stopped pulling messages from pubsub without any error

### ISSUE THREAD

**Issue by trekdemo** [GoogleCloudPlatform/google-cloud-ruby#517]
_First of all, this gem is awesome. Thank you all for your effort._

We run two ruby processes on Google Compute Engine in different zones. On both boxes our processes stopped receiving messages without any error or hiccup, approximately in the same time. We use the `Subscription#wait_for_messages` method to pull messages from the subscription.
_Did any of you experienced similar issues?_

Restarting the processes solved the problem.
This is the code that we use in the processes:

``` ruby
pubsub = Gcloud.new(project, key_path).pubsub
subscription = pubsub.subscription(subscription_name)

loop do
  messages = subscription.wait_for_messages(max: 1000)

  if messages.any?
    process_messages(messages)
  else
    sleep(1)
  end
end
```

**Comment by jgeewax** [comment]
This is news to me... @tmatsuo ? Any ideas what's up here?

**Comment by trekdemo** [comment]
Please not that we suspect a micro service/network outage. It happened at 11-01-2016 8:55pm.

**Comment by blowmage** [comment]
@trekdemo Thank you for opening this issue and making us aware of this. (And thank you for using and your kind words on this project!)

Did the micro-service outage coincide with when your scripts stopped? I think it is possible that `#wait_for_messages` could hang due to a network or service outage, and therefore we can make it more resilient in these cases.

**Comment by jgeewax** [comment]
Yea, this is a great point.

If there's a network problem, by default we should probably try to
reconnect every so often so that when if the problem really was a network
blip, things recover on their own (without these guys having to cycle the
process and establish a new connection).

Can we do that?

**Comment by trekdemo** [comment]
@blowmage sadly I can't confirm the micro outage based on [Google Cloud Status](https://status.cloud.google.com).

But, I did run some tests with the gem, by pulling messages from a live subscription and disconnecting my dev-box from the network (by pulling out the cable). After reconnecting (within 30 seconds - so there was no `Faraday::TimeoutError`) it was able to reconnect and continue receiving the messages.

**Comment by blowmage** [comment]
That's what I'm seeing as well. I'm not sure what happened, but it happened to both services at the same time, so whatever it was we can account for it _when_ we can reproduce it.

**Comment by blowmage** [comment]
To clarify, both of your services hung at 11-01-2016 8:55 PM, right? Is that UTC?

**Comment by trekdemo** [comment]
@blowmage here's the log about the nothing: (UTC? - yes)

```
# Instance one
I, [2016-01-11T19:45:28.230463 #13041]  INFO -- : Batch received with 115 messages
I, [2016-01-11T21:01:06.844735 #21261]  INFO -- : Subscribed to "projects/awesome/topics/production.events" topic…
# Instance two
I, [2016-01-11T19:48:09.136549 #20732]  INFO -- : Batch received with 115 messages
I, [2016-01-11T20:57:53.661836 #16453]  INFO -- : Subscribed to "projects/awesome/topics/production.events" topic...

```

**Comment by tmatsuo** [comment]
@trekdemo I will try to check the server side. Can you tell me the project-id? You can send an e-mail to tmatsuo@google.com.

**Comment by trekdemo** [comment]
@tmatsuo done, hope you find some evidence of outage.

**Comment by swcloud** [comment]
We cannot identify the underlying problem since we're using grpc now.
