### ISSUE TITLE
Switch DNS domain name to one controlled by Google

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#529]
JJ has the gcloud-ruby.com domain name that we can use for the CI builds. Configure the CI project to get permissions to the domain name and then change the CI configuration to use it.

**Comment by blowmage** [comment]
@geigerj Is this something you can help with? This should probably be reassigned, yes?

**Comment by geigerj** [comment]
Could I get some additional context on the request: what does CI need to be configured to do with this domain name?

**Comment by blowmage** [comment]
We need a domain name to be added to the project that the acceptance tests can use to create records against. Right now it is using one of my domains.

**Comment by quartzmo** [comment]
@geigerj The acceptance tests require `GCLOUD_TEST_DNS_DOMAIN` to be set. They test for it [here](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-dns/acceptance/dns_helper.rb#L21).

**Comment by geigerj** [comment]
JJ's domain has lapsed. I'll update once there's another set up.

**Comment by geigerj** [comment]
I registered google-cloud-tests.com. @quartzmo @blowmage You should both have management permissions on the domain through https://domains.google.com/.

Do you need me to do anything else here? The domain is not configured to use Cloud DNS and doesn't point anywhere. I also haven't changed the CI environment variables. Let me know if you need assistance on any of those points.

**Comment by quartzmo** [comment]
@geigerj Thanks, I'll try to test the new domain today.

**Comment by quartzmo** [comment]
I set `GCLOUD_TEST_DNS_DOMAIN=google-cloud-tests.com` and got the following error for every acceptance test:

```sh
Google::Cloud::InvalidArgumentError: invalid: Invalid value for 'entity.managedZone.dnsName': 'a1df3b04.google-cloud-tests.com'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-dns/lib/google/cloud/dns/service.rb:166:in `rescue in execute'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-dns/lib/google/cloud/dns/service.rb:164:in `execute'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-dns/lib/google/cloud/dns/service.rb:91:in `create_zone'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-dns/lib/google/cloud/dns/project.rb:214:in `create_zone'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-dns/acceptance/dns/dns_test.rb:23:in `block (2 levels) in <top (required)>'
```

**Comment by geigerj** [comment]
@quartzmo Did you do any set-up on the domain? As noted, I just registered it and gave you management permissions; I didn't point it anywhere or set it up to use Cloud DNS as its name server.

**Comment by blowmage** [comment]
@quartzmo I think we need to add the domain to the project before we can use it. I'll take the issue and work on getting the new domain working.

**Comment by blowmage** [comment]
The CI environment has been updated.
