### ISSUE TITLE
Allow user to pass authorization

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#542]
The gcloud-common issue [Authorize using oAuth tokens #76](https://github.com/GoogleCloudPlatform/gcloud-common/issues/76) raises the issue that some users may want to store and reuse the same oAuth tokens or authorizations across both gcloud and google-api-ruby-client requests. In google-api-ruby-client, setting the oAuth2 authorization (not token; either Signet or Google Auth Library for Ruby) is simple; in addition, it can be set [globally, per service, and per request](https://github.com/google/google-api-ruby-client#passing-authorization-to-requests).

Currently, gcloud does not allow the user to directly set either an oAuth token, or an authorization from Signet or Google Auth Library for Ruby. Instead, setting the authorization is [buried deeply in private Connection classes](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.6.1/lib/gcloud/storage/connection.rb#L40).

Can we expose this ability?

**Comment by blowmage** [comment]
I'd look at whether it is possible to create a Signet::OAuth2::Client object from just the token, and then pass that object in as the credentials. I would be a tad conservative on changing authorization options until gRPC is fully integrated, so that we don't introduce an option that gRPC may not be able to support.

**Comment by blowmage** [comment]
FWIW, the grpc gem has a dependency on googleauth, and specifically calls [`#updater_proc`](https://github.com/google/google-auth-library-ruby/blob/v0.4.1/lib/googleauth/service_account.rb#L166-L168) on the authorization object. The googleauth gem does [monkey patch `Signet::OAuth2::Client#updater_proc`](https://github.com/google/google-auth-library-ruby/blob/v0.4.1/lib/googleauth/signet.rb#L58-L60), so a valid signet object seems to work just fine.

There are problems with only providing an authorization token. Specifically, when the token expires there is no refresh token to retrieve a new authorization token. So I think there is a limited use for this approach. But if we can get a valid signet object from an authorization token I see no reason why it wouldn't work to pass it in as the keyfile argument.

**Comment by swcloud** [comment]
It should be done. To confirm by @blowmage

**Comment by blowmage** [comment]
The Google API Client docs state:

> Authorization can be specified for the entire client, for an individual service instance, or on a per-request basis.
> 
> Set authorization for all service:
> 
> ```ruby
> Google::Apis::RequestOptions.default.authorization = authorization
> # Services instantiated after this will inherit the authorization
> ```
> 
> On a per-service level:
> 
> ```ruby
> drive = Google::Apis::DriveV2::DriveService.new
> drive.authorization = authorization
> # All requests made with this service will use the same authorization
> ```
>
Per-request:
> 
> ```ruby
> drive.get_file('123', options: { authorization: authorization })
> ```

It is important to note that the `authorization` value in these examples is an instance of `Signet::OAuth2::Client`, and not a string token value.

Google Cloud for Ruby does already support a user passing in authorization, it does this by accepting a `Signet::OAuth2::Client` instance for the credentials. Here is how it would work, using the same object used in the previous code examples:

```ruby
require "google/cloud/bigquery"

bq = Google::Cloud::Bigquery.new "my-project-id", authorization
```

But there are some caveats with this. First, this use is currently [undocumented](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-bigquery/v0.24.0/google/cloud/bigquery?method=new-class). Second, it would only satisfy the "per-service" use case shown above. Is an acceptable solution to this issue be to simply document this?

**Comment by blowmage** [comment]
^ @swcloud @quartzmo

**Comment by frankyn** [comment]
Ping @geigerj could you take a look at this issue?

In addition, I understand the Ruby client doesn't require a user to manually set Compute Engine credentials, but different forms of authentication have been requested for new auth docs -> https://cloud.google.com/docs/authentication/production. 

It would be helpful to at least document the different authentication workflows for the Client Library. 

Based on an email thread with @blowmage  and @quartzmo. The Compute Engine credentials workflow is the following:
```ruby
require "googleauth"
require "google/cloud/env"
require "google/cloud/storage"

storage = Google::Cloud::Storage.new project: Google::Cloud.env.project_id,
                                                              keyfile: Google::Auth::GCECredentials.new

storage.buckets.each do |bucket|
  puts bucket.name
end
```

**Comment by geigerj** [comment]
@frankyn There is work in progress to add a (documented!) `keyfile` parameter to the initializer for the GAPICs. @landrito is on point for this, and we expect it to come in with the next refresh of the GAPICs, within the month.

IIUC from @blowmage's comment above,  for the existing manually written client libraries, we just need to document the `keyfile` parameter for the per-service use case? If so, let's do that.

For the global use case, I was under the impression that we had the `GOOGLE_CLOUD_KEYFILE[_JSON]` env variable for that?

**Comment by frankyn** [comment]
Thanks @geigerj!

**Comment by quartzmo** [comment]
Related to #1729.

**Comment by blowmage** [comment]
Today's releases add a Credentials class to each gem, and support passing a Credentials object in the constructor. I believe this satisfies this issue, so I'm closing it.
