### ISSUE TITLE
Unable to Create/Update/Delete Logging Sinks with Service Account

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#563]
We are putting the logging implementation through its paces and are unable to modify a sink resource using a service account. But we can modify using user accounts.  I don't see any mention of this on the [official docs](https://cloud.google.com/logging/docs/api/introduction_v2). Is this something specific to our service account? Or is this a broader restriction ala. Resource Manager? How should we document access to these resources?

We are seeing this behavior accessing logging v2beta1 with grpc.

**Comment by blowmage** [comment]
The [gcloud-node docs](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.28.0/logging/sink?method=create) state:

> This method only works if you are authenticated as yourself, e.g. using the gcloud SDK.

So it looks like we are unable to use service accounts to manage sinks. Is that correct?

**Comment by quartzmo** [comment]
Placing `on hold` since this seems to be by current design.
