### ISSUE TITLE
Sending interrupt does not cancel connection quickly enough

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#608]
As [reported](https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/605#issuecomment-204537001) by @ptinsley:

>  idle workers in a listen loop take a decent amount of time to honor an interrupt where previously it was almost instant.

**Comment by blowmage** [comment]
@ptinsley: Is this still something you are seeing?

**Comment by blowmage** [comment]
I believe this has been resolved by GRPC. I am able to send an interrupt in IRB and the listen loop will halt immediately.
