### ISSUE TITLE
Should writing an empty array no longer return true? 

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#613]
Currently, passing an empty array to `Project#write_entries` produces the following (successful) behavior, since the service does not raise an illegal argument error or similar:

``` ruby
logging.write_entries [] #=> true
```

Should we do something to inform the client, such as return `false` or raise an error?

**Comment by dazuma** [comment]
This would be a breaking change. And I can see a pretty strong argument for leaving it as-is. A common case might be for an application to do some stuff that may buffer up 0 or more log entries, then transmit the entire buffer in a batch. You would expect that if the buffer size is 0, that the transmission might optimize itself away but shouldn't return an error.

**Comment by quartzmo** [comment]
SGTM, thanks for your input @dazuma. Closing.
