### ISSUE TITLE
Add support to url safe in datastore key

### ISSUE THREAD

**Issue by vyper** [GoogleCloudPlatform/google-cloud-ruby#656]
Add support to url safe in datastore key

Sample in Python:
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/ndb/entities/snippets.py#L79

**Comment by quartzmo** [comment]
@vyper Please see previous discussion of this topic on GoogleCloudPlatform/gcloud-node#625.

**Comment by quartzmo** [comment]
@vyper Based on the discussion above, should we conclude the same here:

> it should be figured out by the user, as we're not doing anything unique

and close this issue? Or is there something different/new?

**Comment by blowmage** [comment]
@quartzmo Thanks for posting that URL, I was trying to find some context for `urlsafe`. I agree with the discussion on that issue. (Also, your google-fu is better than mine. 😄)

I think there might be some benefit for supporting `urlsafe` for folks transitioning their apps from appengine to compute, but I don't know if it belongs in gcloud-ruby. Perhaps an extension?

**Comment by quartzmo** [comment]
Maybe a well-linked gist?

**Comment by vyper** [comment]
Buy I want to be able to search for it... Hehe. Datastore dont support find or query using urlsafe.

**Comment by blowmage** [comment]
I haven't found much info on decoding the `urlsafe` data. This [answer on SO](http://stackoverflow.com/a/25108306) recommends you decode the `urlsafe` value using ndb, and _then_ convert it to a Datastore key.

To illustrate, this `urlsafe`:

```ruby
"ahNzfnByb21wdGFwcG9pbnRtZW50chULEghTY2hlZHVsZRiAgICD2e7xxxxx"
```

decodes to the following string:

```ruby
"j\x13s~promptappointmentr\x15\v\x12\bSchedule\x18\x80\x80\x80\x83\xD9\xEE\xF1\xC7\x1Cq"
```

That looks like protobuf bytes. And sure enough JJ mentions in the link @quartzmo posted that "What you're looking at is really just a (mostly) base64 encoded version of the `entity_pb.Reference` protobuf." AFAIK we don't have access to `entity_pb.Reference` from Datastore, so I don't see how we could support this.

**Comment by blowmage** [comment]
Closing as we currently don't think it is possible. Please reopen if there is a way to identify a Datastore Key from a ndb `urlsafe`.

**Comment by vyper** [comment]
@blowmage how I can use this? I not found! ):

![screen shot 2016-05-12 at 21 05 35](https://cloud.githubusercontent.com/assets/22549/15234176/586b6cae-1885-11e6-8968-1bce81268e09.png)

**Comment by jgeewax** [comment]
Do we use the Datastore Key proto? If so, this should just be the base-64 encoded serialized representation of the Key....

**Comment by vyper** [comment]
To find without know how key is composite!

**Comment by blowmage** [comment]
@jgeewax I can't find any protobuf definition for ndb Key, and I don't read the encoding well enough to know how to decode it. Any info you could pass our way is appreciated.

**Comment by jgeewax** [comment]
Sorry, to be more clear: we populate a Ruby protobuf object (a Datastore
"Key"), right? And serialize that to binary before sending it over the wire
to the v1beta3 API endpoint?

If you pipe that serialized binary through a Base64 encoder (instead of
sending it over the wire), the output should be the key format people are
talking about.

**Comment by blowmage** [comment]
That will only work if the proto definitions of Datastore Key and NDB Key are the same, which they don't appear to be. To illustrate:

```ruby
urlsafe = "ahNzfnByb21wdGFwcG9pbnRtZW50chULEghTY2hlZHVsZRiAgICD2e7xxxxx"

require "base64"
proto = Base64.urlsafe_decode64 urlsafe

require "google/datastore/v1beta3/entity
key = Google::Datastore::V1beta3::Key.decode proto
#=> Google::Protobuf::ParseError: Error occurred during parsing: Unexpected EOF inside skipped data
```

**Comment by jgeewax** [comment]
Is that key actually valid? It doesn't check out on http://datastore-key.appspot.com/ ...

**Comment by blowmage** [comment]
The urlsafe string you provided does not decode as a v1beta3 key.

```ruby
urlsafe = "ahZzfmJ1c3RsaW5nLWtheWFrLTkxNTE2chALEgZQZXJzb24iBG5hbWUM"

require "base64"
proto = Base64.urlsafe_decode64 urlsafe

require "google/datastore/v1beta3/entity"
key = Google::Datastore::V1beta3::Key.decode proto
#=> <Google::Datastore::V1beta3::Key: partition_id: nil, path: []>
```

It also does not decode as a Google Protobuf Any:

```ruby
require "google/protobuf/any"
Google::Protobuf::Any.decode proto
#=> <Google::Protobuf::Any: type_url: "", value: "">
```

**Comment by blowmage** [comment]
If you look at the bytes of the urlsafe you provided, they look like this:

```ruby
urlsafe = "ahZzfmJ1c3RsaW5nLWtheWFrLTkxNTE2chALEgZQZXJzb24iBG5hbWUM"
urlsafe_proto = Base64.urlsafe_decode64 urlsafe
#=> "j\x16s~bustling-kayak-91516r\x10\v\x12\x06Person\"\x04name\f"
```

If you look at the bytes of the proto generated by v1beta3 they look similar, but are still different:

```ruby
key = gcloud.datastore.key "Person", "name"
key_proto = Google::Datastore::V1beta3::Key.encode key.to_grpc
#=> "\x12\x0E\n\x06Person\x1A\x04name"

Again, I'm not the best at reading the protobuf bytes, so if there is a .proto file for the NDB Key I'd really like to see it. I believe we can approximate the application id by prepending `s~` to the project id, but I don't know how to parse the rest of the bytes without the NDB Key proto definition.

**Comment by jgeewax** [comment]
Right... I think we're dealing with different protos here. In Python we have the old "Reference" proto (https://code.google.com/p/googleappengine/source/browse/trunk/python/google/appengine/datastore/entity_pb.py#1701) which works as expected (in Python at least):

```python
import entity_pb
import base64
key = "ahZzfmJ1c3RsaW5nLWtheWFrLTkxNTE2chALEgZQZXJzb24iBG5hbWUM"
ref = entity_pb.Reference()
ref.ParseFromString(base64.b64decode(key))
print ref
```

Which spits out: `app: "s~bustling-kayak-91516" path { Element { type: "Person" name: "name" } }`

@pcostell : How do we deal with AppEngine Datastore serialized keys (like the example here) which uses the `entity_pb.Reference` protobuf in our Cloud Datastore v1beta3 world?

**Comment by pcostell** [comment]
We are working on defining a new serialized format which is proto version agnostic. I definitely don't think we should try to use the old one we used in App Engine. I'll work on getting that language fixed in the console.

**Comment by blowmage** [comment]
@pcostell Glad to hear there is a new serialization format coming!

This issue is specifically to support the old App Engine `urlsafe` strings. I can imaging that maintaining existing URLs is important for folks attempting to move apps from App Engine to ruby. I personally don't think this belongs in glcoud-ruby, but I can see having this functionality in an extension library. That said, we really are stuck until we can get the .proto definition for NDB's Reference/Key. Is it possible for us to obtain that?

**Comment by pcostell** [comment]
This isn't really possibly. Even if you have the proto format, you don't have the application id (as opposed to the project is). I'd rather backport the format into app engine libraries if we need to support a seamless migration from GAE to ruby. At this point, the urlsafe keys are just a format used in 2 libraries, and not a Cloud Datastore-wide feature.

**Comment by blowmage** [comment]
@pcostell Thank you for the clarification! That jives with my understanding. @jgeewax, what do you think?

**Comment by dmcgrath** [comment]
I agree with Patrick.
