### ISSUE TITLE
Support for Speech API

### ISSUE THREAD

**Issue by findchris** [GoogleCloudPlatform/google-cloud-ruby#664]
With the [Speech API](https://cloud.google.com/speech/) released, I thought creating an issue to track its support in `gcloud` would be a good idea.

**Comment by quartzmo** [comment]
@findchris For sure! Thanks for opening it! I'll create a `speech` label right now.

**Comment by quartzmo** [comment]
The google-cloud-speech [gem](https://rubygems.org/gems/google-cloud-speech) is now available!
