### ISSUE TITLE
Doesn't work on JRuby

### ISSUE THREAD

**Issue by barakcoh** [GoogleCloudPlatform/google-cloud-ruby#712]
Hi

Trying to upgrade my Logstash input https://github.com/Wondermall/logstash-input-google-cloud-pubsub
But `gcloud-ruby`'s dependency on `google-protobuf` is causing it to trigger a native extensions build which is not supported by JRuby, making `gcloud-ruby` unusable for JRuby based environments which is a shame because it could be tremendously useful for Logstash.

I've tried `JRUBY_OPTS="--2.0 -Xcext.enabled=true"` but no dice, even though `google-protobuf` does check the `RUBY_PLATFORM` and it looks to me it shouldn't be running the native extensions build but I'm no expert in gem building.

```
Building native extensions.  This could take a while...
ERROR:  Error installing gcloud:
    ERROR: Failed to build gem native extension.

    /opt/logstash/vendor/jruby/bin/jruby -r ./siteconf20160524-809-1vt2zkd.rb extconf.rb
NotImplementedError: C extension support is not enabled. Pass -Xcext.enabled=true to JRuby or set JRUBY_OPTS.

   (root) at /opt/logstash/vendor/jruby/lib/ruby/shared/mkmf.rb:8
  require at org/jruby/RubyKernel.java:1040
   (root) at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
   (root) at extconf.rb:3

extconf failed, uncaught signal 1

Gem files will remain installed in /opt/logstash/vendor/bundle/jruby/1.9/gems/google-protobuf-3.0.0.alpha.5.0.5.1 for inspection.
Results logged to /opt/logstash/vendor/bundle/jruby/1.9/extensions/universal-java-1.8/1.9/google-protobuf-3.0.0.alpha.5.0.5.1/gem_make.out
```

**Comment by quartzmo** [comment]
@barakcoh Thanks for reporting this, and sorry about the trouble. My understanding is that JRuby should use [protobuf/java](https://github.com/google/protobuf/blob/master/java/README.md) instead of trying to install the Ruby C extensions. Can you try installing `google-protobuf` independently from `gcloud` in your environment, and if it still fails, open an issue in [google/protobuf](https://github.com/google/protobuf/issues) instead? We definitely want to resolve this.

**Comment by blowmage** [comment]
I'm looking into this.

**Comment by blowmage** [comment]
@barakcoh What platform are you seeing this behavior on? Mac? Linux? x86? x64?

**Comment by barakcoh** [comment]
@quartzmo that was my understanding as well, however that doesn't seem to be the case.
@blowmage I'm building a docker container on Docker for Mac which is essentially running Alpine linux AFAIK.

```
git:(master) ✗ docker run -it logstash:2.3 bash
root@f7ae3cc8b987:/# GEM_HOME=/opt/logstash/vendor/bundle/jruby/1.9 JRUBY_OPTS="--2.0" /opt/logstash/vendor/jruby/bin/jruby /opt/logstash/vendor/jruby/bin/gem install gcloud
....
Successfully installed google-api-client-0.8.6
Fetching: google-protobuf-3.0.0.alpha.5.0.5.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing gcloud:
	ERROR: Failed to build gem native extension.

    /opt/logstash/vendor/jruby/bin/jruby -r ./siteconf20160525-7-fiydnu.rb extconf.rb
NotImplementedError: C extension support is not enabled. Pass -Xcext.enabled=true to JRuby or set JRUBY_OPTS.

   (root) at /opt/logstash/vendor/jruby/lib/ruby/shared/mkmf.rb:8
  require at org/jruby/RubyKernel.java:1040
   (root) at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
   (root) at extconf.rb:3

extconf failed, uncaught signal 1

Gem files will remain installed in /opt/logstash/vendor/bundle/jruby/1.9/gems/google-protobuf-3.0.0.alpha.5.0.5.1 for inspection.
Results logged to /opt/logstash/vendor/bundle/jruby/1.9/extensions/universal-java-1.8/1.9/google-protobuf-3.0.0.alpha.5.0.5.1/gem_make.out
```

**Comment by Damaotimlin** [comment]
have same issue here +1

**Comment by quartzmo** [comment]
@Damaotimlin Can you provide the details of your environment? Thank you!

**Comment by Damaotimlin** [comment]
@quartzmo Please see below and let me know if you need any further information !
rails -v `5.0.0.rc1`
ruby -v `jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [darwin-x86_64]`
gem -v `2.6.4`
bundler -v `1.12.5`
gcloud -v 
````
Google Cloud SDK 114.0.0
bq 2.0.24
bq-nix 2.0.24
core 2016.06.09
core-nix 2016.06.06
gcloud
gsutil 4.19
gsutil-nix 4.19
```

Gemfile.lock
```
...
gcloud (0.6.0)
      beefcake (~> 1.0)
      digest-crc (~> 0.4)
      google-api-client (~> 0.8.3)
      mime-types (~> 2.4)
      zonefile (~> 1.04)
PLATFORMS
  java

DEPENDENCIES
  bundler (>= 1.12.5)
  byebug
  coffee-rails (~> 4.1.0)
  firebase
  gcloud (<= 0.6)
  haml
  jbuilder (~> 2.0)
  jquery-rails
  listen (~> 3.0.5)
  puma (~> 3.0)
  rails (>= 5.0.0.rc1, < 5.1)
  redis (~> 3.0)
  sass-rails (~> 5.0)
  spring
  spring-watcher-listen (~> 2.0.0)
  therubyrhino
  turbolinks (~> 5.x)
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console

RUBY VERSION
   ruby 2.3.0p0 (jruby 9.1.2.0)

BUNDLED WITH
   1.12.5
...
```

**Comment by Damaotimlin** [comment]
After I successfully install `google-protobuf (3.0.0.alpha.6.0.0)` follow by java and ruby(jruby) guide.
https://github.com/google/protobuf/tree/master/java
https://github.com/google/protobuf/tree/master/ruby

While I try to install `jruby -S gem install gcloud`, it still force me to install `google-protobuf (3.0.0.alpha.5.0.5.1)` and run into C extensions error again and again.

Don't know how to keep my jrails move forward in google. I really like the ideas of GAE and NoSQL storage + Firebase, if which can plus jruby performance would be greater. 

Please helps, thanks !

**Comment by quartzmo** [comment]
@blowmage Any ideas, other than to fork gcloud-ruby?

**Comment by blowmage** [comment]
The issue here isn't gcloud-ruby, it's the grpc and google-protobuf gems. What is needed is for those gems to support JRuby. That is where I would start.

**Comment by genghuiluo** [comment]
exactly same issue when install with jruby on Solaris10.

**Comment by ylastic** [comment]
Same issue on installing with JRuby,  OSX El Capitan.

**Comment by pchaganti** [comment]
Trying to use JRuby so we can speed up some of our BigQuery analytics pieces. Any workarounds to get gcloud to install and work on JRuby?

thanks!

**Comment by blowmage** [comment]
@pchaganti The `grpc` and `google-protobuf` gems are needed for services that connect using gRPC. However, BigQuery does not use gRPC and instead uses the JSON endpoints. So, instead of installing the `google-cloud` gem which contains all services, try just installing the `google-cloud-bigquery` gem which will only connect to BigQuery.

**Comment by quartzmo** [comment]
@pchaganti Did you try installing just the [google-cloud-bigquery gem](https://rubygems.org/gems/google-cloud-bigquery)? It has no dependency on gRPC, and thus it should work on JRuby.

**Comment by pchaganti** [comment]
Ah! @quartzmo  @blowmage  Thanks. Will try this out.

**Comment by JasonLunn** [comment]
[google-cloud-datastore](https://rubygems.org/gems/google-cloud-datastore) does have dependencies on `grpc` and `google-protobuf` so this workaround doesn't help. Any hope of this bug getting addressed soon?

**Comment by JasonLunn** [comment]
Trying to get this fixed via https://github.com/google/protobuf/pull/2199

**Comment by quartzmo** [comment]
@JasonLunn Thanks for pursuing this!

**Comment by JasonLunn** [comment]
@quartzmo / @blowmage - https://github.com/google/protobuf/pull/2199 merged a week ago but I haven't yet seen a gem pushed to RubyGems for the JRuby platform. My [last comment](https://github.com/google/protobuf/pull/2199#issuecomment-251471515) on the PR (about the release process) hasn't been answered - and ideas?

**Comment by blowmage** [comment]
Unfortunately we don't have any visibility into the GRPC team or what their release schedule is.

**Comment by swcloud** [comment]
blocked by grpc team.

**Comment by JasonLunn** [comment]
CC: @remi

**Comment by JasonLunn** [comment]
I can confirm that protobuf has released version [3.1.0](https://rubygems.org/gems/google-protobuf/versions/3.1.0-java) with a `java` platform, which leaves grpc/grpc#6705 as the next known issue.

**Comment by JasonLunn** [comment]
For anyone still following along, JRuby support for gRPC is blocked on https://github.com/grpc/proposal/pull/13 before work can begin in earnest...

**Comment by danoscarmike** [comment]
@geigerj @blowmage suggest we close this issue and move this to the feature backlog (wiki).  @hsaliak and grpc team confirm that the user contributed route is the only viable and that is being tracked elsewhere.

**Comment by danoscarmike** [comment]
Added to feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-ruby/wiki/Feature-backlog

**Comment by Goltergaul** [comment]
are there any news on this? I just stumbled upon this myself
