### ISSUE TITLE
Support rotating keys with File#rewrite

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#730]
The following Storage API method is not currently supported by gcloud-ruby:
- [objects.rewrite](https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite) - Rewrites a source object to a destination object. Optionally overrides metadata. Can be used to [rotate keys](https://cloud.google.com/storage/docs/encryption#customer-supplied) (see #722.)

**Comment by frankyn** [comment]
@quartzmo, What's the status on the objects.rewrite operation?

**Comment by quartzmo** [comment]
@frankyn Thanks for re-surfacing this issue!

@blowmage Does anything block us from implementing this one?

**Comment by blowmage** [comment]
Nothing blocks us AFAIK. Not exactly sure how involved it will be to implement, but it looks fairly big. Lots of settings that can be set in that operation, and it can involve multiple requests based on whether the file is a composite.

**Comment by frankyn** [comment]
The Python client library currently has this implemented and here's a [sample](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/storage/cloud-client/encryption.py#L96) of their surface.

**Comment by quartzmo** [comment]
@frankyn Thanks!
