### ISSUE TITLE
Add support for the App Engine Admin API

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-ruby#732]
We have an Admin API (service management) for App Engine here:
https://cloud.google.com/appengine/docs/admin-api/reference/rest/

It's a pretty basic CRUD / REST style API, but it would be great to have wrappers that make it easier to use.

**Comment by blowmage** [comment]
Moving this issue to the [backlog wiki](https://github.com/GoogleCloudPlatform/google-cloud-ruby/wiki/Feature-backlog).
