### ISSUE TITLE
Confusing behaviour of Pubsub listen method with max parameter 

### ISSUE THREAD

**Issue by wardbekker** [GoogleCloudPlatform/google-cloud-ruby#737]
I find the 'batch' option using the max: parameter for the pubsub listen method confusing: It's not really batching, as it just guarantees a max amount of block yields before the method returns. Also not a batch of messages (e.g. array) is passed as the block argument, but a single msg.

I've run in this issue, because I was actually looking for a real batching listen method, on that will listen without a maximum, but with a batch size, something like this:

> sub = pubsub.subscription "my-topic-sub"
> sub.listen batch_size: 20 do |msgs|
>   # msgs.each do { |msg| .. }
> end

**Comment by quartzmo** [comment]
@wardbekker 

Thanks for opening this issue. This is good feedback about the mention of "batch" being confusing in the context of this method. 

Regarding a real batching listen method, have you any suggestions for how to implement it? Here is the underlying API for [PullRequest](https://cloud.google.com/pubsub/reference/rpc/google.pubsub.v1#pullrequest), for reference.

**Comment by wardbekker** [comment]
Below a workaround for the behaviour I was looking for. It's pulling and yielding an array of messages upto `max_messages`. 

```
  def batch_listen(sub, max_messages)
    while true
      yield(sub.pull(max: max_messages, immediate: false))
    end
  end
  
  batch_listen(sub, 30) do |messages|
    # process msg batch
  end
```

**Comment by wardbekker** [comment]
Actually, it looks like a trivial change to the current code. 

```
      def listen max: 100, autoack: false
        loop do
          msgs = wait_for_messages max: max, autoack: autoack
          yield(msgs)
        end
      end
```

**Comment by jgeewax** [comment]
@wardbekker , Thanks for the feedback -- really appreciate you taking the time.

Out of curiosity ... can you share any more about the higher-level use case of what you're trying to accomplish? I'm just trying to understand the scenario where getting chunks of 20 is easier to work with than a stream of individual requests.

**Comment by wardbekker** [comment]
Use case: I use pub/sub for queuing i.a. image annotation via Google Vision API. There are [request usage limits ](https://cloud.google.com/vision/docs/image-best-practices#usage_limits) like requests per second.  You can specify multiple images per annotation request to have higher throughput. As my  solutions creates one pub/sub message per annotation request, I like to batch listen from the subscription.

**Comment by quartzmo** [comment]
@wardbekker Thanks for sharing this use case, really cool to hear about these services being used together.

**Comment by blowmage** [comment]
@wardbekker Thanks for bringing this up. I'm sorry that the documentation caused you confusion. We will remove the word "batch" so that others won't also get tripped up by that.

I'm glad that you have identified a solution that you consider "trivial". Enabling folks to craft their own solutions was our intention, and I'm glad you arrived there. I think your batch use case makes sense. This is something we are open to supporting along side the current `listen` implementation, but it would be in addition to and not replace it. Please take a look at our [Contributors Guide](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/CONTRIBUTING.md) and let us know if you have any questions on making contributions to gcloud-ruby.

**Comment by wardbekker** [comment]
Thx @quartzmo and @blowmage 

BTW: My apologies for using the term "trivial". Maintaining and improving this great ruby gem is anything but trivial offcourse, so thank you!

I'll will take a look at the contributers guide and see if I can start working on a contribution.

**Comment by blowmage** [comment]
Documentation updated in #749.
