### ISSUE TITLE
gcr.io listing tags?

### ISSUE THREAD

**Issue by 34code** [GoogleCloudPlatform/google-cloud-ruby#739]
feature request..

would love to get access to gcr.io images and tags and creation dates.. so i can set up some cleanup scripts to remove old versions of images.

we deploy about 3x per day and this can lead to many many tags over time

**Comment by blowmage** [comment]
We were just looking at the container registry yesterday! I agree this would be great to support. Thanks for opening the issue.

**Comment by blowmage** [comment]
Moving this issue to the [backlog wiki](https://github.com/GoogleCloudPlatform/google-cloud-ruby/wiki/Feature-backlog).

**Comment by tareksamni** [comment]
@blowmage I'd like to work on this one .. did any pick it or should I?

**Comment by quartzmo** [comment]
@jbolinger What do you think about adding this?

**Comment by jbolinger** [comment]
Sounds perfectly reasonable to me @quartzmo, but I actually don't have much visibility or control of the backlog for things like this. 

If you and @blowmage aren't sure how you'd like to handle it I know who we can ping for some additional advice, but otherwise I'll just defer back to you.

**Comment by tareksamni** [comment]
@jbolinger @quartzmo @blowmage Apparently, GCP does not have an API for this but there is docker registry API that we can use to achieve the same results.

What would you like to do here? to implement and integrate with docker registry? or to wait for APIs from GCP?

**Comment by quartzmo** [comment]
@jbolinger I think we will always need your guidance on adding APIs. We wouldn't want to duplicate work with generated support.

**Comment by jbolinger** [comment]
@quartzmo totally understand, and I wish I had guidance to give 😄. Let's have @jonparrott take a look at this one so we're aligned with any potential changes on the GCP side that I wouldn't be aware of.

**Comment by jonparrott** [comment]
gcr.io does not have a separate API beyond the normal Docker registry API. I would suggest using standard docker client libraries for this purpose.
