### ISSUE TITLE
Subscription name is not optional

### ISSUE THREAD

**Issue by Draiken** [GoogleCloudPlatform/google-cloud-ruby#740]
https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.11.0/lib/gcloud/pubsub/topic.rb#L94-L141

The example says we can leave out the name and get a generated name, but the method requires a name.

It's also not a good example, since we give name `my-topic-sub` and get name `generated-sub-name`

**Comment by Draiken** [comment]
Nevermind... duplicate of #193

**Comment by blowmage** [comment]
Ho @Draiken, thanks for opening this issue. We thought we had removed that example from the documentation when we discovered the discrepancy between the official API documentation and the API behavior. That is very confusing. I'm sorry for that. We will get the documentation updated.

**Comment by blowmage** [comment]
@quartzmo Can you make sure the documentation is correct?

**Comment by quartzmo** [comment]
Yes, I'll look into it.
