### ISSUE TITLE
Update Resource Manager to v1 (and gRPC?)

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#755]
Resource Manager [Rest API `v1`](https://cloud.google.com/resource-manager/reference/rest/v1/projects) is now available. A [RPC API `v1`](https://cloud.google.com/resource-manager/reference/rpc/) also appears to be available.

gcloud-ruby is [currently targeting](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.11.0/lib/gcloud/resource_manager/connection.rb#L27) Rest API `v1beta1`.

**Comment by blowmage** [comment]
Are protobufs available? I don't see any in the [googleapis repo](https://github.com/googleapis/googleapis/tree/master/google).

**Comment by blowmage** [comment]
@jgeewax Any word on Resource Manager support for gRPC?

**Comment by jgeewax** [comment]
@blowmage I created a bug to ask for these.... hopefully will hear back this week.

**Comment by bjwatson** [comment]
We'll create a new issue when these protos are public.
