### ISSUE TITLE
Expand acceptance testing

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#759]
The current acceptance tests do not provide sufficient coverage. Tests should be added for all services, until we have the confidence to release without additional manual testing after making project-wide changes, such as those in #733 .

**Comment by quartzmo** [comment]
I mistakenly closed this issue in a commit message. Re-opening because the following services still need expanded acceptance testing:

- [ ] Datastore
- [ ] Logging
- [ ] Pub/Sub

**Comment by bjwatson** [comment]
@quartzmo Please scope this more tightly.

**Comment by quartzmo** [comment]
I reviewed the acceptance testing for the three packages listed above (Datastore, Logging, and Pub/Sub), and feel that the coverage is adequate at this time. (Logging is also covered by integration tests.) So I will not be opening more tightly-scoped issues to replace this issue.
