### ISSUE TITLE
chunk_size

### ISSUE THREAD

**Issue by gramos74** [GoogleCloudPlatform/google-cloud-ruby#764]
Some days ago I created a pull request https://github.com/GoogleCloudPlatform/gcloud-ruby/pull/757
because I realised that the chunk_size was removed from the version 0.11.

But I see now that it is available again in the master branch... so you can close it if you want.

**Comment by gramos74** [comment]
ops... this is a huge problem for us

which google api client version is ?

**Comment by blowmage** [comment]
[0.9.11](https://rubygems.org/gems/google-api-client/versions/0.9.11)

**Comment by gramos74** [comment]
Ok, I will do a fork of 0.11 with my fix.

I will investigate that point with the new google api client unless you are faster than me :)

Thaks

**Comment by quartzmo** [comment]
@gramos74 Much thanks for your help and input on this issue!

**Comment by gramos74** [comment]
The Hurley that the new google api client use is : https://github.com/lostisland/hurley ?

**Comment by quartzmo** [comment]
Yes, correct. We are also aware of this (and concerned):

> DEAD project, don't use

**Comment by gramos74** [comment]
ooohhhh... I'm shocked :o

**Comment by blowmage** [comment]
This issue should have closed in November when the PR #757 was closed.
