### ISSUE TITLE
Question / feature request: error handling / retries in Datastore

### ISSUE THREAD

**Issue by timanovsky** [GoogleCloudPlatform/google-cloud-ruby#808]
**Question**: What is current error handling procedure and retry approach? Documentation says 

> You can configure how many times API requests may be automatically retried. When an API request fails, the response will be inspected to see if the request meets criteria indicating that it may succeed on retry, such as 500 and 503 status codes or a specific internal error code such as rateLimitExceeded. If it meets the criteria, the request will be retried after a delay. If another error occurs, the delay will be increased before a subsequent attempt, until the retries limit is reached.

However from the code (`service.rb`, `backoff.rb`) I see that operation is only retried in case of grpc code 14. What is this code? It is not documented. Does it cover rate limit back off? What about network errors?

In the past with API v2 I used the following list of exception to retry the operation (in my wrapper):

``` ruby
    repeatable = exception.is_a?(Faraday::TimeoutError) || exception.is_a?(Faraday::ConnectionFailed)
    repeatable ||= exception.is_a?(Faraday::SSLError)
    repeatable ||= exception.try(:response).present? &&
                   exception.response.try(:env).present? &&
                   ((500..599).include?(exception.response.env.status) || [401, 409].include?(exception.response.env.status))
    repeatable ||= exception.is_a?(SocketError)
    repeatable ||= exception.is_a?(Errno::EPIPE) || exception.is_a?(Errno::ECONNRESET) || exception.is_a?(Errno::ECONNABORTED)
```

Which all have been observed during running on production and all proven to be retriable. 

**Feature request**: Make `retries` configurable per request. There are different types of requests in application which require different handling of errors/retries. For example if error happening during web page load I'd better show error to user and let him retry rather than render page a minute later after background retries. Some operations are ok to fail as we can retry higher level application level transaction. But some operations are critical and must be retried heavily. So optional `retries` parameter to all API calls would be helpful.

**Comment by quartzmo** [comment]
@timanovsky Thank you for yet another well-written and thoughtful issue. Here are some supporting links: First, [the retry handling for gRPC](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.12.0/lib/gcloud/backoff.rb#L114), which as you note, only tests for one error code: `self.grpc_codes = [14]` (which is `UNAVAILABLE `.)

The documentation that I could find for [gRPC status codes](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md) does not contain the integer type codes, but you can see the code mappings in [google/protobuf/stubs/status.h](https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/status.h).

**Comment by quartzmo** [comment]
Here is the [Datastore documentation for error codes](https://cloud.google.com/datastore/docs/concepts/errors#error_codes).

**Comment by quartzmo** [comment]
It seems to me that retry handling (like a lot of things) should be **customizable with sensible defaults**. I agree that the smallest scope of customization should be a single method (API request), but it is also good to avoid duplication and support applying the same customization to multiple method calls. So I am wondering if an enclosing block might work.

  This would be similar to the age-old pattern for transactions, so I'll include both in an example:

  ```ruby
  task_key = datastore.key "Task", "sampleTask"

  datastore.retries limit: 10, codes: [:ABORTED, :DEADLINE_EXCEEDED, :UNAVAILABLE] do
    datastore.transaction do |tx|
      if tx.find(task_key).nil?
        task = datastore.entity task_key do |t|
          t["type"] = "Personal"
          t["done"] = false
          t["priority"] = 4
          t["description"] = "Learn Cloud Datastore"
        end
        tx.save task
      end
    end
  end
  ```

Note that `ABORTED`, `DEADLINE_EXCEEDED`, and `UNAVAILABLE` are the three conditions in which retrying is recommended by the Datastore documentation, so they should probably be the defaults. But let's assume that the defaults are something different, and that this is an override.

**Comment by blowmage** [comment]
In the future the retry behavior will be controlled these [these GAX classes](https://github.com/googleapis/gax-ruby/blob/0fd4c80015b3b519d5c60e1410cfd9e1c57dc977/lib/google/gax.rb#L184-L232). I have no idea how (or if) gcloud-ruby exposes it. GAX should retry when needed, so I would tend towards ensuring that GAX behaves correctly over exposing the configuration in gcloud-ruby.

**Comment by quartzmo** [comment]
I would personally hope that the GAX configuration is accessible when using gcloud-ruby with GAX.

@blowmage Any timeline on moving to GAX? Would it be worth it for me to attempt a PR supporting per-method retry configuration for gRPC in the meantime?

**Comment by blowmage** [comment]
I wouldn't want to add to the existing API before we know exactly what we can support across Google API Client, gRPC, and GAX.

**Comment by blowmage** [comment]
To answer the original question, retries are now handled by Google API Client for REST services, and the code that used to be `Gcloud::Backoff` for gRPC services. But moving forward, retries for the gRPC services will handled by GAX. This change may happen as soon as the next major release.

The challenge is how gcloud-ruby maintains a consistent API across REST and gRPC services, across different dependencies. Right now that is the `retries` optional argument when creating new service objects.

```ruby
require "gcloud"

gcloud = Gcloud.new "my-todo-project-id",
                    "/path/to/keyfile.json"
datastore = gcloud.datastore retries: 10
```

The onus is upon gcloud-ruby and its upstream dependencies to make sure that all errors that should be retried are retried. I think it was probably a mistake to expose `Gcloud::Backoff` in the public API.

**Comment by timanovsky** [comment]
@quartzmo Thanks for the link to documentation. From what I see there `INTERNAL` should also be retried. It is recommended once, but... Also it looks like `RESOURCE_EXHAUSTED`is the quota exhaustion, then should not the library properly handle the back off?

And still not clear how network errors propagate (if they do) from grpc layer. 

I have run the project on test setup for last 16 hours, but didn't see any error yet. It is not heavily loaded deployment though, with v2 API I saw about one error a day. And just for the record, and may be of interest to you, on heavily loaded production setup (v2) we see 1/10,000 error rate (all corrected by retries).

**Comment by timanovsky** [comment]
Here are more error codes: http://www.grpc.io/docs/guides/error.html

**Comment by quartzmo** [comment]
@timanovsky I'm very interested to hear what errors are raised in your fully-loaded deployment. Thanks again.

**Comment by timanovsky** [comment]
@quartzmo See code snippet in my initial comment. All cases were added after seeing on production (except that 500..599 range was added in full). You may wonder about seeing `SSLError` but yes, it is indeed happening, and it is indeed transient. Just sometimes SSL handshake is rejected by server.

**Comment by timanovsky** [comment]
@quartzmo Sorry, you probably meant new API. That I will be able to tell in a week probably

**Comment by quartzmo** [comment]
@timanovsky Yes, I meant the new one. And trust me, we want to do all we can to make sure you can continue to upgrade your production deployment(s). If you have any chance to look into GAX, and if you find anything in it that concerns you, please let us know.

**Comment by timanovsky** [comment]
@quartzmo  That's the first error surfaced :
`Gcloud::InternalError: 13:{"created":"@1470385322.049611107","description":"OS Error","errno":32,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":340,"os_error":"Broken pipe","syscall":"sendmsg"} `

`cause` :  `GRPC::BadStatus: 13:{"created":"@1470385322.049611107","description":"OS Error","errno":32,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":340,"os_error":"Broken pipe","syscall":"sendmsg"}`

**Comment by quartzmo** [comment]
Hmmmm, `"Broken pipe"`!

Any idea about this @blowmage?

**Comment by blowmage** [comment]
No idea. It looks like a problem in the GRPC client though. What OS and hardware is this running on?

@murgatroid99 Do you have any input on this?

**Comment by timanovsky** [comment]
@blowmage This is on Heroku

**Comment by timanovsky** [comment]
FYI, i have seen this exception (broken pipe) three times so far. I believe it is some form of socket error.  For now I added retry logic in case of this exception.
THis one https://github.com/grpc/grpc/issues/7661 worries me much more though.

**Comment by quartzmo** [comment]
@timanovsky:

1. Is grpc/grpc#7661 possibly a gcloud-ruby bug?
2. Do you want to open a grpc issue for this [broken pipe error](https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/808#issuecomment-237834246)?
3. Are you happy with the latest gcloud-ruby retry implementation? If so, are you ok to close this issue?

**Comment by timanovsky** [comment]
1 & 2 makes sense. Here we go: #817; https://github.com/grpc/grpc/issues/7663
3. How I can be happy if I need to keep observing my live deployment to see which exceptions pop up to application layer and then implement retry logic there. Sorry.

**Comment by quartzmo** [comment]
@timanovsky Makes sense. Can you suggest an API design for gcloud-ruby that will let you configure the retry implementation for arbitrary exceptions? The goal in my mind is that clients should never need to implement retry logic, but should have control over when retry occurs. (Do you agree?)

**Comment by timanovsky** [comment]
@quartzmo For me the retry API is a smaller problem than unknown/undocumented exceptions. The former is understood problem and if there is API in `gclud-ruby` I could use it, or I could use external retry logic. However not knowing what exceptions to expect and what returned exception classes really mean makes it very hard to build production grade system. 

Nobody has answered yet what is throttling behavior. Are requests retried automatically at proper intervals, or I have to do it in upper layer. If later what exception code should I expect?

**Comment by quartzmo** [comment]
@timanovsky I agree with all points. We will do our best to improve the documentation of the possible exception types, as well as to document the retry intervals.

**Comment by bmclean** [comment]
@timanovsky We are seeing the broken pipe errors several times a day on Heroku as well.
```
status=500 error='Gcloud::InternalError: 13:{"created":"@1471638568.698771416","description":"OS Error","errno":32,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":340,"os_error":"Broken pipe","syscall":"sendmsg"}'
```
Are you finding an application retry successful?

**Comment by timanovsky** [comment]
yes, retrying has always been successful.

Best regards,
Alexey Timanovsky.

**Comment by quartzmo** [comment]
I believe this has been resolved by exposing the GAPIC client configuration. But please feel free to reopen if you still encounter issues with retry.
