### ISSUE TITLE
Unwanted debug prints in console

### ISSUE THREAD

**Issue by timanovsky** [GoogleCloudPlatform/google-cloud-ruby#814]
Hi, with new 0.12.1 release I see messages on console like below when I start my application. As far as I remember, there were no with 0.11. It is not critical, but a bit nasty
```
I0802 05:08:16.217477358   23373 ev_epoll_linux.c:84]        epoll engine will be using signal: 36
D0802 05:08:16.217850760   23373 ev_posix.c:106]             Using polling engine: epoll
```

**Comment by blowmage** [comment]
Those logging statements are coming from [within the GRPC C code](https://github.com/grpc/grpc/blob/13d3e3b7e2538025148dd08956765eab516b2f0b/src/core/lib/iomgr/ev_posix.c#L106). The GRPC ruby gem loads the C code, and supports ruby's logger with `GRPC.logger`. However, log messages within the C code [does not use the same logging mechanism](https://github.com/grpc/grpc/blob/8fb6c924b54775be2d9fea52a39cc930460558de/include/grpc/impl/codegen/log.h#L77) as the ruby code. I am unaware of how (or if) we can direct those logging statements elsewhere.

**Comment by blowmage** [comment]
@timanovsky The 0.20.0 release uses grpc 1.0 and it looks to me that the polling library chosen is no longer being printed. Can you verify and close this issue? Thanks!

**Comment by timanovsky** [comment]
ok, will check

Best regards,
Alexey Timanovsky.
