### ISSUE TITLE
Question/documentation: thread safety and concurrency

### ISSUE THREAD

**Issue by timanovsky** [GoogleCloudPlatform/google-cloud-ruby#816]
Hello,
would be good to have documentation describing how to use the library in multithreaded environment. Does user need to create multiple say `Gcloud.datastore` objects, one per thread, or is it possible to use single object?
I currently assume the former and use a connection pool gem to manage connections.

**Comment by quartzmo** [comment]
@apolcyn Do you know? Given that the [`Google::Datastore::V1beta3::Datastore::Stub` instance is memoized](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.12.1/lib/gcloud/datastore/service.rb#L46-L47), is using this single instance threadsafe?

**Comment by apolcyn** [comment]
The client stub is thread safe, assuming a standard ruby interpreter like MRI.

The grpc client stub is meant to be able to make multiple calls from different threads on the same client.

**Comment by quartzmo** [comment]
@apolcyn Thank you! I agree with @timanovsky that it would be good to mention this in the documentation. This issue should remain open until this done.

**Comment by apolcyn** [comment]
I should even add that it's encouraged to use the same stub for as many calls as possible to the same serve. It's set up to be able to share multiple calls across a single http2 connection, and you should be able to get much better performance this way.

Thanks for bringing this up, this should be noted somewhere in grpc ruby docs if it's unclear.

**Comment by bmclean** [comment]
@apolcyn In issue #691 we had discussed using a Rails initializer with one datastore object for each web server thread instead of one datastore object for all threads. Something like this:

`Thread.current[:dataset] ||= Gcloud.datastore(config)`

To confirm, we would be better off using one datastore object shared across all threads?

`@dataset ||= Gcloud.datastore(config)`

**Comment by quartzmo** [comment]
@apolcyn If you can find mention of this in the gRPC docs, please link it here! I searched earlier today, but couldn't find it.

**Comment by apolcyn** [comment]
@bmclean yes it should be better to use a single client stub from a performance perspective, and there shouldn't be any reason not to use the same client as long as you have the same channel settings on all of them (e.g., all of the client stubs that you're creating use the same channel credentials, and are all set to make calls to the same server).
