### ISSUE TITLE
Update top-level guides to reflect individual gems

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#831]
The top-level guides (README, CONTRIBUTING, OVERVIEW) should be updated to reflect the switch to individual gems from the monolithic gem. Where appropriate, content can be moved from the top-level guide to individual guides.

**Comment by quartzmo** [comment]
This is related to #832.

**Comment by quartzmo** [comment]
@blowmage What do you think about replacing the current content in CONTRIBUTING.md with a referral list of links to the gh-pages docs pages for contributing? Something like:

> Please see the specific contributing instructions for:
> * [google-cloud](https://quartzmo.github.io/gcloud-ruby/#/docs/google-cloud/v0.12.2/guides/contributing)
> * [google-cloud-core](https://quartzmo.github.io/gcloud-ruby/#/docs/google-cloud-core/v0.12.2/guides/contributing)
> * [google-cloud-datastore](https://quartzmo.github.io/gcloud-ruby/#/docs/google-cloud-datastore/v0.12.2/guides/contributing)
> * ...

**Comment by quartzmo** [comment]
The duplication between CONTRIBUTING.md and https://googlecloudplatform.github.io/gcloud-ruby/#/docs/v0.12.2/guides/contributing seems undesirable...

**Comment by quartzmo** [comment]
I forgot to update CONTRIBUTING.md. Reopening.

**Comment by quartzmo** [comment]
Regarding contributing, these are the services with acceptance tests:

google-cloud-bigquery
google-cloud-datastore
google-cloud-dns
google-cloud-language
google-cloud-logging
google-cloud-pubsub
google-cloud-speech
google-cloud-storage
google-cloud-translate
google-cloud-vision

(all but resource manager)

**Comment by blowmage** [comment]
This should have been re-closed by abcf98e.
