### ISSUE TITLE
Docs for 0.20.0 for BQ not working

### ISSUE THREAD

**Issue by pchaganti** [GoogleCloudPlatform/google-cloud-ruby#865]
Unable to browse the docs for BQ with the latest release.

Clicking on https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.20.0/google/cloud/bigquery/dataset loads up the main page.

**Comment by blowmage** [comment]
Thanks for the report. We'll get it fixed.

**Comment by quartzmo** [comment]
@pchaganti The BigQuery docs paths are fixed now. Thanks again for reporting this error!
