### ISSUE TITLE
Datastore - 0.20.0 - Ancestor query structure has changed

### ISSUE THREAD

**Issue by bmclean** [GoogleCloudPlatform/google-cloud-ruby#868]
We see differences in the construction of query ancestors when upgrading from `gcloud 0.12.2` to `google-cloud-datastore 0.20.0`. For example:

```
query = CloudDatastore.dataset.query('MockEntityKind')
parent_key_int = CloudDatastore.dataset.key('ParentMockEntityKind', 12345)
grpc = query.ancestor(parent_key_int).to_grpc
ancestor_filter = grpc.filter.composite_filter.filters.first
ancestor_int_key = ancestor_filter.property_filter.value.key_value.path[0]

query = CloudDatastore.dataset.query('MockEntityKind')
parent_key_string = CloudDatastore.dataset.key('ParentMockEntityKind', 'ABCDEF')
grpc = query.ancestor(parent_key_string).to_grpc
ancestor_filter = grpc.filter.composite_filter.filters.first
ancestor_string_key = ancestor_filter.property_filter.value.key_value.path[0]
```
Inspecting ancestor_int_key and ancestor_string_key using `gcloud 0.12.2`:
```
<Google::Datastore::V1beta3::Key::PathElement: kind: "ParentMockEntityKind", id: 12345, name: nil>
<Google::Datastore::V1beta3::Key::PathElement: kind: "ParentMockEntityKind", id: nil, name: "ABCDEF">
```
Inspecting ancestor_int_key and ancestor_string_key using `google-cloud-datastore 0.20.0`:
```
<Google::Datastore::V1::Key::PathElement: kind: "ParentMockEntityKind", id: 12345, name: "">
<Google::Datastore::V1::Key::PathElement: kind: "ParentMockEntityKind", id: 0, name: "ABCDEF">
```
This change doesn't seem to be causing any problems (except with our test suite) but does seem a bit strange. When using an ancestor with an integer id the ancestor name is now set to empty string (previously nil) and when using an ancestor with a name the ancestor id is now set to 0 (previously nil).

**Comment by quartzmo** [comment]
@bmclean Yes, this is correct. The change from `nil` values to defaults such as `""` and `0` is due to [this correctness fix](https://github.com/google/protobuf/blob/master/CHANGES.txt#L127) in google/protobuf. We have had to update our tests for this behavior. It sounds like you'll need to do the same. Thanks for reporting!

**Comment by quartzmo** [comment]
Oops, maybe I replied too quickly. The `id` and `name` fields do not seem likely to be `oneof` fields. I'll keep this issue open and look into it.

**Comment by blowmage** [comment]
Yes, instead of testing the `id` and `name` values, try testing the key object's `id_type` value. See 5351cc9fddbec35f5efc1b1ed57a9901cc464b90

**Comment by blowmage** [comment]
Oops, sorry. Wrong commit. I meant 243227c5664268d2fb80122c6ebb361d0315d8f6

**Comment by bmclean** [comment]
@blowmage `id_type` is perfect. Thanks!
