### ISSUE TITLE
Emit header for gRPC messages

### ISSUE THREAD

**Issue by pcostell** [GoogleCloudPlatform/google-cloud-ruby#869]
gRPC connections currently don't have enough information in the request for us to do efficient traffic management/routing. 

Will you add a header that allows for us to optimize for this on the server? The header format is:

```
name: google-cloud-resource-prefix
value: projects/my-project-id
```

In general, the prefix would be the same as the JSON-over-http URL up to any custom method. For example, a Cloud Datastore commit message over JSON would hit the url `projects/my-project-id:commit`.

Here is an example usage in the cloud-bigtable-client: https://github.com/GoogleCloudPlatform/cloud-bigtable-client/pull/915/files#diff-1078787e69bc1d7c5bb8507f0a87a143R83

**Comment by blowmage** [comment]
Is this needed just for Datastore? Or does every service using GRPC to connect need this as well?

**Comment by pcostell** [comment]
This will be needed for all services though we are working with the gRPC team to expose this information automatically.

/cc @eddavisson

**Comment by eddavisson** [comment]
As @pcostell notes, our eventual goal is to build this into the gRPC layer, but we'd like to get something in place in the meantime.

**Comment by blowmage** [comment]
I thought I understood how to set custom headers in the GRPC client, but it turns out I was confused. Can you point us to some documentation on configuring the GRPC client or making API calls with custom headers? @jmuk is there anything in GAX that exposes this?

**Comment by jmuk** [comment]
It seems a bit obscure, but gRPC sends the custom metadata as the headers, see https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

Metadata can be specified for individual method call with optional `metadata:` parameter. For Ruby, the keys are `Symbol` for some reasons, and the values are string.

In GAX, `CallOptions` has `kwargs` which are (I think) used as the HTTP headers in gRPC:

- https://github.com/googleapis/gax-ruby/blob/master/lib/google/gax.rb#L167
- https://github.com/googleapis/gax-ruby/blob/master/lib/google/gax/api_callable.rb#L379

So you can use that if you're using GAX.

Unfortunately this can't be customized at the constructor of the generated files, so you will have to specify on the every method call.

**Comment by quartzmo** [comment]
Thank you @jmuk! That is very helpful.
