### ISSUE TITLE
Verify case of headers

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-ruby#870]
**This might be a no-op, but please double check. Filing this issue just in case.**

We need to ensure that all headers used for gRPC are written in lower-case. Please review this [Pull Request](https://github.com/GoogleCloudPlatform/gcloud-python/pull/2212) for reference of what needs to be updated.

Again, perhaps this doesn't apply to your language. Feel free to comment and then close the issue (after double checking).

**Comment by quartzmo** [comment]
Thanks for the heads-up @omaray! Will do.

**Comment by omaray** [comment]
Hey folks, are we good here? Can we close?

**Comment by quartzmo** [comment]
I believe that in google-cloud-ruby, gRPC headers are never set directly. See this [Pub/Sub stub initialization code](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb#L43-L57) for an example similar to that in the Python PR above.

Closing. (@blowmage: Please affirm or re-open, thanks!)

**Comment by blowmage** [comment]
I'm not aware of any custom headers in the GRPC service implementations.
