### ISSUE TITLE
Update google-cloud-ruby landing page to rename "gcloud" (where appropriate)

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-ruby#879]
The current [Landing Page for Ruby](https://googlecloudplatform.github.io/google-cloud-ruby/#/) mentions "gcloud" still. We should update to "google-cloud" as appropriate. The [Landing Page for Node](https://googlecloudplatform.github.io/google-cloud-node/#/) is a good reference.

_Note: if this is not the right place to file the issue (perhaps in gcloud-common?) feel free to close of course and re-open elsewhere - or make this a dup!_

**Comment by quartzmo** [comment]
Dup of #866, which was closed, but the gh-pages branch was never updated with the change. Done now.

**Comment by blowmage** [comment]
Thanks @quartzmo!
