### ISSUE TITLE
How to read datastore blob values created as ndb compressed JsonProperty

### ISSUE THREAD

**Issue by bmclean** [GoogleCloudPlatform/google-cloud-ruby#888]
We have entities in our datastore that were previously created using the ndb [JsonProperty](https://cloud.google.com/appengine/docs/python/ndb/entity-property-reference) with `compressed=True`. For example:
`ndb.JsonProperty(compressed=True)`
How do we use these with google-cloud-datastore? After we retrieve the entity the property is a StringIO object, so we tried this:
`Zlib::GzipReader.new(entity)`
but we get Zlib::GzipFile::Error (not in gzip format).

**Comment by blowmage** [comment]
All blob values will be returned as a StringIO object. I am not familiar with ndb or its compression configuration. Is the value readable as a JSON stream? Or does it look t be compressed?

**Comment by bmclean** [comment]
Here is an example of the value of a compressed JsonProperty straight out of the datastore:
```
value = 'eJyVz7EKAjEMBuBXkc5GkqZNcm5tbF9DHNwElwOH497dejgIDmKm/PDzhSwhlVRdYwNppwxETaBgHlsnci+KphaOuyVEJEFj3MLjOp/n+3y5jRSZRRPjAdd1vwtSY8/q+gGapfoHSKgSs8kAh7fVJozfNR7zPtoGXrpV4OoVkpNB7c7QO06KUhi9/fhCxeilrU/Te0PY'
```
If I run this:
```
Zlib.inflate(Base64.decode64(value)) 
```
I get the correct result. However, I can't see how to perform the equivalent on the StringIO object that is returned using google-cloud-datastore.

**Comment by blowmage** [comment]
What about this?

```ruby
Zlib.inflate(Base64.decode64(value.read))
```

**Comment by bmclean** [comment]
Yes, thank you that works. I had tried:
```
Zlib.inflate(Base64.decode64(value.gets))
```
which gives Zlib::BufError (buffer error) but I didn't think to try read.

**Comment by blowmage** [comment]
Glad it worked!
