### ISSUE TITLE
Code: duplicate files

### ISSUE THREAD

**Issue by timanovsky** [GoogleCloudPlatform/google-cloud-ruby#893]
https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-core/lib/google/cloud/core/backoff.rb 
and 
https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-core/lib/google/cloud/core/grpc_backoff.rb

First should probably be deleted

**Comment by quartzmo** [comment]
Thanks for catching this duplication! Our goal is to replace this functionality soon with GAX, at which time we will remove both files.
