### ISSUE TITLE
Sync Coveralls Repo

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#897]
The coveralls repo needs to be synched after the repo was renamed. Coverage reports are not currently being run on commits or pull requests. We don't have permissions to the repo on Coveralls, so I assume this is something JJ can do.

**Comment by jgeewax** [comment]
/cc @silvolu 

need to update https://coveralls.io/github/GoogleCloudPlatform/gcloud-ruby

**Comment by blowmage** [comment]
I created a new project on Coveralls. It doesn't have all the history of the old project, but CircleCI is configured to push coverage data to it now.

https://coveralls.io/github/GoogleCloudPlatform/google-cloud-ruby
