### ISSUE TITLE
High latency when using Logger class

### ISSUE THREAD

**Issue by dazuma** [GoogleCloudPlatform/google-cloud-ruby#898]
It appears that the Google::Cloud::Logging::Logger class makes individual blocking RPCs for each log entry. We were prototyping a Rails app that emits maybe a few dozen log entries per request, and this quickly became by far the bulk of the request latency as a whole.

Is there currently any plan or discussion around non-blocking RPCs, batching log entries, and/or any other ideas for improving Logger latency?

**Comment by blowmage** [comment]
No current plans, but we are open to any/all of these ideas to improve.

**Comment by quartzmo** [comment]
@dazuma Great issue! Thanks for investigating this. I'm sure there are obstacles, but it would be awesome to have access to your test/demo app, if by any chance you can open-source it. (and most importantly: its deployment configuration...)

**Comment by dazuma** [comment]
Closing this, since the AsyncWriter work has been merged.

**Comment by blowmage** [comment]
Thanks Dan!
