### ISSUE TITLE
Support generation/metageneration flags?

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#90]
Do we support the ifGenerationMatch / ifGenerationNotMatch / ifMetagenerationMatch / ifMetagenerationNotMatch flags on the following API calls?
- [ ] Bucket delete
- [ ] Bucket get
- [ ] Bucket patch
- [ ] Bucket update
- [ ] File copy
- [ ] File delete
- [ ] File get
- [ ] File insert
- [ ] File patch
- [ ] File update

**Comment by blowmage** [comment]
I don't see any explicit support for these flags in gcloud-node or gcloud-python.

**Comment by blowmage** [comment]
The more I think about this, the more I think this is something we could use in gcloud-ruby without exposing it directly in the API. We could add the flags to the update/patch calls to make sure the record isn't stale.

**Comment by Capstan** [comment]
Buckets don't have generations. Objects have both. If you don't use patch, but rather manual read/modify/write via get/update, the update should necessarily use ifMetagenerationMatch so that you don't clobber intervening edits.

**Comment by blowmage** [comment]
Right, buckets have [metageneration parameters](https://cloud.google.com/storage/docs/json_api/v1/buckets/update) on their crud API calls, and files/objects have both generation and metageneration.

**Comment by blowmage** [comment]
Let me know if this needs to be in gcloud-ruby for release and I'll assign it to the appropriate milestone.

**Comment by Capstan** [comment]
In order of priority:
1. Being able to specify an object generation for read, copy, compose
2. Being able to specify an object generation & metageneration, and bucket metageneration for CRUD.

ifGenerationMatch=0 is the equivalent of "don't overwrite", which ends up being useful.

**Comment by danoscarmike** [comment]
Hi Mike, closing this.  Please reopen with more description if still relevant.  Thanks.  Dan
