### ISSUE TITLE
Cloud Vision docs for Ruby feedback: typo perhaps.

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-ruby#905]
The very first sentence is the following: 

"Google Cloud Vision allows easy integration of vision detection features developer applications, including image labeling, face and landmark detection, optical character recognition (OCR), and tagging of explicit content."

The "...developer applications..." sounds a bit off. I wonder if you meant to say "... to develop applications..." or perhaps something else.

**Comment by omaray** [comment]
Just noticed the right sentence in this page: http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-vision/v0.20.2/google/cloud/vision/project

I guess you are missing the word "within", such as "...features within developer applications..." in the original page: 

http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-vision/v0.20.2/google/cloud/vision

**Comment by quartzmo** [comment]
Yes, a typo, thank you for the thorough review! Fixing now.
