### ISSUE TITLE
URL for Best Practices is invalid

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-ruby#906]
In the "Creating Images" paragraph of the Cloud Vision docs, the "Best Practices - Image Sizing" link send the user to a 404.

Current value: https://cloud.google.com/vision/docs/image-best-practices#image_sizing

Expected value: https://cloud.google.com/vision/docs/best-practices#image_sizing

**Comment by omaray** [comment]
In fact, I'm noticing the wrong URL being used in a few places:

http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-vision/v0.20.2/google/cloud/vision

http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-vision/v0.20.2/google/cloud/vision/image

**Comment by omaray** [comment]
and here: http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-vision/v0.20.2/google/cloud/vision/project

**Comment by quartzmo** [comment]
@omaray Thanks for catching this change!
