### ISSUE TITLE
Not advertising individual modules in docs

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-ruby#907]
In the Vision docs (and others too) we are still advertising to `require "google/cloud"` and instantiate the Service through `Google::Cloud.new`.

I was wondering if there were plans to show in the docs that individual modules could be installed instead and then how to instantiate the individual services.

For example, in [Vision for Node.js](https://googlecloudplatform.github.io/google-cloud-node/#/docs/vision/0.2.0/vision), we see that we can install the single module and then it shows how to instantiate the client from that module. 

So in Ruby I guess would be something like `Google::Cloud::Vision.new() `

**Comment by quartzmo** [comment]
@omaray The emphasis on the top-level "umbrella" factory for services was a deliberate decision, but it can certainly be revisited. I believe the usage should be consistent across the documentation at this time (all examples should use `require "google/cloud"`), and if there is consensus to change it, all examples except perhaps a few should then be changed to `require "google/cloud/<service>"`.

Another option would be to add a second example to the top-level guide for each service, demonstrating how to load only the individual service.

Comments/opinions welcome!

/cc @blowmage @jgeewax @callmehiphop @stephenplusplus

**Comment by callmehiphop** [comment]
We created a [template](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/scripts/docs/overview.template.html) for the service overview.

**Comment by stephenplusplus** [comment]
Ah, right. So we have a build process that takes that template and injects the instantiation code in the right context, then plops it into the `overview`.

https://github.com/GoogleCloudPlatform/google-cloud-node/blob/gh-pages/json/bigquery/0.1.1/dataset.json:
```json
{
  "id":"bigquery/dataset",
  "type":"class",
  "name":"Dataset",
  "overview":"<p>\n  This class allows you interact with Google BigQuery.\n</p>\n\n<p>\n  First, install <code>@google-cloud/bigquery</code> with npm:\n</p>\n\n<div hljs language=\"bash\">$ npm install --save @google-cloud/bigquery</div>\n\n<p>\n  If you are running your app on Google Compute Engine, you won't need to worry about supplying connection configuration options to <code>@google-cloud/bigquery</code>— we figure that out for you.\n</p>\n\n<p>\n  However, if you're running your app elsewhere, you will need to provide project details to authenticate API requests.\n</p>\n\n<h4>Compute Engine</h4>\n<div hljs language=\"javascript\">\nvar bigquery = require('@google-cloud/bigquery')();\n</div>\n\n<h4>Elsewhere</h4>\n<div hljs language=\"javascript\">\nvar bigquery = require('@google-cloud/bigquery')({\n  projectId: 'grape-spaceship-123',\n  keyFilename: '/path/to/keyfile.json'\n});\n</div>\n\n<p>\n  The full set of options which can be passed to <code>@google-cloud/bigquery</code> are outlined in our <a href=\"#/docs/bigquery/0.1.0/guides/authentication\">Authentication guide</a>.\n</p>\n\n",
  "description":"",
  "source":"packages/bigquery/src/dataset.js",
  "parent":"bigquery",
  ...
}
```

> I believe the usage should be consistent across the documentation at this time (all examples should use require "google/cloud")

The "Getting Started" process can be a huge area of frustration for the user, so introducing ambiguity in the docs was going to be a problem. For Node, we prioritized putting docs in the correct context for the module the user is viewing, but ignore if this doesn't translate the same to your language/conventions.

**Comment by blowmage** [comment]
We've actually put a lot of effort into maintaining the monolithic API when users are using the individual packages. For example, if the user only installs the `google-cloud-vision` gem, and does _not_ have `google-cloud` umbrella gem installed, they can continue to use the monolithic API.

```ruby
require "google/cloud"

gcloud = Google::Cloud.new
vision = gcloud.vision

image = vision.image "path/to/face.jpg"

annotation = vision.annotate image
```

You can change the require to `require "google/cloud/vision"` and above code will run unchanged.

**Comment by blowmage** [comment]
We also support creating the `vision` object without creating the `gcloud` object first:

```ruby
require "google/cloud/vision"

vision = Google::Cloud.vision

image = vision.image "path/to/face.jpg"

annotation = vision.annotate image
```

This also works whether users `require "google/cloud"` or `require "google/cloud/vision"`.

For the most part Ruby respects the PERL philosophy of allowing multiple ways to do things.

**Comment by quartzmo** [comment]
The proposal for resolving this issue is to change the `require` statements in examples for **individual gems** only, leaving the examples in the `google-cloud` umbrella package unchanged.

Thus, the [Vision examples for the umbrella package](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.20.0/google/cloud/vision) will continue to show:


```ruby
require "google/cloud"

gcloud = Google::Cloud.new
vision = gcloud.vision
...
```

However, the [Vision examples for the `google-cloud-vision` package](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-vision/v0.20.2/google/cloud/vision) will all be changed to:

```ruby
require "google/cloud/vision"

gcloud = Google::Cloud.new
vision = gcloud.vision
...
```

If this sounds right to everyone, I'll go ahead and make the changes.

**Comment by blowmage** [comment]
I just want to make sure everyone knows this change is not necessary to use the library. Either require works.

**Comment by omaray** [comment]
I should be able to just `gem install google-cloud-vision` though, right? And then your example above should work basically (even if I don't install the umbrella package `google-cloud`).

**Comment by blowmage** [comment]
Yep, exactly right.

**Comment by omaray** [comment]
kewl.

**Comment by quartzmo** [comment]
It turns out that having different examples in the umbrella package, [as discussed above](https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/907#issuecomment-248152489) is not currently feasible, since the docs for the umbrella package are simply copied from the individual packages.

**Comment by blowmage** [comment]
Yeah, makes sense.
