### ISSUE TITLE
BigQuery client doesn't implement Projects.list

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/google-cloud-ruby#911]
As far as I can tell, google-cloud-bigquery does not implement Projects.list

API reference: https://cloud.google.com/bigquery/docs/reference/v2/projects/list
Documentation: https://cloud.google.com/bigquery/docs/managing_jobs_datasets_projects#projects
Endpoint: https://www.googleapis.com/bigquery/v2/projects

For reference, see similar issue filed and fixed for google-cloud-python:
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2143

**Comment by quartzmo** [comment]
@remi Thanks for bring this omission to our attention. I read the Python issue and PR, it all makes sense. We will add it.

**Comment by blowmage** [comment]
Hi @remi, today google-cloud-bigquery version 0.20.2 was released with this. Please take a look. Thanks for opening the issue!
