### ISSUE TITLE
Should we support storage object method Compose?

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#94]
Does gcloud support composing a new storage object from existing objects? (https://cloud.google.com/storage/docs/json_api/v1/objects/compose)

This API is not called in the node or python projects.

**Comment by jgeewax** [comment]
I think we should support it, going to dream up some code that I'd want to write for this....

**Comment by jgeewax** [comment]
**Option 1: Put this on the bucket**

Seems like it makes a good deal of sense to put as a bucket-level method. The idea is you get a bucket, and then compose several objects from the bucket into a new object in that same bucket.

```ruby
storage = Gcloud.storage
bucket = storage.find_bucket "my-bucket"

# Compose with multiple arguments
f = bucket.compose "/path/to/target/new.file",
                   "/path/to/part1/remote.file",
                   "/path/to/part2/remote.file"

# Compose with a list
files_to_compose = [
  "/path/to/part1/remote.file",
  "/path/to/part2/remote.file"
]
f = bucket.compose "/path/to/target/new.file",
                   files_to_compose
```

**Option 2: Make this a "factory-style" method on the File object?**

I don't like that so much, and it might actually not be a reasonable idea... I also don't know how Ruby-ish this is... doesn't seem to fit well, but I could be wrong.

```ruby
storage = Gcloud.storage
f = storage.File.from_composition "my-bucket", "/path/to/target/new.file",
                                  files_to_compose
```

**Option 3: Make this a top-level operation (`storage.compose`)**

I think this leads to the potential for confusion that you can compose objects across buckets (which doesn't seem to be the case in the documentation). It also requires that we pick up the destination bucket based on the files provided...

```ruby
storage = Gcloud.storage
bucket = storage.find_bucket "my-bucket"
file1 = bucket.find_file "/path/to/part1/remote.file"
file2 = bucket.find_file "/path/to/part2/remote.file"
f = storage.compose_file "/path/to/target/new.file", file1, file2
# or
f = storage.compose_file "/path/to/target/new.file", [file1, file2]
```

**Option 3a: Same but pass in a bucket and file paths**

This doesn't really fix much, and I still don't like it ...
```ruby
storage = Gcloud.storage
bucket = storage.find_bucket "my-bucket"
f = storage.compose_file bucket, "/path/to/target/new.file"
                                 "/path/to/part1/remote.file",
                                 "/path/to/part2/remote.file",
```

---

I really prefer option 1. @blowmage , any thoughts?

**Comment by Capstan** [comment]
I'd say option 1 or 2 and specifically not option 3 / 3a. Depending on your answer to another comment elsewhere, could we stuff in a File object representing a not-yet-extant GCS object you're about to write (or really, form by composition)?

We think of it internally as 1, but we don't have reified objects that can have factories. (We just have the data model objects.) It's also not merely on the bucket, but really more like a function of the bucket's files() collection (rather than some other property of the bucket).

**Comment by blowmage** [comment]
We have gotten a request to provide this functionality so I am reopening this issue.
