### ISSUE TITLE
list methods in vkit generated code should support page_token

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#943]
In all cases in which underlying Google Cloud service APIs support pagination with tokens, `google-cloud`  has exposed this functionality, which @blowmage and I feel is very important for web development use cases in which only minimal state may be available between page requests. Here is an example:

```ruby
page_1 = pubsub.topics
token = page_1.token
# In a new context, in which only the literal value of `token` has been preserved...
page_2 = pubsub.topics token: token
```

`gax-ruby`'s [`PagedEnumerable` exposes the `page_token`](https://github.com/googleapis/gax-ruby/commit/b89c4e867bcc23cdd4583318cd3b66f30a7db887), but we need to be able to pass it back to list methods in vkit-generated code that has been added to `google-cloud`.

The following list methods should be modified to accept an optional `page_token` parameter:

* google-cloud-logging
  * `ConfigServiceV2Api#list_sinks`
  * `LoggingServiceV2Api#list_log_entries`
  * `LoggingServiceV2Api#list_monitored_resource_descriptors`
  * `MetricsServiceV2Api#list_log_metrics`
* google-cloud-pubsub
  * `PublisherApi#list_topics`
  * `PublisherApi#list_topic_subscriptions`
  * `SubscriberApi#list_subscriptions`

/cc @jmuk @swcloud

**Comment by jmuk** [comment]
We provides page_token as in a part of `options` actually (see https://github.com/googleapis/gax-ruby/blob/master/lib/google/gax.rb#L164), so it would work as
```ruby
page_2 = pubsub.topics options: Google::Gax::CallOptions.new(page_token: token)
```

This design is borrowed from Python's one.

What would be the better way here?  Unflatten all of the call-options field as the keyword arguments to the method?

**Comment by quartzmo** [comment]
@jmuk Thank you, the `page_token` option in `CallOptions` works perfectly. I was so certain I knew everything in `CallOptions` that I didn't look there.

As for the API design, the only thing that I find non-intuitive is that it will be present for all methods, not just list methods, correct?

Thank you for responding, very happy to now close this issue.
