### ISSUE TITLE
Python link in language drop-down sends user to gcloud-python

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-ruby#944]
The language drop-down on the [Client Library Reference page for Ruby](https://googlecloudplatform.github.io/google-cloud-ruby/#/) sends users to gcloud-python when selecting Python:

![image](https://cloud.githubusercontent.com/assets/6609430/18977480/6ee5d7a0-866f-11e6-8750-e4bbf6216529.png)

It's a problem because sometimes we'll see a 404 appear.

[Expected]
It should point to google-cloud-python.

**Comment by quartzmo** [comment]
This was a gcloud-common issue (GoogleCloudPlatform/gcloud-common#194). Fixed now on google-cloud-ruby docs.
