### ISSUE TITLE
Change title of tab from gcloud to google-cloud-ruby

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-ruby#945]
When opening the [Client Library Reference page for Ruby](https://googlecloudplatform.github.io/google-cloud-ruby/#/) we can notice that the tab title says `gcloud`:

![image](https://cloud.githubusercontent.com/assets/6609430/18977514/ce43caa4-866f-11e6-8682-0c1ea1956292.png)

[Expected Result]
We should update it to say `google-cloud-ruby`.

**Comment by quartzmo** [comment]
We changed the title to `google-cloud-ruby` some time ago, but the automated doc site update script in `gcloud-common` overwrites `index.html` regularly. You can see that it reverted the title to `gcloud` in [this commit](https://github.com/GoogleCloudPlatform/google-cloud-ruby/commit/2f1ca8164cac7229d70b20200842851fd71cf3df).

I will open a `gcloud-common` issue to resolve this for all platforms using the shared site.

**Comment by quartzmo** [comment]
Closing, since 100% of the fix will be in gcloud-common.
