### ISSUE TITLE
Correct way to retrieve signed url to put object

### ISSUE THREAD

**Issue by vyper** [GoogleCloudPlatform/google-cloud-ruby#955]
I trying to retrieve signed url to put an object in storage, but `#file` returns `nil`.

```ruby
storage = Google::Cloud.new.storage
bucket = storage.bucket 'my-bucket'

# when file not exists, I can't use #signed_url
file = bucket.file 'my-file.txt'
# => nil

# But, sending temp file I can use #signed_url
file = bucket.create_file Tempfile.new, 'my-file.txt'
# => #<Google::Cloud::Storage::File:0x00558399936080> ...
url = file.signed_url method: 'PUT', expires: 600
# => "https://storage.googleapis.com/my-bucket/my-file.txt?GoogleAccessId= .."
```

**Comment by quartzmo** [comment]
@vyper Just to be sure that I understand what you want to do, can you provide an example that shows the success path? If the method(s) that you want to call do not exist, write it as if they did. Thanks!

**Comment by vyper** [comment]
I need signed url for a new file (inexistent file)...

```
$ gsutil signurl -m PUT key.json gs://my-bucket/inexistent-file.txt
URL	HTTP Method	Expiration	Signed URL
gs://my-bucket/inexistent-file.txt	PUT	2016-10-13 22:17:53	https://storage.googleapis.com/my-bucket/inexistent-file.txt?Google....
```

**Comment by quartzmo** [comment]
I'm sorry, can you write an example for this library (google-cloud-storage) which shows the actual (and proposed) API calls that will achieve your goal?

**Comment by Capstan** [comment]
And you want a one-shot upload? `PUT` only? This versus either of

- signed URL to create a resumable upload session
- POST policy for use in a traditional browser web form 

My understanding is that if you know the object name you want to upload to, you should still be able to produced a signed URL for it in some fashion, though perhaps not through the `file` object.

**Comment by Capstan** [comment]
Maybe `bucket.signed_url`for URL operations on existing buckets (list objects, write new object) and `storage.signed_url` for URL operations to create new buckets.
