### ISSUE TITLE
Update a File by generation

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#97]
The Storage API allows updates to be performed on a specific object version/generation. The default is the update is performed on the most recent version/generation. Is this something that gcloud-ruby needs to support? Or is that outside of the typical use and not worth complicating the API to support it?

**Comment by blowmage** [comment]
@jgeewax This is one of those things that seems outside the 90% use case.

**Comment by Capstan** [comment]
It is certainly outside of the 90% use case.

The two caveats are:
* For folks with versioning turned on, it's the only way to see/use archived objects.
* It is the way to know that you are still operating on the same object. You don't to start downloading GCS object, have it fail midway through, and then retry on the live GCS object – you want to retry on the GCS object *at that generation* or you will end up with a mixed response, which will look like corrupted data to the user.
