### ISSUE TITLE
Should all RubyGems URLs use SSL?

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#994]
I just noticed that [google-cloud-error_reporting/Gemfile](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-error_reporting/Gemfile) and [google-cloud-monitoring/Gemfile](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-monitoring/Gemfile) use SSL to access rubygems.org (`source 'https://rubygems.org'`), while the older Gemfiles do not. Should all Gemfiles be updated to use SSL?

**Comment by blowmage** [comment]
We should be using HTTPS across the board. I would also like to see the Gemfile, gemspec, and Rakefile files all consistent across the gems.

**Comment by quartzmo** [comment]
@blowmage Can you link to examples of correct and incorrect usages?

**Comment by blowmage** [comment]
Usages of what?

**Comment by quartzmo** [comment]
Anything you know of that is currently inconsistent in Gemfile, gemspec, and Rakefile files. Feel free to open new issues, or just add to this one. Or do you want to just fix them in a PR sometime?

**Comment by blowmage** [comment]
Inconsistent doesn't mean incorrect. But it would be easier to search/replace dependencies if the gemspec files looked similar, for example. 

I don't think every inconsistency needs its own issue though.
