### ISSUE TITLE
Outdated references to google/apis/vision_v1?

### ISSUE THREAD

**Issue by Ricowere** [GoogleCloudPlatform/google-cloud-ruby#997]
Hi guys!

After having installed the version `'0.21.0'` of google-cloud-vision and following carefully the documentation (awesome docs by the way) that it's provided, I was stuck with a weird error.

`#<LoadError: cannot load such file -- google/apis/vision_v1>"`

After researching a bit in the gem I've discovered there are references in the code that may are outdated given the fact you're using protobuf. See this [one](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-vision/lib/google/cloud/vision/image.rb#L17) for instance.

I'm not sure if its an outdated or a real dependency of google-cloud-vision. So we could figure out either two solutions, add `'google-api-client', '~> 0.9'`as a dependency in the `gemspec` or remove the outdated references.

PS: I've just found this two references to vision_v1. 

[annotate.rb](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-vision/lib/google/cloud/vision/annotate.rb#L17)
[image.rb](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-vision/lib/google/cloud/vision/image.rb#L17)

Hope it helps.
Cheers!
David

**Comment by blowmage** [comment]
Hi @Ricowere, thank you for opening the issue. Indeed, the latest release, 0.21.0 moved the implementation from using the Google API Client library to using GRPC and the generated protobuf code. These requires should have been removed. We will fix this and release a fix ASAP.

**Comment by Ricowere** [comment]
@blowmage thanks! It was very quick.

**Comment by blowmage** [comment]
@Ricowere This is fixed in google-cloud-vision 0.21.1. Please upgrade and let us know if that works for you. Thank you very much for reporting this issue to us!

**Comment by Ricowere** [comment]
@blowmage `google-cloud-vision 0.21.1` working fine 💪 . Thanks guys.
